// Code generated by ailang. DO NOT EDIT.
package sim_gen

func initArrival_impl(_unused0 interface{}) interface{} {
	return &ArrivalState{Phase: NewArrivalPhasePhaseBlackHole(), PhaseTime: float64(0), TotalTime: float64(0), Velocity: float64(0.99), GrIntensity: float64(1), CurrentPlanet: NewCurrentPlanetNoPlanet(), ShipTimeYears: float64(47.3), GalaxyYear: int64(2157)}
}

func InitArrival() *ArrivalState {
	return initArrival_impl(struct{}{}).(*ArrivalState)
}

func phaseTargetVelocity_impl(phase interface{}) interface{} {
	return func() interface{} {
		_scrutinee := phase
		_ = _scrutinee // suppress unused
		_adt := _scrutinee.(*ArrivalPhase)
		switch _adt.Kind {
		case ArrivalPhaseKindPhaseBlackHole:
			return float64(0.99)
		case ArrivalPhaseKindPhaseEmergence:
			return float64(0.99)
		case ArrivalPhaseKindPhaseStabilizing:
			return float64(0.95)
		case ArrivalPhaseKindPhaseSaturn:
			return float64(0.9)
		case ArrivalPhaseKindPhaseJupiter:
			return float64(0.8)
		case ArrivalPhaseKindPhaseMars:
			return float64(0.5)
		case ArrivalPhaseKindPhaseEarth:
			return float64(0)
		case ArrivalPhaseKindPhaseComplete:
			return float64(0)
		default:
			panic("non-exhaustive match")
		}
	}()
}

func phaseTargetVelocity(phase *ArrivalPhase) float64 {
	return phaseTargetVelocity_impl(phase).(float64)
}

func phasePlanet_impl(phase interface{}) interface{} {
	return func() interface{} {
		_scrutinee := phase
		_ = _scrutinee // suppress unused
		_adt := _scrutinee.(*ArrivalPhase)
		switch _adt.Kind {
		case ArrivalPhaseKindPhaseSaturn:
			return NewCurrentPlanetSaturn()
		case ArrivalPhaseKindPhaseJupiter:
			return NewCurrentPlanetJupiter()
		case ArrivalPhaseKindPhaseMars:
			return NewCurrentPlanetMars()
		case ArrivalPhaseKindPhaseEarth:
			return NewCurrentPlanetEarth()
		default:
			return NewCurrentPlanetNoPlanet()
		}
	}()
}

func phasePlanet(phase *ArrivalPhase) *CurrentPlanet {
	return phasePlanet_impl(phase).(*CurrentPlanet)
}

func nextPhase_impl(phase interface{}) interface{} {
	return func() interface{} {
		_scrutinee := phase
		_ = _scrutinee // suppress unused
		_adt := _scrutinee.(*ArrivalPhase)
		switch _adt.Kind {
		case ArrivalPhaseKindPhaseBlackHole:
			return NewArrivalPhasePhaseEmergence()
		case ArrivalPhaseKindPhaseEmergence:
			return NewArrivalPhasePhaseStabilizing()
		case ArrivalPhaseKindPhaseStabilizing:
			return NewArrivalPhasePhaseSaturn()
		case ArrivalPhaseKindPhaseSaturn:
			return NewArrivalPhasePhaseJupiter()
		case ArrivalPhaseKindPhaseJupiter:
			return NewArrivalPhasePhaseMars()
		case ArrivalPhaseKindPhaseMars:
			return NewArrivalPhasePhaseEarth()
		case ArrivalPhaseKindPhaseEarth:
			return NewArrivalPhasePhaseComplete()
		case ArrivalPhaseKindPhaseComplete:
			return NewArrivalPhasePhaseComplete()
		default:
			panic("non-exhaustive match")
		}
	}()
}

func nextPhase(phase *ArrivalPhase) *ArrivalPhase {
	return nextPhase_impl(phase).(*ArrivalPhase)
}

func shouldTransition_impl(phase interface{}, phaseTime interface{}) interface{} {
	return func() interface{} {
		_scrutinee := phase
		_ = _scrutinee // suppress unused
		_adt := _scrutinee.(*ArrivalPhase)
		switch _adt.Kind {
		case ArrivalPhaseKindPhaseBlackHole:
			return GtFloat(phaseTime, float64(8))
		case ArrivalPhaseKindPhaseEmergence:
			return GtFloat(phaseTime, float64(5))
		case ArrivalPhaseKindPhaseStabilizing:
			return GtFloat(phaseTime, float64(3))
		case ArrivalPhaseKindPhaseSaturn:
			return GtFloat(phaseTime, float64(5))
		case ArrivalPhaseKindPhaseJupiter:
			return GtFloat(phaseTime, float64(5))
		case ArrivalPhaseKindPhaseMars:
			return GtFloat(phaseTime, float64(5))
		case ArrivalPhaseKindPhaseEarth:
			return GtFloat(phaseTime, float64(5))
		case ArrivalPhaseKindPhaseComplete:
			return false
		default:
			panic("non-exhaustive match")
		}
	}()
}

func shouldTransition(phase *ArrivalPhase, phaseTime float64) bool {
	return shouldTransition_impl(phase, phaseTime).(bool)
}

func isArrivalComplete_impl(state interface{}) interface{} {
	var tmp1 interface{} = FieldGet(state, "phase")
	return func() interface{} {
		_scrutinee := tmp1
		_ = _scrutinee // suppress unused
		_adt := _scrutinee.(*ArrivalPhase)
		switch _adt.Kind {
		case ArrivalPhaseKindPhaseComplete:
			return true
		default:
			return false
		}
	}()
}

func IsArrivalComplete(state *ArrivalState) bool {
	return isArrivalComplete_impl(state).(bool)
}

func getArrivalVelocity_impl(state interface{}) interface{} {
	return FieldGet(state, "velocity")
}

func GetArrivalVelocity(state *ArrivalState) float64 {
	return getArrivalVelocity_impl(state).(float64)
}

func getArrivalPlanetName_impl(state interface{}) interface{} {
	var tmp2 interface{} = FieldGet(state, "currentPlanet")
	return func() interface{} {
		_scrutinee := tmp2
		_ = _scrutinee // suppress unused
		_adt := _scrutinee.(*CurrentPlanet)
		switch _adt.Kind {
		case CurrentPlanetKindNoPlanet:
			return ""
		case CurrentPlanetKindSaturn:
			return "saturn"
		case CurrentPlanetKindJupiter:
			return "jupiter"
		case CurrentPlanetKindMars:
			return "mars"
		case CurrentPlanetKindEarth:
			return "earth"
		default:
			panic("non-exhaustive match")
		}
	}()
}

func GetArrivalPlanetName(state *ArrivalState) string {
	return getArrivalPlanetName_impl(state).(string)
}

func getArrivalPhaseName_impl(state interface{}) interface{} {
	var tmp3 interface{} = FieldGet(state, "phase")
	return func() interface{} {
		_scrutinee := tmp3
		_ = _scrutinee // suppress unused
		_adt := _scrutinee.(*ArrivalPhase)
		switch _adt.Kind {
		case ArrivalPhaseKindPhaseBlackHole:
			return "blackhole"
		case ArrivalPhaseKindPhaseEmergence:
			return "emergence"
		case ArrivalPhaseKindPhaseStabilizing:
			return "stabilizing"
		case ArrivalPhaseKindPhaseSaturn:
			return "saturn"
		case ArrivalPhaseKindPhaseJupiter:
			return "jupiter"
		case ArrivalPhaseKindPhaseMars:
			return "mars"
		case ArrivalPhaseKindPhaseEarth:
			return "earth"
		case ArrivalPhaseKindPhaseComplete:
			return "complete"
		default:
			panic("non-exhaustive match")
		}
	}()
}

func GetArrivalPhaseName(state *ArrivalState) string {
	return getArrivalPhaseName_impl(state).(string)
}

func getGRIntensity_impl(state interface{}) interface{} {
	return FieldGet(state, "grIntensity")
}

func GetGRIntensity(state *ArrivalState) float64 {
	return getGRIntensity_impl(state).(float64)
}

func calcGRDecay_impl(phase interface{}, phaseTime interface{}, currentGR interface{}) interface{} {
	return func() interface{} {
		_scrutinee := phase
		_ = _scrutinee // suppress unused
		_adt := _scrutinee.(*ArrivalPhase)
		switch _adt.Kind {
		case ArrivalPhaseKindPhaseBlackHole:
			return func() interface{} {
				var progress interface{} = DivFloat(phaseTime, float64(8))
				_ = progress // suppress unused
				return func() interface{} {
					var tmp4 interface{} = GtFloat(progress, float64(1))
					_ = tmp4 // suppress unused
					return func() interface{} {
						if tmp4.(bool) {
							return float64(0)
						}
						return SubFloat(float64(1), progress)
					}()
				}()
			}()
		default:
			return float64(0)
		}
	}()
}

func calcGRDecay(phase *ArrivalPhase, phaseTime float64, currentGR float64) float64 {
	return calcGRDecay_impl(phase, phaseTime, currentGR).(float64)
}

func stepArrival_impl(state interface{}, input interface{}) interface{} {
	var dt interface{} = FieldGet(input, "dt")
	var newPhaseTime interface{} = func() interface{} {
		var tmp12 interface{} = FieldGet(state, "phaseTime")
		_ = tmp12 // suppress unused
		return AddFloat(tmp12, dt)
	}()
	var newTotalTime interface{} = func() interface{} {
		var tmp11 interface{} = FieldGet(state, "totalTime")
		_ = tmp11 // suppress unused
		return AddFloat(tmp11, dt)
	}()
	var newGR interface{} = func() interface{} {
		var tmp9 interface{} = FieldGet(state, "phase")
		_ = tmp9 // suppress unused
		return func() interface{} {
			var tmp10 interface{} = FieldGet(state, "grIntensity")
			_ = tmp10 // suppress unused
			return calcGRDecay_impl(tmp9, newPhaseTime, tmp10)
		}()
	}()
	var transition interface{} = func() interface{} {
		var tmp8 interface{} = FieldGet(state, "phase")
		_ = tmp8 // suppress unused
		return shouldTransition_impl(tmp8, newPhaseTime)
	}()
	return func() interface{} {
		if transition.(bool) {
			return func() interface{} {
				var nextPh interface{} = func() interface{} {
					var tmp7 interface{} = FieldGet(state, "phase")
					_ = tmp7 // suppress unused
					return nextPhase_impl(tmp7)
				}()
				_ = nextPh // suppress unused
				return func() interface{} {
					var nextVel interface{} = phaseTargetVelocity_impl(nextPh)
					_ = nextVel // suppress unused
					return func() interface{} {
						var nextPlanet interface{} = phasePlanet_impl(nextPh)
						_ = nextPlanet // suppress unused
						return func() interface{} {
							var tmp5 interface{} = FieldGet(state, "shipTimeYears")
							_ = tmp5 // suppress unused
							return func() interface{} {
								var tmp6 interface{} = FieldGet(state, "galaxyYear")
								_ = tmp6 // suppress unused
								return &ArrivalState{Phase: nextPh.(*ArrivalPhase), PhaseTime: float64(0), TotalTime: newTotalTime.(float64), Velocity: nextVel.(float64), GrIntensity: float64(0), CurrentPlanet: nextPlanet.(*CurrentPlanet), ShipTimeYears: tmp5.(float64), GalaxyYear: tmp6.(int64)}
							}()
						}()
					}()
				}()
			}()
		}
		return RecordUpdate(state, map[string]interface{}{"phaseTime": newPhaseTime, "totalTime": newTotalTime, "grIntensity": newGR})
	}()
}

func StepArrival(state *ArrivalState, input *ArrivalInput) *ArrivalState {
	return stepArrival_impl(state, input).(*ArrivalState)
}
