// Code generated by ailang. DO NOT EDIT.
package sim_gen

import (
	"math"
)

func colorFloor_impl(_unused0 interface{}) interface{} {
	return int64(707406591)
}

func colorFloor() int64 {
	return colorFloor_impl(struct{}{}).(int64)
}

func colorFloorGlow_impl(_unused0 interface{}) interface{} {
	return int64(858993919)
}

func colorFloorGlow() int64 {
	return colorFloorGlow_impl(struct{}{}).(int64)
}

func colorDomeEdge_impl(_unused0 interface{}) interface{} {
	return int64(439041279)
}

func colorDomeEdge() int64 {
	return colorDomeEdge_impl(struct{}{}).(int64)
}

func colorWalkway_impl(_unused0 interface{}) interface{} {
	return int64(1145324799)
}

func colorWalkway() int64 {
	return colorWalkway_impl(struct{}{}).(int64)
}

func colorCaptainArea_impl(_unused0 interface{}) interface{} {
	return int64(606348543)
}

func colorCaptainArea() int64 {
	return colorCaptainArea_impl(struct{}{}).(int64)
}

func colorWall_impl(_unused0 interface{}) interface{} {
	return int64(252645631)
}

func colorWall() int64 {
	return colorWall_impl(struct{}{}).(int64)
}

func colorHelm_impl(_unused0 interface{}) interface{} {
	return int64(4120593151)
}

func colorHelm() int64 {
	return colorHelm_impl(struct{}{}).(int64)
}

func colorComms_impl(_unused0 interface{}) interface{} {
	return int64(14540799)
}

func colorComms() int64 {
	return colorComms_impl(struct{}{}).(int64)
}

func colorStatus_impl(_unused0 interface{}) interface{} {
	return int64(2566914303)
}

func colorStatus() int64 {
	return colorStatus_impl(struct{}{}).(int64)
}

func colorNav_impl(_unused0 interface{}) interface{} {
	return int64(4294935039)
}

func colorNav() int64 {
	return colorNav_impl(struct{}{}).(int64)
}

func colorScience_impl(_unused0 interface{}) interface{} {
	return int64(16744447)
}

func colorScience() int64 {
	return colorScience_impl(struct{}{}).(int64)
}

func colorCaptain_impl(_unused0 interface{}) interface{} {
	return int64(4294940415)
}

func colorCaptain() int64 {
	return colorCaptain_impl(struct{}{}).(int64)
}

func colorCrewPilot_impl(_unused0 interface{}) interface{} {
	return int64(4120593151)
}

func colorCrewPilot() int64 {
	return colorCrewPilot_impl(struct{}{}).(int64)
}

func colorCrewComms_impl(_unused0 interface{}) interface{} {
	return int64(14540799)
}

func colorCrewComms() int64 {
	return colorCrewComms_impl(struct{}{}).(int64)
}

func colorCrewEngineer_impl(_unused0 interface{}) interface{} {
	return int64(2566914303)
}

func colorCrewEngineer() int64 {
	return colorCrewEngineer_impl(struct{}{}).(int64)
}

func colorCrewScientist_impl(_unused0 interface{}) interface{} {
	return int64(16744447)
}

func colorCrewScientist() int64 {
	return colorCrewScientist_impl(struct{}{}).(int64)
}

func colorCrewCaptain_impl(_unused0 interface{}) interface{} {
	return int64(4294940415)
}

func colorCrewCaptain() int64 {
	return colorCrewCaptain_impl(struct{}{}).(int64)
}

func colorPlayer_impl(_unused0 interface{}) interface{} {
	return int64(65280)
}

func colorPlayer() int64 {
	return colorPlayer_impl(struct{}{}).(int64)
}

func makeDomeViewState_impl(planetId interface{}, velocity interface{}, angle interface{}) interface{} {
	return &DomeViewState{TargetPlanetId: planetId.(int64), ShipVelocity: velocity.(float64), ViewAngle: angle.(float64)}
}

func MakeDomeViewState(planetId int64, velocity float64, angle float64) *DomeViewState {
	return makeDomeViewState_impl(planetId, velocity, angle).(*DomeViewState)
}

func initDomeState_impl(_unused0 interface{}) interface{} {
	return &DomeState{CruiseTime: float64(0), CruiseDuration: float64(60), CruiseVelocity: float64(0.15), CameraZ: float64(10), TargetPlanet: int64(4)}
}

func InitDomeState() *DomeState {
	return initDomeState_impl(struct{}{}).(*DomeState)
}

func stepDome_impl(state interface{}, dt interface{}) interface{} {
	var newTime interface{} = func() interface{} {
		var tmp12 interface{} = FieldGet(state, "cruiseTime")
		_ = tmp12 // suppress unused
		return AddFloat(tmp12, dt)
	}()
	var loopedTime interface{} = func() interface{} {
		var tmp10 interface{} = FieldGet(state, "cruiseDuration")
		_ = tmp10 // suppress unused
		var tmp11 interface{} = GtFloat(newTime, tmp10)
		_ = tmp11 // suppress unused
		return func() interface{} {
			if tmp11.(bool) {
				return float64(0)
			}
			return newTime
		}()
	}()
	var progress interface{} = func() interface{} {
		var tmp9 interface{} = FieldGet(state, "cruiseDuration")
		_ = tmp9 // suppress unused
		return DivFloat(loopedTime, tmp9)
	}()
	var eased interface{} = func() interface{} {
		var tmp6 interface{} = MulFloat(progress, progress)
		_ = tmp6 // suppress unused
		var tmp7 interface{} = MulFloat(float64(2), progress)
		_ = tmp7 // suppress unused
		var tmp8 interface{} = SubFloat(float64(3), tmp7)
		_ = tmp8 // suppress unused
		return MulFloat(tmp6, tmp8)
	}()
	var startZ interface{} = float64(10)
	var endZ interface{} = SubFloat(float64(0), float64(155))
	var newCamZ interface{} = func() interface{} {
		var tmp4 interface{} = SubFloat(startZ, endZ)
		_ = tmp4 // suppress unused
		var tmp5 interface{} = MulFloat(tmp4, eased)
		_ = tmp5 // suppress unused
		return SubFloat(startZ, tmp5)
	}()
	var tmp1 interface{} = FieldGet(state, "cruiseDuration")
	var tmp2 interface{} = FieldGet(state, "cruiseVelocity")
	var tmp3 interface{} = FieldGet(state, "targetPlanet")
	return &DomeState{CruiseTime: loopedTime.(float64), CruiseDuration: tmp1.(float64), CruiseVelocity: tmp2.(float64), CameraZ: newCamZ.(float64), TargetPlanet: tmp3.(int64)}
}

func StepDome(state *DomeState, dt float64) *DomeState {
	return stepDome_impl(state, dt).(*DomeState)
}

func getPlanets_impl(_unused0 interface{}) interface{} {
	var tmp13 interface{} = &Planet{Name: "Neptune", ColorRGBA: int64(1350665471), Distance: float64(15), Radius: float64(20), YOffset: float64(2.25)}
	var tmp14 interface{} = &Planet{Name: "Saturn", ColorRGBA: int64(3535748351), Distance: float64(50), Radius: float64(36), YOffset: float64(7.5)}
	var tmp15 interface{} = &Planet{Name: "Jupiter", ColorRGBA: int64(3702191359), Distance: float64(90), Radius: float64(44), YOffset: float64(13.5)}
	var tmp16 interface{} = &Planet{Name: "Mars", ColorRGBA: int64(3361734911), Distance: float64(130), Radius: float64(10), YOffset: float64(19.5)}
	var tmp17 interface{} = &Planet{Name: "Earth", ColorRGBA: int64(1014743295), Distance: float64(150), Radius: float64(14), YOffset: float64(22.5)}
	return []interface{}{tmp13, tmp14, tmp15, tmp16, tmp17}
}

func GetPlanets() []*Planet {
	return getPlanets_impl(struct{}{}).([]*Planet)
}

func getDomeVelocity_impl(state interface{}) interface{} {
	return FieldGet(state, "cruiseVelocity")
}

func GetDomeVelocity(state *DomeState) float64 {
	return getDomeVelocity_impl(state).(float64)
}

func getDomeProgress_impl(state interface{}) interface{} {
	var tmp18 interface{} = FieldGet(state, "cruiseTime")
	var tmp19 interface{} = FieldGet(state, "cruiseDuration")
	return DivFloat(tmp18, tmp19)
}

func GetDomeProgress(state *DomeState) float64 {
	return getDomeProgress_impl(state).(float64)
}

func layerDome_impl(_unused0 interface{}) interface{} {
	return SubInt(int64(0), int64(10))
}

func layerDome() int64 {
	return layerDome_impl(struct{}{}).(int64)
}

func renderPlanet_impl(planet interface{}, cameraZ interface{}, scrW interface{}, scrH interface{}) interface{} {
	var relZ interface{} = func() interface{} {
		var tmp29 interface{} = FieldGet(planet, "distance")
		_ = tmp29 // suppress unused
		return AddFloat(tmp29, cameraZ)
	}()
	var tmp20 interface{} = LeFloat(relZ, float64(0.5))
	return func() interface{} {
		var scale interface{} = DivFloat(float64(100), relZ)
		_ = scale // suppress unused
		var screenX interface{} = DivFloat(scrW, float64(2))
		_ = screenX // suppress unused
		var baseY interface{} = float64(200)
		_ = baseY // suppress unused
		var screenY interface{} = func() interface{} {
			var tmp26 interface{} = FieldGet(planet, "yOffset")
			_ = tmp26 // suppress unused
			return func() interface{} {
				var tmp27 interface{} = MulFloat(tmp26, scale)
				_ = tmp27 // suppress unused
				return func() interface{} {
					var tmp28 interface{} = MulFloat(tmp27, float64(5))
					_ = tmp28 // suppress unused
					return AddFloat(baseY, tmp28)
				}()
			}()
		}()
		_ = screenY // suppress unused
		var visibleRadius interface{} = func() interface{} {
			var tmp25 interface{} = FieldGet(planet, "radius")
			_ = tmp25 // suppress unused
			return MulFloat(tmp25, scale)
		}()
		_ = visibleRadius // suppress unused
		var tmp21 interface{} = LtFloat(visibleRadius, float64(1))
		_ = tmp21 // suppress unused
		if tmp20.(bool) {
			return []interface{}{}
		}
		if tmp21.(bool) {
			return []interface{}{}
		}
		return func() interface{} {
			var tmp22 interface{} = FieldGet(planet, "colorRGBA")
			_ = tmp22 // suppress unused
			return func() interface{} {
				var tmp23 interface{} = layerDome_impl(struct{}{})
				_ = tmp23 // suppress unused
				return func() interface{} {
					var tmp24 interface{} = NewDrawCmdCircleRGBA(screenX.(float64), screenY.(float64), visibleRadius.(float64), tmp22.(int64), true, tmp23.(int64))
					_ = tmp24 // suppress unused
					return []interface{}{tmp24}
				}()
			}()
		}()
	}()
}

func renderPlanet(planet *Planet, cameraZ float64, scrW float64, scrH float64) []*DrawCmd {
	return ConvertToDrawCmdSlice(renderPlanet_impl(planet, cameraZ, scrW, scrH))
}

func renderPlanetsRec_impl(planets interface{}, cameraZ interface{}, scrW interface{}, scrH interface{}) interface{} {
	return func() interface{} {
		_scrutinee := planets
		_ = _scrutinee // suppress unused
		if ListLen(_scrutinee) == 0 {
			return []interface{}{}
		} else if ListLen(_scrutinee) >= 1 {
			p := ListHead(_scrutinee)
			_ = p // suppress unused
			rest := ListTail(_scrutinee)
			_ = rest // suppress unused
			return func() interface{} {
				var tmp30 interface{} = renderPlanet_impl(p, cameraZ, scrW, scrH)
				_ = tmp30 // suppress unused
				var tmp31 interface{} = renderPlanetsRec_impl(rest, cameraZ, scrW, scrH)
				_ = tmp31 // suppress unused
				return Concat(tmp30, tmp31)
			}()
		} else {
			panic("non-exhaustive match")
		}
	}()
}

func renderPlanetsRec(planets []*Planet, cameraZ float64, scrW float64, scrH float64) []*DrawCmd {
	return ConvertToDrawCmdSlice(renderPlanetsRec_impl(planets, cameraZ, scrW, scrH))
}

func screenWidth_impl(_unused0 interface{}) interface{} {
	return float64(1280)
}

func screenWidth() float64 {
	return screenWidth_impl(struct{}{}).(float64)
}

func screenHeight_impl(_unused0 interface{}) interface{} {
	return float64(960)
}

func screenHeight() float64 {
	return screenHeight_impl(struct{}{}).(float64)
}

func renderDomePlanets_impl(state interface{}) interface{} {
	var scrW interface{} = screenWidth_impl(struct{}{})
	var scrH interface{} = screenHeight_impl(struct{}{})
	var tmp32 interface{} = getPlanets_impl(struct{}{})
	var tmp33 interface{} = FieldGet(state, "cameraZ")
	return renderPlanetsRec_impl(tmp32, tmp33, scrW, scrH)
}

func RenderDomePlanets(state *DomeState) []*DrawCmd {
	return ConvertToDrawCmdSlice(renderDomePlanets_impl(state))
}

func layerDomeBg_impl(_unused0 interface{}) interface{} {
	return SubInt(int64(0), int64(20))
}

func layerDomeBg() int64 {
	return layerDomeBg_impl(struct{}{}).(int64)
}

func layerBubbleArc3D_impl(_unused0 interface{}) interface{} {
	return int64(5)
}

func layerBubbleArc3D() int64 {
	return layerBubbleArc3D_impl(struct{}{}).(int64)
}

func renderDome_impl(state interface{}) interface{} {
	var tmp34 interface{} = layerDomeBg_impl(struct{}{})
	var tmp35 interface{} = NewDrawCmdSpaceBg(tmp34.(int64))
	var tmp36 interface{} = layerBubbleArc3D_impl(struct{}{})
	var tmp37 interface{} = NewDrawCmdBubbleArc(tmp36.(int64))
	return []interface{}{tmp35, tmp37}
}

func RenderDome(state *DomeState) []*DrawCmd {
	return ConvertToDrawCmdSlice(renderDome_impl(state))
}

func strutColor_impl(_unused0 interface{}) interface{} {
	return int64(1275068520)
}

func strutColor() int64 {
	return strutColor_impl(struct{}{}).(int64)
}

func strutHighlight_impl(_unused0 interface{}) interface{} {
	return int64(1887670408)
}

func strutHighlight() int64 {
	return strutHighlight_impl(struct{}{}).(int64)
}

func layerStruts_impl(_unused0 interface{}) interface{} {
	return NegInt(int64(1))
}

func layerStruts() int64 {
	return layerStruts_impl(struct{}{}).(int64)
}

func strutCount_impl(_unused0 interface{}) interface{} {
	return int64(8)
}

func strutCount() int64 {
	return strutCount_impl(struct{}{}).(int64)
}

func arcCenterY_impl(_unused0 interface{}) interface{} {
	return float64(1600)
}

func arcCenterY() float64 {
	return arcCenterY_impl(struct{}{}).(float64)
}

func arcRadius_impl(_unused0 interface{}) interface{} {
	return float64(900)
}

func arcRadius() float64 {
	return arcRadius_impl(struct{}{}).(float64)
}

func strutBaseX_impl(index interface{}, total interface{}) interface{} {
	var centerX interface{} = func() interface{} {
		var tmp48 interface{} = screenWidth_impl(struct{}{})
		_ = tmp48 // suppress unused
		return DivFloat(tmp48, float64(2))
	}()
	var angleRange interface{} = func() interface{} {
		var tmp47 interface{} = math.Pi
		_ = tmp47 // suppress unused
		return DivFloat(tmp47, float64(3))
	}()
	var angleStep interface{} = func() interface{} {
		var tmp44 interface{} = MulFloat(angleRange, float64(2))
		_ = tmp44 // suppress unused
		var tmp45 interface{} = SubInt(total, int64(1))
		_ = tmp45 // suppress unused
		var tmp46 interface{} = IntToFloat(tmp45)
		_ = tmp46 // suppress unused
		return DivFloat(tmp44, tmp46)
	}()
	var angle interface{} = func() interface{} {
		var tmp41 interface{} = SubFloat(float64(0), angleRange)
		_ = tmp41 // suppress unused
		var tmp42 interface{} = IntToFloat(index)
		_ = tmp42 // suppress unused
		var tmp43 interface{} = MulFloat(tmp42, angleStep)
		_ = tmp43 // suppress unused
		return AddFloat(tmp41, tmp43)
	}()
	var tmp38 interface{} = arcRadius_impl(struct{}{})
	var tmp39 interface{} = math.Sin(angle.(float64))
	var tmp40 interface{} = MulFloat(tmp38, tmp39)
	return AddFloat(centerX, tmp40)
}

func strutBaseX(index int64, total int64) float64 {
	return strutBaseX_impl(index, total).(float64)
}

func strutBaseY_impl(index interface{}, total interface{}) interface{} {
	var angleRange interface{} = func() interface{} {
		var tmp59 interface{} = math.Pi
		_ = tmp59 // suppress unused
		return DivFloat(tmp59, float64(3))
	}()
	var angleStep interface{} = func() interface{} {
		var tmp56 interface{} = MulFloat(angleRange, float64(2))
		_ = tmp56 // suppress unused
		var tmp57 interface{} = SubInt(total, int64(1))
		_ = tmp57 // suppress unused
		var tmp58 interface{} = IntToFloat(tmp57)
		_ = tmp58 // suppress unused
		return DivFloat(tmp56, tmp58)
	}()
	var angle interface{} = func() interface{} {
		var tmp53 interface{} = SubFloat(float64(0), angleRange)
		_ = tmp53 // suppress unused
		var tmp54 interface{} = IntToFloat(index)
		_ = tmp54 // suppress unused
		var tmp55 interface{} = MulFloat(tmp54, angleStep)
		_ = tmp55 // suppress unused
		return AddFloat(tmp53, tmp55)
	}()
	var tmp49 interface{} = arcCenterY_impl(struct{}{})
	var tmp50 interface{} = arcRadius_impl(struct{}{})
	var tmp51 interface{} = math.Cos(angle.(float64))
	var tmp52 interface{} = MulFloat(tmp50, tmp51)
	return SubFloat(tmp49, tmp52)
}

func strutBaseY(index int64, total int64) float64 {
	return strutBaseY_impl(index, total).(float64)
}

func strutTopX_impl(index interface{}, total interface{}) interface{} {
	var baseX interface{} = strutBaseX_impl(index, total)
	var centerX interface{} = func() interface{} {
		var tmp61 interface{} = screenWidth_impl(struct{}{})
		_ = tmp61 // suppress unused
		return DivFloat(tmp61, float64(2))
	}()
	var dx interface{} = SubFloat(baseX, centerX)
	var tmp60 interface{} = MulFloat(dx, float64(0.3))
	return AddFloat(baseX, tmp60)
}

func strutTopX(index int64, total int64) float64 {
	return strutTopX_impl(index, total).(float64)
}

func strutTopY_impl(index interface{}, total interface{}) interface{} {
	var baseY interface{} = strutBaseY_impl(index, total)
	return SubFloat(baseY, float64(150))
}

func strutTopY(index int64, total int64) float64 {
	return strutTopY_impl(index, total).(float64)
}

func strutParallax_impl(index interface{}, total interface{}, cameraZ interface{}) interface{} {
	var centerIndex interface{} = func() interface{} {
		var tmp65 interface{} = SubInt(total, int64(1))
		_ = tmp65 // suppress unused
		var tmp66 interface{} = IntToFloat(tmp65)
		_ = tmp66 // suppress unused
		return DivFloat(tmp66, float64(2))
	}()
	var offsetFromCenter interface{} = func() interface{} {
		var tmp64 interface{} = IntToFloat(index)
		_ = tmp64 // suppress unused
		return SubFloat(tmp64, centerIndex)
	}()
	var progress interface{} = func() interface{} {
		var tmp63 interface{} = SubFloat(float64(10), cameraZ)
		_ = tmp63 // suppress unused
		return DivFloat(tmp63, float64(165))
	}()
	var tmp62 interface{} = MulFloat(offsetFromCenter, progress)
	return MulFloat(tmp62, float64(3))
}

func strutParallax(index int64, total int64, cameraZ float64) float64 {
	return strutParallax_impl(index, total, cameraZ).(float64)
}

func renderStrutWithParallax_impl(index interface{}, total interface{}, cameraZ interface{}) interface{} {
	var parallax interface{} = strutParallax_impl(index, total, cameraZ)
	var tmp67 interface{} = strutBaseX_impl(index, total)
	var tmp68 interface{} = strutBaseY_impl(index, total)
	var tmp69 interface{} = strutTopX_impl(index, total)
	var tmp70 interface{} = AddFloat(tmp69, parallax)
	var tmp71 interface{} = strutTopY_impl(index, total)
	var tmp72 interface{} = strutColor_impl(struct{}{})
	var tmp73 interface{} = layerStruts_impl(struct{}{})
	return NewDrawCmdLine(tmp67.(float64), tmp68.(float64), tmp70.(float64), tmp71.(float64), tmp72.(int64), float64(2), tmp73.(int64))
}

func renderStrutWithParallax(index int64, total int64, cameraZ float64) *DrawCmd {
	return renderStrutWithParallax_impl(index, total, cameraZ).(*DrawCmd)
}

func renderStrutsRec_impl(index interface{}, total interface{}, cameraZ interface{}) interface{} {
	var tmp74 interface{} = GeInt(index, total)
	return func() interface{} {
		if tmp74.(bool) {
			return []interface{}{}
		}
		return func() interface{} {
			var tmp75 interface{} = renderStrutWithParallax_impl(index, total, cameraZ)
			_ = tmp75 // suppress unused
			var tmp76 interface{} = AddInt(index, int64(1))
			_ = tmp76 // suppress unused
			var tmp77 interface{} = renderStrutsRec_impl(tmp76, total, cameraZ)
			_ = tmp77 // suppress unused
			return Cons(tmp75, tmp77)
		}()
	}()
}

func renderStrutsRec(index int64, total int64, cameraZ float64) []*DrawCmd {
	return ConvertToDrawCmdSlice(renderStrutsRec_impl(index, total, cameraZ))
}

func renderStruts_impl(state interface{}) interface{} {
	var tmp78 interface{} = strutCount_impl(struct{}{})
	var tmp79 interface{} = FieldGet(state, "domeState")
	var tmp80 interface{} = FieldGet(tmp79, "cameraZ")
	return renderStrutsRec_impl(int64(0), tmp78, tmp80)
}

func RenderStruts(state *BridgeState) []*DrawCmd {
	return ConvertToDrawCmdSlice(renderStruts_impl(state))
}

func tileFloor_impl(_unused0 interface{}) interface{} {
	return int64(1000)
}

func TileFloor() int64 {
	return tileFloor_impl(struct{}{}).(int64)
}

func tileFloorGlow_impl(_unused0 interface{}) interface{} {
	return int64(1001)
}

func TileFloorGlow() int64 {
	return tileFloorGlow_impl(struct{}{}).(int64)
}

func tileConsoleBase_impl(_unused0 interface{}) interface{} {
	return int64(1002)
}

func TileConsoleBase() int64 {
	return tileConsoleBase_impl(struct{}{}).(int64)
}

func tileWalkway_impl(_unused0 interface{}) interface{} {
	return int64(1003)
}

func TileWalkway() int64 {
	return tileWalkway_impl(struct{}{}).(int64)
}

func tileDomeEdge_impl(_unused0 interface{}) interface{} {
	return int64(1004)
}

func TileDomeEdge() int64 {
	return tileDomeEdge_impl(struct{}{}).(int64)
}

func tileWall_impl(_unused0 interface{}) interface{} {
	return int64(1005)
}

func TileWall() int64 {
	return tileWall_impl(struct{}{}).(int64)
}

func tileHatch_impl(_unused0 interface{}) interface{} {
	return int64(1006)
}

func TileHatch() int64 {
	return tileHatch_impl(struct{}{}).(int64)
}

func tileCaptainArea_impl(_unused0 interface{}) interface{} {
	return int64(1007)
}

func TileCaptainArea() int64 {
	return tileCaptainArea_impl(struct{}{}).(int64)
}

func spriteConsoleHelm_impl(_unused0 interface{}) interface{} {
	return int64(1100)
}

func SpriteConsoleHelm() int64 {
	return spriteConsoleHelm_impl(struct{}{}).(int64)
}

func spriteConsoleComms_impl(_unused0 interface{}) interface{} {
	return int64(1101)
}

func SpriteConsoleComms() int64 {
	return spriteConsoleComms_impl(struct{}{}).(int64)
}

func spriteConsoleStatus_impl(_unused0 interface{}) interface{} {
	return int64(1102)
}

func SpriteConsoleStatus() int64 {
	return spriteConsoleStatus_impl(struct{}{}).(int64)
}

func spriteConsoleNav_impl(_unused0 interface{}) interface{} {
	return int64(1103)
}

func SpriteConsoleNav() int64 {
	return spriteConsoleNav_impl(struct{}{}).(int64)
}

func spriteConsoleScience_impl(_unused0 interface{}) interface{} {
	return int64(1104)
}

func SpriteConsoleScience() int64 {
	return spriteConsoleScience_impl(struct{}{}).(int64)
}

func spriteConsoleCaptain_impl(_unused0 interface{}) interface{} {
	return int64(1105)
}

func SpriteConsoleCaptain() int64 {
	return spriteConsoleCaptain_impl(struct{}{}).(int64)
}

func spriteCrewPilot_impl(_unused0 interface{}) interface{} {
	return int64(1200)
}

func SpriteCrewPilot() int64 {
	return spriteCrewPilot_impl(struct{}{}).(int64)
}

func spriteCrewComms_impl(_unused0 interface{}) interface{} {
	return int64(1201)
}

func SpriteCrewComms() int64 {
	return spriteCrewComms_impl(struct{}{}).(int64)
}

func spriteCrewEngineer_impl(_unused0 interface{}) interface{} {
	return int64(1202)
}

func SpriteCrewEngineer() int64 {
	return spriteCrewEngineer_impl(struct{}{}).(int64)
}

func spriteCrewScientist_impl(_unused0 interface{}) interface{} {
	return int64(1203)
}

func SpriteCrewScientist() int64 {
	return spriteCrewScientist_impl(struct{}{}).(int64)
}

func spriteCrewCaptain_impl(_unused0 interface{}) interface{} {
	return int64(1204)
}

func SpriteCrewCaptain() int64 {
	return spriteCrewCaptain_impl(struct{}{}).(int64)
}

func spritePlayer_impl(_unused0 interface{}) interface{} {
	return int64(1205)
}

func SpritePlayer() int64 {
	return spritePlayer_impl(struct{}{}).(int64)
}

func makeCoord_impl(x interface{}, y interface{}) interface{} {
	return &Coord{X: x.(int64), Y: y.(int64)}
}

func makeCoord(x int64, y int64) *Coord {
	return makeCoord_impl(x, y).(*Coord)
}

func distSq_impl(x interface{}, y interface{}, cx interface{}, cy interface{}) interface{} {
	var dx interface{} = SubInt(x, cx)
	var dy interface{} = SubInt(y, cy)
	var tmp81 interface{} = MulInt(dx, dx)
	var tmp82 interface{} = MulInt(dy, dy)
	return AddInt(tmp81, tmp82)
}

func distSq(x int64, y int64, cx int64, cy int64) int64 {
	return distSq_impl(x, y, cx, cy).(int64)
}

func isOnDisc_impl(x interface{}, y interface{}, cx interface{}, cy interface{}, radius interface{}) interface{} {
	var tmp83 interface{} = distSq_impl(x, y, cx, cy)
	var tmp84 interface{} = MulInt(radius, radius)
	return LeInt(tmp83, tmp84)
}

func IsOnDisc(x int64, y int64, cx int64, cy int64, radius int64) bool {
	return isOnDisc_impl(x, y, cx, cy, radius).(bool)
}

func isWalkable_impl(state interface{}, x interface{}, y interface{}) interface{} {
	var dSq interface{} = func() interface{} {
		var tmp87 interface{} = FieldGet(state, "discCenterX")
		_ = tmp87 // suppress unused
		var tmp88 interface{} = FieldGet(state, "discCenterY")
		_ = tmp88 // suppress unused
		return distSq_impl(x, y, tmp87, tmp88)
	}()
	var radiusSq interface{} = func() interface{} {
		var tmp85 interface{} = FieldGet(state, "discRadius")
		_ = tmp85 // suppress unused
		var tmp86 interface{} = FieldGet(state, "discRadius")
		_ = tmp86 // suppress unused
		return MulInt(tmp85, tmp86)
	}()
	return LtInt(dSq, radiusSq)
}

func IsWalkable(state *BridgeState, x int64, y int64) bool {
	return isWalkable_impl(state, x, y).(bool)
}

func getTileType_impl(x interface{}, y interface{}, cx interface{}, cy interface{}, radius interface{}) interface{} {
	var dSq interface{} = distSq_impl(x, y, cx, cy)
	var radiusSq interface{} = MulInt(radius, radius)
	var edgeSq interface{} = func() interface{} {
		var tmp96 interface{} = SubInt(radius, int64(1))
		_ = tmp96 // suppress unused
		var tmp97 interface{} = SubInt(radius, int64(1))
		_ = tmp97 // suppress unused
		return MulInt(tmp96, tmp97)
	}()
	var tmp89 interface{} = GeInt(dSq, radiusSq)
	return func() interface{} {
		var tmp90 interface{} = GeInt(dSq, edgeSq)
		_ = tmp90 // suppress unused
		var tmp91 interface{} = LeInt(dSq, int64(9))
		_ = tmp91 // suppress unused
		var tmp92 interface{} = LeInt(dSq, int64(36))
		_ = tmp92 // suppress unused
		var tmp93 interface{} = AddInt(x, y)
		_ = tmp93 // suppress unused
		var tmp94 interface{} = ModInt(tmp93, int64(8))
		_ = tmp94 // suppress unused
		var tmp95 interface{} = EqInt(tmp94, int64(0))
		_ = tmp95 // suppress unused
		if tmp89.(bool) {
			return tileWall_impl(struct{}{})
		}
		if tmp90.(bool) {
			return tileDomeEdge_impl(struct{}{})
		}
		if tmp91.(bool) {
			return tileCaptainArea_impl(struct{}{})
		}
		if tmp92.(bool) {
			return tileFloorGlow_impl(struct{}{})
		}
		if tmp95.(bool) {
			return tileWalkway_impl(struct{}{})
		}
		return tileFloor_impl(struct{}{})
	}()
}

func GetTileType(x int64, y int64, cx int64, cy int64, radius int64) int64 {
	return getTileType_impl(x, y, cx, cy, radius).(int64)
}

func viewportSize_impl(_unused0 interface{}) interface{} {
	return int64(10)
}

func ViewportSize() int64 {
	return viewportSize_impl(struct{}{}).(int64)
}

func stationSprite_impl(station interface{}) interface{} {
	return func() interface{} {
		_scrutinee := station
		_ = _scrutinee // suppress unused
		_adt := _scrutinee.(*BridgeStation)
		switch _adt.Kind {
		case BridgeStationKindStationHelm:
			return spriteConsoleHelm_impl(struct{}{})
		case BridgeStationKindStationComms:
			return spriteConsoleComms_impl(struct{}{})
		case BridgeStationKindStationStatus:
			return spriteConsoleStatus_impl(struct{}{})
		case BridgeStationKindStationNav:
			return spriteConsoleNav_impl(struct{}{})
		case BridgeStationKindStationScience:
			return spriteConsoleScience_impl(struct{}{})
		case BridgeStationKindStationCaptain:
			return spriteConsoleCaptain_impl(struct{}{})
		case BridgeStationKindStationNone:
			return int64(0)
		default:
			panic("non-exhaustive match")
		}
	}()
}

func StationSprite(station *BridgeStation) int64 {
	return stationSprite_impl(station).(int64)
}

func crewSprite_impl(station interface{}) interface{} {
	return func() interface{} {
		_scrutinee := station
		_ = _scrutinee // suppress unused
		_adt := _scrutinee.(*BridgeStation)
		switch _adt.Kind {
		case BridgeStationKindStationHelm:
			return spriteCrewPilot_impl(struct{}{})
		case BridgeStationKindStationComms:
			return spriteCrewComms_impl(struct{}{})
		case BridgeStationKindStationStatus:
			return spriteCrewEngineer_impl(struct{}{})
		case BridgeStationKindStationScience:
			return spriteCrewScientist_impl(struct{}{})
		case BridgeStationKindStationCaptain:
			return spriteCrewCaptain_impl(struct{}{})
		case BridgeStationKindStationNav:
			return spriteCrewEngineer_impl(struct{}{})
		case BridgeStationKindStationNone:
			return spriteCrewPilot_impl(struct{}{})
		default:
			panic("non-exhaustive match")
		}
	}()
}

func CrewSprite(station *BridgeStation) int64 {
	return crewSprite_impl(station).(int64)
}

func moveInDirection_impl(pos interface{}, dir interface{}) interface{} {
	var px interface{} = FieldGet(pos, "x")
	var py interface{} = FieldGet(pos, "y")
	return func() interface{} {
		_scrutinee := dir
		_ = _scrutinee // suppress unused
		switch _scrutinee {
		default:
			return func() interface{} {
				var tmp98 interface{} = SubInt(py, int64(1))
				_ = tmp98 // suppress unused
				return makeCoord_impl(px, tmp98)
			}()
		}
	}()
}

func MoveInDirection(pos *Coord, dir *Direction) *Coord {
	return moveInDirection_impl(pos, dir).(*Coord)
}

func discRadiusDefault_impl(_unused0 interface{}) interface{} {
	return int64(24)
}

func DiscRadiusDefault() int64 {
	return discRadiusDefault_impl(struct{}{}).(int64)
}

func discCenterDefault_impl(_unused0 interface{}) interface{} {
	return int64(24)
}

func DiscCenterDefault() int64 {
	return discCenterDefault_impl(struct{}{}).(int64)
}

func createConsoles_impl(_unused0 interface{}) interface{} {
	var cx interface{} = discCenterDefault_impl(struct{}{})
	var cy interface{} = discCenterDefault_impl(struct{}{})
	var tmp102 interface{} = SubInt(cy, int64(10))
	var tmp103 interface{} = makeCoord_impl(cx, tmp102)
	var tmp104 interface{} = spriteConsoleHelm_impl(struct{}{})
	var tmp105 interface{} = &ConsoleState{Station: NewBridgeStationStationHelm(), Pos: tmp103.(*Coord), Active: true, HasAlert: false, SpriteId: tmp104.(int64)}
	var tmp106 interface{} = SubInt(cx, int64(8))
	var tmp107 interface{} = SubInt(cy, int64(8))
	var tmp108 interface{} = makeCoord_impl(tmp106, tmp107)
	var tmp109 interface{} = spriteConsoleComms_impl(struct{}{})
	var tmp110 interface{} = &ConsoleState{Station: NewBridgeStationStationComms(), Pos: tmp108.(*Coord), Active: true, HasAlert: false, SpriteId: tmp109.(int64)}
	var tmp111 interface{} = AddInt(cx, int64(8))
	var tmp112 interface{} = SubInt(cy, int64(8))
	var tmp113 interface{} = makeCoord_impl(tmp111, tmp112)
	var tmp114 interface{} = spriteConsoleStatus_impl(struct{}{})
	var tmp115 interface{} = &ConsoleState{Station: NewBridgeStationStationStatus(), Pos: tmp113.(*Coord), Active: true, HasAlert: false, SpriteId: tmp114.(int64)}
	var tmp116 interface{} = makeCoord_impl(cx, cy)
	var tmp117 interface{} = spriteConsoleCaptain_impl(struct{}{})
	var tmp118 interface{} = &ConsoleState{Station: NewBridgeStationStationCaptain(), Pos: tmp116.(*Coord), Active: true, HasAlert: false, SpriteId: tmp117.(int64)}
	var tmp119 interface{} = SubInt(cx, int64(12))
	var tmp120 interface{} = makeCoord_impl(tmp119, cy)
	var tmp121 interface{} = spriteConsoleNav_impl(struct{}{})
	var tmp122 interface{} = &ConsoleState{Station: NewBridgeStationStationNav(), Pos: tmp120.(*Coord), Active: true, HasAlert: false, SpriteId: tmp121.(int64)}
	var tmp123 interface{} = AddInt(cx, int64(12))
	var tmp124 interface{} = makeCoord_impl(tmp123, cy)
	var tmp125 interface{} = spriteConsoleScience_impl(struct{}{})
	var tmp126 interface{} = &ConsoleState{Station: NewBridgeStationStationScience(), Pos: tmp124.(*Coord), Active: true, HasAlert: false, SpriteId: tmp125.(int64)}
	return []interface{}{tmp105, tmp110, tmp115, tmp118, tmp122, tmp126}
}

func CreateConsoles() []*ConsoleState {
	return ConvertToConsoleStateSlice(createConsoles_impl(struct{}{}))
}

func createDefaultCrew_impl(_unused0 interface{}) interface{} {
	var cx interface{} = discCenterDefault_impl(struct{}{})
	var cy interface{} = discCenterDefault_impl(struct{}{})
	var tmp127 interface{} = &CrewID{Id: int64(1), Name: "Pilot Chen"}
	var tmp128 interface{} = SubInt(cy, int64(9))
	var tmp129 interface{} = makeCoord_impl(cx, tmp128)
	var tmp130 interface{} = &CrewPosition{Crew: tmp127.(*CrewID), Station: NewBridgeStationStationHelm(), Pos: tmp129.(*Coord), Facing: NewDirectionNorth(), Activity: NewCrewActivityActivityWorking()}
	var tmp131 interface{} = &CrewID{Id: int64(2), Name: "Comms Officer Patel"}
	var tmp132 interface{} = SubInt(cx, int64(8))
	var tmp133 interface{} = SubInt(cy, int64(7))
	var tmp134 interface{} = makeCoord_impl(tmp132, tmp133)
	var tmp135 interface{} = &CrewPosition{Crew: tmp131.(*CrewID), Station: NewBridgeStationStationComms(), Pos: tmp134.(*Coord), Facing: NewDirectionNorth(), Activity: NewCrewActivityActivityWorking()}
	var tmp136 interface{} = &CrewID{Id: int64(3), Name: "Engineer Torres"}
	var tmp137 interface{} = AddInt(cx, int64(8))
	var tmp138 interface{} = SubInt(cy, int64(7))
	var tmp139 interface{} = makeCoord_impl(tmp137, tmp138)
	var tmp140 interface{} = &CrewPosition{Crew: tmp136.(*CrewID), Station: NewBridgeStationStationStatus(), Pos: tmp139.(*Coord), Facing: NewDirectionNorth(), Activity: NewCrewActivityActivityWorking()}
	var tmp141 interface{} = &CrewID{Id: int64(4), Name: "Navigator Kim"}
	var tmp142 interface{} = SubInt(cx, int64(11))
	var tmp143 interface{} = makeCoord_impl(tmp142, cy)
	var tmp144 interface{} = &CrewPosition{Crew: tmp141.(*CrewID), Station: NewBridgeStationStationNav(), Pos: tmp143.(*Coord), Facing: NewDirectionEast(), Activity: NewCrewActivityActivityWorking()}
	var tmp145 interface{} = &CrewID{Id: int64(5), Name: "Science Officer Okafor"}
	var tmp146 interface{} = AddInt(cx, int64(11))
	var tmp147 interface{} = makeCoord_impl(tmp146, cy)
	var tmp148 interface{} = &CrewPosition{Crew: tmp145.(*CrewID), Station: NewBridgeStationStationScience(), Pos: tmp147.(*Coord), Facing: NewDirectionWest(), Activity: NewCrewActivityActivityWorking()}
	var tmp149 interface{} = &CrewID{Id: int64(6), Name: "Captain Reyes"}
	var tmp150 interface{} = AddInt(cy, int64(1))
	var tmp151 interface{} = makeCoord_impl(cx, tmp150)
	var tmp152 interface{} = &CrewPosition{Crew: tmp149.(*CrewID), Station: NewBridgeStationStationCaptain(), Pos: tmp151.(*Coord), Facing: NewDirectionNorth(), Activity: NewCrewActivityActivityIdle()}
	return []interface{}{tmp130, tmp135, tmp140, tmp144, tmp148, tmp152}
}

func CreateDefaultCrew() []*CrewPosition {
	return ConvertToCrewPositionSlice(createDefaultCrew_impl(struct{}{}))
}

func initBridge_impl(_unused0 interface{}) interface{} {
	var cx interface{} = discCenterDefault_impl(struct{}{})
	var cy interface{} = discCenterDefault_impl(struct{}{})
	var radius interface{} = discRadiusDefault_impl(struct{}{})
	var tmp153 interface{} = AddInt(cy, int64(16))
	var tmp154 interface{} = makeCoord_impl(cx, tmp153)
	var tmp155 interface{} = AddInt(cy, int64(16))
	var tmp156 interface{} = createDefaultCrew_impl(struct{}{})
	var tmp157 interface{} = createConsoles_impl(struct{}{})
	var tmp158 interface{} = makeDomeViewState_impl(int64(0), float64(0.15), float64(0))
	var tmp159 interface{} = initDomeState_impl(struct{}{})
	return &BridgeState{PlayerPos: tmp154.(*Coord), PlayerFacing: NewDirectionNorth(), MoveState: NewMoveStateMoveIdle(), CameraX: cx.(int64), CameraY: tmp155.(int64), CrewPositions: ConvertToCrewPositionSlice(tmp156), Consoles: ConvertToConsoleStateSlice(tmp157), HoveredInteractable: NewOptionNone(), SelectedInteractable: NewOptionNone(), DomeView: tmp158.(*DomeViewState), DomeState: tmp159.(*DomeState), Tick: int64(0), DiscRadius: radius.(int64), DiscCenterX: cx.(int64), DiscCenterY: cy.(int64)}
}

func InitBridge() *BridgeState {
	return initBridge_impl(struct{}{}).(*BridgeState)
}

func layerFloor_impl(_unused0 interface{}) interface{} {
	return int64(0)
}

func layerFloor() int64 {
	return layerFloor_impl(struct{}{}).(int64)
}

func layerConsoles_impl(_unused0 interface{}) interface{} {
	return int64(1)
}

func layerConsoles() int64 {
	return layerConsoles_impl(struct{}{}).(int64)
}

func layerCrew_impl(_unused0 interface{}) interface{} {
	return int64(2)
}

func layerCrew() int64 {
	return layerCrew_impl(struct{}{}).(int64)
}

func layerPlayer_impl(_unused0 interface{}) interface{} {
	return int64(3)
}

func layerPlayer() int64 {
	return layerPlayer_impl(struct{}{}).(int64)
}

func layerPlanets3D_impl(_unused0 interface{}) interface{} {
	return int64(4)
}

func layerPlanets3D() int64 {
	return layerPlanets3D_impl(struct{}{}).(int64)
}

func layerUI_impl(_unused0 interface{}) interface{} {
	return int64(100)
}

func layerUI() int64 {
	return layerUI_impl(struct{}{}).(int64)
}

func colorWhite_impl(_unused0 interface{}) interface{} {
	return int64(4294967295)
}

func colorWhite() int64 {
	return colorWhite_impl(struct{}{}).(int64)
}

func screenOffsetX_impl(_unused0 interface{}) interface{} {
	return float64(640)
}

func screenOffsetX() float64 {
	return screenOffsetX_impl(struct{}{}).(float64)
}

func screenOffsetY_impl(_unused0 interface{}) interface{} {
	return float64(750)
}

func screenOffsetY() float64 {
	return screenOffsetY_impl(struct{}{}).(float64)
}

func tileColor_impl(tileType interface{}) interface{} {
	var tmp160 interface{} = tileWall_impl(struct{}{})
	var tmp161 interface{} = EqInt(tileType, tmp160)
	return func() interface{} {
		var tmp162 interface{} = tileDomeEdge_impl(struct{}{})
		_ = tmp162 // suppress unused
		var tmp163 interface{} = EqInt(tileType, tmp162)
		_ = tmp163 // suppress unused
		var tmp164 interface{} = tileCaptainArea_impl(struct{}{})
		_ = tmp164 // suppress unused
		var tmp165 interface{} = EqInt(tileType, tmp164)
		_ = tmp165 // suppress unused
		var tmp166 interface{} = tileFloorGlow_impl(struct{}{})
		_ = tmp166 // suppress unused
		var tmp167 interface{} = EqInt(tileType, tmp166)
		_ = tmp167 // suppress unused
		var tmp168 interface{} = tileWalkway_impl(struct{}{})
		_ = tmp168 // suppress unused
		var tmp169 interface{} = EqInt(tileType, tmp168)
		_ = tmp169 // suppress unused
		if tmp161.(bool) {
			return colorWall_impl(struct{}{})
		}
		if tmp163.(bool) {
			return colorDomeEdge_impl(struct{}{})
		}
		if tmp165.(bool) {
			return colorCaptainArea_impl(struct{}{})
		}
		if tmp167.(bool) {
			return colorFloorGlow_impl(struct{}{})
		}
		if tmp169.(bool) {
			return colorWalkway_impl(struct{}{})
		}
		return colorFloor_impl(struct{}{})
	}()
}

func tileColor(tileType int64) int64 {
	return tileColor_impl(tileType).(int64)
}

func renderTileAt_impl(worldX interface{}, worldY interface{}, camX interface{}, camY interface{}, tileType interface{}) interface{} {
	var relX interface{} = SubInt(worldX, camX)
	var relY interface{} = SubInt(worldY, camY)
	var isoX interface{} = func() interface{} {
		var tmp178 interface{} = SubInt(relX, relY)
		_ = tmp178 // suppress unused
		var tmp179 interface{} = MulInt(tmp178, int64(32))
		_ = tmp179 // suppress unused
		return IntToFloat(tmp179)
	}()
	var isoY interface{} = func() interface{} {
		var tmp176 interface{} = AddInt(relX, relY)
		_ = tmp176 // suppress unused
		var tmp177 interface{} = MulInt(tmp176, int64(16))
		_ = tmp177 // suppress unused
		return IntToFloat(tmp177)
	}()
	var screenX interface{} = func() interface{} {
		var tmp175 interface{} = screenOffsetX_impl(struct{}{})
		_ = tmp175 // suppress unused
		return AddFloat(isoX, tmp175)
	}()
	var screenY interface{} = func() interface{} {
		var tmp174 interface{} = screenOffsetY_impl(struct{}{})
		_ = tmp174 // suppress unused
		return AddFloat(isoY, tmp174)
	}()
	var tmp170 interface{} = SubFloat(screenX, float64(28))
	var tmp171 interface{} = SubFloat(screenY, float64(12))
	var tmp172 interface{} = tileColor_impl(tileType)
	var tmp173 interface{} = layerFloor_impl(struct{}{})
	return NewDrawCmdRectRGBA(tmp170.(float64), tmp171.(float64), float64(56), float64(28), tmp172.(int64), tmp173.(int64))
}

func renderTileAt(worldX int64, worldY int64, camX int64, camY int64, tileType int64) *DrawCmd {
	return renderTileAt_impl(worldX, worldY, camX, camY, tileType).(*DrawCmd)
}

func renderFloorRowViewportRec_impl(state interface{}, x interface{}, y interface{}, maxX interface{}, acc interface{}) interface{} {
	var tmp180 interface{} = GtInt(x, maxX)
	return func() interface{} {
		if tmp180.(bool) {
			return acc
		}
		return func() interface{} {
			var tmp181 interface{} = AddInt(x, int64(1))
			_ = tmp181 // suppress unused
			var tmp182 interface{} = FieldGet(state, "cameraX")
			_ = tmp182 // suppress unused
			var tmp183 interface{} = FieldGet(state, "cameraY")
			_ = tmp183 // suppress unused
			var tmp184 interface{} = FieldGet(state, "discCenterX")
			_ = tmp184 // suppress unused
			var tmp185 interface{} = FieldGet(state, "discCenterY")
			_ = tmp185 // suppress unused
			var tmp186 interface{} = FieldGet(state, "discRadius")
			_ = tmp186 // suppress unused
			var tmp187 interface{} = getTileType_impl(x, y, tmp184, tmp185, tmp186)
			_ = tmp187 // suppress unused
			var tmp188 interface{} = renderTileAt_impl(x, y, tmp182, tmp183, tmp187)
			_ = tmp188 // suppress unused
			var tmp189 interface{} = Cons(tmp188, acc)
			_ = tmp189 // suppress unused
			return renderFloorRowViewportRec_impl(state, tmp181, y, maxX, tmp189)
		}()
	}()
}

func renderFloorRowViewportRec(state *BridgeState, x int64, y int64, maxX int64, acc []*DrawCmd) []*DrawCmd {
	return ConvertToDrawCmdSlice(renderFloorRowViewportRec_impl(state, x, y, maxX, acc))
}

func renderFloorRowViewport_impl(state interface{}, x interface{}, y interface{}, maxX interface{}) interface{} {
	var tmp190 interface{} = []interface{}{}
	return renderFloorRowViewportRec_impl(state, x, y, maxX, tmp190)
}

func renderFloorRowViewport(state *BridgeState, x int64, y int64, maxX int64) []*DrawCmd {
	return ConvertToDrawCmdSlice(renderFloorRowViewport_impl(state, x, y, maxX))
}

func renderFloorRowsViewport_impl(state interface{}, y interface{}, maxY interface{}, minX interface{}, maxX interface{}) interface{} {
	var tmp191 interface{} = GtInt(y, maxY)
	return func() interface{} {
		if tmp191.(bool) {
			return []interface{}{}
		}
		return func() interface{} {
			var tmp192 interface{} = renderFloorRowViewport_impl(state, minX, y, maxX)
			_ = tmp192 // suppress unused
			var tmp193 interface{} = AddInt(y, int64(1))
			_ = tmp193 // suppress unused
			var tmp194 interface{} = renderFloorRowsViewport_impl(state, tmp193, maxY, minX, maxX)
			_ = tmp194 // suppress unused
			return Concat(tmp192, tmp194)
		}()
	}()
}

func renderFloorRowsViewport(state *BridgeState, y int64, maxY int64, minX int64, maxX int64) []*DrawCmd {
	return ConvertToDrawCmdSlice(renderFloorRowsViewport_impl(state, y, maxY, minX, maxX))
}

func renderBridgeFloor_impl(state interface{}) interface{} {
	var vp interface{} = viewportSize_impl(struct{}{})
	var minX interface{} = func() interface{} {
		var tmp198 interface{} = FieldGet(state, "cameraX")
		_ = tmp198 // suppress unused
		return SubInt(tmp198, vp)
	}()
	var maxX interface{} = func() interface{} {
		var tmp197 interface{} = FieldGet(state, "cameraX")
		_ = tmp197 // suppress unused
		return AddInt(tmp197, vp)
	}()
	var minY interface{} = func() interface{} {
		var tmp196 interface{} = FieldGet(state, "cameraY")
		_ = tmp196 // suppress unused
		return SubInt(tmp196, vp)
	}()
	var maxY interface{} = func() interface{} {
		var tmp195 interface{} = FieldGet(state, "cameraY")
		_ = tmp195 // suppress unused
		return AddInt(tmp195, vp)
	}()
	return renderFloorRowsViewport_impl(state, minY, maxY, minX, maxX)
}

func RenderBridgeFloor(state *BridgeState) []*DrawCmd {
	return ConvertToDrawCmdSlice(renderBridgeFloor_impl(state))
}

func inViewport_impl(wx interface{}, wy interface{}, camX interface{}, camY interface{}) interface{} {
	var vp interface{} = viewportSize_impl(struct{}{})
	var dx interface{} = SubInt(wx, camX)
	var dy interface{} = SubInt(wy, camY)
	var tmp199 interface{} = SubInt(int64(0), vp)
	var tmp200 interface{} = SubInt(tmp199, int64(2))
	var tmp201 interface{} = GeInt(dx, tmp200)
	var tmp202 interface{} = AddInt(vp, int64(2))
	var tmp203 interface{} = LeInt(dx, tmp202)
	var tmp204 interface{} = func() interface{} {
		if tmp201.(bool) {
			return tmp203
		}
		return false
	}()
	var tmp205 interface{} = SubInt(int64(0), vp)
	var tmp206 interface{} = SubInt(tmp205, int64(2))
	var tmp207 interface{} = GeInt(dy, tmp206)
	var tmp208 interface{} = func() interface{} {
		if tmp204.(bool) {
			return tmp207
		}
		return false
	}()
	var tmp209 interface{} = AddInt(vp, int64(2))
	var tmp210 interface{} = LeInt(dy, tmp209)
	return func() interface{} {
		if tmp208.(bool) {
			return tmp210
		}
		return false
	}()
}

func inViewport(wx int64, wy int64, camX int64, camY int64) bool {
	return inViewport_impl(wx, wy, camX, camY).(bool)
}

func consoleColor_impl(station interface{}) interface{} {
	return func() interface{} {
		_scrutinee := station
		_ = _scrutinee // suppress unused
		_adt := _scrutinee.(*BridgeStation)
		switch _adt.Kind {
		case BridgeStationKindStationHelm:
			return colorHelm_impl(struct{}{})
		case BridgeStationKindStationComms:
			return colorComms_impl(struct{}{})
		case BridgeStationKindStationStatus:
			return colorStatus_impl(struct{}{})
		case BridgeStationKindStationNav:
			return colorNav_impl(struct{}{})
		case BridgeStationKindStationScience:
			return colorScience_impl(struct{}{})
		case BridgeStationKindStationCaptain:
			return colorCaptain_impl(struct{}{})
		case BridgeStationKindStationNone:
			return colorFloor_impl(struct{}{})
		default:
			panic("non-exhaustive match")
		}
	}()
}

func consoleColor(station *BridgeStation) int64 {
	return consoleColor_impl(station).(int64)
}

func crewColor_impl(station interface{}) interface{} {
	return func() interface{} {
		_scrutinee := station
		_ = _scrutinee // suppress unused
		_adt := _scrutinee.(*BridgeStation)
		switch _adt.Kind {
		case BridgeStationKindStationHelm:
			return colorCrewPilot_impl(struct{}{})
		case BridgeStationKindStationComms:
			return colorCrewComms_impl(struct{}{})
		case BridgeStationKindStationStatus:
			return colorCrewEngineer_impl(struct{}{})
		case BridgeStationKindStationNav:
			return colorCrewEngineer_impl(struct{}{})
		case BridgeStationKindStationScience:
			return colorCrewScientist_impl(struct{}{})
		case BridgeStationKindStationCaptain:
			return colorCrewCaptain_impl(struct{}{})
		case BridgeStationKindStationNone:
			return colorPlayer_impl(struct{}{})
		default:
			panic("non-exhaustive match")
		}
	}()
}

func crewColor(station *BridgeStation) int64 {
	return crewColor_impl(station).(int64)
}

func renderConsole_impl(console interface{}, camX interface{}, camY interface{}) interface{} {
	var relX interface{} = func() interface{} {
		var tmp224 interface{} = FieldGet(console, "pos")
		_ = tmp224 // suppress unused
		var tmp225 interface{} = FieldGet(tmp224, "x")
		_ = tmp225 // suppress unused
		return SubInt(tmp225, camX)
	}()
	var relY interface{} = func() interface{} {
		var tmp222 interface{} = FieldGet(console, "pos")
		_ = tmp222 // suppress unused
		var tmp223 interface{} = FieldGet(tmp222, "y")
		_ = tmp223 // suppress unused
		return SubInt(tmp223, camY)
	}()
	var isoX interface{} = func() interface{} {
		var tmp220 interface{} = SubInt(relX, relY)
		_ = tmp220 // suppress unused
		var tmp221 interface{} = MulInt(tmp220, int64(32))
		_ = tmp221 // suppress unused
		return IntToFloat(tmp221)
	}()
	var isoY interface{} = func() interface{} {
		var tmp218 interface{} = AddInt(relX, relY)
		_ = tmp218 // suppress unused
		var tmp219 interface{} = MulInt(tmp218, int64(16))
		_ = tmp219 // suppress unused
		return IntToFloat(tmp219)
	}()
	var screenX interface{} = func() interface{} {
		var tmp217 interface{} = screenOffsetX_impl(struct{}{})
		_ = tmp217 // suppress unused
		return AddFloat(isoX, tmp217)
	}()
	var screenY interface{} = func() interface{} {
		var tmp216 interface{} = screenOffsetY_impl(struct{}{})
		_ = tmp216 // suppress unused
		return AddFloat(isoY, tmp216)
	}()
	var color interface{} = func() interface{} {
		var tmp215 interface{} = FieldGet(console, "station")
		_ = tmp215 // suppress unused
		return consoleColor_impl(tmp215)
	}()
	var tmp211 interface{} = SubFloat(screenX, float64(24))
	var tmp212 interface{} = SubFloat(screenY, float64(32))
	var tmp213 interface{} = layerConsoles_impl(struct{}{})
	var tmp214 interface{} = NewDrawCmdRectRGBA(tmp211.(float64), tmp212.(float64), float64(48), float64(24), color.(int64), tmp213.(int64))
	return []interface{}{tmp214}
}

func renderConsole(console *ConsoleState, camX int64, camY int64) []*DrawCmd {
	return ConvertToDrawCmdSlice(renderConsole_impl(console, camX, camY))
}

func renderConsolesRec_impl(consoles interface{}, camX interface{}, camY interface{}) interface{} {
	return func() interface{} {
		_scrutinee := consoles
		_ = _scrutinee // suppress unused
		if ListLen(_scrutinee) == 0 {
			return []interface{}{}
		} else if ListLen(_scrutinee) >= 1 {
			c := ListHead(_scrutinee)
			_ = c // suppress unused
			rest := ListTail(_scrutinee)
			_ = rest // suppress unused
			return func() interface{} {
				var tmp226 interface{} = FieldGet(c, "pos")
				_ = tmp226 // suppress unused
				var tmp227 interface{} = FieldGet(tmp226, "x")
				_ = tmp227 // suppress unused
				var tmp228 interface{} = FieldGet(c, "pos")
				_ = tmp228 // suppress unused
				var tmp229 interface{} = FieldGet(tmp228, "y")
				_ = tmp229 // suppress unused
				var tmp230 interface{} = inViewport_impl(tmp227, tmp229, camX, camY)
				_ = tmp230 // suppress unused
				return func() interface{} {
					if tmp230.(bool) {
						return func() interface{} {
							var tmp231 interface{} = renderConsole_impl(c, camX, camY)
							_ = tmp231 // suppress unused
							return func() interface{} {
								var tmp232 interface{} = renderConsolesRec_impl(rest, camX, camY)
								_ = tmp232 // suppress unused
								return Concat(tmp231, tmp232)
							}()
						}()
					}
					return renderConsolesRec_impl(rest, camX, camY)
				}()
			}()
		} else {
			panic("non-exhaustive match")
		}
	}()
}

func renderConsolesRec(consoles []*ConsoleState, camX int64, camY int64) []*DrawCmd {
	return ConvertToDrawCmdSlice(renderConsolesRec_impl(consoles, camX, camY))
}

func renderConsoles_impl(state interface{}) interface{} {
	var tmp233 interface{} = FieldGet(state, "consoles")
	var tmp234 interface{} = FieldGet(state, "cameraX")
	var tmp235 interface{} = FieldGet(state, "cameraY")
	return renderConsolesRec_impl(tmp233, tmp234, tmp235)
}

func RenderConsoles(state *BridgeState) []*DrawCmd {
	return ConvertToDrawCmdSlice(renderConsoles_impl(state))
}

func renderCrewMember_impl(crew interface{}, camX interface{}, camY interface{}) interface{} {
	var relX interface{} = func() interface{} {
		var tmp255 interface{} = FieldGet(crew, "pos")
		_ = tmp255 // suppress unused
		var tmp256 interface{} = FieldGet(tmp255, "x")
		_ = tmp256 // suppress unused
		return SubInt(tmp256, camX)
	}()
	var relY interface{} = func() interface{} {
		var tmp253 interface{} = FieldGet(crew, "pos")
		_ = tmp253 // suppress unused
		var tmp254 interface{} = FieldGet(tmp253, "y")
		_ = tmp254 // suppress unused
		return SubInt(tmp254, camY)
	}()
	var isoX interface{} = func() interface{} {
		var tmp251 interface{} = SubInt(relX, relY)
		_ = tmp251 // suppress unused
		var tmp252 interface{} = MulInt(tmp251, int64(32))
		_ = tmp252 // suppress unused
		return IntToFloat(tmp252)
	}()
	var isoY interface{} = func() interface{} {
		var tmp249 interface{} = AddInt(relX, relY)
		_ = tmp249 // suppress unused
		var tmp250 interface{} = MulInt(tmp249, int64(16))
		_ = tmp250 // suppress unused
		return IntToFloat(tmp250)
	}()
	var screenX interface{} = func() interface{} {
		var tmp248 interface{} = screenOffsetX_impl(struct{}{})
		_ = tmp248 // suppress unused
		return AddFloat(isoX, tmp248)
	}()
	var screenY interface{} = func() interface{} {
		var tmp247 interface{} = screenOffsetY_impl(struct{}{})
		_ = tmp247 // suppress unused
		return AddFloat(isoY, tmp247)
	}()
	var color interface{} = func() interface{} {
		var tmp246 interface{} = FieldGet(crew, "station")
		_ = tmp246 // suppress unused
		return crewColor_impl(tmp246)
	}()
	var tmp236 interface{} = SubFloat(screenY, float64(8))
	var tmp237 interface{} = layerCrew_impl(struct{}{})
	var tmp238 interface{} = NewDrawCmdCircleRGBA(screenX.(float64), tmp236.(float64), float64(12), color.(int64), true, tmp237.(int64))
	var tmp239 interface{} = FieldGet(crew, "crew")
	var tmp240 interface{} = FieldGet(tmp239, "name")
	var tmp241 interface{} = SubFloat(screenX, float64(30))
	var tmp242 interface{} = AddFloat(screenY, float64(8))
	var tmp243 interface{} = layerCrew_impl(struct{}{})
	var tmp244 interface{} = AddInt(tmp243, int64(1))
	var tmp245 interface{} = NewDrawCmdText(tmp240.(string), tmp241.(float64), tmp242.(float64), int64(8), int64(4294967295), tmp244.(int64))
	return []interface{}{tmp238, tmp245}
}

func renderCrewMember(crew *CrewPosition, camX int64, camY int64) []*DrawCmd {
	return ConvertToDrawCmdSlice(renderCrewMember_impl(crew, camX, camY))
}

func renderCrewRec_impl(crew interface{}, camX interface{}, camY interface{}) interface{} {
	return func() interface{} {
		_scrutinee := crew
		_ = _scrutinee // suppress unused
		if ListLen(_scrutinee) == 0 {
			return []interface{}{}
		} else if ListLen(_scrutinee) >= 1 {
			c := ListHead(_scrutinee)
			_ = c // suppress unused
			rest := ListTail(_scrutinee)
			_ = rest // suppress unused
			return func() interface{} {
				var tmp257 interface{} = FieldGet(c, "pos")
				_ = tmp257 // suppress unused
				var tmp258 interface{} = FieldGet(tmp257, "x")
				_ = tmp258 // suppress unused
				var tmp259 interface{} = FieldGet(c, "pos")
				_ = tmp259 // suppress unused
				var tmp260 interface{} = FieldGet(tmp259, "y")
				_ = tmp260 // suppress unused
				var tmp261 interface{} = inViewport_impl(tmp258, tmp260, camX, camY)
				_ = tmp261 // suppress unused
				return func() interface{} {
					if tmp261.(bool) {
						return func() interface{} {
							var tmp262 interface{} = renderCrewMember_impl(c, camX, camY)
							_ = tmp262 // suppress unused
							return func() interface{} {
								var tmp263 interface{} = renderCrewRec_impl(rest, camX, camY)
								_ = tmp263 // suppress unused
								return Concat(tmp262, tmp263)
							}()
						}()
					}
					return renderCrewRec_impl(rest, camX, camY)
				}()
			}()
		} else {
			panic("non-exhaustive match")
		}
	}()
}

func renderCrewRec(crew []*CrewPosition, camX int64, camY int64) []*DrawCmd {
	return ConvertToDrawCmdSlice(renderCrewRec_impl(crew, camX, camY))
}

func renderBridgeCrew_impl(state interface{}) interface{} {
	var tmp264 interface{} = FieldGet(state, "crewPositions")
	var tmp265 interface{} = FieldGet(state, "cameraX")
	var tmp266 interface{} = FieldGet(state, "cameraY")
	return renderCrewRec_impl(tmp264, tmp265, tmp266)
}

func RenderBridgeCrew(state *BridgeState) []*DrawCmd {
	return ConvertToDrawCmdSlice(renderBridgeCrew_impl(state))
}

func renderPlayer_impl(state interface{}) interface{} {
	var relX interface{} = func() interface{} {
		var tmp287 interface{} = FieldGet(state, "playerPos")
		_ = tmp287 // suppress unused
		var tmp288 interface{} = FieldGet(tmp287, "x")
		_ = tmp288 // suppress unused
		var tmp289 interface{} = FieldGet(state, "cameraX")
		_ = tmp289 // suppress unused
		return SubInt(tmp288, tmp289)
	}()
	var relY interface{} = func() interface{} {
		var tmp284 interface{} = FieldGet(state, "playerPos")
		_ = tmp284 // suppress unused
		var tmp285 interface{} = FieldGet(tmp284, "y")
		_ = tmp285 // suppress unused
		var tmp286 interface{} = FieldGet(state, "cameraY")
		_ = tmp286 // suppress unused
		return SubInt(tmp285, tmp286)
	}()
	var isoX interface{} = func() interface{} {
		var tmp282 interface{} = SubInt(relX, relY)
		_ = tmp282 // suppress unused
		var tmp283 interface{} = MulInt(tmp282, int64(32))
		_ = tmp283 // suppress unused
		return IntToFloat(tmp283)
	}()
	var isoY interface{} = func() interface{} {
		var tmp280 interface{} = AddInt(relX, relY)
		_ = tmp280 // suppress unused
		var tmp281 interface{} = MulInt(tmp280, int64(16))
		_ = tmp281 // suppress unused
		return IntToFloat(tmp281)
	}()
	var screenX interface{} = func() interface{} {
		var tmp279 interface{} = screenOffsetX_impl(struct{}{})
		_ = tmp279 // suppress unused
		return AddFloat(isoX, tmp279)
	}()
	var screenY interface{} = func() interface{} {
		var tmp278 interface{} = screenOffsetY_impl(struct{}{})
		_ = tmp278 // suppress unused
		return AddFloat(isoY, tmp278)
	}()
	var tmp267 interface{} = SubFloat(screenX, float64(10))
	var tmp268 interface{} = SubFloat(screenY, float64(18))
	var tmp269 interface{} = colorPlayer_impl(struct{}{})
	var tmp270 interface{} = layerPlayer_impl(struct{}{})
	var tmp271 interface{} = NewDrawCmdRectRGBA(tmp267.(float64), tmp268.(float64), float64(20), float64(20), tmp269.(int64), tmp270.(int64))
	var tmp272 interface{} = SubFloat(screenX, float64(12))
	var tmp273 interface{} = AddFloat(screenY, float64(8))
	var tmp274 interface{} = colorPlayer_impl(struct{}{})
	var tmp275 interface{} = layerPlayer_impl(struct{}{})
	var tmp276 interface{} = AddInt(tmp275, int64(1))
	var tmp277 interface{} = NewDrawCmdText("YOU", tmp272.(float64), tmp273.(float64), int64(10), tmp274.(int64), tmp276.(int64))
	return []interface{}{tmp271, tmp277}
}

func RenderPlayer(state *BridgeState) []*DrawCmd {
	return ConvertToDrawCmdSlice(renderPlayer_impl(state))
}

func stationName_impl(station interface{}) interface{} {
	return func() interface{} {
		_scrutinee := station
		_ = _scrutinee // suppress unused
		_adt := _scrutinee.(*BridgeStation)
		switch _adt.Kind {
		case BridgeStationKindStationHelm:
			return "HELM"
		case BridgeStationKindStationComms:
			return "COMMS"
		case BridgeStationKindStationStatus:
			return "STATUS"
		case BridgeStationKindStationScience:
			return "SCIENCE"
		default:
			stationWeapons := _adt
			_ = stationWeapons // suppress unused
			return "WEAPONS"
		}
	}()
}

func stationName(station *BridgeStation) string {
	return stationName_impl(station).(string)
}

func colorDarkBg_impl(_unused0 interface{}) interface{} {
	return int64(540029132)
}

func colorDarkBg() int64 {
	return colorDarkBg_impl(struct{}{}).(int64)
}

func colorYellow_impl(_unused0 interface{}) interface{} {
	return int64(4293559551)
}

func colorYellow() int64 {
	return colorYellow_impl(struct{}{}).(int64)
}

func colorPanelBg_impl(_unused0 interface{}) interface{} {
	return int64(270545120)
}

func colorPanelBg() int64 {
	return colorPanelBg_impl(struct{}{}).(int64)
}

func colorUIGreen_impl(_unused0 interface{}) interface{} {
	return int64(1157595391)
}

func colorUIGreen() int64 {
	return colorUIGreen_impl(struct{}{}).(int64)
}

func colorUIGray_impl(_unused0 interface{}) interface{} {
	return int64(2290649343)
}

func colorUIGray() int64 {
	return colorUIGray_impl(struct{}{}).(int64)
}

func renderInteractionPrompt_impl(state interface{}) interface{} {
	var tmp290 interface{} = FieldGet(state, "hoveredInteractable")
	return func() interface{} {
		_scrutinee := tmp290
		_ = _scrutinee // suppress unused
		_adt := _scrutinee.(*Option)
		switch _adt.Kind {
		default:
			none := _adt
			_ = none // suppress unused
			return []interface{}{}
		case OptionKindSome:
			interactable := _adt.Some.Value0
			_ = interactable // suppress unused
			return func() interface{} {
				_scrutinee := interactable
				_ = _scrutinee // suppress unused
				_adt := _scrutinee
				switch _adt.Kind {
				case InteractableIDKindInteractConsole:
					station := _adt.InteractConsole.Value0
					_ = station // suppress unused
					return func() interface{} {
						var tmp291 interface{} = colorDarkBg_impl(struct{}{})
						_ = tmp291 // suppress unused
						var tmp292 interface{} = layerUI_impl(struct{}{})
						_ = tmp292 // suppress unused
						var tmp293 interface{} = NewDrawCmdRectRGBA(float64(480), float64(650), float64(320), float64(40), tmp291.(int64), tmp292.(int64))
						_ = tmp293 // suppress unused
						var tmp294 interface{} = colorYellow_impl(struct{}{})
						_ = tmp294 // suppress unused
						var tmp295 interface{} = layerUI_impl(struct{}{})
						_ = tmp295 // suppress unused
						var tmp296 interface{} = AddInt(tmp295, int64(1))
						_ = tmp296 // suppress unused
						var tmp297 interface{} = NewDrawCmdText("Press E: Interact", float64(530), float64(665), int64(12), tmp294.(int64), tmp296.(int64))
						_ = tmp297 // suppress unused
						return []interface{}{tmp293, tmp297}
					}()
				case InteractableIDKindInteractCrew:
					crew := _adt.InteractCrew.Value0
					_ = crew // suppress unused
					return func() interface{} {
						var tmp298 interface{} = colorDarkBg_impl(struct{}{})
						_ = tmp298 // suppress unused
						var tmp299 interface{} = layerUI_impl(struct{}{})
						_ = tmp299 // suppress unused
						var tmp300 interface{} = NewDrawCmdRectRGBA(float64(480), float64(650), float64(320), float64(40), tmp298.(int64), tmp299.(int64))
						_ = tmp300 // suppress unused
						var tmp301 interface{} = colorYellow_impl(struct{}{})
						_ = tmp301 // suppress unused
						var tmp302 interface{} = layerUI_impl(struct{}{})
						_ = tmp302 // suppress unused
						var tmp303 interface{} = AddInt(tmp302, int64(1))
						_ = tmp303 // suppress unused
						var tmp304 interface{} = NewDrawCmdText("Press E: Talk", float64(530), float64(665), int64(12), tmp301.(int64), tmp303.(int64))
						_ = tmp304 // suppress unused
						return []interface{}{tmp300, tmp304}
					}()
				case InteractableIDKindInteractHatch:
					deck := _adt.InteractHatch.Value0
					_ = deck // suppress unused
					return func() interface{} {
						var tmp305 interface{} = colorDarkBg_impl(struct{}{})
						_ = tmp305 // suppress unused
						var tmp306 interface{} = layerUI_impl(struct{}{})
						_ = tmp306 // suppress unused
						var tmp307 interface{} = NewDrawCmdRectRGBA(float64(480), float64(650), float64(320), float64(40), tmp305.(int64), tmp306.(int64))
						_ = tmp307 // suppress unused
						var tmp308 interface{} = colorYellow_impl(struct{}{})
						_ = tmp308 // suppress unused
						var tmp309 interface{} = layerUI_impl(struct{}{})
						_ = tmp309 // suppress unused
						var tmp310 interface{} = AddInt(tmp309, int64(1))
						_ = tmp310 // suppress unused
						var tmp311 interface{} = NewDrawCmdText("Press E: Use hatch", float64(530), float64(665), int64(12), tmp308.(int64), tmp310.(int64))
						_ = tmp311 // suppress unused
						return []interface{}{tmp307, tmp311}
					}()
				default:
					panic("non-exhaustive match")
				}
			}()
		}
	}()
}

func RenderInteractionPrompt(state *BridgeState) []*DrawCmd {
	return ConvertToDrawCmdSlice(renderInteractionPrompt_impl(state))
}

func renderSelectedPanel_impl(state interface{}) interface{} {
	var tmp312 interface{} = FieldGet(state, "selectedInteractable")
	return func() interface{} {
		_scrutinee := tmp312
		_ = _scrutinee // suppress unused
		_adt := _scrutinee.(*Option)
		switch _adt.Kind {
		default:
			none := _adt
			_ = none // suppress unused
			return []interface{}{}
		case OptionKindSome:
			interactable := _adt.Some.Value0
			_ = interactable // suppress unused
			return func() interface{} {
				_scrutinee := interactable
				_ = _scrutinee // suppress unused
				_adt := _scrutinee
				switch _adt.Kind {
				case InteractableIDKindInteractConsole:
					station := _adt.InteractConsole.Value0
					_ = station // suppress unused
					return func() interface{} {
						var tmp313 interface{} = colorPanelBg_impl(struct{}{})
						_ = tmp313 // suppress unused
						var tmp314 interface{} = layerUI_impl(struct{}{})
						_ = tmp314 // suppress unused
						var tmp315 interface{} = NewDrawCmdRectRGBA(float64(880), float64(100), float64(360), float64(280), tmp313.(int64), tmp314.(int64))
						_ = tmp315 // suppress unused
						var tmp316 interface{} = consoleColor_impl(station)
						_ = tmp316 // suppress unused
						var tmp317 interface{} = layerUI_impl(struct{}{})
						_ = tmp317 // suppress unused
						var tmp318 interface{} = AddInt(tmp317, int64(1))
						_ = tmp318 // suppress unused
						var tmp319 interface{} = NewDrawCmdRectRGBA(float64(880), float64(100), float64(360), float64(40), tmp316.(int64), tmp318.(int64))
						_ = tmp319 // suppress unused
						var tmp320 interface{} = stationName_impl(station)
						_ = tmp320 // suppress unused
						var tmp321 interface{} = colorWhite_impl(struct{}{})
						_ = tmp321 // suppress unused
						var tmp322 interface{} = layerUI_impl(struct{}{})
						_ = tmp322 // suppress unused
						var tmp323 interface{} = AddInt(tmp322, int64(2))
						_ = tmp323 // suppress unused
						var tmp324 interface{} = NewDrawCmdText(tmp320.(string), float64(1000), float64(115), int64(14), tmp321.(int64), tmp323.(int64))
						_ = tmp324 // suppress unused
						var tmp325 interface{} = colorUIGreen_impl(struct{}{})
						_ = tmp325 // suppress unused
						var tmp326 interface{} = layerUI_impl(struct{}{})
						_ = tmp326 // suppress unused
						var tmp327 interface{} = AddInt(tmp326, int64(2))
						_ = tmp327 // suppress unused
						var tmp328 interface{} = NewDrawCmdText("Status: OPERATIONAL", float64(900), float64(170), int64(12), tmp325.(int64), tmp327.(int64))
						_ = tmp328 // suppress unused
						var tmp329 interface{} = colorUIGray_impl(struct{}{})
						_ = tmp329 // suppress unused
						var tmp330 interface{} = layerUI_impl(struct{}{})
						_ = tmp330 // suppress unused
						var tmp331 interface{} = AddInt(tmp330, int64(2))
						_ = tmp331 // suppress unused
						var tmp332 interface{} = NewDrawCmdText("Press E or ESC to close", float64(900), float64(340), int64(10), tmp329.(int64), tmp331.(int64))
						_ = tmp332 // suppress unused
						return []interface{}{tmp315, tmp319, tmp324, tmp328, tmp332}
					}()
				case InteractableIDKindInteractCrew:
					crew := _adt.InteractCrew.Value0
					_ = crew // suppress unused
					return func() interface{} {
						var tmp333 interface{} = colorPanelBg_impl(struct{}{})
						_ = tmp333 // suppress unused
						var tmp334 interface{} = layerUI_impl(struct{}{})
						_ = tmp334 // suppress unused
						var tmp335 interface{} = NewDrawCmdRectRGBA(float64(880), float64(100), float64(360), float64(280), tmp333.(int64), tmp334.(int64))
						_ = tmp335 // suppress unused
						var tmp336 interface{} = colorPlayer_impl(struct{}{})
						_ = tmp336 // suppress unused
						var tmp337 interface{} = layerUI_impl(struct{}{})
						_ = tmp337 // suppress unused
						var tmp338 interface{} = AddInt(tmp337, int64(1))
						_ = tmp338 // suppress unused
						var tmp339 interface{} = NewDrawCmdRectRGBA(float64(880), float64(100), float64(360), float64(40), tmp336.(int64), tmp338.(int64))
						_ = tmp339 // suppress unused
						var tmp340 interface{} = FieldGet(crew, "name")
						_ = tmp340 // suppress unused
						var tmp341 interface{} = colorWhite_impl(struct{}{})
						_ = tmp341 // suppress unused
						var tmp342 interface{} = layerUI_impl(struct{}{})
						_ = tmp342 // suppress unused
						var tmp343 interface{} = AddInt(tmp342, int64(2))
						_ = tmp343 // suppress unused
						var tmp344 interface{} = NewDrawCmdText(tmp340.(string), float64(1000), float64(115), int64(14), tmp341.(int64), tmp343.(int64))
						_ = tmp344 // suppress unused
						var tmp345 interface{} = colorWhite_impl(struct{}{})
						_ = tmp345 // suppress unused
						var tmp346 interface{} = layerUI_impl(struct{}{})
						_ = tmp346 // suppress unused
						var tmp347 interface{} = AddInt(tmp346, int64(2))
						_ = tmp347 // suppress unused
						var tmp348 interface{} = NewDrawCmdText("Crew Member", float64(900), float64(170), int64(12), tmp345.(int64), tmp347.(int64))
						_ = tmp348 // suppress unused
						var tmp349 interface{} = colorUIGray_impl(struct{}{})
						_ = tmp349 // suppress unused
						var tmp350 interface{} = layerUI_impl(struct{}{})
						_ = tmp350 // suppress unused
						var tmp351 interface{} = AddInt(tmp350, int64(2))
						_ = tmp351 // suppress unused
						var tmp352 interface{} = NewDrawCmdText("Press E or ESC to close", float64(900), float64(340), int64(10), tmp349.(int64), tmp351.(int64))
						_ = tmp352 // suppress unused
						return []interface{}{tmp335, tmp339, tmp344, tmp348, tmp352}
					}()
				case InteractableIDKindInteractHatch:
					deck := _adt.InteractHatch.Value0
					_ = deck // suppress unused
					return func() interface{} {
						var tmp353 interface{} = colorPanelBg_impl(struct{}{})
						_ = tmp353 // suppress unused
						var tmp354 interface{} = layerUI_impl(struct{}{})
						_ = tmp354 // suppress unused
						var tmp355 interface{} = NewDrawCmdRectRGBA(float64(880), float64(100), float64(360), float64(200), tmp353.(int64), tmp354.(int64))
						_ = tmp355 // suppress unused
						var tmp356 interface{} = colorWhite_impl(struct{}{})
						_ = tmp356 // suppress unused
						var tmp357 interface{} = layerUI_impl(struct{}{})
						_ = tmp357 // suppress unused
						var tmp358 interface{} = AddInt(tmp357, int64(1))
						_ = tmp358 // suppress unused
						var tmp359 interface{} = NewDrawCmdText("HATCH", float64(1000), float64(115), int64(14), tmp356.(int64), tmp358.(int64))
						_ = tmp359 // suppress unused
						var tmp360 interface{} = colorUIGray_impl(struct{}{})
						_ = tmp360 // suppress unused
						var tmp361 interface{} = layerUI_impl(struct{}{})
						_ = tmp361 // suppress unused
						var tmp362 interface{} = AddInt(tmp361, int64(2))
						_ = tmp362 // suppress unused
						var tmp363 interface{} = NewDrawCmdText("Press E or ESC to close", float64(900), float64(260), int64(10), tmp360.(int64), tmp362.(int64))
						_ = tmp363 // suppress unused
						return []interface{}{tmp355, tmp359, tmp363}
					}()
				default:
					panic("non-exhaustive match")
				}
			}()
		}
	}()
}

func RenderSelectedPanel(state *BridgeState) []*DrawCmd {
	return ConvertToDrawCmdSlice(renderSelectedPanel_impl(state))
}

func renderBridge_impl(state interface{}) interface{} {
	var tmp364 interface{} = FieldGet(state, "domeState")
	var tmp365 interface{} = renderDome_impl(tmp364)
	var tmp366 interface{} = renderStruts_impl(state)
	var tmp367 interface{} = Concat(tmp365, tmp366)
	var tmp368 interface{} = renderBridgeFloor_impl(state)
	var tmp369 interface{} = Concat(tmp367, tmp368)
	var tmp370 interface{} = renderConsoles_impl(state)
	var tmp371 interface{} = Concat(tmp369, tmp370)
	var tmp372 interface{} = renderBridgeCrew_impl(state)
	var tmp373 interface{} = Concat(tmp371, tmp372)
	var tmp374 interface{} = renderPlayer_impl(state)
	var tmp375 interface{} = Concat(tmp373, tmp374)
	var tmp376 interface{} = renderInteractionPrompt_impl(state)
	var tmp377 interface{} = Concat(tmp375, tmp376)
	var tmp378 interface{} = renderSelectedPanel_impl(state)
	return Concat(tmp377, tmp378)
}

func RenderBridge(state *BridgeState) []*DrawCmd {
	return ConvertToDrawCmdSlice(renderBridge_impl(state))
}

func keyW_impl(_unused0 interface{}) interface{} {
	return int64(87)
}

func keyW() int64 {
	return keyW_impl(struct{}{}).(int64)
}

func keyA_impl(_unused0 interface{}) interface{} {
	return int64(65)
}

func keyA() int64 {
	return keyA_impl(struct{}{}).(int64)
}

func keyS_impl(_unused0 interface{}) interface{} {
	return int64(83)
}

func keyS() int64 {
	return keyS_impl(struct{}{}).(int64)
}

func keyD_impl(_unused0 interface{}) interface{} {
	return int64(68)
}

func keyD() int64 {
	return keyD_impl(struct{}{}).(int64)
}

func keyUp_impl(_unused0 interface{}) interface{} {
	return int64(265)
}

func keyUp() int64 {
	return keyUp_impl(struct{}{}).(int64)
}

func keyDown_impl(_unused0 interface{}) interface{} {
	return int64(264)
}

func keyDown() int64 {
	return keyDown_impl(struct{}{}).(int64)
}

func keyLeft_impl(_unused0 interface{}) interface{} {
	return int64(263)
}

func keyLeft() int64 {
	return keyLeft_impl(struct{}{}).(int64)
}

func keyRight_impl(_unused0 interface{}) interface{} {
	return int64(262)
}

func keyRight() int64 {
	return keyRight_impl(struct{}{}).(int64)
}

func keyE_impl(_unused0 interface{}) interface{} {
	return int64(69)
}

func keyE() int64 {
	return keyE_impl(struct{}{}).(int64)
}

func keyEscape_impl(_unused0 interface{}) interface{} {
	return int64(256)
}

func keyEscape() int64 {
	return keyEscape_impl(struct{}{}).(int64)
}

func hasKeyRec_impl(keyCode interface{}, keys interface{}) interface{} {
	return func() interface{} {
		_scrutinee := keys
		_ = _scrutinee // suppress unused
		if ListLen(_scrutinee) == 0 {
			return false
		} else if ListLen(_scrutinee) >= 1 {
			k := ListHead(_scrutinee)
			_ = k // suppress unused
			rest := ListTail(_scrutinee)
			_ = rest // suppress unused
			return func() interface{} {
				var tmp379 interface{} = FieldGet(k, "key")
				_ = tmp379 // suppress unused
				var tmp380 interface{} = EqInt(tmp379, keyCode)
				_ = tmp380 // suppress unused
				var tmp381 interface{} = FieldGet(k, "kind")
				_ = tmp381 // suppress unused
				var tmp382 interface{} = EqString(tmp381, "pressed")
				_ = tmp382 // suppress unused
				var tmp383 interface{} = func() interface{} {
					if tmp380.(bool) {
						return tmp382
					}
					return false
				}()
				_ = tmp383 // suppress unused
				return func() interface{} {
					if tmp383.(bool) {
						return true
					}
					return hasKeyRec_impl(keyCode, rest)
				}()
			}()
		} else {
			panic("non-exhaustive match")
		}
	}()
}

func hasKeyRec(keyCode int64, keys []*KeyEvent) bool {
	return hasKeyRec_impl(keyCode, keys).(bool)
}

func hasKey_impl(keyCode interface{}, input interface{}) interface{} {
	var tmp384 interface{} = FieldGet(input, "keys")
	return hasKeyRec_impl(keyCode, tmp384)
}

func hasKey(keyCode int64, input *FrameInput) bool {
	return hasKey_impl(keyCode, input).(bool)
}

func getInputDirection_impl(input interface{}) interface{} {
	var tmp385 interface{} = keyW_impl(struct{}{})
	var tmp386 interface{} = hasKey_impl(tmp385, input)
	var tmp387 interface{} = keyUp_impl(struct{}{})
	var tmp388 interface{} = hasKey_impl(tmp387, input)
	var tmp389 interface{} = func() interface{} {
		if tmp386.(bool) {
			return true
		}
		return tmp388
	}()
	return func() interface{} {
		var tmp390 interface{} = keyS_impl(struct{}{})
		_ = tmp390 // suppress unused
		var tmp391 interface{} = hasKey_impl(tmp390, input)
		_ = tmp391 // suppress unused
		var tmp392 interface{} = keyDown_impl(struct{}{})
		_ = tmp392 // suppress unused
		var tmp393 interface{} = hasKey_impl(tmp392, input)
		_ = tmp393 // suppress unused
		var tmp394 interface{} = func() interface{} {
			if tmp391.(bool) {
				return true
			}
			return tmp393
		}()
		_ = tmp394 // suppress unused
		var tmp395 interface{} = keyA_impl(struct{}{})
		_ = tmp395 // suppress unused
		var tmp396 interface{} = hasKey_impl(tmp395, input)
		_ = tmp396 // suppress unused
		var tmp397 interface{} = keyLeft_impl(struct{}{})
		_ = tmp397 // suppress unused
		var tmp398 interface{} = hasKey_impl(tmp397, input)
		_ = tmp398 // suppress unused
		var tmp399 interface{} = func() interface{} {
			if tmp396.(bool) {
				return true
			}
			return tmp398
		}()
		_ = tmp399 // suppress unused
		var tmp400 interface{} = keyD_impl(struct{}{})
		_ = tmp400 // suppress unused
		var tmp401 interface{} = hasKey_impl(tmp400, input)
		_ = tmp401 // suppress unused
		var tmp402 interface{} = keyRight_impl(struct{}{})
		_ = tmp402 // suppress unused
		var tmp403 interface{} = hasKey_impl(tmp402, input)
		_ = tmp403 // suppress unused
		var tmp404 interface{} = func() interface{} {
			if tmp401.(bool) {
				return true
			}
			return tmp403
		}()
		_ = tmp404 // suppress unused
		if tmp389.(bool) {
			return NewOptionSome(NewDirectionNorth())
		}
		if tmp394.(bool) {
			return NewOptionSome(NewDirectionSouth())
		}
		if tmp399.(bool) {
			return NewOptionSome(NewDirectionWest())
		}
		if tmp404.(bool) {
			return NewOptionSome(NewDirectionEast())
		}
		return NewOptionNone()
	}()
}

func getInputDirection(input *FrameInput) *Option {
	return getInputDirection_impl(input).(*Option)
}

func tryMovePlayer_impl(state interface{}, dir interface{}) interface{} {
	var newPos interface{} = func() interface{} {
		var tmp411 interface{} = FieldGet(state, "playerPos")
		_ = tmp411 // suppress unused
		return moveInDirection_impl(tmp411, dir)
	}()
	var tmp405 interface{} = FieldGet(newPos, "x")
	var tmp406 interface{} = FieldGet(newPos, "y")
	var tmp407 interface{} = isWalkable_impl(state, tmp405, tmp406)
	return func() interface{} {
		if tmp407.(bool) {
			return func() interface{} {
				var tmp408 interface{} = NewMoveStateMoveWalking(dir.(*Direction))
				_ = tmp408 // suppress unused
				var tmp409 interface{} = FieldGet(newPos, "x")
				_ = tmp409 // suppress unused
				var tmp410 interface{} = FieldGet(newPos, "y")
				_ = tmp410 // suppress unused
				return RecordUpdate(state, map[string]interface{}{"cameraY": tmp410, "playerPos": newPos, "playerFacing": dir, "moveState": tmp408, "cameraX": tmp409})
			}()
		}
		return RecordUpdate(state, map[string]interface{}{"playerFacing": dir, "moveState": NewMoveStateMoveIdle()})
	}()
}

func tryMovePlayer(state *BridgeState, dir *Direction) *BridgeState {
	return tryMovePlayer_impl(state, dir).(*BridgeState)
}

func setPlayerIdle_impl(state interface{}) interface{} {
	return RecordUpdate(state, map[string]interface{}{"moveState": NewMoveStateMoveIdle()})
}

func setPlayerIdle(state *BridgeState) *BridgeState {
	return setPlayerIdle_impl(state).(*BridgeState)
}

func absInt_impl(x interface{}) interface{} {
	var tmp412 interface{} = LtInt(x, int64(0))
	return func() interface{} {
		if tmp412.(bool) {
			return SubInt(int64(0), x)
		}
		return x
	}()
}

func absInt(x int64) int64 {
	return absInt_impl(x).(int64)
}

func manhattanDistance_impl(a interface{}, b interface{}) interface{} {
	var tmp413 interface{} = FieldGet(a, "x")
	var tmp414 interface{} = FieldGet(b, "x")
	var tmp415 interface{} = SubInt(tmp413, tmp414)
	var tmp416 interface{} = absInt_impl(tmp415)
	var tmp417 interface{} = FieldGet(a, "y")
	var tmp418 interface{} = FieldGet(b, "y")
	var tmp419 interface{} = SubInt(tmp417, tmp418)
	var tmp420 interface{} = absInt_impl(tmp419)
	return AddInt(tmp416, tmp420)
}

func manhattanDistance(a *Coord, b *Coord) int64 {
	return manhattanDistance_impl(a, b).(int64)
}

func isNearConsole_impl(playerPos interface{}, console interface{}) interface{} {
	var tmp421 interface{} = FieldGet(console, "pos")
	var tmp422 interface{} = manhattanDistance_impl(playerPos, tmp421)
	return LeInt(tmp422, int64(2))
}

func isNearConsole(playerPos *Coord, console *ConsoleState) bool {
	return isNearConsole_impl(playerPos, console).(bool)
}

func findNearbyConsoleRec_impl(playerPos interface{}, consoles interface{}) interface{} {
	return func() interface{} {
		_scrutinee := consoles
		_ = _scrutinee // suppress unused
		if ListLen(_scrutinee) == 0 {
			return NewOptionNone()
		} else if ListLen(_scrutinee) >= 1 {
			c := ListHead(_scrutinee)
			_ = c // suppress unused
			rest := ListTail(_scrutinee)
			_ = rest // suppress unused
			return func() interface{} {
				var tmp423 interface{} = isNearConsole_impl(playerPos, c)
				_ = tmp423 // suppress unused
				return func() interface{} {
					if tmp423.(bool) {
						return func() interface{} {
							var tmp424 interface{} = FieldGet(c, "station")
							_ = tmp424 // suppress unused
							return NewOptionSome(tmp424)
						}()
					}
					return findNearbyConsoleRec_impl(playerPos, rest)
				}()
			}()
		} else {
			panic("non-exhaustive match")
		}
	}()
}

func findNearbyConsoleRec(playerPos *Coord, consoles []*ConsoleState) *Option {
	return findNearbyConsoleRec_impl(playerPos, consoles).(*Option)
}

func findNearbyInteractable_impl(state interface{}) interface{} {
	var tmp425 interface{} = FieldGet(state, "playerPos")
	var tmp426 interface{} = FieldGet(state, "consoles")
	var tmp427 interface{} = findNearbyConsoleRec_impl(tmp425, tmp426)
	return func() interface{} {
		_scrutinee := tmp427
		_ = _scrutinee // suppress unused
		_adt := _scrutinee.(*Option)
		switch _adt.Kind {
		case OptionKindSome:
			station := _adt.Some.Value0
			_ = station // suppress unused
			return func() interface{} {
				var tmp428 interface{} = NewInteractableIDInteractConsole(station)
				_ = tmp428 // suppress unused
				return NewOptionSome(tmp428)
			}()
		default:
			none := _adt
			_ = none // suppress unused
			return NewOptionNone()
		}
	}()
}

func findNearbyInteractable(state *BridgeState) *Option {
	return findNearbyInteractable_impl(state).(*Option)
}

func updateHover_impl(state interface{}) interface{} {
	var tmp429 interface{} = findNearbyInteractable_impl(state)
	return RecordUpdate(state, map[string]interface{}{"hoveredInteractable": tmp429})
}

func updateHover(state *BridgeState) *BridgeState {
	return updateHover_impl(state).(*BridgeState)
}

func deselectInteractable_impl(state interface{}) interface{} {
	return RecordUpdate(state, map[string]interface{}{"selectedInteractable": NewOptionNone()})
}

func deselectInteractable(state *BridgeState) *BridgeState {
	return deselectInteractable_impl(state).(*BridgeState)
}

func selectHovered_impl(state interface{}) interface{} {
	var tmp430 interface{} = FieldGet(state, "hoveredInteractable")
	return RecordUpdate(state, map[string]interface{}{"selectedInteractable": tmp430})
}

func selectHovered(state *BridgeState) *BridgeState {
	return selectHovered_impl(state).(*BridgeState)
}

func toggleSelection_impl(state interface{}) interface{} {
	var tmp431 interface{} = FieldGet(state, "selectedInteractable")
	return func() interface{} {
		_scrutinee := tmp431
		_ = _scrutinee // suppress unused
		_adt := _scrutinee.(*Option)
		switch _adt.Kind {
		case OptionKindSome:
			return deselectInteractable_impl(state)
		default:
			none := _adt
			_ = none // suppress unused
			return selectHovered_impl(state)
		}
	}()
}

func toggleSelection(state *BridgeState) *BridgeState {
	return toggleSelection_impl(state).(*BridgeState)
}

func clearSelection_impl(state interface{}) interface{} {
	return RecordUpdate(state, map[string]interface{}{"selectedInteractable": NewOptionNone()})
}

func clearSelection(state *BridgeState) *BridgeState {
	return clearSelection_impl(state).(*BridgeState)
}

func processBridgeInput_impl(state interface{}, input interface{}) interface{} {
	var afterMove interface{} = func() interface{} {
		var tmp436 interface{} = getInputDirection_impl(input)
		_ = tmp436 // suppress unused
		return func() interface{} {
			_scrutinee := tmp436
			_ = _scrutinee // suppress unused
			_adt := _scrutinee.(*Option)
			switch _adt.Kind {
			case OptionKindSome:
				dir := _adt.Some.Value0
				_ = dir // suppress unused
				return tryMovePlayer_impl(state, dir)
			default:
				none := _adt
				_ = none // suppress unused
				return setPlayerIdle_impl(state)
			}
		}()
	}()
	var afterHover interface{} = updateHover_impl(afterMove)
	var tmp432 interface{} = keyEscape_impl(struct{}{})
	var tmp433 interface{} = hasKey_impl(tmp432, input)
	return func() interface{} {
		var tmp434 interface{} = keyE_impl(struct{}{})
		_ = tmp434 // suppress unused
		var tmp435 interface{} = hasKey_impl(tmp434, input)
		_ = tmp435 // suppress unused
		if tmp433.(bool) {
			return clearSelection_impl(afterHover)
		}
		if tmp435.(bool) {
			return toggleSelection_impl(afterHover)
		}
		return afterHover
	}()
}

func ProcessBridgeInput(state *BridgeState, input *FrameInput) *BridgeState {
	return processBridgeInput_impl(state, input).(*BridgeState)
}

func getPatrolDirection_impl(crewId interface{}, frame interface{}) interface{} {
	var phase interface{} = func() interface{} {
		var tmp437 interface{} = DivInt(frame, int64(30))
		_ = tmp437 // suppress unused
		var tmp438 interface{} = MulInt(crewId, int64(7))
		_ = tmp438 // suppress unused
		var tmp439 interface{} = AddInt(tmp437, tmp438)
		_ = tmp439 // suppress unused
		return ModInt(tmp439, int64(4))
	}()
	return func() interface{} {
		_scrutinee := phase
		_ = _scrutinee // suppress unused
		switch _scrutinee {
		case int64(0):
			return NewDirectionNorth()
		case int64(1):
			return NewDirectionEast()
		case int64(2):
			return NewDirectionSouth()
		default:
			return NewDirectionWest()
		}
	}()
}

func getPatrolDirection(crewId int64, frame int64) *Direction {
	return getPatrolDirection_impl(crewId, frame).(*Direction)
}

func tryMoveCrew_impl(crew interface{}, dir interface{}, state interface{}) interface{} {
	var newPos interface{} = func() interface{} {
		var tmp443 interface{} = FieldGet(crew, "pos")
		_ = tmp443 // suppress unused
		return moveInDirection_impl(tmp443, dir)
	}()
	var tmp440 interface{} = FieldGet(newPos, "x")
	var tmp441 interface{} = FieldGet(newPos, "y")
	var tmp442 interface{} = isWalkable_impl(state, tmp440, tmp441)
	return func() interface{} {
		if tmp442.(bool) {
			return RecordUpdate(crew, map[string]interface{}{"pos": newPos, "facing": dir})
		}
		return RecordUpdate(crew, map[string]interface{}{"facing": dir})
	}()
}

func tryMoveCrew(crew *CrewPosition, dir *Direction, state *BridgeState) *CrewPosition {
	return tryMoveCrew_impl(crew, dir, state).(*CrewPosition)
}

func updateCrewMember_impl(crew interface{}, frame interface{}, state interface{}) interface{} {
	var tmp444 interface{} = ModInt(frame, int64(30))
	var tmp445 interface{} = EqInt(tmp444, int64(0))
	return func() interface{} {
		if tmp445.(bool) {
			return func() interface{} {
				var tmp446 interface{} = FieldGet(crew, "crew")
				_ = tmp446 // suppress unused
				var tmp447 interface{} = FieldGet(tmp446, "id")
				_ = tmp447 // suppress unused
				var tmp448 interface{} = getPatrolDirection_impl(tmp447, frame)
				_ = tmp448 // suppress unused
				return tryMoveCrew_impl(crew, tmp448, state)
			}()
		}
		return crew
	}()
}

func updateCrewMember(crew *CrewPosition, frame int64, state *BridgeState) *CrewPosition {
	return updateCrewMember_impl(crew, frame, state).(*CrewPosition)
}

func updateCrewRec_impl(crew interface{}, frame interface{}, state interface{}) interface{} {
	return func() interface{} {
		_scrutinee := crew
		_ = _scrutinee // suppress unused
		if ListLen(_scrutinee) == 0 {
			return []interface{}{}
		} else if ListLen(_scrutinee) >= 1 {
			c := ListHead(_scrutinee)
			_ = c // suppress unused
			rest := ListTail(_scrutinee)
			_ = rest // suppress unused
			return func() interface{} {
				var tmp449 interface{} = updateCrewMember_impl(c, frame, state)
				_ = tmp449 // suppress unused
				var tmp450 interface{} = updateCrewRec_impl(rest, frame, state)
				_ = tmp450 // suppress unused
				return Cons(tmp449, tmp450)
			}()
		} else {
			panic("non-exhaustive match")
		}
	}()
}

func updateCrewRec(crew []*CrewPosition, frame int64, state *BridgeState) []*CrewPosition {
	return ConvertToCrewPositionSlice(updateCrewRec_impl(crew, frame, state))
}

func stepBridge_impl(state interface{}, frame interface{}) interface{} {
	var dt interface{} = DivFloat(float64(1), float64(60))
	var updatedDome interface{} = func() interface{} {
		var tmp456 interface{} = FieldGet(state, "domeState")
		_ = tmp456 // suppress unused
		return stepDome_impl(tmp456, dt)
	}()
	var updatedDomeView interface{} = func() interface{} {
		var tmp452 interface{} = FieldGet(updatedDome, "targetPlanet")
		_ = tmp452 // suppress unused
		var tmp453 interface{} = FieldGet(updatedDome, "cruiseVelocity")
		_ = tmp453 // suppress unused
		var tmp454 interface{} = FieldGet(state, "domeView")
		_ = tmp454 // suppress unused
		var tmp455 interface{} = FieldGet(tmp454, "viewAngle")
		_ = tmp455 // suppress unused
		return makeDomeViewState_impl(tmp452, tmp453, tmp455)
	}()
	var updatedCrew interface{} = func() interface{} {
		var tmp451 interface{} = FieldGet(state, "crewPositions")
		_ = tmp451 // suppress unused
		return updateCrewRec_impl(tmp451, frame, state)
	}()
	return RecordUpdate(state, map[string]interface{}{"domeView": updatedDomeView, "tick": frame, "crewPositions": updatedCrew, "domeState": updatedDome})
}

func StepBridge(state *BridgeState, frame int64) *BridgeState {
	return stepBridge_impl(state, frame).(*BridgeState)
}
