// Code generated by ailang. DO NOT EDIT.
package sim_gen

import (
	"math"
)

func colorFloor_impl(_unused0 interface{}) interface{} {
	return int64(707406591)
}

func colorFloor() int64 {
	return colorFloor_impl(struct{}{}).(int64)
}

func colorFloorGlow_impl(_unused0 interface{}) interface{} {
	return int64(858993919)
}

func colorFloorGlow() int64 {
	return colorFloorGlow_impl(struct{}{}).(int64)
}

func colorDomeEdge_impl(_unused0 interface{}) interface{} {
	return int64(439041279)
}

func colorDomeEdge() int64 {
	return colorDomeEdge_impl(struct{}{}).(int64)
}

func colorWalkway_impl(_unused0 interface{}) interface{} {
	return int64(1145324799)
}

func colorWalkway() int64 {
	return colorWalkway_impl(struct{}{}).(int64)
}

func colorCaptainArea_impl(_unused0 interface{}) interface{} {
	return int64(606348543)
}

func colorCaptainArea() int64 {
	return colorCaptainArea_impl(struct{}{}).(int64)
}

func colorWall_impl(_unused0 interface{}) interface{} {
	return int64(252645631)
}

func colorWall() int64 {
	return colorWall_impl(struct{}{}).(int64)
}

func colorHelm_impl(_unused0 interface{}) interface{} {
	return int64(4120593151)
}

func colorHelm() int64 {
	return colorHelm_impl(struct{}{}).(int64)
}

func colorComms_impl(_unused0 interface{}) interface{} {
	return int64(14540799)
}

func colorComms() int64 {
	return colorComms_impl(struct{}{}).(int64)
}

func colorStatus_impl(_unused0 interface{}) interface{} {
	return int64(2566914303)
}

func colorStatus() int64 {
	return colorStatus_impl(struct{}{}).(int64)
}

func colorNav_impl(_unused0 interface{}) interface{} {
	return int64(4294935039)
}

func colorNav() int64 {
	return colorNav_impl(struct{}{}).(int64)
}

func colorScience_impl(_unused0 interface{}) interface{} {
	return int64(16744447)
}

func colorScience() int64 {
	return colorScience_impl(struct{}{}).(int64)
}

func colorCaptain_impl(_unused0 interface{}) interface{} {
	return int64(4294940415)
}

func colorCaptain() int64 {
	return colorCaptain_impl(struct{}{}).(int64)
}

func colorCrewPilot_impl(_unused0 interface{}) interface{} {
	return int64(4120593151)
}

func colorCrewPilot() int64 {
	return colorCrewPilot_impl(struct{}{}).(int64)
}

func colorCrewComms_impl(_unused0 interface{}) interface{} {
	return int64(14540799)
}

func colorCrewComms() int64 {
	return colorCrewComms_impl(struct{}{}).(int64)
}

func colorCrewEngineer_impl(_unused0 interface{}) interface{} {
	return int64(2566914303)
}

func colorCrewEngineer() int64 {
	return colorCrewEngineer_impl(struct{}{}).(int64)
}

func colorCrewScientist_impl(_unused0 interface{}) interface{} {
	return int64(16744447)
}

func colorCrewScientist() int64 {
	return colorCrewScientist_impl(struct{}{}).(int64)
}

func colorCrewCaptain_impl(_unused0 interface{}) interface{} {
	return int64(4294940415)
}

func colorCrewCaptain() int64 {
	return colorCrewCaptain_impl(struct{}{}).(int64)
}

func colorPlayer_impl(_unused0 interface{}) interface{} {
	return int64(65280)
}

func colorPlayer() int64 {
	return colorPlayer_impl(struct{}{}).(int64)
}

func makeDomeViewState_impl(planetId interface{}, velocity interface{}, angle interface{}) interface{} {
	return &DomeViewState{TargetPlanetId: planetId.(int64), ShipVelocity: velocity.(float64), ViewAngle: angle.(float64)}
}

func MakeDomeViewState(planetId int64, velocity float64, angle float64) *DomeViewState {
	return makeDomeViewState_impl(planetId, velocity, angle).(*DomeViewState)
}

func initDomeState_impl(_unused0 interface{}) interface{} {
	return &DomeState{CruiseTime: float64(0), CruiseDuration: float64(60), CruiseVelocity: float64(0.15), CameraZ: float64(10), TargetPlanet: int64(4)}
}

func InitDomeState() *DomeState {
	return initDomeState_impl(struct{}{}).(*DomeState)
}

func stepDome_impl(state interface{}, dt interface{}) interface{} {
	var newTime interface{} = func() interface{} {
		var tmp12 interface{} = FieldGet(state, "cruiseTime")
		_ = tmp12 // suppress unused
		return AddFloat(tmp12, dt)
	}()
	var loopedTime interface{} = func() interface{} {
		var tmp10 interface{} = FieldGet(state, "cruiseDuration")
		_ = tmp10 // suppress unused
		return func() interface{} {
			var tmp11 interface{} = GtFloat(newTime, tmp10)
			_ = tmp11 // suppress unused
			return func() interface{} {
				if tmp11.(bool) {
					return float64(0)
				}
				return newTime
			}()
		}()
	}()
	var progress interface{} = func() interface{} {
		var tmp9 interface{} = FieldGet(state, "cruiseDuration")
		_ = tmp9 // suppress unused
		return DivFloat(loopedTime, tmp9)
	}()
	var eased interface{} = func() interface{} {
		var tmp6 interface{} = MulFloat(progress, progress)
		_ = tmp6 // suppress unused
		return func() interface{} {
			var tmp7 interface{} = MulFloat(float64(2), progress)
			_ = tmp7 // suppress unused
			return func() interface{} {
				var tmp8 interface{} = SubFloat(float64(3), tmp7)
				_ = tmp8 // suppress unused
				return MulFloat(tmp6, tmp8)
			}()
		}()
	}()
	var startZ interface{} = float64(10)
	var endZ interface{} = SubFloat(float64(0), float64(155))
	var newCamZ interface{} = func() interface{} {
		var tmp4 interface{} = SubFloat(startZ, endZ)
		_ = tmp4 // suppress unused
		return func() interface{} {
			var tmp5 interface{} = MulFloat(tmp4, eased)
			_ = tmp5 // suppress unused
			return SubFloat(startZ, tmp5)
		}()
	}()
	var tmp1 interface{} = FieldGet(state, "cruiseDuration")
	var tmp2 interface{} = FieldGet(state, "cruiseVelocity")
	var tmp3 interface{} = FieldGet(state, "targetPlanet")
	return &DomeState{CruiseTime: loopedTime.(float64), CruiseDuration: tmp1.(float64), CruiseVelocity: tmp2.(float64), CameraZ: newCamZ.(float64), TargetPlanet: tmp3.(int64)}
}

func StepDome(state *DomeState, dt float64) *DomeState {
	return stepDome_impl(state, dt).(*DomeState)
}

func getPlanets_impl(_unused0 interface{}) interface{} {
	var tmp13 interface{} = &Planet{Name: "Neptune", ColorRGBA: int64(1350665471), Distance: float64(15), Radius: float64(20), YOffset: float64(2.25)}
	var tmp14 interface{} = &Planet{Name: "Saturn", ColorRGBA: int64(3535748351), Distance: float64(50), Radius: float64(36), YOffset: float64(7.5)}
	var tmp15 interface{} = &Planet{Name: "Jupiter", ColorRGBA: int64(3702191359), Distance: float64(90), Radius: float64(44), YOffset: float64(13.5)}
	var tmp16 interface{} = &Planet{Name: "Mars", ColorRGBA: int64(3361734911), Distance: float64(130), Radius: float64(10), YOffset: float64(19.5)}
	var tmp17 interface{} = &Planet{Name: "Earth", ColorRGBA: int64(1014743295), Distance: float64(150), Radius: float64(14), YOffset: float64(22.5)}
	return []interface{}{tmp13, tmp14, tmp15, tmp16, tmp17}
}

func GetPlanets() []*Planet {
	return getPlanets_impl(struct{}{}).([]*Planet)
}

func getDomeVelocity_impl(state interface{}) interface{} {
	return FieldGet(state, "cruiseVelocity")
}

func GetDomeVelocity(state *DomeState) float64 {
	return getDomeVelocity_impl(state).(float64)
}

func getDomeProgress_impl(state interface{}) interface{} {
	var tmp18 interface{} = FieldGet(state, "cruiseTime")
	var tmp19 interface{} = FieldGet(state, "cruiseDuration")
	return DivFloat(tmp18, tmp19)
}

func GetDomeProgress(state *DomeState) float64 {
	return getDomeProgress_impl(state).(float64)
}

func layerDome_impl(_unused0 interface{}) interface{} {
	return SubInt(int64(0), int64(10))
}

func layerDome() int64 {
	return layerDome_impl(struct{}{}).(int64)
}

func renderPlanet_impl(planet interface{}, cameraZ interface{}, scrW interface{}, scrH interface{}) interface{} {
	var relZ interface{} = func() interface{} {
		var tmp29 interface{} = FieldGet(planet, "distance")
		_ = tmp29 // suppress unused
		return AddFloat(tmp29, cameraZ)
	}()
	var tmp20 interface{} = LeFloat(relZ, float64(0.5))
	return func() interface{} {
		var scale interface{} = DivFloat(float64(100), relZ)
		_ = scale // suppress unused
		var screenX interface{} = DivFloat(scrW, float64(2))
		_ = screenX // suppress unused
		var baseY interface{} = float64(200)
		_ = baseY // suppress unused
		var screenY interface{} = func() interface{} {
			var tmp26 interface{} = FieldGet(planet, "yOffset")
			_ = tmp26 // suppress unused
			return func() interface{} {
				var tmp27 interface{} = MulFloat(tmp26, scale)
				_ = tmp27 // suppress unused
				return func() interface{} {
					var tmp28 interface{} = MulFloat(tmp27, float64(5))
					_ = tmp28 // suppress unused
					return AddFloat(baseY, tmp28)
				}()
			}()
		}()
		_ = screenY // suppress unused
		var visibleRadius interface{} = func() interface{} {
			var tmp25 interface{} = FieldGet(planet, "radius")
			_ = tmp25 // suppress unused
			return MulFloat(tmp25, scale)
		}()
		_ = visibleRadius // suppress unused
		var tmp21 interface{} = LtFloat(visibleRadius, float64(1))
		_ = tmp21 // suppress unused
		if tmp20.(bool) {
			return []interface{}{}
		}
		if tmp21.(bool) {
			return []interface{}{}
		}
		return func() interface{} {
			var tmp22 interface{} = FieldGet(planet, "colorRGBA")
			_ = tmp22 // suppress unused
			return func() interface{} {
				var tmp23 interface{} = layerDome_impl(struct{}{})
				_ = tmp23 // suppress unused
				return func() interface{} {
					var tmp24 interface{} = NewDrawCmdCircleRGBA(screenX.(float64), screenY.(float64), visibleRadius.(float64), tmp22.(int64), true, tmp23.(int64))
					_ = tmp24 // suppress unused
					return []interface{}{tmp24}
				}()
			}()
		}()
	}()
}

func renderPlanet(planet *Planet, cameraZ float64, scrW float64, scrH float64) []*DrawCmd {
	return ConvertToDrawCmdSlice(renderPlanet_impl(planet, cameraZ, scrW, scrH))
}

func renderPlanetsRec_impl(planets interface{}, cameraZ interface{}, scrW interface{}, scrH interface{}) interface{} {
	return func() interface{} {
		_scrutinee := planets
		_ = _scrutinee // suppress unused
		if ListLen(_scrutinee) == 0 {
			return []interface{}{}
		} else if ListLen(_scrutinee) >= 1 {
			p := ListHead(_scrutinee)
			_ = p // suppress unused
			rest := ListTail(_scrutinee)
			_ = rest // suppress unused
			return func() interface{} {
				var tmp30 interface{} = renderPlanet_impl(p, cameraZ, scrW, scrH)
				_ = tmp30 // suppress unused
				return func() interface{} {
					var tmp31 interface{} = renderPlanetsRec_impl(rest, cameraZ, scrW, scrH)
					_ = tmp31 // suppress unused
					return Concat(tmp30, tmp31)
				}()
			}()
		} else {
			panic("non-exhaustive match")
		}
	}()
}

func renderPlanetsRec(planets []*Planet, cameraZ float64, scrW float64, scrH float64) []*DrawCmd {
	return ConvertToDrawCmdSlice(renderPlanetsRec_impl(planets, cameraZ, scrW, scrH))
}

func screenWidth_impl(_unused0 interface{}) interface{} {
	return float64(1280)
}

func screenWidth() float64 {
	return screenWidth_impl(struct{}{}).(float64)
}

func screenHeight_impl(_unused0 interface{}) interface{} {
	return float64(960)
}

func screenHeight() float64 {
	return screenHeight_impl(struct{}{}).(float64)
}

func renderDomePlanets_impl(state interface{}) interface{} {
	var scrW interface{} = screenWidth_impl(struct{}{})
	var scrH interface{} = screenHeight_impl(struct{}{})
	var tmp32 interface{} = getPlanets_impl(struct{}{})
	var tmp33 interface{} = FieldGet(state, "cameraZ")
	return renderPlanetsRec_impl(tmp32, tmp33, scrW, scrH)
}

func RenderDomePlanets(state *DomeState) []*DrawCmd {
	return ConvertToDrawCmdSlice(renderDomePlanets_impl(state))
}

func layerDomeBg_impl(_unused0 interface{}) interface{} {
	return SubInt(int64(0), int64(20))
}

func layerDomeBg() int64 {
	return layerDomeBg_impl(struct{}{}).(int64)
}

func layerPlanets3D_impl(_unused0 interface{}) interface{} {
	return int64(4)
}

func layerPlanets3D() int64 {
	return layerPlanets3D_impl(struct{}{}).(int64)
}

func layerBubbleArc3D_impl(_unused0 interface{}) interface{} {
	return int64(5)
}

func layerBubbleArc3D() int64 {
	return layerBubbleArc3D_impl(struct{}{}).(int64)
}

func renderDome_impl(state interface{}) interface{} {
	var tmp34 interface{} = layerDomeBg_impl(struct{}{})
	var tmp35 interface{} = NewDrawCmdSpaceBg(tmp34.(int64))
	var tmp36 interface{} = layerPlanets3D_impl(struct{}{})
	var tmp37 interface{} = NewDrawCmdPlanets3D(tmp36.(int64))
	var tmp38 interface{} = layerBubbleArc3D_impl(struct{}{})
	var tmp39 interface{} = NewDrawCmdBubbleArc(tmp38.(int64))
	return []interface{}{tmp35, tmp37, tmp39}
}

func RenderDome(state *DomeState) []*DrawCmd {
	return ConvertToDrawCmdSlice(renderDome_impl(state))
}

func strutColor_impl(_unused0 interface{}) interface{} {
	return int64(1275068520)
}

func strutColor() int64 {
	return strutColor_impl(struct{}{}).(int64)
}

func strutHighlight_impl(_unused0 interface{}) interface{} {
	return int64(1887670408)
}

func strutHighlight() int64 {
	return strutHighlight_impl(struct{}{}).(int64)
}

func layerStruts_impl(_unused0 interface{}) interface{} {
	return NegInt(int64(1))
}

func layerStruts() int64 {
	return layerStruts_impl(struct{}{}).(int64)
}

func strutCount_impl(_unused0 interface{}) interface{} {
	return int64(8)
}

func strutCount() int64 {
	return strutCount_impl(struct{}{}).(int64)
}

func arcCenterY_impl(_unused0 interface{}) interface{} {
	return float64(1600)
}

func arcCenterY() float64 {
	return arcCenterY_impl(struct{}{}).(float64)
}

func arcRadius_impl(_unused0 interface{}) interface{} {
	return float64(900)
}

func arcRadius() float64 {
	return arcRadius_impl(struct{}{}).(float64)
}

func strutBaseX_impl(index interface{}, total interface{}) interface{} {
	var centerX interface{} = func() interface{} {
		var tmp50 interface{} = screenWidth_impl(struct{}{})
		_ = tmp50 // suppress unused
		return DivFloat(tmp50, float64(2))
	}()
	var angleRange interface{} = func() interface{} {
		var tmp49 interface{} = math.Pi
		_ = tmp49 // suppress unused
		return DivFloat(tmp49, float64(3))
	}()
	var angleStep interface{} = func() interface{} {
		var tmp46 interface{} = MulFloat(angleRange, float64(2))
		_ = tmp46 // suppress unused
		return func() interface{} {
			var tmp47 interface{} = SubInt(total, int64(1))
			_ = tmp47 // suppress unused
			return func() interface{} {
				var tmp48 interface{} = IntToFloat(tmp47)
				_ = tmp48 // suppress unused
				return DivFloat(tmp46, tmp48)
			}()
		}()
	}()
	var angle interface{} = func() interface{} {
		var tmp43 interface{} = SubFloat(float64(0), angleRange)
		_ = tmp43 // suppress unused
		return func() interface{} {
			var tmp44 interface{} = IntToFloat(index)
			_ = tmp44 // suppress unused
			return func() interface{} {
				var tmp45 interface{} = MulFloat(tmp44, angleStep)
				_ = tmp45 // suppress unused
				return AddFloat(tmp43, tmp45)
			}()
		}()
	}()
	var tmp40 interface{} = arcRadius_impl(struct{}{})
	var tmp41 interface{} = math.Sin(angle.(float64))
	var tmp42 interface{} = MulFloat(tmp40, tmp41)
	return AddFloat(centerX, tmp42)
}

func strutBaseX(index int64, total int64) float64 {
	return strutBaseX_impl(index, total).(float64)
}

func strutBaseY_impl(index interface{}, total interface{}) interface{} {
	var angleRange interface{} = func() interface{} {
		var tmp61 interface{} = math.Pi
		_ = tmp61 // suppress unused
		return DivFloat(tmp61, float64(3))
	}()
	var angleStep interface{} = func() interface{} {
		var tmp58 interface{} = MulFloat(angleRange, float64(2))
		_ = tmp58 // suppress unused
		return func() interface{} {
			var tmp59 interface{} = SubInt(total, int64(1))
			_ = tmp59 // suppress unused
			return func() interface{} {
				var tmp60 interface{} = IntToFloat(tmp59)
				_ = tmp60 // suppress unused
				return DivFloat(tmp58, tmp60)
			}()
		}()
	}()
	var angle interface{} = func() interface{} {
		var tmp55 interface{} = SubFloat(float64(0), angleRange)
		_ = tmp55 // suppress unused
		return func() interface{} {
			var tmp56 interface{} = IntToFloat(index)
			_ = tmp56 // suppress unused
			return func() interface{} {
				var tmp57 interface{} = MulFloat(tmp56, angleStep)
				_ = tmp57 // suppress unused
				return AddFloat(tmp55, tmp57)
			}()
		}()
	}()
	var tmp51 interface{} = arcCenterY_impl(struct{}{})
	var tmp52 interface{} = arcRadius_impl(struct{}{})
	var tmp53 interface{} = math.Cos(angle.(float64))
	var tmp54 interface{} = MulFloat(tmp52, tmp53)
	return SubFloat(tmp51, tmp54)
}

func strutBaseY(index int64, total int64) float64 {
	return strutBaseY_impl(index, total).(float64)
}

func strutTopX_impl(index interface{}, total interface{}) interface{} {
	var baseX interface{} = strutBaseX_impl(index, total)
	var centerX interface{} = func() interface{} {
		var tmp63 interface{} = screenWidth_impl(struct{}{})
		_ = tmp63 // suppress unused
		return DivFloat(tmp63, float64(2))
	}()
	var dx interface{} = SubFloat(baseX, centerX)
	var tmp62 interface{} = MulFloat(dx, float64(0.3))
	return AddFloat(baseX, tmp62)
}

func strutTopX(index int64, total int64) float64 {
	return strutTopX_impl(index, total).(float64)
}

func strutTopY_impl(index interface{}, total interface{}) interface{} {
	var baseY interface{} = strutBaseY_impl(index, total)
	return SubFloat(baseY, float64(150))
}

func strutTopY(index int64, total int64) float64 {
	return strutTopY_impl(index, total).(float64)
}

func strutParallax_impl(index interface{}, total interface{}, cameraZ interface{}) interface{} {
	var centerIndex interface{} = func() interface{} {
		var tmp67 interface{} = SubInt(total, int64(1))
		_ = tmp67 // suppress unused
		return func() interface{} {
			var tmp68 interface{} = IntToFloat(tmp67)
			_ = tmp68 // suppress unused
			return DivFloat(tmp68, float64(2))
		}()
	}()
	var offsetFromCenter interface{} = func() interface{} {
		var tmp66 interface{} = IntToFloat(index)
		_ = tmp66 // suppress unused
		return SubFloat(tmp66, centerIndex)
	}()
	var progress interface{} = func() interface{} {
		var tmp65 interface{} = SubFloat(float64(10), cameraZ)
		_ = tmp65 // suppress unused
		return DivFloat(tmp65, float64(165))
	}()
	var tmp64 interface{} = MulFloat(offsetFromCenter, progress)
	return MulFloat(tmp64, float64(3))
}

func strutParallax(index int64, total int64, cameraZ float64) float64 {
	return strutParallax_impl(index, total, cameraZ).(float64)
}

func renderStrutWithParallax_impl(index interface{}, total interface{}, cameraZ interface{}) interface{} {
	var parallax interface{} = strutParallax_impl(index, total, cameraZ)
	var tmp69 interface{} = strutBaseX_impl(index, total)
	var tmp70 interface{} = strutBaseY_impl(index, total)
	var tmp71 interface{} = strutTopX_impl(index, total)
	var tmp72 interface{} = AddFloat(tmp71, parallax)
	var tmp73 interface{} = strutTopY_impl(index, total)
	var tmp74 interface{} = strutColor_impl(struct{}{})
	var tmp75 interface{} = layerStruts_impl(struct{}{})
	return NewDrawCmdLine(tmp69.(float64), tmp70.(float64), tmp72.(float64), tmp73.(float64), tmp74.(int64), float64(2), tmp75.(int64))
}

func renderStrutWithParallax(index int64, total int64, cameraZ float64) *DrawCmd {
	return renderStrutWithParallax_impl(index, total, cameraZ).(*DrawCmd)
}

func renderStrutsRec_impl(index interface{}, total interface{}, cameraZ interface{}) interface{} {
	var tmp76 interface{} = GeInt(index, total)
	return func() interface{} {
		if tmp76.(bool) {
			return []interface{}{}
		}
		return func() interface{} {
			var tmp77 interface{} = renderStrutWithParallax_impl(index, total, cameraZ)
			_ = tmp77 // suppress unused
			return func() interface{} {
				var tmp78 interface{} = AddInt(index, int64(1))
				_ = tmp78 // suppress unused
				return func() interface{} {
					var tmp79 interface{} = renderStrutsRec_impl(tmp78, total, cameraZ)
					_ = tmp79 // suppress unused
					return Cons(tmp77, tmp79)
				}()
			}()
		}()
	}()
}

func renderStrutsRec(index int64, total int64, cameraZ float64) []*DrawCmd {
	return ConvertToDrawCmdSlice(renderStrutsRec_impl(index, total, cameraZ))
}

func renderStruts_impl(state interface{}) interface{} {
	var tmp80 interface{} = strutCount_impl(struct{}{})
	var tmp81 interface{} = FieldGet(state, "domeState")
	var tmp82 interface{} = FieldGet(tmp81, "cameraZ")
	return renderStrutsRec_impl(int64(0), tmp80, tmp82)
}

func RenderStruts(state *BridgeState) []*DrawCmd {
	return ConvertToDrawCmdSlice(renderStruts_impl(state))
}

func tileFloor_impl(_unused0 interface{}) interface{} {
	return int64(1000)
}

func TileFloor() int64 {
	return tileFloor_impl(struct{}{}).(int64)
}

func tileFloorGlow_impl(_unused0 interface{}) interface{} {
	return int64(1001)
}

func TileFloorGlow() int64 {
	return tileFloorGlow_impl(struct{}{}).(int64)
}

func tileConsoleBase_impl(_unused0 interface{}) interface{} {
	return int64(1002)
}

func TileConsoleBase() int64 {
	return tileConsoleBase_impl(struct{}{}).(int64)
}

func tileWalkway_impl(_unused0 interface{}) interface{} {
	return int64(1003)
}

func TileWalkway() int64 {
	return tileWalkway_impl(struct{}{}).(int64)
}

func tileDomeEdge_impl(_unused0 interface{}) interface{} {
	return int64(1004)
}

func TileDomeEdge() int64 {
	return tileDomeEdge_impl(struct{}{}).(int64)
}

func tileWall_impl(_unused0 interface{}) interface{} {
	return int64(1005)
}

func TileWall() int64 {
	return tileWall_impl(struct{}{}).(int64)
}

func tileHatch_impl(_unused0 interface{}) interface{} {
	return int64(1006)
}

func TileHatch() int64 {
	return tileHatch_impl(struct{}{}).(int64)
}

func tileCaptainArea_impl(_unused0 interface{}) interface{} {
	return int64(1007)
}

func TileCaptainArea() int64 {
	return tileCaptainArea_impl(struct{}{}).(int64)
}

func spriteConsoleHelm_impl(_unused0 interface{}) interface{} {
	return int64(1100)
}

func SpriteConsoleHelm() int64 {
	return spriteConsoleHelm_impl(struct{}{}).(int64)
}

func spriteConsoleComms_impl(_unused0 interface{}) interface{} {
	return int64(1101)
}

func SpriteConsoleComms() int64 {
	return spriteConsoleComms_impl(struct{}{}).(int64)
}

func spriteConsoleStatus_impl(_unused0 interface{}) interface{} {
	return int64(1102)
}

func SpriteConsoleStatus() int64 {
	return spriteConsoleStatus_impl(struct{}{}).(int64)
}

func spriteConsoleNav_impl(_unused0 interface{}) interface{} {
	return int64(1103)
}

func SpriteConsoleNav() int64 {
	return spriteConsoleNav_impl(struct{}{}).(int64)
}

func spriteConsoleScience_impl(_unused0 interface{}) interface{} {
	return int64(1104)
}

func SpriteConsoleScience() int64 {
	return spriteConsoleScience_impl(struct{}{}).(int64)
}

func spriteConsoleCaptain_impl(_unused0 interface{}) interface{} {
	return int64(1105)
}

func SpriteConsoleCaptain() int64 {
	return spriteConsoleCaptain_impl(struct{}{}).(int64)
}

func spriteCrewPilot_impl(_unused0 interface{}) interface{} {
	return int64(1200)
}

func SpriteCrewPilot() int64 {
	return spriteCrewPilot_impl(struct{}{}).(int64)
}

func spriteCrewComms_impl(_unused0 interface{}) interface{} {
	return int64(1201)
}

func SpriteCrewComms() int64 {
	return spriteCrewComms_impl(struct{}{}).(int64)
}

func spriteCrewEngineer_impl(_unused0 interface{}) interface{} {
	return int64(1202)
}

func SpriteCrewEngineer() int64 {
	return spriteCrewEngineer_impl(struct{}{}).(int64)
}

func spriteCrewScientist_impl(_unused0 interface{}) interface{} {
	return int64(1203)
}

func SpriteCrewScientist() int64 {
	return spriteCrewScientist_impl(struct{}{}).(int64)
}

func spriteCrewCaptain_impl(_unused0 interface{}) interface{} {
	return int64(1204)
}

func SpriteCrewCaptain() int64 {
	return spriteCrewCaptain_impl(struct{}{}).(int64)
}

func spritePlayer_impl(_unused0 interface{}) interface{} {
	return int64(1205)
}

func SpritePlayer() int64 {
	return spritePlayer_impl(struct{}{}).(int64)
}

func makeCoord_impl(x interface{}, y interface{}) interface{} {
	return &Coord{X: x.(int64), Y: y.(int64)}
}

func makeCoord(x int64, y int64) *Coord {
	return makeCoord_impl(x, y).(*Coord)
}

func distSq_impl(x interface{}, y interface{}, cx interface{}, cy interface{}) interface{} {
	var dx interface{} = SubInt(x, cx)
	var dy interface{} = SubInt(y, cy)
	var tmp83 interface{} = MulInt(dx, dx)
	var tmp84 interface{} = MulInt(dy, dy)
	return AddInt(tmp83, tmp84)
}

func distSq(x int64, y int64, cx int64, cy int64) int64 {
	return distSq_impl(x, y, cx, cy).(int64)
}

func isOnDisc_impl(x interface{}, y interface{}, cx interface{}, cy interface{}, radius interface{}) interface{} {
	var tmp85 interface{} = distSq_impl(x, y, cx, cy)
	var tmp86 interface{} = MulInt(radius, radius)
	return LeInt(tmp85, tmp86)
}

func IsOnDisc(x int64, y int64, cx int64, cy int64, radius int64) bool {
	return isOnDisc_impl(x, y, cx, cy, radius).(bool)
}

func isWalkable_impl(state interface{}, x interface{}, y interface{}) interface{} {
	var dSq interface{} = func() interface{} {
		var tmp89 interface{} = FieldGet(state, "discCenterX")
		_ = tmp89 // suppress unused
		return func() interface{} {
			var tmp90 interface{} = FieldGet(state, "discCenterY")
			_ = tmp90 // suppress unused
			return distSq_impl(x, y, tmp89, tmp90)
		}()
	}()
	var radiusSq interface{} = func() interface{} {
		var tmp87 interface{} = FieldGet(state, "discRadius")
		_ = tmp87 // suppress unused
		return func() interface{} {
			var tmp88 interface{} = FieldGet(state, "discRadius")
			_ = tmp88 // suppress unused
			return MulInt(tmp87, tmp88)
		}()
	}()
	return LtInt(dSq, radiusSq)
}

func IsWalkable(state *BridgeState, x int64, y int64) bool {
	return isWalkable_impl(state, x, y).(bool)
}

func getTileType_impl(x interface{}, y interface{}, cx interface{}, cy interface{}, radius interface{}) interface{} {
	var dSq interface{} = distSq_impl(x, y, cx, cy)
	var radiusSq interface{} = MulInt(radius, radius)
	var edgeSq interface{} = func() interface{} {
		var tmp98 interface{} = SubInt(radius, int64(1))
		_ = tmp98 // suppress unused
		return func() interface{} {
			var tmp99 interface{} = SubInt(radius, int64(1))
			_ = tmp99 // suppress unused
			return MulInt(tmp98, tmp99)
		}()
	}()
	var tmp91 interface{} = GeInt(dSq, radiusSq)
	return func() interface{} {
		var tmp92 interface{} = GeInt(dSq, edgeSq)
		_ = tmp92 // suppress unused
		var tmp93 interface{} = LeInt(dSq, int64(9))
		_ = tmp93 // suppress unused
		var tmp94 interface{} = LeInt(dSq, int64(36))
		_ = tmp94 // suppress unused
		var tmp95 interface{} = AddInt(x, y)
		_ = tmp95 // suppress unused
		var tmp96 interface{} = ModInt(tmp95, int64(8))
		_ = tmp96 // suppress unused
		var tmp97 interface{} = EqInt(tmp96, int64(0))
		_ = tmp97 // suppress unused
		if tmp91.(bool) {
			return tileWall_impl(struct{}{})
		}
		if tmp92.(bool) {
			return tileDomeEdge_impl(struct{}{})
		}
		if tmp93.(bool) {
			return tileCaptainArea_impl(struct{}{})
		}
		if tmp94.(bool) {
			return tileFloorGlow_impl(struct{}{})
		}
		if tmp97.(bool) {
			return tileWalkway_impl(struct{}{})
		}
		return tileFloor_impl(struct{}{})
	}()
}

func GetTileType(x int64, y int64, cx int64, cy int64, radius int64) int64 {
	return getTileType_impl(x, y, cx, cy, radius).(int64)
}

func viewportSize_impl(_unused0 interface{}) interface{} {
	return int64(10)
}

func ViewportSize() int64 {
	return viewportSize_impl(struct{}{}).(int64)
}

func stationSprite_impl(station interface{}) interface{} {
	return func() interface{} {
		_scrutinee := station
		_ = _scrutinee // suppress unused
		_adt := _scrutinee.(*BridgeStation)
		switch _adt.Kind {
		case BridgeStationKindStationHelm:
			return spriteConsoleHelm_impl(struct{}{})
		case BridgeStationKindStationComms:
			return spriteConsoleComms_impl(struct{}{})
		case BridgeStationKindStationStatus:
			return spriteConsoleStatus_impl(struct{}{})
		case BridgeStationKindStationNav:
			return spriteConsoleNav_impl(struct{}{})
		case BridgeStationKindStationScience:
			return spriteConsoleScience_impl(struct{}{})
		case BridgeStationKindStationCaptain:
			return spriteConsoleCaptain_impl(struct{}{})
		case BridgeStationKindStationNone:
			return int64(0)
		default:
			panic("non-exhaustive match")
		}
	}()
}

func StationSprite(station *BridgeStation) int64 {
	return stationSprite_impl(station).(int64)
}

func crewSprite_impl(station interface{}) interface{} {
	return func() interface{} {
		_scrutinee := station
		_ = _scrutinee // suppress unused
		_adt := _scrutinee.(*BridgeStation)
		switch _adt.Kind {
		case BridgeStationKindStationHelm:
			return spriteCrewPilot_impl(struct{}{})
		case BridgeStationKindStationComms:
			return spriteCrewComms_impl(struct{}{})
		case BridgeStationKindStationStatus:
			return spriteCrewEngineer_impl(struct{}{})
		case BridgeStationKindStationScience:
			return spriteCrewScientist_impl(struct{}{})
		case BridgeStationKindStationCaptain:
			return spriteCrewCaptain_impl(struct{}{})
		case BridgeStationKindStationNav:
			return spriteCrewEngineer_impl(struct{}{})
		case BridgeStationKindStationNone:
			return spriteCrewPilot_impl(struct{}{})
		default:
			panic("non-exhaustive match")
		}
	}()
}

func CrewSprite(station *BridgeStation) int64 {
	return crewSprite_impl(station).(int64)
}

func moveInDirection_impl(pos interface{}, dir interface{}) interface{} {
	var px interface{} = FieldGet(pos, "x")
	var py interface{} = FieldGet(pos, "y")
	return func() interface{} {
		_scrutinee := dir
		_ = _scrutinee // suppress unused
		switch _scrutinee {
		default:
			return func() interface{} {
				var tmp100 interface{} = SubInt(py, int64(1))
				_ = tmp100 // suppress unused
				return makeCoord_impl(px, tmp100)
			}()
		}
	}()
}

func MoveInDirection(pos *Coord, dir *Direction) *Coord {
	return moveInDirection_impl(pos, dir).(*Coord)
}

func discRadiusDefault_impl(_unused0 interface{}) interface{} {
	return int64(24)
}

func DiscRadiusDefault() int64 {
	return discRadiusDefault_impl(struct{}{}).(int64)
}

func discCenterDefault_impl(_unused0 interface{}) interface{} {
	return int64(24)
}

func DiscCenterDefault() int64 {
	return discCenterDefault_impl(struct{}{}).(int64)
}

func createConsoles_impl(_unused0 interface{}) interface{} {
	var cx interface{} = discCenterDefault_impl(struct{}{})
	var cy interface{} = discCenterDefault_impl(struct{}{})
	var tmp104 interface{} = SubInt(cy, int64(10))
	var tmp105 interface{} = makeCoord_impl(cx, tmp104)
	var tmp106 interface{} = spriteConsoleHelm_impl(struct{}{})
	var tmp107 interface{} = &ConsoleState{Station: NewBridgeStationStationHelm(), Pos: tmp105.(*Coord), Active: true, HasAlert: false, SpriteId: tmp106.(int64)}
	var tmp108 interface{} = SubInt(cx, int64(8))
	var tmp109 interface{} = SubInt(cy, int64(8))
	var tmp110 interface{} = makeCoord_impl(tmp108, tmp109)
	var tmp111 interface{} = spriteConsoleComms_impl(struct{}{})
	var tmp112 interface{} = &ConsoleState{Station: NewBridgeStationStationComms(), Pos: tmp110.(*Coord), Active: true, HasAlert: false, SpriteId: tmp111.(int64)}
	var tmp113 interface{} = AddInt(cx, int64(8))
	var tmp114 interface{} = SubInt(cy, int64(8))
	var tmp115 interface{} = makeCoord_impl(tmp113, tmp114)
	var tmp116 interface{} = spriteConsoleStatus_impl(struct{}{})
	var tmp117 interface{} = &ConsoleState{Station: NewBridgeStationStationStatus(), Pos: tmp115.(*Coord), Active: true, HasAlert: false, SpriteId: tmp116.(int64)}
	var tmp118 interface{} = makeCoord_impl(cx, cy)
	var tmp119 interface{} = spriteConsoleCaptain_impl(struct{}{})
	var tmp120 interface{} = &ConsoleState{Station: NewBridgeStationStationCaptain(), Pos: tmp118.(*Coord), Active: true, HasAlert: false, SpriteId: tmp119.(int64)}
	var tmp121 interface{} = SubInt(cx, int64(12))
	var tmp122 interface{} = makeCoord_impl(tmp121, cy)
	var tmp123 interface{} = spriteConsoleNav_impl(struct{}{})
	var tmp124 interface{} = &ConsoleState{Station: NewBridgeStationStationNav(), Pos: tmp122.(*Coord), Active: true, HasAlert: false, SpriteId: tmp123.(int64)}
	var tmp125 interface{} = AddInt(cx, int64(12))
	var tmp126 interface{} = makeCoord_impl(tmp125, cy)
	var tmp127 interface{} = spriteConsoleScience_impl(struct{}{})
	var tmp128 interface{} = &ConsoleState{Station: NewBridgeStationStationScience(), Pos: tmp126.(*Coord), Active: true, HasAlert: false, SpriteId: tmp127.(int64)}
	return []interface{}{tmp107, tmp112, tmp117, tmp120, tmp124, tmp128}
}

func CreateConsoles() []*ConsoleState {
	return ConvertToConsoleStateSlice(createConsoles_impl(struct{}{}))
}

func createDefaultCrew_impl(_unused0 interface{}) interface{} {
	var cx interface{} = discCenterDefault_impl(struct{}{})
	var cy interface{} = discCenterDefault_impl(struct{}{})
	var tmp129 interface{} = &CrewID{Id: int64(1), Name: "Pilot Chen"}
	var tmp130 interface{} = SubInt(cy, int64(9))
	var tmp131 interface{} = makeCoord_impl(cx, tmp130)
	var tmp132 interface{} = &CrewPosition{Crew: tmp129.(*CrewID), Station: NewBridgeStationStationHelm(), Pos: tmp131.(*Coord), Facing: NewDirectionNorth(), Activity: NewCrewActivityActivityWorking()}
	var tmp133 interface{} = &CrewID{Id: int64(2), Name: "Comms Officer Patel"}
	var tmp134 interface{} = SubInt(cx, int64(8))
	var tmp135 interface{} = SubInt(cy, int64(7))
	var tmp136 interface{} = makeCoord_impl(tmp134, tmp135)
	var tmp137 interface{} = &CrewPosition{Crew: tmp133.(*CrewID), Station: NewBridgeStationStationComms(), Pos: tmp136.(*Coord), Facing: NewDirectionNorth(), Activity: NewCrewActivityActivityWorking()}
	var tmp138 interface{} = &CrewID{Id: int64(3), Name: "Engineer Torres"}
	var tmp139 interface{} = AddInt(cx, int64(8))
	var tmp140 interface{} = SubInt(cy, int64(7))
	var tmp141 interface{} = makeCoord_impl(tmp139, tmp140)
	var tmp142 interface{} = &CrewPosition{Crew: tmp138.(*CrewID), Station: NewBridgeStationStationStatus(), Pos: tmp141.(*Coord), Facing: NewDirectionNorth(), Activity: NewCrewActivityActivityWorking()}
	var tmp143 interface{} = &CrewID{Id: int64(4), Name: "Navigator Kim"}
	var tmp144 interface{} = SubInt(cx, int64(11))
	var tmp145 interface{} = makeCoord_impl(tmp144, cy)
	var tmp146 interface{} = &CrewPosition{Crew: tmp143.(*CrewID), Station: NewBridgeStationStationNav(), Pos: tmp145.(*Coord), Facing: NewDirectionEast(), Activity: NewCrewActivityActivityWorking()}
	var tmp147 interface{} = &CrewID{Id: int64(5), Name: "Science Officer Okafor"}
	var tmp148 interface{} = AddInt(cx, int64(11))
	var tmp149 interface{} = makeCoord_impl(tmp148, cy)
	var tmp150 interface{} = &CrewPosition{Crew: tmp147.(*CrewID), Station: NewBridgeStationStationScience(), Pos: tmp149.(*Coord), Facing: NewDirectionWest(), Activity: NewCrewActivityActivityWorking()}
	var tmp151 interface{} = &CrewID{Id: int64(6), Name: "Captain Reyes"}
	var tmp152 interface{} = AddInt(cy, int64(1))
	var tmp153 interface{} = makeCoord_impl(cx, tmp152)
	var tmp154 interface{} = &CrewPosition{Crew: tmp151.(*CrewID), Station: NewBridgeStationStationCaptain(), Pos: tmp153.(*Coord), Facing: NewDirectionNorth(), Activity: NewCrewActivityActivityIdle()}
	return []interface{}{tmp132, tmp137, tmp142, tmp146, tmp150, tmp154}
}

func CreateDefaultCrew() []*CrewPosition {
	return ConvertToCrewPositionSlice(createDefaultCrew_impl(struct{}{}))
}

func initBridge_impl(_unused0 interface{}) interface{} {
	var cx interface{} = discCenterDefault_impl(struct{}{})
	var cy interface{} = discCenterDefault_impl(struct{}{})
	var radius interface{} = discRadiusDefault_impl(struct{}{})
	var tmp155 interface{} = AddInt(cy, int64(16))
	var tmp156 interface{} = makeCoord_impl(cx, tmp155)
	var tmp157 interface{} = AddInt(cy, int64(16))
	var tmp158 interface{} = createDefaultCrew_impl(struct{}{})
	var tmp159 interface{} = createConsoles_impl(struct{}{})
	var tmp160 interface{} = makeDomeViewState_impl(int64(0), float64(0.15), float64(0))
	var tmp161 interface{} = initDomeState_impl(struct{}{})
	return &BridgeState{PlayerPos: tmp156.(*Coord), PlayerFacing: NewDirectionNorth(), MoveState: NewMoveStateMoveIdle(), CameraX: cx.(int64), CameraY: tmp157.(int64), CrewPositions: ConvertToCrewPositionSlice(tmp158), Consoles: ConvertToConsoleStateSlice(tmp159), HoveredInteractable: NewOptionNone(), SelectedInteractable: NewOptionNone(), DomeView: tmp160.(*DomeViewState), DomeState: tmp161.(*DomeState), Tick: int64(0), DiscRadius: radius.(int64), DiscCenterX: cx.(int64), DiscCenterY: cy.(int64)}
}

func InitBridge() *BridgeState {
	return initBridge_impl(struct{}{}).(*BridgeState)
}

func layerFloor_impl(_unused0 interface{}) interface{} {
	return int64(0)
}

func layerFloor() int64 {
	return layerFloor_impl(struct{}{}).(int64)
}

func layerConsoles_impl(_unused0 interface{}) interface{} {
	return int64(1)
}

func layerConsoles() int64 {
	return layerConsoles_impl(struct{}{}).(int64)
}

func layerCrew_impl(_unused0 interface{}) interface{} {
	return int64(2)
}

func layerCrew() int64 {
	return layerCrew_impl(struct{}{}).(int64)
}

func layerPlayer_impl(_unused0 interface{}) interface{} {
	return int64(3)
}

func layerPlayer() int64 {
	return layerPlayer_impl(struct{}{}).(int64)
}

func colorWhite_impl(_unused0 interface{}) interface{} {
	return int64(4294967295)
}

func colorWhite() int64 {
	return colorWhite_impl(struct{}{}).(int64)
}

func screenOffsetX_impl(_unused0 interface{}) interface{} {
	return float64(640)
}

func screenOffsetX() float64 {
	return screenOffsetX_impl(struct{}{}).(float64)
}

func screenOffsetY_impl(_unused0 interface{}) interface{} {
	return float64(750)
}

func screenOffsetY() float64 {
	return screenOffsetY_impl(struct{}{}).(float64)
}

func tileColor_impl(tileType interface{}) interface{} {
	var tmp162 interface{} = tileWall_impl(struct{}{})
	var tmp163 interface{} = EqInt(tileType, tmp162)
	return func() interface{} {
		var tmp164 interface{} = tileDomeEdge_impl(struct{}{})
		_ = tmp164 // suppress unused
		var tmp165 interface{} = EqInt(tileType, tmp164)
		_ = tmp165 // suppress unused
		var tmp166 interface{} = tileCaptainArea_impl(struct{}{})
		_ = tmp166 // suppress unused
		var tmp167 interface{} = EqInt(tileType, tmp166)
		_ = tmp167 // suppress unused
		var tmp168 interface{} = tileFloorGlow_impl(struct{}{})
		_ = tmp168 // suppress unused
		var tmp169 interface{} = EqInt(tileType, tmp168)
		_ = tmp169 // suppress unused
		var tmp170 interface{} = tileWalkway_impl(struct{}{})
		_ = tmp170 // suppress unused
		var tmp171 interface{} = EqInt(tileType, tmp170)
		_ = tmp171 // suppress unused
		if tmp163.(bool) {
			return colorWall_impl(struct{}{})
		}
		if tmp165.(bool) {
			return colorDomeEdge_impl(struct{}{})
		}
		if tmp167.(bool) {
			return colorCaptainArea_impl(struct{}{})
		}
		if tmp169.(bool) {
			return colorFloorGlow_impl(struct{}{})
		}
		if tmp171.(bool) {
			return colorWalkway_impl(struct{}{})
		}
		return colorFloor_impl(struct{}{})
	}()
}

func tileColor(tileType int64) int64 {
	return tileColor_impl(tileType).(int64)
}

func renderTileAt_impl(worldX interface{}, worldY interface{}, camX interface{}, camY interface{}, tileType interface{}) interface{} {
	var relX interface{} = SubInt(worldX, camX)
	var relY interface{} = SubInt(worldY, camY)
	var isoX interface{} = func() interface{} {
		var tmp180 interface{} = SubInt(relX, relY)
		_ = tmp180 // suppress unused
		return func() interface{} {
			var tmp181 interface{} = MulInt(tmp180, int64(32))
			_ = tmp181 // suppress unused
			return IntToFloat(tmp181)
		}()
	}()
	var isoY interface{} = func() interface{} {
		var tmp178 interface{} = AddInt(relX, relY)
		_ = tmp178 // suppress unused
		return func() interface{} {
			var tmp179 interface{} = MulInt(tmp178, int64(16))
			_ = tmp179 // suppress unused
			return IntToFloat(tmp179)
		}()
	}()
	var screenX interface{} = func() interface{} {
		var tmp177 interface{} = screenOffsetX_impl(struct{}{})
		_ = tmp177 // suppress unused
		return AddFloat(isoX, tmp177)
	}()
	var screenY interface{} = func() interface{} {
		var tmp176 interface{} = screenOffsetY_impl(struct{}{})
		_ = tmp176 // suppress unused
		return AddFloat(isoY, tmp176)
	}()
	var tmp172 interface{} = SubFloat(screenX, float64(28))
	var tmp173 interface{} = SubFloat(screenY, float64(12))
	var tmp174 interface{} = tileColor_impl(tileType)
	var tmp175 interface{} = layerFloor_impl(struct{}{})
	return NewDrawCmdRectRGBA(tmp172.(float64), tmp173.(float64), float64(56), float64(28), tmp174.(int64), tmp175.(int64))
}

func renderTileAt(worldX int64, worldY int64, camX int64, camY int64, tileType int64) *DrawCmd {
	return renderTileAt_impl(worldX, worldY, camX, camY, tileType).(*DrawCmd)
}

func renderFloorRowViewportRec_impl(state interface{}, x interface{}, y interface{}, maxX interface{}, acc interface{}) interface{} {
	var tmp182 interface{} = GtInt(x, maxX)
	return func() interface{} {
		if tmp182.(bool) {
			return acc
		}
		return func() interface{} {
			var tmp183 interface{} = AddInt(x, int64(1))
			_ = tmp183 // suppress unused
			return func() interface{} {
				var tmp184 interface{} = FieldGet(state, "cameraX")
				_ = tmp184 // suppress unused
				return func() interface{} {
					var tmp185 interface{} = FieldGet(state, "cameraY")
					_ = tmp185 // suppress unused
					return func() interface{} {
						var tmp186 interface{} = FieldGet(state, "discCenterX")
						_ = tmp186 // suppress unused
						return func() interface{} {
							var tmp187 interface{} = FieldGet(state, "discCenterY")
							_ = tmp187 // suppress unused
							return func() interface{} {
								var tmp188 interface{} = FieldGet(state, "discRadius")
								_ = tmp188 // suppress unused
								return func() interface{} {
									var tmp189 interface{} = getTileType_impl(x, y, tmp186, tmp187, tmp188)
									_ = tmp189 // suppress unused
									return func() interface{} {
										var tmp190 interface{} = renderTileAt_impl(x, y, tmp184, tmp185, tmp189)
										_ = tmp190 // suppress unused
										return func() interface{} {
											var tmp191 interface{} = Cons(tmp190, acc)
											_ = tmp191 // suppress unused
											return renderFloorRowViewportRec_impl(state, tmp183, y, maxX, tmp191)
										}()
									}()
								}()
							}()
						}()
					}()
				}()
			}()
		}()
	}()
}

func renderFloorRowViewportRec(state *BridgeState, x int64, y int64, maxX int64, acc []*DrawCmd) []*DrawCmd {
	return ConvertToDrawCmdSlice(renderFloorRowViewportRec_impl(state, x, y, maxX, acc))
}

func renderFloorRowViewport_impl(state interface{}, x interface{}, y interface{}, maxX interface{}) interface{} {
	var tmp192 interface{} = []interface{}{}
	return renderFloorRowViewportRec_impl(state, x, y, maxX, tmp192)
}

func renderFloorRowViewport(state *BridgeState, x int64, y int64, maxX int64) []*DrawCmd {
	return ConvertToDrawCmdSlice(renderFloorRowViewport_impl(state, x, y, maxX))
}

func renderFloorRowsViewport_impl(state interface{}, y interface{}, maxY interface{}, minX interface{}, maxX interface{}) interface{} {
	var tmp193 interface{} = GtInt(y, maxY)
	return func() interface{} {
		if tmp193.(bool) {
			return []interface{}{}
		}
		return func() interface{} {
			var tmp194 interface{} = renderFloorRowViewport_impl(state, minX, y, maxX)
			_ = tmp194 // suppress unused
			return func() interface{} {
				var tmp195 interface{} = AddInt(y, int64(1))
				_ = tmp195 // suppress unused
				return func() interface{} {
					var tmp196 interface{} = renderFloorRowsViewport_impl(state, tmp195, maxY, minX, maxX)
					_ = tmp196 // suppress unused
					return Concat(tmp194, tmp196)
				}()
			}()
		}()
	}()
}

func renderFloorRowsViewport(state *BridgeState, y int64, maxY int64, minX int64, maxX int64) []*DrawCmd {
	return ConvertToDrawCmdSlice(renderFloorRowsViewport_impl(state, y, maxY, minX, maxX))
}

func renderBridgeFloor_impl(state interface{}) interface{} {
	var vp interface{} = viewportSize_impl(struct{}{})
	var minX interface{} = func() interface{} {
		var tmp200 interface{} = FieldGet(state, "cameraX")
		_ = tmp200 // suppress unused
		return SubInt(tmp200, vp)
	}()
	var maxX interface{} = func() interface{} {
		var tmp199 interface{} = FieldGet(state, "cameraX")
		_ = tmp199 // suppress unused
		return AddInt(tmp199, vp)
	}()
	var minY interface{} = func() interface{} {
		var tmp198 interface{} = FieldGet(state, "cameraY")
		_ = tmp198 // suppress unused
		return SubInt(tmp198, vp)
	}()
	var maxY interface{} = func() interface{} {
		var tmp197 interface{} = FieldGet(state, "cameraY")
		_ = tmp197 // suppress unused
		return AddInt(tmp197, vp)
	}()
	return renderFloorRowsViewport_impl(state, minY, maxY, minX, maxX)
}

func RenderBridgeFloor(state *BridgeState) []*DrawCmd {
	return ConvertToDrawCmdSlice(renderBridgeFloor_impl(state))
}

func inViewport_impl(wx interface{}, wy interface{}, camX interface{}, camY interface{}) interface{} {
	var vp interface{} = viewportSize_impl(struct{}{})
	var dx interface{} = SubInt(wx, camX)
	var dy interface{} = SubInt(wy, camY)
	var tmp201 interface{} = SubInt(int64(0), vp)
	var tmp202 interface{} = SubInt(tmp201, int64(2))
	var tmp203 interface{} = GeInt(dx, tmp202)
	var tmp204 interface{} = AddInt(vp, int64(2))
	var tmp205 interface{} = LeInt(dx, tmp204)
	var tmp206 interface{} = func() interface{} {
		if tmp203.(bool) {
			return tmp205
		}
		return false
	}()
	var tmp207 interface{} = SubInt(int64(0), vp)
	var tmp208 interface{} = SubInt(tmp207, int64(2))
	var tmp209 interface{} = GeInt(dy, tmp208)
	var tmp210 interface{} = func() interface{} {
		if tmp206.(bool) {
			return tmp209
		}
		return false
	}()
	var tmp211 interface{} = AddInt(vp, int64(2))
	var tmp212 interface{} = LeInt(dy, tmp211)
	return func() interface{} {
		if tmp210.(bool) {
			return tmp212
		}
		return false
	}()
}

func inViewport(wx int64, wy int64, camX int64, camY int64) bool {
	return inViewport_impl(wx, wy, camX, camY).(bool)
}

func consoleColor_impl(station interface{}) interface{} {
	return func() interface{} {
		_scrutinee := station
		_ = _scrutinee // suppress unused
		_adt := _scrutinee.(*BridgeStation)
		switch _adt.Kind {
		case BridgeStationKindStationHelm:
			return colorHelm_impl(struct{}{})
		case BridgeStationKindStationComms:
			return colorComms_impl(struct{}{})
		case BridgeStationKindStationStatus:
			return colorStatus_impl(struct{}{})
		case BridgeStationKindStationNav:
			return colorNav_impl(struct{}{})
		case BridgeStationKindStationScience:
			return colorScience_impl(struct{}{})
		case BridgeStationKindStationCaptain:
			return colorCaptain_impl(struct{}{})
		case BridgeStationKindStationNone:
			return colorFloor_impl(struct{}{})
		default:
			panic("non-exhaustive match")
		}
	}()
}

func consoleColor(station *BridgeStation) int64 {
	return consoleColor_impl(station).(int64)
}

func crewColor_impl(station interface{}) interface{} {
	return func() interface{} {
		_scrutinee := station
		_ = _scrutinee // suppress unused
		_adt := _scrutinee.(*BridgeStation)
		switch _adt.Kind {
		case BridgeStationKindStationHelm:
			return colorCrewPilot_impl(struct{}{})
		case BridgeStationKindStationComms:
			return colorCrewComms_impl(struct{}{})
		case BridgeStationKindStationStatus:
			return colorCrewEngineer_impl(struct{}{})
		case BridgeStationKindStationNav:
			return colorCrewEngineer_impl(struct{}{})
		case BridgeStationKindStationScience:
			return colorCrewScientist_impl(struct{}{})
		case BridgeStationKindStationCaptain:
			return colorCrewCaptain_impl(struct{}{})
		case BridgeStationKindStationNone:
			return colorPlayer_impl(struct{}{})
		default:
			panic("non-exhaustive match")
		}
	}()
}

func crewColor(station *BridgeStation) int64 {
	return crewColor_impl(station).(int64)
}

func renderConsole_impl(console interface{}, camX interface{}, camY interface{}) interface{} {
	var relX interface{} = func() interface{} {
		var tmp226 interface{} = FieldGet(console, "pos")
		_ = tmp226 // suppress unused
		return func() interface{} {
			var tmp227 interface{} = FieldGet(tmp226, "x")
			_ = tmp227 // suppress unused
			return SubInt(tmp227, camX)
		}()
	}()
	var relY interface{} = func() interface{} {
		var tmp224 interface{} = FieldGet(console, "pos")
		_ = tmp224 // suppress unused
		return func() interface{} {
			var tmp225 interface{} = FieldGet(tmp224, "y")
			_ = tmp225 // suppress unused
			return SubInt(tmp225, camY)
		}()
	}()
	var isoX interface{} = func() interface{} {
		var tmp222 interface{} = SubInt(relX, relY)
		_ = tmp222 // suppress unused
		return func() interface{} {
			var tmp223 interface{} = MulInt(tmp222, int64(32))
			_ = tmp223 // suppress unused
			return IntToFloat(tmp223)
		}()
	}()
	var isoY interface{} = func() interface{} {
		var tmp220 interface{} = AddInt(relX, relY)
		_ = tmp220 // suppress unused
		return func() interface{} {
			var tmp221 interface{} = MulInt(tmp220, int64(16))
			_ = tmp221 // suppress unused
			return IntToFloat(tmp221)
		}()
	}()
	var screenX interface{} = func() interface{} {
		var tmp219 interface{} = screenOffsetX_impl(struct{}{})
		_ = tmp219 // suppress unused
		return AddFloat(isoX, tmp219)
	}()
	var screenY interface{} = func() interface{} {
		var tmp218 interface{} = screenOffsetY_impl(struct{}{})
		_ = tmp218 // suppress unused
		return AddFloat(isoY, tmp218)
	}()
	var color interface{} = func() interface{} {
		var tmp217 interface{} = FieldGet(console, "station")
		_ = tmp217 // suppress unused
		return consoleColor_impl(tmp217)
	}()
	var tmp213 interface{} = SubFloat(screenX, float64(24))
	var tmp214 interface{} = SubFloat(screenY, float64(32))
	var tmp215 interface{} = layerConsoles_impl(struct{}{})
	var tmp216 interface{} = NewDrawCmdRectRGBA(tmp213.(float64), tmp214.(float64), float64(48), float64(24), color.(int64), tmp215.(int64))
	return []interface{}{tmp216}
}

func renderConsole(console *ConsoleState, camX int64, camY int64) []*DrawCmd {
	return ConvertToDrawCmdSlice(renderConsole_impl(console, camX, camY))
}

func renderConsolesRec_impl(consoles interface{}, camX interface{}, camY interface{}) interface{} {
	return func() interface{} {
		_scrutinee := consoles
		_ = _scrutinee // suppress unused
		if ListLen(_scrutinee) == 0 {
			return []interface{}{}
		} else if ListLen(_scrutinee) >= 1 {
			c := ListHead(_scrutinee)
			_ = c // suppress unused
			rest := ListTail(_scrutinee)
			_ = rest // suppress unused
			return func() interface{} {
				var tmp228 interface{} = FieldGet(c, "pos")
				_ = tmp228 // suppress unused
				return func() interface{} {
					var tmp229 interface{} = FieldGet(tmp228, "x")
					_ = tmp229 // suppress unused
					return func() interface{} {
						var tmp230 interface{} = FieldGet(c, "pos")
						_ = tmp230 // suppress unused
						return func() interface{} {
							var tmp231 interface{} = FieldGet(tmp230, "y")
							_ = tmp231 // suppress unused
							return func() interface{} {
								var tmp232 interface{} = inViewport_impl(tmp229, tmp231, camX, camY)
								_ = tmp232 // suppress unused
								return func() interface{} {
									if tmp232.(bool) {
										return func() interface{} {
											var tmp233 interface{} = renderConsole_impl(c, camX, camY)
											_ = tmp233 // suppress unused
											return func() interface{} {
												var tmp234 interface{} = renderConsolesRec_impl(rest, camX, camY)
												_ = tmp234 // suppress unused
												return Concat(tmp233, tmp234)
											}()
										}()
									}
									return renderConsolesRec_impl(rest, camX, camY)
								}()
							}()
						}()
					}()
				}()
			}()
		} else {
			panic("non-exhaustive match")
		}
	}()
}

func renderConsolesRec(consoles []*ConsoleState, camX int64, camY int64) []*DrawCmd {
	return ConvertToDrawCmdSlice(renderConsolesRec_impl(consoles, camX, camY))
}

func renderConsoles_impl(state interface{}) interface{} {
	var tmp235 interface{} = FieldGet(state, "consoles")
	var tmp236 interface{} = FieldGet(state, "cameraX")
	var tmp237 interface{} = FieldGet(state, "cameraY")
	return renderConsolesRec_impl(tmp235, tmp236, tmp237)
}

func RenderConsoles(state *BridgeState) []*DrawCmd {
	return ConvertToDrawCmdSlice(renderConsoles_impl(state))
}

func renderCrewMember_impl(crew interface{}, camX interface{}, camY interface{}) interface{} {
	var relX interface{} = func() interface{} {
		var tmp257 interface{} = FieldGet(crew, "pos")
		_ = tmp257 // suppress unused
		return func() interface{} {
			var tmp258 interface{} = FieldGet(tmp257, "x")
			_ = tmp258 // suppress unused
			return SubInt(tmp258, camX)
		}()
	}()
	var relY interface{} = func() interface{} {
		var tmp255 interface{} = FieldGet(crew, "pos")
		_ = tmp255 // suppress unused
		return func() interface{} {
			var tmp256 interface{} = FieldGet(tmp255, "y")
			_ = tmp256 // suppress unused
			return SubInt(tmp256, camY)
		}()
	}()
	var isoX interface{} = func() interface{} {
		var tmp253 interface{} = SubInt(relX, relY)
		_ = tmp253 // suppress unused
		return func() interface{} {
			var tmp254 interface{} = MulInt(tmp253, int64(32))
			_ = tmp254 // suppress unused
			return IntToFloat(tmp254)
		}()
	}()
	var isoY interface{} = func() interface{} {
		var tmp251 interface{} = AddInt(relX, relY)
		_ = tmp251 // suppress unused
		return func() interface{} {
			var tmp252 interface{} = MulInt(tmp251, int64(16))
			_ = tmp252 // suppress unused
			return IntToFloat(tmp252)
		}()
	}()
	var screenX interface{} = func() interface{} {
		var tmp250 interface{} = screenOffsetX_impl(struct{}{})
		_ = tmp250 // suppress unused
		return AddFloat(isoX, tmp250)
	}()
	var screenY interface{} = func() interface{} {
		var tmp249 interface{} = screenOffsetY_impl(struct{}{})
		_ = tmp249 // suppress unused
		return AddFloat(isoY, tmp249)
	}()
	var color interface{} = func() interface{} {
		var tmp248 interface{} = FieldGet(crew, "station")
		_ = tmp248 // suppress unused
		return crewColor_impl(tmp248)
	}()
	var tmp238 interface{} = SubFloat(screenY, float64(8))
	var tmp239 interface{} = layerCrew_impl(struct{}{})
	var tmp240 interface{} = NewDrawCmdCircleRGBA(screenX.(float64), tmp238.(float64), float64(12), color.(int64), true, tmp239.(int64))
	var tmp241 interface{} = FieldGet(crew, "crew")
	var tmp242 interface{} = FieldGet(tmp241, "name")
	var tmp243 interface{} = SubFloat(screenX, float64(30))
	var tmp244 interface{} = AddFloat(screenY, float64(8))
	var tmp245 interface{} = layerCrew_impl(struct{}{})
	var tmp246 interface{} = AddInt(tmp245, int64(1))
	var tmp247 interface{} = NewDrawCmdText(tmp242.(string), tmp243.(float64), tmp244.(float64), int64(8), int64(4294967295), tmp246.(int64))
	return []interface{}{tmp240, tmp247}
}

func renderCrewMember(crew *CrewPosition, camX int64, camY int64) []*DrawCmd {
	return ConvertToDrawCmdSlice(renderCrewMember_impl(crew, camX, camY))
}

func renderCrewRec_impl(crew interface{}, camX interface{}, camY interface{}) interface{} {
	return func() interface{} {
		_scrutinee := crew
		_ = _scrutinee // suppress unused
		if ListLen(_scrutinee) == 0 {
			return []interface{}{}
		} else if ListLen(_scrutinee) >= 1 {
			c := ListHead(_scrutinee)
			_ = c // suppress unused
			rest := ListTail(_scrutinee)
			_ = rest // suppress unused
			return func() interface{} {
				var tmp259 interface{} = FieldGet(c, "pos")
				_ = tmp259 // suppress unused
				return func() interface{} {
					var tmp260 interface{} = FieldGet(tmp259, "x")
					_ = tmp260 // suppress unused
					return func() interface{} {
						var tmp261 interface{} = FieldGet(c, "pos")
						_ = tmp261 // suppress unused
						return func() interface{} {
							var tmp262 interface{} = FieldGet(tmp261, "y")
							_ = tmp262 // suppress unused
							return func() interface{} {
								var tmp263 interface{} = inViewport_impl(tmp260, tmp262, camX, camY)
								_ = tmp263 // suppress unused
								return func() interface{} {
									if tmp263.(bool) {
										return func() interface{} {
											var tmp264 interface{} = renderCrewMember_impl(c, camX, camY)
											_ = tmp264 // suppress unused
											return func() interface{} {
												var tmp265 interface{} = renderCrewRec_impl(rest, camX, camY)
												_ = tmp265 // suppress unused
												return Concat(tmp264, tmp265)
											}()
										}()
									}
									return renderCrewRec_impl(rest, camX, camY)
								}()
							}()
						}()
					}()
				}()
			}()
		} else {
			panic("non-exhaustive match")
		}
	}()
}

func renderCrewRec(crew []*CrewPosition, camX int64, camY int64) []*DrawCmd {
	return ConvertToDrawCmdSlice(renderCrewRec_impl(crew, camX, camY))
}

func renderBridgeCrew_impl(state interface{}) interface{} {
	var tmp266 interface{} = FieldGet(state, "crewPositions")
	var tmp267 interface{} = FieldGet(state, "cameraX")
	var tmp268 interface{} = FieldGet(state, "cameraY")
	return renderCrewRec_impl(tmp266, tmp267, tmp268)
}

func RenderBridgeCrew(state *BridgeState) []*DrawCmd {
	return ConvertToDrawCmdSlice(renderBridgeCrew_impl(state))
}

func renderPlayer_impl(state interface{}) interface{} {
	var relX interface{} = func() interface{} {
		var tmp289 interface{} = FieldGet(state, "playerPos")
		_ = tmp289 // suppress unused
		return func() interface{} {
			var tmp290 interface{} = FieldGet(tmp289, "x")
			_ = tmp290 // suppress unused
			return func() interface{} {
				var tmp291 interface{} = FieldGet(state, "cameraX")
				_ = tmp291 // suppress unused
				return SubInt(tmp290, tmp291)
			}()
		}()
	}()
	var relY interface{} = func() interface{} {
		var tmp286 interface{} = FieldGet(state, "playerPos")
		_ = tmp286 // suppress unused
		return func() interface{} {
			var tmp287 interface{} = FieldGet(tmp286, "y")
			_ = tmp287 // suppress unused
			return func() interface{} {
				var tmp288 interface{} = FieldGet(state, "cameraY")
				_ = tmp288 // suppress unused
				return SubInt(tmp287, tmp288)
			}()
		}()
	}()
	var isoX interface{} = func() interface{} {
		var tmp284 interface{} = SubInt(relX, relY)
		_ = tmp284 // suppress unused
		return func() interface{} {
			var tmp285 interface{} = MulInt(tmp284, int64(32))
			_ = tmp285 // suppress unused
			return IntToFloat(tmp285)
		}()
	}()
	var isoY interface{} = func() interface{} {
		var tmp282 interface{} = AddInt(relX, relY)
		_ = tmp282 // suppress unused
		return func() interface{} {
			var tmp283 interface{} = MulInt(tmp282, int64(16))
			_ = tmp283 // suppress unused
			return IntToFloat(tmp283)
		}()
	}()
	var screenX interface{} = func() interface{} {
		var tmp281 interface{} = screenOffsetX_impl(struct{}{})
		_ = tmp281 // suppress unused
		return AddFloat(isoX, tmp281)
	}()
	var screenY interface{} = func() interface{} {
		var tmp280 interface{} = screenOffsetY_impl(struct{}{})
		_ = tmp280 // suppress unused
		return AddFloat(isoY, tmp280)
	}()
	var tmp269 interface{} = SubFloat(screenX, float64(10))
	var tmp270 interface{} = SubFloat(screenY, float64(18))
	var tmp271 interface{} = colorPlayer_impl(struct{}{})
	var tmp272 interface{} = layerPlayer_impl(struct{}{})
	var tmp273 interface{} = NewDrawCmdRectRGBA(tmp269.(float64), tmp270.(float64), float64(20), float64(20), tmp271.(int64), tmp272.(int64))
	var tmp274 interface{} = SubFloat(screenX, float64(12))
	var tmp275 interface{} = AddFloat(screenY, float64(8))
	var tmp276 interface{} = colorPlayer_impl(struct{}{})
	var tmp277 interface{} = layerPlayer_impl(struct{}{})
	var tmp278 interface{} = AddInt(tmp277, int64(1))
	var tmp279 interface{} = NewDrawCmdText("YOU", tmp274.(float64), tmp275.(float64), int64(10), tmp276.(int64), tmp278.(int64))
	return []interface{}{tmp273, tmp279}
}

func RenderPlayer(state *BridgeState) []*DrawCmd {
	return ConvertToDrawCmdSlice(renderPlayer_impl(state))
}

func renderBridge_impl(state interface{}) interface{} {
	var tmp292 interface{} = FieldGet(state, "domeState")
	var tmp293 interface{} = renderDome_impl(tmp292)
	var tmp294 interface{} = renderStruts_impl(state)
	var tmp295 interface{} = Concat(tmp293, tmp294)
	var tmp296 interface{} = renderBridgeFloor_impl(state)
	var tmp297 interface{} = Concat(tmp295, tmp296)
	var tmp298 interface{} = renderConsoles_impl(state)
	var tmp299 interface{} = Concat(tmp297, tmp298)
	var tmp300 interface{} = renderBridgeCrew_impl(state)
	var tmp301 interface{} = Concat(tmp299, tmp300)
	var tmp302 interface{} = renderPlayer_impl(state)
	return Concat(tmp301, tmp302)
}

func RenderBridge(state *BridgeState) []*DrawCmd {
	return ConvertToDrawCmdSlice(renderBridge_impl(state))
}

func getPatrolDirection_impl(crewId interface{}, frame interface{}) interface{} {
	var phase interface{} = func() interface{} {
		var tmp303 interface{} = DivInt(frame, int64(30))
		_ = tmp303 // suppress unused
		return func() interface{} {
			var tmp304 interface{} = MulInt(crewId, int64(7))
			_ = tmp304 // suppress unused
			return func() interface{} {
				var tmp305 interface{} = AddInt(tmp303, tmp304)
				_ = tmp305 // suppress unused
				return ModInt(tmp305, int64(4))
			}()
		}()
	}()
	return func() interface{} {
		_scrutinee := phase
		_ = _scrutinee // suppress unused
		switch _scrutinee {
		case int64(0):
			return NewDirectionNorth()
		case int64(1):
			return NewDirectionEast()
		case int64(2):
			return NewDirectionSouth()
		default:
			return NewDirectionWest()
		}
	}()
}

func getPatrolDirection(crewId int64, frame int64) *Direction {
	return getPatrolDirection_impl(crewId, frame).(*Direction)
}

func tryMoveCrew_impl(crew interface{}, dir interface{}, state interface{}) interface{} {
	var newPos interface{} = func() interface{} {
		var tmp309 interface{} = FieldGet(crew, "pos")
		_ = tmp309 // suppress unused
		return moveInDirection_impl(tmp309, dir)
	}()
	var tmp306 interface{} = FieldGet(newPos, "x")
	var tmp307 interface{} = FieldGet(newPos, "y")
	var tmp308 interface{} = isWalkable_impl(state, tmp306, tmp307)
	return func() interface{} {
		if tmp308.(bool) {
			return RecordUpdate(crew, map[string]interface{}{"pos": newPos, "facing": dir})
		}
		return RecordUpdate(crew, map[string]interface{}{"facing": dir})
	}()
}

func tryMoveCrew(crew *CrewPosition, dir *Direction, state *BridgeState) *CrewPosition {
	return tryMoveCrew_impl(crew, dir, state).(*CrewPosition)
}

func updateCrewMember_impl(crew interface{}, frame interface{}, state interface{}) interface{} {
	var tmp310 interface{} = ModInt(frame, int64(30))
	var tmp311 interface{} = EqInt(tmp310, int64(0))
	return func() interface{} {
		if tmp311.(bool) {
			return func() interface{} {
				var tmp312 interface{} = FieldGet(crew, "crew")
				_ = tmp312 // suppress unused
				return func() interface{} {
					var tmp313 interface{} = FieldGet(tmp312, "id")
					_ = tmp313 // suppress unused
					return func() interface{} {
						var tmp314 interface{} = getPatrolDirection_impl(tmp313, frame)
						_ = tmp314 // suppress unused
						return tryMoveCrew_impl(crew, tmp314, state)
					}()
				}()
			}()
		}
		return crew
	}()
}

func updateCrewMember(crew *CrewPosition, frame int64, state *BridgeState) *CrewPosition {
	return updateCrewMember_impl(crew, frame, state).(*CrewPosition)
}

func updateCrewRec_impl(crew interface{}, frame interface{}, state interface{}) interface{} {
	return func() interface{} {
		_scrutinee := crew
		_ = _scrutinee // suppress unused
		if ListLen(_scrutinee) == 0 {
			return []interface{}{}
		} else if ListLen(_scrutinee) >= 1 {
			c := ListHead(_scrutinee)
			_ = c // suppress unused
			rest := ListTail(_scrutinee)
			_ = rest // suppress unused
			return func() interface{} {
				var tmp315 interface{} = updateCrewMember_impl(c, frame, state)
				_ = tmp315 // suppress unused
				return func() interface{} {
					var tmp316 interface{} = updateCrewRec_impl(rest, frame, state)
					_ = tmp316 // suppress unused
					return Cons(tmp315, tmp316)
				}()
			}()
		} else {
			panic("non-exhaustive match")
		}
	}()
}

func updateCrewRec(crew []*CrewPosition, frame int64, state *BridgeState) []*CrewPosition {
	return ConvertToCrewPositionSlice(updateCrewRec_impl(crew, frame, state))
}

func stepBridge_impl(state interface{}, frame interface{}) interface{} {
	var dt interface{} = DivFloat(float64(1), float64(60))
	var updatedDome interface{} = func() interface{} {
		var tmp322 interface{} = FieldGet(state, "domeState")
		_ = tmp322 // suppress unused
		return stepDome_impl(tmp322, dt)
	}()
	var updatedDomeView interface{} = func() interface{} {
		var tmp318 interface{} = FieldGet(updatedDome, "targetPlanet")
		_ = tmp318 // suppress unused
		return func() interface{} {
			var tmp319 interface{} = FieldGet(updatedDome, "cruiseVelocity")
			_ = tmp319 // suppress unused
			return func() interface{} {
				var tmp320 interface{} = FieldGet(state, "domeView")
				_ = tmp320 // suppress unused
				return func() interface{} {
					var tmp321 interface{} = FieldGet(tmp320, "viewAngle")
					_ = tmp321 // suppress unused
					return makeDomeViewState_impl(tmp318, tmp319, tmp321)
				}()
			}()
		}()
	}()
	var updatedCrew interface{} = func() interface{} {
		var tmp317 interface{} = FieldGet(state, "crewPositions")
		_ = tmp317 // suppress unused
		return updateCrewRec_impl(tmp317, frame, state)
	}()
	return RecordUpdate(state, map[string]interface{}{"domeView": updatedDomeView, "tick": frame, "crewPositions": updatedCrew, "domeState": updatedDome})
}

func StepBridge(state *BridgeState, frame int64) *BridgeState {
	return stepBridge_impl(state, frame).(*BridgeState)
}
