// Code generated by ailang. DO NOT EDIT.
// Type class dictionary implementations.
package sim_gen

// dict_Num_Int provides Num type class methods for int64
var dict_Num_Int = struct {
	Add func(interface{}, interface{}) interface{}
	Sub func(interface{}, interface{}) interface{}
	Mul func(interface{}, interface{}) interface{}
	Div func(interface{}, interface{}) interface{}
	Neg func(interface{}) interface{}
	Abs func(interface{}) interface{}
}{
	Add: func(x, y interface{}) interface{} { return x.(int64) + y.(int64) },
	Sub: func(x, y interface{}) interface{} { return x.(int64) - y.(int64) },
	Mul: func(x, y interface{}) interface{} { return x.(int64) * y.(int64) },
	Div: func(x, y interface{}) interface{} { return x.(int64) / y.(int64) },
	Neg: func(x interface{}) interface{} { return -x.(int64) },
	Abs: func(x interface{}) interface{} {
		v := x.(int64)
		if v < 0 {
			return -v
		}
		return v
	},
}

// dict_Num_Float provides Num type class methods for float64
var dict_Num_Float = struct {
	Add func(interface{}, interface{}) interface{}
	Sub func(interface{}, interface{}) interface{}
	Mul func(interface{}, interface{}) interface{}
	Div func(interface{}, interface{}) interface{}
	Neg func(interface{}) interface{}
	Abs func(interface{}) interface{}
}{
	Add: func(x, y interface{}) interface{} { return x.(float64) + y.(float64) },
	Sub: func(x, y interface{}) interface{} { return x.(float64) - y.(float64) },
	Mul: func(x, y interface{}) interface{} { return x.(float64) * y.(float64) },
	Div: func(x, y interface{}) interface{} { return x.(float64) / y.(float64) },
	Neg: func(x interface{}) interface{} { return -x.(float64) },
	Abs: func(x interface{}) interface{} {
		v := x.(float64)
		if v < 0 {
			return -v
		}
		return v
	},
}

// dict_Ord_Int provides Ord type class methods for int64
var dict_Ord_Int = struct {
	Lt  func(interface{}, interface{}) interface{}
	Gt  func(interface{}, interface{}) interface{}
	Lte func(interface{}, interface{}) interface{}
	Gte func(interface{}, interface{}) interface{}
}{
	Lt:  func(x, y interface{}) interface{} { return x.(int64) < y.(int64) },
	Gt:  func(x, y interface{}) interface{} { return x.(int64) > y.(int64) },
	Lte: func(x, y interface{}) interface{} { return x.(int64) <= y.(int64) },
	Gte: func(x, y interface{}) interface{} { return x.(int64) >= y.(int64) },
}

// dict_Ord_Float provides Ord type class methods for float64
var dict_Ord_Float = struct {
	Lt  func(interface{}, interface{}) interface{}
	Gt  func(interface{}, interface{}) interface{}
	Lte func(interface{}, interface{}) interface{}
	Gte func(interface{}, interface{}) interface{}
}{
	Lt:  func(x, y interface{}) interface{} { return x.(float64) < y.(float64) },
	Gt:  func(x, y interface{}) interface{} { return x.(float64) > y.(float64) },
	Lte: func(x, y interface{}) interface{} { return x.(float64) <= y.(float64) },
	Gte: func(x, y interface{}) interface{} { return x.(float64) >= y.(float64) },
}

// dict_Ord_String provides Ord type class methods for string
var dict_Ord_String = struct {
	Lt  func(interface{}, interface{}) interface{}
	Gt  func(interface{}, interface{}) interface{}
	Lte func(interface{}, interface{}) interface{}
	Gte func(interface{}, interface{}) interface{}
}{
	Lt:  func(x, y interface{}) interface{} { return x.(string) < y.(string) },
	Gt:  func(x, y interface{}) interface{} { return x.(string) > y.(string) },
	Lte: func(x, y interface{}) interface{} { return x.(string) <= y.(string) },
	Gte: func(x, y interface{}) interface{} { return x.(string) >= y.(string) },
}

// dict_Eq_Int provides Eq type class methods for int64
var dict_Eq_Int = struct {
	Eq  func(interface{}, interface{}) interface{}
	Neq func(interface{}, interface{}) interface{}
}{
	Eq:  func(x, y interface{}) interface{} { return x.(int64) == y.(int64) },
	Neq: func(x, y interface{}) interface{} { return x.(int64) != y.(int64) },
}

// dict_Eq_Float provides Eq type class methods for float64
var dict_Eq_Float = struct {
	Eq  func(interface{}, interface{}) interface{}
	Neq func(interface{}, interface{}) interface{}
}{
	Eq:  func(x, y interface{}) interface{} { return x.(float64) == y.(float64) },
	Neq: func(x, y interface{}) interface{} { return x.(float64) != y.(float64) },
}

// dict_Eq_String provides Eq type class methods for string
var dict_Eq_String = struct {
	Eq  func(interface{}, interface{}) interface{}
	Neq func(interface{}, interface{}) interface{}
}{
	Eq:  func(x, y interface{}) interface{} { return x.(string) == y.(string) },
	Neq: func(x, y interface{}) interface{} { return x.(string) != y.(string) },
}

// dict_Eq_Bool provides Eq type class methods for bool
var dict_Eq_Bool = struct {
	Eq  func(interface{}, interface{}) interface{}
	Neq func(interface{}, interface{}) interface{}
}{
	Eq:  func(x, y interface{}) interface{} { return x.(bool) == y.(bool) },
	Neq: func(x, y interface{}) interface{} { return x.(bool) != y.(bool) },
}
