// Code generated by ailang. DO NOT EDIT.
package sim_gen

func IsInBounds(x interface{}, y interface{}, width interface{}, height interface{}) interface{} {
	return func() interface{} {
		var tmp1 interface{} = GeInt(x, int64(0))
		_ = tmp1 // suppress unused
		return func() interface{} {
			var tmp2 interface{} = LtInt(x, width)
			_ = tmp2 // suppress unused
			return func() interface{} {
				var tmp3 interface{} = func() interface{} {
					if tmp1.(bool) {
						return tmp2
					}
					return false
				}()
				_ = tmp3 // suppress unused
				return func() interface{} {
					var tmp4 interface{} = GeInt(y, int64(0))
					_ = tmp4 // suppress unused
					return func() interface{} {
						var tmp5 interface{} = func() interface{} {
							if tmp3.(bool) {
								return tmp4
							}
							return false
						}()
						_ = tmp5 // suppress unused
						return func() interface{} {
							var tmp6 interface{} = LtInt(y, height)
							_ = tmp6 // suppress unused
							return func() interface{} {
								if tmp5.(bool) {
									return tmp6
								}
								return false
							}()
						}()
					}()
				}()
			}()
		}()
	}()
}

func directionDx(dir interface{}) interface{} {
	return func() interface{} {
		_scrutinee := dir
		_ = _scrutinee // suppress unused
		_adt := _scrutinee.(*Direction)
		switch _adt.Kind {
		case DirectionKindNorth:
			return int64(0)
		case DirectionKindSouth:
			return int64(0)
		case DirectionKindEast:
			return int64(1)
		case DirectionKindWest:
			return NegInt(int64(1))
		default:
			panic("non-exhaustive match")
		}
	}()
}

func directionDy(dir interface{}) interface{} {
	return func() interface{} {
		_scrutinee := dir
		_ = _scrutinee // suppress unused
		_adt := _scrutinee.(*Direction)
		switch _adt.Kind {
		case DirectionKindNorth:
			return NegInt(int64(1))
		case DirectionKindSouth:
			return int64(1)
		case DirectionKindEast:
			return int64(0)
		case DirectionKindWest:
			return int64(0)
		default:
			panic("non-exhaustive match")
		}
	}()
}

func indexToDirection(idx interface{}) interface{} {
	return func() interface{} {
		var tmp7 interface{} = ModInt(idx, int64(4))
		_ = tmp7 // suppress unused
		return func() interface{} {
			_scrutinee := tmp7
			_ = _scrutinee // suppress unused
			switch _scrutinee {
			case int64(0):
				return NewDirectionNorth()
			case int64(1):
				return NewDirectionSouth()
			case int64(2):
				return NewDirectionEast()
			default:
				return NewDirectionWest()
			}
		}()
	}()
}

func pathLength(path interface{}) interface{} {
	return func() interface{} {
		_scrutinee := path
		_ = _scrutinee // suppress unused
		if ListLen(_scrutinee) == 0 {
			return int64(0)
		} else if ListLen(_scrutinee) >= 1 {
			rest := ListTail(_scrutinee)
			_ = rest // suppress unused
			return func() interface{} {
				var tmp8 interface{} = pathLength(rest)
				_ = tmp8 // suppress unused
				return AddInt(int64(1), tmp8)
			}()
		} else {
			panic("non-exhaustive match")
		}
	}()
}

func pathGet(path interface{}, idx interface{}) interface{} {
	return func() interface{} {
		_scrutinee := path
		_ = _scrutinee // suppress unused
		if ListLen(_scrutinee) == 0 {
			return NewDirectionNorth()
		} else if ListLen(_scrutinee) >= 1 {
			dir := ListHead(_scrutinee)
			_ = dir // suppress unused
			rest := ListTail(_scrutinee)
			_ = rest // suppress unused
			return func() interface{} {
				var tmp9 interface{} = LeInt(idx, int64(0))
				_ = tmp9 // suppress unused
				return func() interface{} {
					if tmp9.(bool) {
						return dir
					}
					return func() interface{} {
						var tmp10 interface{} = SubInt(idx, int64(1))
						_ = tmp10 // suppress unused
						return pathGet(rest, tmp10)
					}()
				}()
			}()
		} else {
			panic("non-exhaustive match")
		}
	}()
}

func npcWithPos(npc interface{}, newX interface{}, newY interface{}) interface{} {
	return func() interface{} {
		var tmp11 interface{} = &Coord{X: newX.(int64), Y: newY.(int64)}
		_ = tmp11 // suppress unused
		return RecordUpdate(npc, map[string]interface{}{"pos": tmp11})
	}()
}

func npcWithCounter(npc interface{}, counter interface{}) interface{} {
	return RecordUpdate(npc, map[string]interface{}{"moveCounter": counter})
}

func TryMoveDirection(npc interface{}, dir interface{}, width interface{}, height interface{}) interface{} {
	return func() interface{} {
		var dx interface{} = directionDx(dir)
		_ = dx // suppress unused
		return func() interface{} {
			var dy interface{} = directionDy(dir)
			_ = dy // suppress unused
			return func() interface{} {
				var newX interface{} = func() interface{} {
					var tmp15 interface{} = FieldGet(npc, "pos")
					_ = tmp15 // suppress unused
					return func() interface{} {
						var tmp16 interface{} = FieldGet(tmp15, "x")
						_ = tmp16 // suppress unused
						return AddInt(tmp16, dx)
					}()
				}()
				_ = newX // suppress unused
				return func() interface{} {
					var newY interface{} = func() interface{} {
						var tmp13 interface{} = FieldGet(npc, "pos")
						_ = tmp13 // suppress unused
						return func() interface{} {
							var tmp14 interface{} = FieldGet(tmp13, "y")
							_ = tmp14 // suppress unused
							return AddInt(tmp14, dy)
						}()
					}()
					_ = newY // suppress unused
					return func() interface{} {
						var tmp12 interface{} = IsInBounds(newX, newY, width, height)
						_ = tmp12 // suppress unused
						return func() interface{} {
							if tmp12.(bool) {
								return npcWithPos(npc, newX, newY)
							}
							return npc
						}()
					}()
				}()
			}()
		}()
	}()
}

func updateRandomWalk(npc interface{}, interval interface{}, width interface{}, height interface{}) interface{} {
	return func() interface{} {
		var tmp17 interface{} = FieldGet(npc, "moveCounter")
		_ = tmp17 // suppress unused
		return func() interface{} {
			var tmp18 interface{} = LeInt(tmp17, int64(0))
			_ = tmp18 // suppress unused
			return func() interface{} {
				if tmp18.(bool) {
					return func() interface{} {
						var dirIndex interface{} = handlers.Rand.RandInt(int64(0), int64(3))
						_ = dirIndex // suppress unused
						return func() interface{} {
							var dir interface{} = indexToDirection(dirIndex)
							_ = dir // suppress unused
							return func() interface{} {
								var movedNpc interface{} = TryMoveDirection(npc, dir, width, height)
								_ = movedNpc // suppress unused
								return npcWithCounter(movedNpc, interval)
							}()
						}()
					}()
				}
				return func() interface{} {
					var tmp19 interface{} = FieldGet(npc, "moveCounter")
					_ = tmp19 // suppress unused
					return func() interface{} {
						var tmp20 interface{} = SubInt(tmp19, int64(1))
						_ = tmp20 // suppress unused
						return npcWithCounter(npc, tmp20)
					}()
				}()
			}()
		}()
	}()
}

func updatePatrol(npc interface{}, path interface{}, width interface{}, height interface{}) interface{} {
	return func() interface{} {
		var len interface{} = pathLength(path)
		_ = len // suppress unused
		return func() interface{} {
			var tmp21 interface{} = LeInt(len, int64(0))
			_ = tmp21 // suppress unused
			return func() interface{} {
				if tmp21.(bool) {
					return npc
				}
				return func() interface{} {
					var tmp22 interface{} = FieldGet(npc, "moveCounter")
					_ = tmp22 // suppress unused
					return func() interface{} {
						var tmp23 interface{} = LeInt(tmp22, int64(0))
						_ = tmp23 // suppress unused
						return func() interface{} {
							if tmp23.(bool) {
								return func() interface{} {
									var dir interface{} = func() interface{} {
										var tmp26 interface{} = FieldGet(npc, "patrolIndex")
										_ = tmp26 // suppress unused
										return pathGet(path, tmp26)
									}()
									_ = dir // suppress unused
									return func() interface{} {
										var movedNpc interface{} = TryMoveDirection(npc, dir, width, height)
										_ = movedNpc // suppress unused
										return func() interface{} {
											var nextIndex interface{} = func() interface{} {
												var tmp24 interface{} = FieldGet(npc, "patrolIndex")
												_ = tmp24 // suppress unused
												return func() interface{} {
													var tmp25 interface{} = AddInt(tmp24, int64(1))
													_ = tmp25 // suppress unused
													return ModInt(tmp25, len)
												}()
											}()
											_ = nextIndex // suppress unused
											return RecordUpdate(movedNpc, map[string]interface{}{"patrolIndex": nextIndex, "moveCounter": int64(20)})
										}()
									}()
								}()
							}
							return func() interface{} {
								var tmp27 interface{} = FieldGet(npc, "moveCounter")
								_ = tmp27 // suppress unused
								return func() interface{} {
									var tmp28 interface{} = SubInt(tmp27, int64(1))
									_ = tmp28 // suppress unused
									return npcWithCounter(npc, tmp28)
								}()
							}()
						}()
					}()
				}()
			}()
		}()
	}()
}

func UpdateNPC(npc interface{}, width interface{}, height interface{}) interface{} {
	return func() interface{} {
		var tmp29 interface{} = FieldGet(npc, "pattern")
		_ = tmp29 // suppress unused
		return func() interface{} {
			_scrutinee := tmp29
			_ = _scrutinee // suppress unused
			_adt := _scrutinee.(*MovementPattern)
			switch _adt.Kind {
			case MovementPatternKindPatternStatic:
				return npc
			case MovementPatternKindPatternRandomWalk:
				interval := _adt.PatternRandomWalk.Value0
				_ = interval // suppress unused
				return updateRandomWalk(npc, interval, width, height)
			case MovementPatternKindPatternPatrol:
				path := _adt.PatternPatrol.Value0
				_ = path // suppress unused
				return updatePatrol(npc, path, width, height)
			default:
				panic("non-exhaustive match")
			}
		}()
	}()
}

func UpdateAllNPCs(npcs interface{}, width interface{}, height interface{}) interface{} {
	return func() interface{} {
		_scrutinee := npcs
		_ = _scrutinee // suppress unused
		if ListLen(_scrutinee) == 0 {
			return []interface{}{}
		} else if ListLen(_scrutinee) >= 1 {
			npc := ListHead(_scrutinee)
			_ = npc // suppress unused
			rest := ListTail(_scrutinee)
			_ = rest // suppress unused
			return func() interface{} {
				var tmp30 interface{} = UpdateNPC(npc, width, height)
				_ = tmp30 // suppress unused
				return func() interface{} {
					var tmp31 interface{} = UpdateAllNPCs(rest, width, height)
					_ = tmp31 // suppress unused
					return Cons(tmp30, tmp31)
				}()
			}()
		} else {
			panic("non-exhaustive match")
		}
	}()
}


func generate(n interface{}, f interface{}) interface{} {
	return func() interface{} {
		_scrutinee := n
		_ = _scrutinee // suppress unused
		switch _scrutinee {
		case int64(0):
			return []interface{}{}
		default:
			return func() interface{} {
				var tmp1 interface{} = SubInt(n, int64(1))
				_ = tmp1 // suppress unused
				return func() interface{} {
					var tmp2 interface{} = CallFunc(f, tmp1)
					_ = tmp2 // suppress unused
					return func() interface{} {
						var tmp3 interface{} = SubInt(n, int64(1))
						_ = tmp3 // suppress unused
						return func() interface{} {
							var tmp4 interface{} = generate(tmp3, f)
							_ = tmp4 // suppress unused
							return Cons(tmp2, tmp4)
						}()
					}()
				}()
			}()
		}
	}()
}

func tilesToDraw(tiles interface{}, width interface{}, idx interface{}) interface{} {
	return func() interface{} {
		_scrutinee := tiles
		_ = _scrutinee // suppress unused
		if ListLen(_scrutinee) == 0 {
			return []interface{}{}
		} else if ListLen(_scrutinee) >= 1 {
			t := ListHead(_scrutinee)
			_ = t // suppress unused
			rest := ListTail(_scrutinee)
			_ = rest // suppress unused
			return func() interface{} {
				var x interface{} = ModInt(idx, width)
				_ = x // suppress unused
				return func() interface{} {
					var y interface{} = DivInt(idx, width)
					_ = y // suppress unused
					return func() interface{} {
						var cmd interface{} = func() interface{} {
							var tmp7 interface{} = MulInt(x, int64(8))
							_ = tmp7 // suppress unused
							return func() interface{} {
								var tmp8 interface{} = IntToFloat(tmp7)
								_ = tmp8 // suppress unused
								return func() interface{} {
									var tmp9 interface{} = MulInt(y, int64(8))
									_ = tmp9 // suppress unused
									return func() interface{} {
										var tmp10 interface{} = IntToFloat(tmp9)
										_ = tmp10 // suppress unused
										return func() interface{} {
											var tmp11 interface{} = FieldGet(t, "biome")
											_ = tmp11 // suppress unused
											return NewDrawCmdRect(tmp8.(float64), tmp10.(float64), float64(float64(8)), float64(float64(8)), tmp11.(int64), int64(int64(0)))
										}()
									}()
								}()
							}()
						}()
						_ = cmd // suppress unused
						return func() interface{} {
							var tmp5 interface{} = AddInt(idx, int64(1))
							_ = tmp5 // suppress unused
							return func() interface{} {
								var tmp6 interface{} = tilesToDraw(rest, width, tmp5)
								_ = tmp6 // suppress unused
								return Cons(cmd, tmp6)
							}()
						}()
					}()
				}()
			}()
		} else {
			panic("non-exhaustive match")
		}
	}()
}

func npcsToDraw(npcs interface{}) interface{} {
	return func() interface{} {
		_scrutinee := npcs
		_ = _scrutinee // suppress unused
		if ListLen(_scrutinee) == 0 {
			return []interface{}{}
		} else if ListLen(_scrutinee) >= 1 {
			npc := ListHead(_scrutinee)
			_ = npc // suppress unused
			rest := ListTail(_scrutinee)
			_ = rest // suppress unused
			return func() interface{} {
				var cmd interface{} = func() interface{} {
					var tmp13 interface{} = FieldGet(npc, "pos")
					_ = tmp13 // suppress unused
					return func() interface{} {
						var tmp14 interface{} = FieldGet(tmp13, "x")
						_ = tmp14 // suppress unused
						return func() interface{} {
							var tmp15 interface{} = MulInt(tmp14, int64(8))
							_ = tmp15 // suppress unused
							return func() interface{} {
								var tmp16 interface{} = IntToFloat(tmp15)
								_ = tmp16 // suppress unused
								return func() interface{} {
									var tmp17 interface{} = FieldGet(npc, "pos")
									_ = tmp17 // suppress unused
									return func() interface{} {
										var tmp18 interface{} = FieldGet(tmp17, "y")
										_ = tmp18 // suppress unused
										return func() interface{} {
											var tmp19 interface{} = MulInt(tmp18, int64(8))
											_ = tmp19 // suppress unused
											return func() interface{} {
												var tmp20 interface{} = IntToFloat(tmp19)
												_ = tmp20 // suppress unused
												return func() interface{} {
													var tmp21 interface{} = FieldGet(npc, "id")
													_ = tmp21 // suppress unused
													return func() interface{} {
														var tmp22 interface{} = AddInt(int64(10), tmp21)
														_ = tmp22 // suppress unused
														return NewDrawCmdRect(tmp16.(float64), tmp20.(float64), float64(float64(8)), float64(float64(8)), tmp22.(int64), int64(int64(2)))
													}()
												}()
											}()
										}()
									}()
								}()
							}()
						}()
					}()
				}()
				_ = cmd // suppress unused
				return func() interface{} {
					var tmp12 interface{} = npcsToDraw(rest)
					_ = tmp12 // suppress unused
					return Cons(cmd, tmp12)
				}()
			}()
		} else {
			panic("non-exhaustive match")
		}
	}()
}

func selectionToDraw(sel interface{}) interface{} {
	return func() interface{} {
		_scrutinee := sel
		_ = _scrutinee // suppress unused
		_adt := _scrutinee.(*Selection)
		switch _adt.Kind {
		default:
			selectionNone := _adt
			_ = selectionNone // suppress unused
			return []interface{}{}
		case SelectionKindTile:
			x := _adt.SelectionTile.Value0
			_ = x // suppress unused
			y := _adt.SelectionTile.Value1
			_ = y // suppress unused
			return func() interface{} {
				var tmp23 interface{} = MulInt(x, int64(8))
				_ = tmp23 // suppress unused
				return func() interface{} {
					var tmp24 interface{} = IntToFloat(tmp23)
					_ = tmp24 // suppress unused
					return func() interface{} {
						var tmp25 interface{} = MulInt(y, int64(8))
						_ = tmp25 // suppress unused
						return func() interface{} {
							var tmp26 interface{} = IntToFloat(tmp25)
							_ = tmp26 // suppress unused
							return func() interface{} {
								var tmp27 interface{} = NewDrawCmdRect(tmp24.(float64), tmp26.(float64), float64(float64(8)), float64(float64(8)), int64(int64(4)), int64(int64(3)))
								_ = tmp27 // suppress unused
								return []interface{}{tmp27}
							}()
						}()
					}()
				}()
			}()
		}
	}()
}

func concatDrawCmds(a interface{}, b interface{}) interface{} {
	return func() interface{} {
		_scrutinee := a
		_ = _scrutinee // suppress unused
		if ListLen(_scrutinee) == 0 {
			return b
		} else if ListLen(_scrutinee) >= 1 {
			x := ListHead(_scrutinee)
			_ = x // suppress unused
			rest := ListTail(_scrutinee)
			_ = rest // suppress unused
			return func() interface{} {
				var tmp28 interface{} = concatDrawCmds(rest, b)
				_ = tmp28 // suppress unused
				return Cons(x, tmp28)
			}()
		} else {
			panic("non-exhaustive match")
		}
	}()
}

func processSelection(input interface{}, world interface{}) interface{} {
	return func() interface{} {
		var tmp29 interface{} = FieldGet(input, "clickedThisFrame")
		_ = tmp29 // suppress unused
		return func() interface{} {
			if tmp29.(bool) {
				return func() interface{} {
					var tileX interface{} = func() interface{} {
						var tmp43 interface{} = FieldGet(input, "worldMouseX")
						_ = tmp43 // suppress unused
						return func() interface{} {
							var tmp44 interface{} = DivInt(tmp43, float64(8))
							_ = tmp44 // suppress unused
							return FloatToInt(tmp44)
						}()
					}()
					_ = tileX // suppress unused
					return func() interface{} {
						var tileY interface{} = func() interface{} {
							var tmp41 interface{} = FieldGet(input, "worldMouseY")
							_ = tmp41 // suppress unused
							return func() interface{} {
								var tmp42 interface{} = DivInt(tmp41, float64(8))
								_ = tmp42 // suppress unused
								return FloatToInt(tmp42)
							}()
						}()
						_ = tileY // suppress unused
						return func() interface{} {
							var tmp30 interface{} = GeInt(tileX, int64(0))
							_ = tmp30 // suppress unused
							return func() interface{} {
								var tmp31 interface{} = FieldGet(world, "planet")
								_ = tmp31 // suppress unused
								return func() interface{} {
									var tmp32 interface{} = FieldGet(tmp31, "width")
									_ = tmp32 // suppress unused
									return func() interface{} {
										var tmp33 interface{} = LtInt(tileX, tmp32)
										_ = tmp33 // suppress unused
										return func() interface{} {
											var tmp34 interface{} = func() interface{} {
												if tmp30.(bool) {
													return tmp33
												}
												return false
											}()
											_ = tmp34 // suppress unused
											return func() interface{} {
												var tmp35 interface{} = GeInt(tileY, int64(0))
												_ = tmp35 // suppress unused
												return func() interface{} {
													var tmp36 interface{} = func() interface{} {
														if tmp34.(bool) {
															return tmp35
														}
														return false
													}()
													_ = tmp36 // suppress unused
													return func() interface{} {
														var tmp37 interface{} = FieldGet(world, "planet")
														_ = tmp37 // suppress unused
														return func() interface{} {
															var tmp38 interface{} = FieldGet(tmp37, "height")
															_ = tmp38 // suppress unused
															return func() interface{} {
																var tmp39 interface{} = LtInt(tileY, tmp38)
																_ = tmp39 // suppress unused
																return func() interface{} {
																	var tmp40 interface{} = func() interface{} {
																		if tmp36.(bool) {
																			return tmp39
																		}
																		return false
																	}()
																	_ = tmp40 // suppress unused
																	return func() interface{} {
																		if tmp40.(bool) {
																			return NewSelectionTile(tileX.(int64), tileY.(int64))
																		}
																		return NewSelectionNone()
																	}()
																}()
															}()
														}()
													}()
												}()
											}()
										}()
									}()
								}()
							}()
						}()
					}()
				}()
			}
			return FieldGet(world, "selection")
		}()
	}()
}

func InitWorld(seed interface{}) interface{} {
	return func() interface{} {
		var w interface{} = int64(8)
		_ = w // suppress unused
		return func() interface{} {
			var h interface{} = int64(8)
			_ = h // suppress unused
			return func() interface{} {
				var tiles interface{} = func() interface{} {
					var tmp57 interface{} = MulInt(w, h)
					_ = tmp57 // suppress unused
					return generate(tmp57, func(i interface{}) interface{} {
						return func() interface{} {
							var tmp58 interface{} = ModInt(i, int64(4))
							_ = tmp58 // suppress unused
							return &Tile{Biome: tmp58.(int64)}
						}()
					})
				}()
				_ = tiles // suppress unused
				return func() interface{} {
					var patrolPath interface{} = []interface{}{NewDirectionEast(), NewDirectionEast(), NewDirectionSouth(), NewDirectionSouth(), NewDirectionWest(), NewDirectionWest(), NewDirectionNorth(), NewDirectionNorth()}
					_ = patrolPath // suppress unused
					return func() interface{} {
						var testNpcs interface{} = func() interface{} {
							var tmp46 interface{} = &Coord{X: int64(int64(2)), Y: int64(int64(2))}
							_ = tmp46 // suppress unused
							return func() interface{} {
								var tmp47 interface{} = NewMovementPatternPatternRandomWalk(int64(int64(30)))
								_ = tmp47 // suppress unused
								return func() interface{} {
									var tmp48 interface{} = &NPC{Id: int64(int64(1)), Pos: *(tmp46.(*Coord)), Pattern: *(tmp47.(*MovementPattern)), MoveCounter: int64(int64(30)), PatrolIndex: int64(int64(0))}
									_ = tmp48 // suppress unused
									return func() interface{} {
										var tmp49 interface{} = &Coord{X: int64(int64(5)), Y: int64(int64(3))}
										_ = tmp49 // suppress unused
										return func() interface{} {
											var tmp50 interface{} = NewMovementPatternPatternRandomWalk(int64(int64(45)))
											_ = tmp50 // suppress unused
											return func() interface{} {
												var tmp51 interface{} = &NPC{Id: int64(int64(2)), Pos: *(tmp49.(*Coord)), Pattern: *(tmp50.(*MovementPattern)), MoveCounter: int64(int64(45)), PatrolIndex: int64(int64(0))}
												_ = tmp51 // suppress unused
												return func() interface{} {
													var tmp52 interface{} = &Coord{X: int64(int64(4)), Y: int64(int64(4))}
													_ = tmp52 // suppress unused
													return func() interface{} {
														var tmp53 interface{} = &NPC{Id: int64(int64(3)), Pos: *(tmp52.(*Coord)), Pattern: *NewMovementPatternPatternStatic(), MoveCounter: int64(int64(0)), PatrolIndex: int64(int64(0))}
														_ = tmp53 // suppress unused
														return func() interface{} {
															var tmp54 interface{} = &Coord{X: int64(int64(1)), Y: int64(int64(1))}
															_ = tmp54 // suppress unused
															return func() interface{} {
																var tmp55 interface{} = NewMovementPatternPatternPatrol(convertToDirectionSlice(patrolPath))
																_ = tmp55 // suppress unused
																return func() interface{} {
																	var tmp56 interface{} = &NPC{Id: int64(int64(4)), Pos: *(tmp54.(*Coord)), Pattern: *(tmp55.(*MovementPattern)), MoveCounter: int64(int64(0)), PatrolIndex: int64(int64(0))}
																	_ = tmp56 // suppress unused
																	return []interface{}{tmp48, tmp51, tmp53, tmp56}
																}()
															}()
														}()
													}()
												}()
											}()
										}()
									}()
								}()
							}()
						}()
						_ = testNpcs // suppress unused
						return func() interface{} {
							var tmp45 interface{} = &PlanetState{Width: w.(int64), Height: h.(int64), Tiles: convertToTileSlice(tiles)}
							_ = tmp45 // suppress unused
							return &World{Tick: int64(int64(0)), Planet: *(tmp45.(*PlanetState)), Npcs: convertToNPCSlice(testNpcs), Selection: *NewSelectionNone()}
						}()
					}()
				}()
			}()
		}()
	}()
}

func Step(world interface{}, input interface{}) interface{} {
	return func() interface{} {
		var block0 interface{} = func() interface{} {
			var tmp72 interface{} = FieldGet(world, "tick")
			_ = tmp72 // suppress unused
			return func() interface{} {
				var tmp73 interface{} = Show(tmp72)
				_ = tmp73 // suppress unused
				return func() interface{} {
					var tmp74 interface{} = ConcatString("tick ", tmp73)
					_ = tmp74 // suppress unused
					return Log(tmp74)
				}()
			}()
		}()
		_ = block0 // suppress unused
		return func() interface{} {
			var newSelection interface{} = processSelection(input, world)
			_ = newSelection // suppress unused
			return func() interface{} {
				var newTick interface{} = func() interface{} {
					var tmp71 interface{} = FieldGet(world, "tick")
					_ = tmp71 // suppress unused
					return AddInt(tmp71, int64(1))
				}()
				_ = newTick // suppress unused
				return func() interface{} {
					var updatedNpcs interface{} = func() interface{} {
						var tmp66 interface{} = FieldGet(world, "npcs")
						_ = tmp66 // suppress unused
						return func() interface{} {
							var tmp67 interface{} = FieldGet(world, "planet")
							_ = tmp67 // suppress unused
							return func() interface{} {
								var tmp68 interface{} = FieldGet(tmp67, "width")
								_ = tmp68 // suppress unused
								return func() interface{} {
									var tmp69 interface{} = FieldGet(world, "planet")
									_ = tmp69 // suppress unused
									return func() interface{} {
										var tmp70 interface{} = FieldGet(tmp69, "height")
										_ = tmp70 // suppress unused
										return UpdateAllNPCs(tmp66, tmp68, tmp70)
									}()
								}()
							}()
						}()
					}()
					_ = updatedNpcs // suppress unused
					return func() interface{} {
						var newWorld interface{} = RecordUpdate(world, map[string]interface{}{"tick": newTick, "npcs": updatedNpcs, "selection": newSelection})
						_ = newWorld // suppress unused
						return func() interface{} {
							var tileCmds interface{} = func() interface{} {
								var tmp62 interface{} = FieldGet(world, "planet")
								_ = tmp62 // suppress unused
								return func() interface{} {
									var tmp63 interface{} = FieldGet(tmp62, "tiles")
									_ = tmp63 // suppress unused
									return func() interface{} {
										var tmp64 interface{} = FieldGet(world, "planet")
										_ = tmp64 // suppress unused
										return func() interface{} {
											var tmp65 interface{} = FieldGet(tmp64, "width")
											_ = tmp65 // suppress unused
											return tilesToDraw(tmp63, tmp65, int64(0))
										}()
									}()
								}()
							}()
							_ = tileCmds // suppress unused
							return func() interface{} {
								var npcCmds interface{} = npcsToDraw(updatedNpcs)
								_ = npcCmds // suppress unused
								return func() interface{} {
									var selCmds interface{} = selectionToDraw(newSelection)
									_ = selCmds // suppress unused
									return func() interface{} {
										var drawCmds interface{} = func() interface{} {
											var tmp61 interface{} = concatDrawCmds(tileCmds, npcCmds)
											_ = tmp61 // suppress unused
											return concatDrawCmds(tmp61, selCmds)
										}()
										_ = drawCmds // suppress unused
										return func() interface{} {
											var cam interface{} = &Camera{X: float64(float64(0)), Y: float64(float64(0)), Zoom: float64(float64(1))}
											_ = cam // suppress unused
											return func() interface{} {
												var output interface{} = func() interface{} {
													var tmp59 interface{} = []interface{}{}
													_ = tmp59 // suppress unused
													return func() interface{} {
														var tmp60 interface{} = []interface{}{}
														_ = tmp60 // suppress unused
														return &FrameOutput{Draw: convertToDrawCmdSlice(drawCmds), Sounds: ConvertToInt64Slice(tmp59), Debug: ConvertToStringSlice(tmp60), Camera: *(cam.(*Camera))}
													}()
												}()
												_ = output // suppress unused
												return []interface{}{newWorld, output}
											}()
										}()
									}()
								}()
							}()
						}()
					}()
				}()
			}()
		}()
	}()
}
