// Code generated by ailang. DO NOT EDIT.
package sim_gen

import (
	"math"
)

func diskScaleLength_impl(_unused0 interface{}) interface{} {
	return float64(10000)
}

func diskScaleLength() float64 {
	return diskScaleLength_impl(struct{}{}).(float64)
}

func diskScaleHeight_impl(_unused0 interface{}) interface{} {
	return float64(1000)
}

func diskScaleHeight() float64 {
	return diskScaleHeight_impl(struct{}{}).(float64)
}

func sunGalacticRadius_impl(_unused0 interface{}) interface{} {
	return float64(26000)
}

func sunGalacticRadius() float64 {
	return sunGalacticRadius_impl(struct{}{}).(float64)
}

func localStellarDensity_impl(_unused0 interface{}) interface{} {
	return float64(0.004)
}

func localStellarDensity() float64 {
	return localStellarDensity_impl(struct{}{}).(float64)
}

func galactocentricRadius_impl(pos interface{}) interface{} {
	var r interface{} = func() interface{} {
		var tmp6 interface{} = sunGalacticRadius_impl(struct{}{})
		_ = tmp6 // suppress unused
		var tmp7 interface{} = FieldGet(pos, "x")
		_ = tmp7 // suppress unused
		return SubFloat(tmp6, tmp7)
	}()
	var tmp1 interface{} = MulFloat(r, r)
	var tmp2 interface{} = FieldGet(pos, "y")
	var tmp3 interface{} = FieldGet(pos, "y")
	var tmp4 interface{} = MulFloat(tmp2, tmp3)
	var tmp5 interface{} = AddFloat(tmp1, tmp4)
	return math.Sqrt(tmp5.(float64))
}

func galactocentricRadius(pos *Vec3) float64 {
	return galactocentricRadius_impl(pos).(float64)
}

func stellarDensity_impl(pos interface{}) interface{} {
	var r interface{} = galactocentricRadius_impl(pos)
	var z interface{} = FieldGet(pos, "z")
	var radialFactor interface{} = func() interface{} {
		var tmp12 interface{} = sunGalacticRadius_impl(struct{}{})
		_ = tmp12 // suppress unused
		var tmp13 interface{} = SubFloat(tmp12, r)
		_ = tmp13 // suppress unused
		var tmp14 interface{} = diskScaleLength_impl(struct{}{})
		_ = tmp14 // suppress unused
		var tmp15 interface{} = DivFloat(tmp13, tmp14)
		_ = tmp15 // suppress unused
		return math.Exp(tmp15.(float64))
	}()
	var absZ interface{} = func() interface{} {
		var tmp11 interface{} = LtFloat(z, float64(0))
		_ = tmp11 // suppress unused
		return func() interface{} {
			if tmp11.(bool) {
				return SubFloat(float64(0), z)
			} else {
				return z
			}
		}()
	}()
	var verticalFactor interface{} = func() interface{} {
		var tmp8 interface{} = diskScaleHeight_impl(struct{}{})
		_ = tmp8 // suppress unused
		var tmp9 interface{} = DivFloat(absZ, tmp8)
		_ = tmp9 // suppress unused
		var tmp10 interface{} = SubFloat(float64(0), tmp9)
		_ = tmp10 // suppress unused
		return math.Exp(tmp10.(float64))
	}()
	return MulFloat(radialFactor, verticalFactor)
}

func StellarDensity(pos *Vec3) float64 {
	return stellarDensity_impl(pos).(float64)
}

func positionHash_impl(x interface{}, y interface{}, z interface{}, seed interface{}) interface{} {
	var h1 interface{} = MulInt(x, int64(374761393))
	var h2 interface{} = MulInt(y, int64(668265263))
	var h3 interface{} = MulInt(z, int64(1274126177))
	var h4 interface{} = MulInt(seed, int64(1911520717))
	var combined interface{} = func() interface{} {
		var tmp17 interface{} = AddInt(h1, h2)
		_ = tmp17 // suppress unused
		var tmp18 interface{} = AddInt(tmp17, h3)
		_ = tmp18 // suppress unused
		return AddInt(tmp18, h4)
	}()
	var mixed interface{} = MulInt(combined, int64(2654435769))
	var tmp16 interface{} = LtInt(mixed, int64(0))
	return func() interface{} {
		if tmp16.(bool) {
			return SubInt(int64(0), mixed)
		} else {
			return mixed
		}
	}()
}

func positionHash(x int64, y int64, z int64, seed int64) int64 {
	return positionHash_impl(x, y, z, seed).(int64)
}

func hashToFloat_impl(hash interface{}) interface{} {
	var maxInt interface{} = int64(2147483647)
	var tmp19 interface{} = ModInt(hash, maxInt)
	var tmp20 interface{} = IntToFloat(tmp19)
	var tmp21 interface{} = IntToFloat(maxInt)
	return DivFloat(tmp20, tmp21)
}

func hashToFloat(hash int64) float64 {
	return hashToFloat_impl(hash).(float64)
}

func intToStringPositive_impl(n interface{}) interface{} {
	if EqInt(n, int64(0)).(bool) {
		return ""
	} else {
		return func() interface{} {
			var digit interface{} = ModInt(n, int64(10))
			_ = digit // suppress unused
			var rest interface{} = DivInt(n, int64(10))
			_ = rest // suppress unused
			var digitChar interface{} = func() interface{} {
				_scrutinee := digit
				_ = _scrutinee // suppress unused
				switch _scrutinee {
				case int64(0):
					return "0"
				case int64(1):
					return "1"
				case int64(2):
					return "2"
				case int64(3):
					return "3"
				case int64(4):
					return "4"
				case int64(5):
					return "5"
				case int64(6):
					return "6"
				case int64(7):
					return "7"
				case int64(8):
					return "8"
				default:
					return "9"
				}
			}()
			_ = digitChar // suppress unused
			var tmp23 interface{} = intToStringPositive_impl(rest)
			_ = tmp23 // suppress unused
			return ConcatString(tmp23, digitChar)
		}()
	}
}

func intToStringPositive(n int64) string {
	return intToStringPositive_impl(n).(string)
}

func intToString_impl(n interface{}) interface{} {
	if LtInt(n, int64(0)).(bool) {
		return func() interface{} {
			var tmp25 interface{} = SubInt(int64(0), n)
			_ = tmp25 // suppress unused
			var tmp26 interface{} = intToStringPositive_impl(tmp25)
			_ = tmp26 // suppress unused
			return ConcatString("-", tmp26)
		}()
	} else if EqInt(n, int64(0)).(bool) {
		return "0"
	} else {
		return intToStringPositive_impl(n)
	}
}

func intToString(n int64) string {
	return intToString_impl(n).(string)
}

func generateStar_impl(seed interface{}, cellX interface{}, cellY interface{}, cellZ interface{}, cellSize interface{}) interface{} {
	var hash interface{} = positionHash_impl(cellX, cellY, cellZ, seed)
	var jitterX interface{} = func() interface{} {
		var tmp43 interface{} = AddInt(seed, int64(1))
		_ = tmp43 // suppress unused
		var tmp44 interface{} = positionHash_impl(cellX, cellY, cellZ, tmp43)
		_ = tmp44 // suppress unused
		return hashToFloat_impl(tmp44)
	}()
	var jitterY interface{} = func() interface{} {
		var tmp41 interface{} = AddInt(seed, int64(2))
		_ = tmp41 // suppress unused
		var tmp42 interface{} = positionHash_impl(cellX, cellY, cellZ, tmp41)
		_ = tmp42 // suppress unused
		return hashToFloat_impl(tmp42)
	}()
	var jitterZ interface{} = func() interface{} {
		var tmp39 interface{} = AddInt(seed, int64(3))
		_ = tmp39 // suppress unused
		var tmp40 interface{} = positionHash_impl(cellX, cellY, cellZ, tmp39)
		_ = tmp40 // suppress unused
		return hashToFloat_impl(tmp40)
	}()
	var x interface{} = func() interface{} {
		var tmp37 interface{} = IntToFloat(cellX)
		_ = tmp37 // suppress unused
		var tmp38 interface{} = AddFloat(tmp37, jitterX)
		_ = tmp38 // suppress unused
		return MulFloat(tmp38, cellSize)
	}()
	var y interface{} = func() interface{} {
		var tmp35 interface{} = IntToFloat(cellY)
		_ = tmp35 // suppress unused
		var tmp36 interface{} = AddFloat(tmp35, jitterY)
		_ = tmp36 // suppress unused
		return MulFloat(tmp36, cellSize)
	}()
	var z interface{} = func() interface{} {
		var tmp33 interface{} = IntToFloat(cellZ)
		_ = tmp33 // suppress unused
		var tmp34 interface{} = AddFloat(tmp33, jitterZ)
		_ = tmp34 // suppress unused
		return MulFloat(tmp34, cellSize)
	}()
	var spectralRoll interface{} = func() interface{} {
		var tmp31 interface{} = AddInt(cellX, int64(100))
		_ = tmp31 // suppress unused
		var tmp32 interface{} = positionHash_impl(tmp31, cellY, cellZ, seed)
		_ = tmp32 // suppress unused
		return hashToFloat_impl(tmp32)
	}()
	var spectral interface{} = spectralFromRoll_impl(spectralRoll)
	var hzRoll interface{} = func() interface{} {
		var tmp29 interface{} = AddInt(cellY, int64(100))
		_ = tmp29 // suppress unused
		var tmp30 interface{} = positionHash_impl(cellX, tmp29, cellZ, seed)
		_ = tmp30 // suppress unused
		return hashToFloat_impl(tmp30)
	}()
	var hasHZ interface{} = func() interface{} {
		_scrutinee := spectral
		_ = _scrutinee // suppress unused
		switch _scrutinee {
		default:
			return LtFloat(hzRoll, float64(0.22))
		}
	}()
	var starId interface{} = ModInt(hash, int64(1000000000))
	var name interface{} = func() interface{} {
		var tmp28 interface{} = intToString_impl(starId)
		_ = tmp28 // suppress unused
		return ConcatString("PStar-", tmp28)
	}()
	return makeStar_impl(starId, name, x, y, z, spectral, hasHZ)
}

func GenerateStar(seed int64, cellX int64, cellY int64, cellZ int64, cellSize float64) *Star {
	return generateStar_impl(seed, cellX, cellY, cellZ, cellSize).(*Star)
}

func blendWeight_impl(distanceFromSol interface{}) interface{} {
	var innerRadius interface{} = float64(20)
	var outerRadius interface{} = float64(100)
	var tmp45 interface{} = LtFloat(distanceFromSol, innerRadius)
	return func() interface{} {
		_scrutinee := tmp45
		_ = _scrutinee // suppress unused
		switch _scrutinee {
		case true:
			return float64(0)
		case false:
			return func() interface{} {
				if GtFloat(distanceFromSol, outerRadius).(bool) {
					return float64(1)
				} else {
					return func() interface{} {
						var tmp47 interface{} = SubFloat(distanceFromSol, innerRadius)
						_ = tmp47 // suppress unused
						var tmp48 interface{} = SubFloat(outerRadius, innerRadius)
						_ = tmp48 // suppress unused
						return DivFloat(tmp47, tmp48)
					}()
				}
			}()
		default:
			panic("non-exhaustive match")
		}
	}()
}

func BlendWeight(distanceFromSol float64) float64 {
	return blendWeight_impl(distanceFromSol).(float64)
}

func shouldGenerateStar_impl(seed interface{}, cellX interface{}, cellY interface{}, cellZ interface{}, cellSize interface{}) interface{} {
	var x interface{} = func() interface{} {
		var tmp60 interface{} = IntToFloat(cellX)
		_ = tmp60 // suppress unused
		var tmp61 interface{} = MulFloat(tmp60, cellSize)
		_ = tmp61 // suppress unused
		var tmp62 interface{} = DivFloat(cellSize, float64(2))
		_ = tmp62 // suppress unused
		return AddFloat(tmp61, tmp62)
	}()
	var y interface{} = func() interface{} {
		var tmp57 interface{} = IntToFloat(cellY)
		_ = tmp57 // suppress unused
		var tmp58 interface{} = MulFloat(tmp57, cellSize)
		_ = tmp58 // suppress unused
		var tmp59 interface{} = DivFloat(cellSize, float64(2))
		_ = tmp59 // suppress unused
		return AddFloat(tmp58, tmp59)
	}()
	var z interface{} = func() interface{} {
		var tmp54 interface{} = IntToFloat(cellZ)
		_ = tmp54 // suppress unused
		var tmp55 interface{} = MulFloat(tmp54, cellSize)
		_ = tmp55 // suppress unused
		var tmp56 interface{} = DivFloat(cellSize, float64(2))
		_ = tmp56 // suppress unused
		return AddFloat(tmp55, tmp56)
	}()
	var pos interface{} = makeVec3_impl(x, y, z)
	var density interface{} = stellarDensity_impl(pos)
	var cellVolume interface{} = func() interface{} {
		var tmp53 interface{} = MulFloat(cellSize, cellSize)
		_ = tmp53 // suppress unused
		return MulFloat(tmp53, cellSize)
	}()
	var expectedStars interface{} = func() interface{} {
		var tmp51 interface{} = localStellarDensity_impl(struct{}{})
		_ = tmp51 // suppress unused
		var tmp52 interface{} = MulFloat(density, tmp51)
		_ = tmp52 // suppress unused
		return MulFloat(tmp52, cellVolume)
	}()
	var roll interface{} = func() interface{} {
		var tmp49 interface{} = AddInt(seed, int64(999))
		_ = tmp49 // suppress unused
		var tmp50 interface{} = positionHash_impl(cellX, cellY, cellZ, tmp49)
		_ = tmp50 // suppress unused
		return hashToFloat_impl(tmp50)
	}()
	return LtFloat(roll, expectedStars)
}

func ShouldGenerateStar(seed int64, cellX int64, cellY int64, cellZ int64, cellSize float64) bool {
	return shouldGenerateStar_impl(seed, cellX, cellY, cellZ, cellSize).(bool)
}
