// Code generated by ailang. DO NOT EDIT.
package sim_gen

func kEYA_impl(_unused0 interface{}) interface{} {
	return int64(0)
}

func KEYA() int64 {
	return kEYA_impl(struct{}{}).(int64)
}

func kEYB_impl(_unused0 interface{}) interface{} {
	return int64(1)
}

func KEYB() int64 {
	return kEYB_impl(struct{}{}).(int64)
}

func kEYC_impl(_unused0 interface{}) interface{} {
	return int64(2)
}

func KEYC() int64 {
	return kEYC_impl(struct{}{}).(int64)
}

func kEYD_impl(_unused0 interface{}) interface{} {
	return int64(3)
}

func KEYD() int64 {
	return kEYD_impl(struct{}{}).(int64)
}

func kEYE_impl(_unused0 interface{}) interface{} {
	return int64(4)
}

func KEYE() int64 {
	return kEYE_impl(struct{}{}).(int64)
}

func kEYF_impl(_unused0 interface{}) interface{} {
	return int64(5)
}

func KEYF() int64 {
	return kEYF_impl(struct{}{}).(int64)
}

func kEYG_impl(_unused0 interface{}) interface{} {
	return int64(6)
}

func KEYG() int64 {
	return kEYG_impl(struct{}{}).(int64)
}

func kEYH_impl(_unused0 interface{}) interface{} {
	return int64(7)
}

func KEYH() int64 {
	return kEYH_impl(struct{}{}).(int64)
}

func kEYI_impl(_unused0 interface{}) interface{} {
	return int64(8)
}

func KEYI() int64 {
	return kEYI_impl(struct{}{}).(int64)
}

func kEYJ_impl(_unused0 interface{}) interface{} {
	return int64(9)
}

func KEYJ() int64 {
	return kEYJ_impl(struct{}{}).(int64)
}

func kEYK_impl(_unused0 interface{}) interface{} {
	return int64(10)
}

func KEYK() int64 {
	return kEYK_impl(struct{}{}).(int64)
}

func kEYL_impl(_unused0 interface{}) interface{} {
	return int64(11)
}

func KEYL() int64 {
	return kEYL_impl(struct{}{}).(int64)
}

func kEYM_impl(_unused0 interface{}) interface{} {
	return int64(12)
}

func KEYM() int64 {
	return kEYM_impl(struct{}{}).(int64)
}

func kEYN_impl(_unused0 interface{}) interface{} {
	return int64(13)
}

func KEYN() int64 {
	return kEYN_impl(struct{}{}).(int64)
}

func kEYO_impl(_unused0 interface{}) interface{} {
	return int64(14)
}

func KEYO() int64 {
	return kEYO_impl(struct{}{}).(int64)
}

func kEYP_impl(_unused0 interface{}) interface{} {
	return int64(15)
}

func KEYP() int64 {
	return kEYP_impl(struct{}{}).(int64)
}

func kEYQ_impl(_unused0 interface{}) interface{} {
	return int64(16)
}

func KEYQ() int64 {
	return kEYQ_impl(struct{}{}).(int64)
}

func kEYR_impl(_unused0 interface{}) interface{} {
	return int64(17)
}

func KEYR() int64 {
	return kEYR_impl(struct{}{}).(int64)
}

func kEYS_impl(_unused0 interface{}) interface{} {
	return int64(18)
}

func KEYS() int64 {
	return kEYS_impl(struct{}{}).(int64)
}

func kEYT_impl(_unused0 interface{}) interface{} {
	return int64(19)
}

func KEYT() int64 {
	return kEYT_impl(struct{}{}).(int64)
}

func kEYU_impl(_unused0 interface{}) interface{} {
	return int64(20)
}

func KEYU() int64 {
	return kEYU_impl(struct{}{}).(int64)
}

func kEYV_impl(_unused0 interface{}) interface{} {
	return int64(21)
}

func KEYV() int64 {
	return kEYV_impl(struct{}{}).(int64)
}

func kEYW_impl(_unused0 interface{}) interface{} {
	return int64(22)
}

func KEYW() int64 {
	return kEYW_impl(struct{}{}).(int64)
}

func kEYX_impl(_unused0 interface{}) interface{} {
	return int64(23)
}

func KEYX() int64 {
	return kEYX_impl(struct{}{}).(int64)
}

func kEYY_impl(_unused0 interface{}) interface{} {
	return int64(24)
}

func KEYY() int64 {
	return kEYY_impl(struct{}{}).(int64)
}

func kEYZ_impl(_unused0 interface{}) interface{} {
	return int64(25)
}

func KEYZ() int64 {
	return kEYZ_impl(struct{}{}).(int64)
}

func kEYDOWN_impl(_unused0 interface{}) interface{} {
	return int64(28)
}

func KEYDOWN() int64 {
	return kEYDOWN_impl(struct{}{}).(int64)
}

func kEYLEFT_impl(_unused0 interface{}) interface{} {
	return int64(29)
}

func KEYLEFT() int64 {
	return kEYLEFT_impl(struct{}{}).(int64)
}

func kEYRIGHT_impl(_unused0 interface{}) interface{} {
	return int64(30)
}

func KEYRIGHT() int64 {
	return kEYRIGHT_impl(struct{}{}).(int64)
}

func kEYUP_impl(_unused0 interface{}) interface{} {
	return int64(31)
}

func KEYUP() int64 {
	return kEYUP_impl(struct{}{}).(int64)
}

func kEY0_impl(_unused0 interface{}) interface{} {
	return int64(43)
}

func KEY0() int64 {
	return kEY0_impl(struct{}{}).(int64)
}

func kEY1_impl(_unused0 interface{}) interface{} {
	return int64(44)
}

func KEY1() int64 {
	return kEY1_impl(struct{}{}).(int64)
}

func kEY2_impl(_unused0 interface{}) interface{} {
	return int64(45)
}

func KEY2() int64 {
	return kEY2_impl(struct{}{}).(int64)
}

func kEY3_impl(_unused0 interface{}) interface{} {
	return int64(46)
}

func KEY3() int64 {
	return kEY3_impl(struct{}{}).(int64)
}

func kEY4_impl(_unused0 interface{}) interface{} {
	return int64(47)
}

func KEY4() int64 {
	return kEY4_impl(struct{}{}).(int64)
}

func kEY5_impl(_unused0 interface{}) interface{} {
	return int64(48)
}

func KEY5() int64 {
	return kEY5_impl(struct{}{}).(int64)
}

func kEY6_impl(_unused0 interface{}) interface{} {
	return int64(49)
}

func KEY6() int64 {
	return kEY6_impl(struct{}{}).(int64)
}

func kEY7_impl(_unused0 interface{}) interface{} {
	return int64(50)
}

func KEY7() int64 {
	return kEY7_impl(struct{}{}).(int64)
}

func kEY8_impl(_unused0 interface{}) interface{} {
	return int64(51)
}

func KEY8() int64 {
	return kEY8_impl(struct{}{}).(int64)
}

func kEY9_impl(_unused0 interface{}) interface{} {
	return int64(52)
}

func KEY9() int64 {
	return kEY9_impl(struct{}{}).(int64)
}

func kEYENTER_impl(_unused0 interface{}) interface{} {
	return int64(54)
}

func KEYENTER() int64 {
	return kEYENTER_impl(struct{}{}).(int64)
}

func kEYESCAPE_impl(_unused0 interface{}) interface{} {
	return int64(56)
}

func KEYESCAPE() int64 {
	return kEYESCAPE_impl(struct{}{}).(int64)
}

func kEYF1_impl(_unused0 interface{}) interface{} {
	return int64(57)
}

func KEYF1() int64 {
	return kEYF1_impl(struct{}{}).(int64)
}

func kEYF2_impl(_unused0 interface{}) interface{} {
	return int64(58)
}

func KEYF2() int64 {
	return kEYF2_impl(struct{}{}).(int64)
}

func kEYF3_impl(_unused0 interface{}) interface{} {
	return int64(59)
}

func KEYF3() int64 {
	return kEYF3_impl(struct{}{}).(int64)
}

func kEYF4_impl(_unused0 interface{}) interface{} {
	return int64(60)
}

func KEYF4() int64 {
	return kEYF4_impl(struct{}{}).(int64)
}

func kEYF5_impl(_unused0 interface{}) interface{} {
	return int64(61)
}

func KEYF5() int64 {
	return kEYF5_impl(struct{}{}).(int64)
}

func kEYF6_impl(_unused0 interface{}) interface{} {
	return int64(62)
}

func KEYF6() int64 {
	return kEYF6_impl(struct{}{}).(int64)
}

func kEYF7_impl(_unused0 interface{}) interface{} {
	return int64(63)
}

func KEYF7() int64 {
	return kEYF7_impl(struct{}{}).(int64)
}

func kEYF8_impl(_unused0 interface{}) interface{} {
	return int64(64)
}

func KEYF8() int64 {
	return kEYF8_impl(struct{}{}).(int64)
}

func kEYF9_impl(_unused0 interface{}) interface{} {
	return int64(65)
}

func KEYF9() int64 {
	return kEYF9_impl(struct{}{}).(int64)
}

func kEYF10_impl(_unused0 interface{}) interface{} {
	return int64(66)
}

func KEYF10() int64 {
	return kEYF10_impl(struct{}{}).(int64)
}

func kEYF11_impl(_unused0 interface{}) interface{} {
	return int64(67)
}

func KEYF11() int64 {
	return kEYF11_impl(struct{}{}).(int64)
}

func kEYF12_impl(_unused0 interface{}) interface{} {
	return int64(68)
}

func KEYF12() int64 {
	return kEYF12_impl(struct{}{}).(int64)
}

func kEYSPACE_impl(_unused0 interface{}) interface{} {
	return int64(116)
}

func KEYSPACE() int64 {
	return kEYSPACE_impl(struct{}{}).(int64)
}

func kEYTAB_impl(_unused0 interface{}) interface{} {
	return int64(117)
}

func KEYTAB() int64 {
	return kEYTAB_impl(struct{}{}).(int64)
}

func kEYSHIFT_impl(_unused0 interface{}) interface{} {
	return int64(120)
}

func KEYSHIFT() int64 {
	return kEYSHIFT_impl(struct{}{}).(int64)
}

func kEYCTRL_impl(_unused0 interface{}) interface{} {
	return int64(121)
}

func KEYCTRL() int64 {
	return kEYCTRL_impl(struct{}{}).(int64)
}

func kEYALT_impl(_unused0 interface{}) interface{} {
	return int64(122)
}

func KEYALT() int64 {
	return kEYALT_impl(struct{}{}).(int64)
}

func kEYBRACKETLEFT_impl(_unused0 interface{}) interface{} {
	return int64(36)
}

func KEYBRACKETLEFT() int64 {
	return kEYBRACKETLEFT_impl(struct{}{}).(int64)
}

func kEYBRACKETRIGHT_impl(_unused0 interface{}) interface{} {
	return int64(37)
}

func KEYBRACKETRIGHT() int64 {
	return kEYBRACKETRIGHT_impl(struct{}{}).(int64)
}

func input__hasKeyEvent_impl(keys interface{}, keyCode interface{}, eventKind interface{}) interface{} {
	return func() interface{} {
		_scrutinee := keys
		_ = _scrutinee // suppress unused
		if ListLen(_scrutinee) == 0 {
			return false
		} else if ListLen(_scrutinee) >= 1 {
			k := ListHead(_scrutinee)
			_ = k // suppress unused
			rest := ListTail(_scrutinee)
			_ = rest // suppress unused
			return func() interface{} {
				var tmp1 interface{} = FieldGet(k, "key")
				_ = tmp1 // suppress unused
				var tmp2 interface{} = dict_Eq_Int.Eq(tmp1, keyCode)
				_ = tmp2 // suppress unused
				var tmp3 interface{} = FieldGet(k, "kind")
				_ = tmp3 // suppress unused
				var tmp4 interface{} = dict_Eq_String.Eq(tmp3, eventKind)
				_ = tmp4 // suppress unused
				var tmp5 interface{} = func() interface{} {
					if tmp2.(bool) {
						return tmp4
					}
					return false
				}()
				_ = tmp5 // suppress unused
				return func() interface{} {
					if tmp5.(bool) {
						return true
					}
					return input__hasKeyEvent_impl(rest, keyCode, eventKind)
				}()
			}()
		} else {
			panic("non-exhaustive match")
		}
	}()
}

func input__hasKeyEvent(keys []KeyEvent, keyCode int64, eventKind string) bool {
	return input__hasKeyEvent_impl(keys, keyCode, eventKind).(bool)
}

func isKeyJustPressed_impl(keys interface{}, keyCode interface{}) interface{} {
	return input__hasKeyEvent_impl(keys, keyCode, "press")
}

func IsKeyJustPressed(keys []KeyEvent, keyCode int64) bool {
	return isKeyJustPressed_impl(keys, keyCode).(bool)
}

func isKeyHeld_impl(keys interface{}, keyCode interface{}) interface{} {
	return input__hasKeyEvent_impl(keys, keyCode, "down")
}

func IsKeyHeld(keys []KeyEvent, keyCode int64) bool {
	return isKeyHeld_impl(keys, keyCode).(bool)
}

func isKeyJustReleased_impl(keys interface{}, keyCode interface{}) interface{} {
	return input__hasKeyEvent_impl(keys, keyCode, "up")
}

func IsKeyJustReleased(keys []KeyEvent, keyCode int64) bool {
	return isKeyJustReleased_impl(keys, keyCode).(bool)
}

func input__anyKeyPressedHelper_impl(keys interface{}, keyCodes interface{}) interface{} {
	return func() interface{} {
		_scrutinee := keyCodes
		_ = _scrutinee // suppress unused
		if ListLen(_scrutinee) == 0 {
			return false
		} else if ListLen(_scrutinee) >= 1 {
			code := ListHead(_scrutinee)
			_ = code // suppress unused
			rest := ListTail(_scrutinee)
			_ = rest // suppress unused
			return func() interface{} {
				var tmp6 interface{} = isKeyJustPressed_impl(keys, code)
				_ = tmp6 // suppress unused
				return func() interface{} {
					if tmp6.(bool) {
						return true
					}
					return input__anyKeyPressedHelper_impl(keys, rest)
				}()
			}()
		} else {
			panic("non-exhaustive match")
		}
	}()
}

func input__anyKeyPressedHelper(keys []KeyEvent, keyCodes []int64) bool {
	return input__anyKeyPressedHelper_impl(keys, keyCodes).(bool)
}

func anyKeyJustPressed_impl(keys interface{}, keyCodes interface{}) interface{} {
	return input__anyKeyPressedHelper_impl(keys, keyCodes)
}

func AnyKeyJustPressed(keys []KeyEvent, keyCodes []int64) bool {
	return anyKeyJustPressed_impl(keys, keyCodes).(bool)
}

func input__anyKeyHeldHelper_impl(keys interface{}, keyCodes interface{}) interface{} {
	return func() interface{} {
		_scrutinee := keyCodes
		_ = _scrutinee // suppress unused
		if ListLen(_scrutinee) == 0 {
			return false
		} else if ListLen(_scrutinee) >= 1 {
			code := ListHead(_scrutinee)
			_ = code // suppress unused
			rest := ListTail(_scrutinee)
			_ = rest // suppress unused
			return func() interface{} {
				var tmp7 interface{} = isKeyHeld_impl(keys, code)
				_ = tmp7 // suppress unused
				return func() interface{} {
					if tmp7.(bool) {
						return true
					}
					return input__anyKeyHeldHelper_impl(keys, rest)
				}()
			}()
		} else {
			panic("non-exhaustive match")
		}
	}()
}

func input__anyKeyHeldHelper(keys []KeyEvent, keyCodes []int64) bool {
	return input__anyKeyHeldHelper_impl(keys, keyCodes).(bool)
}

func anyKeyHeld_impl(keys interface{}, keyCodes interface{}) interface{} {
	return input__anyKeyHeldHelper_impl(keys, keyCodes)
}

func AnyKeyHeld(keys []KeyEvent, keyCodes []int64) bool {
	return anyKeyHeld_impl(keys, keyCodes).(bool)
}

func mOUSELEFT_impl(_unused0 interface{}) interface{} {
	return int64(0)
}

func MOUSELEFT() int64 {
	return mOUSELEFT_impl(struct{}{}).(int64)
}

func mOUSERIGHT_impl(_unused0 interface{}) interface{} {
	return int64(1)
}

func MOUSERIGHT() int64 {
	return mOUSERIGHT_impl(struct{}{}).(int64)
}

func mOUSEMIDDLE_impl(_unused0 interface{}) interface{} {
	return int64(2)
}

func MOUSEMIDDLE() int64 {
	return mOUSEMIDDLE_impl(struct{}{}).(int64)
}

func input__hasMouseEvent_impl(events interface{}, buttonCode interface{}, eventKind interface{}) interface{} {
	return func() interface{} {
		_scrutinee := events
		_ = _scrutinee // suppress unused
		if ListLen(_scrutinee) == 0 {
			return false
		} else if ListLen(_scrutinee) >= 1 {
			e := ListHead(_scrutinee)
			_ = e // suppress unused
			rest := ListTail(_scrutinee)
			_ = rest // suppress unused
			return func() interface{} {
				var tmp8 interface{} = FieldGet(e, "button")
				_ = tmp8 // suppress unused
				var tmp9 interface{} = dict_Eq_Int.Eq(tmp8, buttonCode)
				_ = tmp9 // suppress unused
				var tmp10 interface{} = FieldGet(e, "kind")
				_ = tmp10 // suppress unused
				var tmp11 interface{} = dict_Eq_String.Eq(tmp10, eventKind)
				_ = tmp11 // suppress unused
				var tmp12 interface{} = func() interface{} {
					if tmp9.(bool) {
						return tmp11
					}
					return false
				}()
				_ = tmp12 // suppress unused
				return func() interface{} {
					if tmp12.(bool) {
						return true
					}
					return input__hasMouseEvent_impl(rest, buttonCode, eventKind)
				}()
			}()
		} else {
			panic("non-exhaustive match")
		}
	}()
}

func input__hasMouseEvent(events []MouseEvent, buttonCode int64, eventKind string) bool {
	return input__hasMouseEvent_impl(events, buttonCode, eventKind).(bool)
}

func isMouseJustPressed_impl(events interface{}, buttonCode interface{}) interface{} {
	return input__hasMouseEvent_impl(events, buttonCode, "press")
}

func IsMouseJustPressed(events []MouseEvent, buttonCode int64) bool {
	return isMouseJustPressed_impl(events, buttonCode).(bool)
}

func isMouseHeld_impl(events interface{}, buttonCode interface{}) interface{} {
	return input__hasMouseEvent_impl(events, buttonCode, "down")
}

func IsMouseHeld(events []MouseEvent, buttonCode int64) bool {
	return isMouseHeld_impl(events, buttonCode).(bool)
}

func isMouseJustReleased_impl(events interface{}, buttonCode interface{}) interface{} {
	return input__hasMouseEvent_impl(events, buttonCode, "up")
}

func IsMouseJustReleased(events []MouseEvent, buttonCode int64) bool {
	return isMouseJustReleased_impl(events, buttonCode).(bool)
}

func isLeftClick_impl(events interface{}) interface{} {
	var tmp13 interface{} = mOUSELEFT_impl(struct{}{})
	return isMouseJustPressed_impl(events, tmp13)
}

func IsLeftClick(events []MouseEvent) bool {
	return isLeftClick_impl(events).(bool)
}

func isRightClick_impl(events interface{}) interface{} {
	var tmp14 interface{} = mOUSERIGHT_impl(struct{}{})
	return isMouseJustPressed_impl(events, tmp14)
}

func IsRightClick(events []MouseEvent) bool {
	return isRightClick_impl(events).(bool)
}
