// Code generated by ailang. DO NOT EDIT.
package sim_gen

func demoSpriteWater_impl(_unused0 interface{}) interface{} {
	return int64(1)
}

func demoSpriteWater() int64 {
	return demoSpriteWater_impl(struct{}{}).(int64)
}

func demoSpriteForest_impl(_unused0 interface{}) interface{} {
	return int64(2)
}

func demoSpriteForest() int64 {
	return demoSpriteForest_impl(struct{}{}).(int64)
}

func demoSpriteDesert_impl(_unused0 interface{}) interface{} {
	return int64(3)
}

func demoSpriteDesert() int64 {
	return demoSpriteDesert_impl(struct{}{}).(int64)
}

func demoSpriteMountain_impl(_unused0 interface{}) interface{} {
	return int64(4)
}

func demoSpriteMountain() int64 {
	return demoSpriteMountain_impl(struct{}{}).(int64)
}

func demoSpritePlayer_impl(_unused0 interface{}) interface{} {
	return int64(105)
}

func demoSpritePlayer() int64 {
	return demoSpritePlayer_impl(struct{}{}).(int64)
}

func demoSpriteNpcRed_impl(_unused0 interface{}) interface{} {
	return int64(100)
}

func demoSpriteNpcRed() int64 {
	return demoSpriteNpcRed_impl(struct{}{}).(int64)
}

func demoSpriteNpcGreen_impl(_unused0 interface{}) interface{} {
	return int64(101)
}

func demoSpriteNpcGreen() int64 {
	return demoSpriteNpcGreen_impl(struct{}{}).(int64)
}

func demoSpriteNpcBlue_impl(_unused0 interface{}) interface{} {
	return int64(102)
}

func demoSpriteNpcBlue() int64 {
	return demoSpriteNpcBlue_impl(struct{}{}).(int64)
}

func demoSpriteNpcYellow_impl(_unused0 interface{}) interface{} {
	return int64(103)
}

func demoSpriteNpcYellow() int64 {
	return demoSpriteNpcYellow_impl(struct{}{}).(int64)
}

func demoSpriteNpcPurple_impl(_unused0 interface{}) interface{} {
	return int64(104)
}

func demoSpriteNpcPurple() int64 {
	return demoSpriteNpcPurple_impl(struct{}{}).(int64)
}

func demoLayerFloor_impl(_unused0 interface{}) interface{} {
	return int64(0)
}

func demoLayerFloor() int64 {
	return demoLayerFloor_impl(struct{}{}).(int64)
}

func demoLayerPlayer_impl(_unused0 interface{}) interface{} {
	return int64(1)
}

func demoLayerPlayer() int64 {
	return demoLayerPlayer_impl(struct{}{}).(int64)
}

func demoParallaxFar_impl(_unused0 interface{}) interface{} {
	return int64(6)
}

func demoParallaxFar() int64 {
	return demoParallaxFar_impl(struct{}{}).(int64)
}

func demoParallaxMid_impl(_unused0 interface{}) interface{} {
	return int64(8)
}

func demoParallaxMid() int64 {
	return demoParallaxMid_impl(struct{}{}).(int64)
}

func demoParallaxNear_impl(_unused0 interface{}) interface{} {
	return int64(10)
}

func demoParallaxNear() int64 {
	return demoParallaxNear_impl(struct{}{}).(int64)
}

func demoParallaxMain_impl(_unused0 interface{}) interface{} {
	return int64(16)
}

func demoParallaxMain() int64 {
	return demoParallaxMain_impl(struct{}{}).(int64)
}

func demoKeyW_impl(_unused0 interface{}) interface{} {
	return int64(22)
}

func demoKeyW() int64 {
	return demoKeyW_impl(struct{}{}).(int64)
}

func demoKeyA_impl(_unused0 interface{}) interface{} {
	return int64(0)
}

func demoKeyA() int64 {
	return demoKeyA_impl(struct{}{}).(int64)
}

func demoKeyS_impl(_unused0 interface{}) interface{} {
	return int64(18)
}

func demoKeyS() int64 {
	return demoKeyS_impl(struct{}{}).(int64)
}

func demoKeyD_impl(_unused0 interface{}) interface{} {
	return int64(3)
}

func demoKeyD() int64 {
	return demoKeyD_impl(struct{}{}).(int64)
}

func demoKeyUp_impl(_unused0 interface{}) interface{} {
	return int64(31)
}

func demoKeyUp() int64 {
	return demoKeyUp_impl(struct{}{}).(int64)
}

func demoKeyDown_impl(_unused0 interface{}) interface{} {
	return int64(28)
}

func demoKeyDown() int64 {
	return demoKeyDown_impl(struct{}{}).(int64)
}

func demoKeyLeft_impl(_unused0 interface{}) interface{} {
	return int64(29)
}

func demoKeyLeft() int64 {
	return demoKeyLeft_impl(struct{}{}).(int64)
}

func demoKeyRight_impl(_unused0 interface{}) interface{} {
	return int64(30)
}

func demoKeyRight() int64 {
	return demoKeyRight_impl(struct{}{}).(int64)
}

func demoTileW_impl(_unused0 interface{}) interface{} {
	return float64(64)
}

func demoTileW() float64 {
	return demoTileW_impl(struct{}{}).(float64)
}

func demoTileH_impl(_unused0 interface{}) interface{} {
	return float64(32)
}

func demoTileH() float64 {
	return demoTileH_impl(struct{}{}).(float64)
}

func demoIsoMoveUp_impl(_unused0 interface{}) interface{} {
	var tmp1 interface{} = SubInt(int64(0), int64(1))
	var tmp2 interface{} = SubInt(int64(0), int64(1))
	return &IsoMove{Dx: tmp1.(int64), Dy: tmp2.(int64)}
}

func demoIsoMoveUp() *IsoMove {
	return demoIsoMoveUp_impl(struct{}{}).(*IsoMove)
}

func demoIsoMoveDown_impl(_unused0 interface{}) interface{} {
	return &IsoMove{Dx: int64(1), Dy: int64(1)}
}

func demoIsoMoveDown() *IsoMove {
	return demoIsoMoveDown_impl(struct{}{}).(*IsoMove)
}

func demoIsoMoveLeft_impl(_unused0 interface{}) interface{} {
	var tmp3 interface{} = SubInt(int64(0), int64(1))
	return &IsoMove{Dx: tmp3.(int64), Dy: int64(1)}
}

func demoIsoMoveLeft() *IsoMove {
	return demoIsoMoveLeft_impl(struct{}{}).(*IsoMove)
}

func demoIsoMoveRight_impl(_unused0 interface{}) interface{} {
	var tmp4 interface{} = SubInt(int64(0), int64(1))
	return &IsoMove{Dx: int64(1), Dy: tmp4.(int64)}
}

func demoIsoMoveRight() *IsoMove {
	return demoIsoMoveRight_impl(struct{}{}).(*IsoMove)
}

func demoHasKeyRec_impl(keyCode interface{}, keys interface{}) interface{} {
	return func() interface{} {
		_scrutinee := keys
		_ = _scrutinee // suppress unused
		if ListLen(_scrutinee) == 0 {
			return false
		} else if ListLen(_scrutinee) >= 1 {
			k := ListHead(_scrutinee)
			_ = k // suppress unused
			rest := ListTail(_scrutinee)
			_ = rest // suppress unused
			return func() interface{} {
				var tmp5 interface{} = FieldGet(k, "key")
				_ = tmp5 // suppress unused
				var tmp6 interface{} = EqInt(tmp5, keyCode)
				_ = tmp6 // suppress unused
				var tmp7 interface{} = FieldGet(k, "kind")
				_ = tmp7 // suppress unused
				var tmp8 interface{} = EqString(tmp7, "pressed")
				_ = tmp8 // suppress unused
				var tmp9 interface{} = func() interface{} {
					if tmp6.(bool) {
						return tmp8
					}
					return false
				}()
				_ = tmp9 // suppress unused
				return func() interface{} {
					if tmp9.(bool) {
						return true
					}
					return demoHasKeyRec_impl(keyCode, rest)
				}()
			}()
		} else {
			panic("non-exhaustive match")
		}
	}()
}

func demoHasKeyRec(keyCode int64, keys []*KeyEvent) bool {
	return demoHasKeyRec_impl(keyCode, keys).(bool)
}

func demoHasKey_impl(keyCode interface{}, input interface{}) interface{} {
	var tmp10 interface{} = FieldGet(input, "keys")
	return demoHasKeyRec_impl(keyCode, tmp10)
}

func demoHasKey(keyCode int64, input *FrameInput) bool {
	return demoHasKey_impl(keyCode, input).(bool)
}

func demoGetIsoMovement_impl(input interface{}) interface{} {
	var tmp11 interface{} = demoKeyW_impl(struct{}{})
	var tmp12 interface{} = demoHasKey_impl(tmp11, input)
	var tmp13 interface{} = demoKeyUp_impl(struct{}{})
	var tmp14 interface{} = demoHasKey_impl(tmp13, input)
	var tmp15 interface{} = func() interface{} {
		if tmp12.(bool) {
			return true
		}
		return tmp14
	}()
	return func() interface{} {
		var tmp17 interface{} = demoKeyS_impl(struct{}{})
		_ = tmp17 // suppress unused
		var tmp18 interface{} = demoHasKey_impl(tmp17, input)
		_ = tmp18 // suppress unused
		var tmp19 interface{} = demoKeyDown_impl(struct{}{})
		_ = tmp19 // suppress unused
		var tmp20 interface{} = demoHasKey_impl(tmp19, input)
		_ = tmp20 // suppress unused
		var tmp21 interface{} = func() interface{} {
			if tmp18.(bool) {
				return true
			}
			return tmp20
		}()
		_ = tmp21 // suppress unused
		var tmp23 interface{} = demoKeyA_impl(struct{}{})
		_ = tmp23 // suppress unused
		var tmp24 interface{} = demoHasKey_impl(tmp23, input)
		_ = tmp24 // suppress unused
		var tmp25 interface{} = demoKeyLeft_impl(struct{}{})
		_ = tmp25 // suppress unused
		var tmp26 interface{} = demoHasKey_impl(tmp25, input)
		_ = tmp26 // suppress unused
		var tmp27 interface{} = func() interface{} {
			if tmp24.(bool) {
				return true
			}
			return tmp26
		}()
		_ = tmp27 // suppress unused
		var tmp29 interface{} = demoKeyD_impl(struct{}{})
		_ = tmp29 // suppress unused
		var tmp30 interface{} = demoHasKey_impl(tmp29, input)
		_ = tmp30 // suppress unused
		var tmp31 interface{} = demoKeyRight_impl(struct{}{})
		_ = tmp31 // suppress unused
		var tmp32 interface{} = demoHasKey_impl(tmp31, input)
		_ = tmp32 // suppress unused
		var tmp33 interface{} = func() interface{} {
			if tmp30.(bool) {
				return true
			}
			return tmp32
		}()
		_ = tmp33 // suppress unused
		if tmp15.(bool) {
			return func() interface{} {
				var tmp16 interface{} = demoIsoMoveUp_impl(struct{}{})
				_ = tmp16 // suppress unused
				return NewOptionSome(tmp16)
			}()
		}
		if tmp21.(bool) {
			return func() interface{} {
				var tmp22 interface{} = demoIsoMoveDown_impl(struct{}{})
				_ = tmp22 // suppress unused
				return NewOptionSome(tmp22)
			}()
		}
		if tmp27.(bool) {
			return func() interface{} {
				var tmp28 interface{} = demoIsoMoveLeft_impl(struct{}{})
				_ = tmp28 // suppress unused
				return NewOptionSome(tmp28)
			}()
		}
		if tmp33.(bool) {
			return func() interface{} {
				var tmp34 interface{} = demoIsoMoveRight_impl(struct{}{})
				_ = tmp34 // suppress unused
				return NewOptionSome(tmp34)
			}()
		}
		return NewOptionNone()
	}()
}

func demoGetIsoMovement(input *FrameInput) *Option {
	return demoGetIsoMovement_impl(input).(*Option)
}

func demoTileToWorldX_impl(tileX interface{}, tileY interface{}) interface{} {
	var tmp35 interface{} = SubInt(tileX, tileY)
	var tmp36 interface{} = IntToFloat(tmp35)
	var tmp37 interface{} = demoTileW_impl(struct{}{})
	var tmp38 interface{} = DivFloat(tmp37, float64(2))
	return MulFloat(tmp36, tmp38)
}

func demoTileToWorldX(tileX int64, tileY int64) float64 {
	return demoTileToWorldX_impl(tileX, tileY).(float64)
}

func demoTileToWorldY_impl(tileX interface{}, tileY interface{}) interface{} {
	var tmp39 interface{} = AddInt(tileX, tileY)
	var tmp40 interface{} = IntToFloat(tmp39)
	var tmp41 interface{} = demoTileH_impl(struct{}{})
	var tmp42 interface{} = DivFloat(tmp41, float64(2))
	return MulFloat(tmp40, tmp42)
}

func demoTileToWorldY(tileX int64, tileY int64) float64 {
	return demoTileToWorldY_impl(tileX, tileY).(float64)
}

func initIsoDemo_impl(_unused0 interface{}) interface{} {
	var startX interface{} = int64(8)
	var startY interface{} = int64(8)
	var worldX interface{} = demoTileToWorldX_impl(startX, startY)
	var worldY interface{} = demoTileToWorldY_impl(startX, startY)
	return &IsoWalkState{PlayerX: startX.(int64), PlayerY: startY.(int64), GridWidth: int64(16), GridHeight: int64(16), Tick: int64(0), CamX: worldX.(float64), CamY: worldY.(float64)}
}

func InitIsoDemo() *IsoWalkState {
	return initIsoDemo_impl(struct{}{}).(*IsoWalkState)
}

func inBounds_impl(x interface{}, y interface{}, w interface{}, h interface{}) interface{} {
	var tmp43 interface{} = GeInt(x, int64(0))
	var tmp44 interface{} = LtInt(x, w)
	var tmp45 interface{} = func() interface{} {
		if tmp43.(bool) {
			return tmp44
		}
		return false
	}()
	var tmp46 interface{} = GeInt(y, int64(0))
	var tmp47 interface{} = func() interface{} {
		if tmp45.(bool) {
			return tmp46
		}
		return false
	}()
	var tmp48 interface{} = LtInt(y, h)
	return func() interface{} {
		if tmp47.(bool) {
			return tmp48
		}
		return false
	}()
}

func inBounds(x int64, y int64, w int64, h int64) bool {
	return inBounds_impl(x, y, w, h).(bool)
}

func tryMove_impl(state interface{}, move interface{}) interface{} {
	var newX interface{} = func() interface{} {
		var tmp54 interface{} = FieldGet(state, "playerX")
		_ = tmp54 // suppress unused
		var tmp55 interface{} = FieldGet(move, "dx")
		_ = tmp55 // suppress unused
		return AddInt(tmp54, tmp55)
	}()
	var newY interface{} = func() interface{} {
		var tmp52 interface{} = FieldGet(state, "playerY")
		_ = tmp52 // suppress unused
		var tmp53 interface{} = FieldGet(move, "dy")
		_ = tmp53 // suppress unused
		return AddInt(tmp52, tmp53)
	}()
	var tmp49 interface{} = FieldGet(state, "gridWidth")
	var tmp50 interface{} = FieldGet(state, "gridHeight")
	var tmp51 interface{} = inBounds_impl(newX, newY, tmp49, tmp50)
	return func() interface{} {
		if tmp51.(bool) {
			return RecordUpdate(state, map[string]interface{}{"playerX": newX, "playerY": newY})
		}
		return state
	}()
}

func tryMove(state *IsoWalkState, move *IsoMove) *IsoWalkState {
	return tryMove_impl(state, move).(*IsoWalkState)
}

func demoUpdateCamera_impl(state interface{}) interface{} {
	var targetX interface{} = func() interface{} {
		var tmp66 interface{} = FieldGet(state, "playerX")
		_ = tmp66 // suppress unused
		var tmp67 interface{} = FieldGet(state, "playerY")
		_ = tmp67 // suppress unused
		return demoTileToWorldX_impl(tmp66, tmp67)
	}()
	var targetY interface{} = func() interface{} {
		var tmp64 interface{} = FieldGet(state, "playerX")
		_ = tmp64 // suppress unused
		var tmp65 interface{} = FieldGet(state, "playerY")
		_ = tmp65 // suppress unused
		return demoTileToWorldY_impl(tmp64, tmp65)
	}()
	var lerpFactor interface{} = float64(0.15)
	var newCamX interface{} = func() interface{} {
		var tmp60 interface{} = FieldGet(state, "camX")
		_ = tmp60 // suppress unused
		var tmp61 interface{} = FieldGet(state, "camX")
		_ = tmp61 // suppress unused
		var tmp62 interface{} = SubFloat(targetX, tmp61)
		_ = tmp62 // suppress unused
		var tmp63 interface{} = MulFloat(tmp62, lerpFactor)
		_ = tmp63 // suppress unused
		return AddFloat(tmp60, tmp63)
	}()
	var newCamY interface{} = func() interface{} {
		var tmp56 interface{} = FieldGet(state, "camY")
		_ = tmp56 // suppress unused
		var tmp57 interface{} = FieldGet(state, "camY")
		_ = tmp57 // suppress unused
		var tmp58 interface{} = SubFloat(targetY, tmp57)
		_ = tmp58 // suppress unused
		var tmp59 interface{} = MulFloat(tmp58, lerpFactor)
		_ = tmp59 // suppress unused
		return AddFloat(tmp56, tmp59)
	}()
	return RecordUpdate(state, map[string]interface{}{"camY": newCamY, "camX": newCamX})
}

func demoUpdateCamera(state *IsoWalkState) *IsoWalkState {
	return demoUpdateCamera_impl(state).(*IsoWalkState)
}

func stepIsoDemo_impl(state interface{}, input interface{}) interface{} {
	var afterMove interface{} = func() interface{} {
		var tmp70 interface{} = demoGetIsoMovement_impl(input)
		_ = tmp70 // suppress unused
		return func() interface{} {
			_scrutinee := tmp70
			_ = _scrutinee // suppress unused
			_adt := _scrutinee.(*Option)
			switch _adt.Kind {
			case OptionKindSome:
				move := _adt.Some.Value0
				_ = move // suppress unused
				return tryMove_impl(state, move)
			default:
				none := _adt
				_ = none // suppress unused
				return state
			}
		}()
	}()
	var afterCamera interface{} = demoUpdateCamera_impl(afterMove)
	var tmp68 interface{} = FieldGet(afterCamera, "tick")
	var tmp69 interface{} = AddInt(tmp68, int64(1))
	return RecordUpdate(afterCamera, map[string]interface{}{"tick": tmp69})
}

func StepIsoDemo(state *IsoWalkState, input *FrameInput) *IsoWalkState {
	return stepIsoDemo_impl(state, input).(*IsoWalkState)
}

func demoMakeCoord_impl(x interface{}, y interface{}) interface{} {
	return &Coord{X: x.(int64), Y: y.(int64)}
}

func demoMakeCoord(x int64, y int64) *Coord {
	return demoMakeCoord_impl(x, y).(*Coord)
}

func demoRgba_impl(r interface{}, g interface{}, b interface{}, a interface{}) interface{} {
	var tmp71 interface{} = MulInt(r, int64(16777216))
	var tmp72 interface{} = MulInt(g, int64(65536))
	var tmp73 interface{} = AddInt(tmp71, tmp72)
	var tmp74 interface{} = MulInt(b, int64(256))
	var tmp75 interface{} = AddInt(tmp73, tmp74)
	return AddInt(tmp75, a)
}

func demoRgba(r int64, g int64, b int64, a int64) int64 {
	return demoRgba_impl(r, g, b, a).(int64)
}

func demoMakeMarker_impl(x interface{}, y interface{}, w interface{}, h interface{}, rgba interface{}, layer interface{}) interface{} {
	return NewDrawCmdMarker(x.(float64), y.(float64), w.(float64), h.(float64), rgba.(int64), layer.(int64), layer.(int64))
}

func demoMakeMarker(x float64, y float64, w float64, h float64, rgba int64, layer int64) *DrawCmd {
	return demoMakeMarker_impl(x, y, w, h, rgba, layer).(*DrawCmd)
}

func demoRenderParallaxGridRec_impl(x interface{}, y interface{}, maxX interface{}, maxY interface{}, spacing interface{}, rgba interface{}, layer interface{}, scale interface{}, acc interface{}) interface{} {
	var tmp76 interface{} = GeInt(y, maxY)
	return func() interface{} {
		var tmp77 interface{} = GeInt(x, maxX)
		_ = tmp77 // suppress unused
		if tmp76.(bool) {
			return acc
		}
		if tmp77.(bool) {
			return func() interface{} {
				var tmp78 interface{} = SubInt(int64(0), maxX)
				_ = tmp78 // suppress unused
				return func() interface{} {
					var tmp79 interface{} = AddInt(y, spacing)
					_ = tmp79 // suppress unused
					return demoRenderParallaxGridRec_impl(tmp78, tmp79, maxX, maxY, spacing, rgba, layer, scale, acc)
				}()
			}()
		}
		return func() interface{} {
			var worldX interface{} = func() interface{} {
				var tmp84 interface{} = IntToFloat(x)
				_ = tmp84 // suppress unused
				return MulFloat(tmp84, scale)
			}()
			_ = worldX // suppress unused
			return func() interface{} {
				var worldY interface{} = func() interface{} {
					var tmp82 interface{} = IntToFloat(y)
					_ = tmp82 // suppress unused
					return func() interface{} {
						var tmp83 interface{} = MulFloat(tmp82, scale)
						_ = tmp83 // suppress unused
						return AddFloat(tmp83, float64(256))
					}()
				}()
				_ = worldY // suppress unused
				return func() interface{} {
					var markerW interface{} = MulFloat(scale, float64(0.7))
					_ = markerW // suppress unused
					return func() interface{} {
						var markerH interface{} = MulFloat(scale, float64(0.35))
						_ = markerH // suppress unused
						return func() interface{} {
							var marker interface{} = demoMakeMarker_impl(worldX, worldY, markerW, markerH, rgba, layer)
							_ = marker // suppress unused
							return func() interface{} {
								var tmp80 interface{} = AddInt(x, spacing)
								_ = tmp80 // suppress unused
								return func() interface{} {
									var tmp81 interface{} = Cons(marker, acc)
									_ = tmp81 // suppress unused
									return demoRenderParallaxGridRec_impl(tmp80, y, maxX, maxY, spacing, rgba, layer, scale, tmp81)
								}()
							}()
						}()
					}()
				}()
			}()
		}()
	}()
}

func demoRenderParallaxGridRec(x int64, y int64, maxX int64, maxY int64, spacing int64, rgba int64, layer int64, scale float64, acc []*DrawCmd) []*DrawCmd {
	return ConvertToDrawCmdSlice(demoRenderParallaxGridRec_impl(x, y, maxX, maxY, spacing, rgba, layer, scale, acc))
}

func demoRenderFarGrid_impl(_unused0 interface{}) interface{} {
	var rgba interface{} = demoRgba_impl(int64(40), int64(50), int64(70), int64(180))
	var tmp85 interface{} = SubInt(int64(0), int64(40))
	var tmp86 interface{} = SubInt(int64(0), int64(40))
	var tmp87 interface{} = demoParallaxFar_impl(struct{}{})
	var tmp88 interface{} = []interface{}{}
	return demoRenderParallaxGridRec_impl(tmp85, tmp86, int64(40), int64(40), int64(5), rgba, tmp87, float64(60), tmp88)
}

func demoRenderFarGrid() []*DrawCmd {
	return ConvertToDrawCmdSlice(demoRenderFarGrid_impl(struct{}{}))
}

func demoRenderMidGrid_impl(_unused0 interface{}) interface{} {
	var rgba interface{} = demoRgba_impl(int64(60), int64(80), int64(100), int64(150))
	var tmp89 interface{} = SubInt(int64(0), int64(30))
	var tmp90 interface{} = SubInt(int64(0), int64(30))
	var tmp91 interface{} = demoParallaxMid_impl(struct{}{})
	var tmp92 interface{} = []interface{}{}
	return demoRenderParallaxGridRec_impl(tmp89, tmp90, int64(30), int64(30), int64(4), rgba, tmp91, float64(50), tmp92)
}

func demoRenderMidGrid() []*DrawCmd {
	return ConvertToDrawCmdSlice(demoRenderMidGrid_impl(struct{}{}))
}

func demoRenderNearGrid_impl(_unused0 interface{}) interface{} {
	var rgba interface{} = demoRgba_impl(int64(80), int64(100), int64(120), int64(120))
	var tmp93 interface{} = SubInt(int64(0), int64(25))
	var tmp94 interface{} = SubInt(int64(0), int64(25))
	var tmp95 interface{} = demoParallaxNear_impl(struct{}{})
	var tmp96 interface{} = []interface{}{}
	return demoRenderParallaxGridRec_impl(tmp93, tmp94, int64(25), int64(25), int64(3), rgba, tmp95, float64(40), tmp96)
}

func demoRenderNearGrid() []*DrawCmd {
	return ConvertToDrawCmdSlice(demoRenderNearGrid_impl(struct{}{}))
}

func demoGetTileSprite_impl(x interface{}, y interface{}) interface{} {
	var pattern interface{} = func() interface{} {
		var tmp100 interface{} = AddInt(x, y)
		_ = tmp100 // suppress unused
		return ModInt(tmp100, int64(4))
	}()
	var tmp97 interface{} = EqInt(pattern, int64(0))
	return func() interface{} {
		var tmp98 interface{} = EqInt(pattern, int64(1))
		_ = tmp98 // suppress unused
		var tmp99 interface{} = EqInt(pattern, int64(2))
		_ = tmp99 // suppress unused
		if tmp97.(bool) {
			return demoSpriteForest_impl(struct{}{})
		}
		if tmp98.(bool) {
			return demoSpriteDesert_impl(struct{}{})
		}
		if tmp99.(bool) {
			return demoSpriteWater_impl(struct{}{})
		}
		return demoSpriteMountain_impl(struct{}{})
	}()
}

func demoGetTileSprite(x int64, y int64) int64 {
	return demoGetTileSprite_impl(x, y).(int64)
}

func demoRenderTile_impl(x interface{}, y interface{}) interface{} {
	var tmp101 interface{} = demoMakeCoord_impl(x, y)
	var tmp102 interface{} = demoGetTileSprite_impl(x, y)
	var tmp103 interface{} = demoLayerFloor_impl(struct{}{})
	return NewDrawCmdIsoTile(tmp101.(*Coord), int64(0), tmp102.(int64), tmp103.(int64), int64(0))
}

func demoRenderTile(x int64, y int64) *DrawCmd {
	return demoRenderTile_impl(x, y).(*DrawCmd)
}

func demoRenderRowRec_impl(y interface{}, x interface{}, maxX interface{}, acc interface{}) interface{} {
	var tmp104 interface{} = GeInt(x, maxX)
	return func() interface{} {
		if tmp104.(bool) {
			return acc
		}
		return func() interface{} {
			var tmp105 interface{} = AddInt(x, int64(1))
			_ = tmp105 // suppress unused
			var tmp106 interface{} = demoRenderTile_impl(x, y)
			_ = tmp106 // suppress unused
			var tmp107 interface{} = Cons(tmp106, acc)
			_ = tmp107 // suppress unused
			return demoRenderRowRec_impl(y, tmp105, maxX, tmp107)
		}()
	}()
}

func demoRenderRowRec(y int64, x int64, maxX int64, acc []*DrawCmd) []*DrawCmd {
	return ConvertToDrawCmdSlice(demoRenderRowRec_impl(y, x, maxX, acc))
}

func demoRenderRow_impl(y interface{}, width interface{}) interface{} {
	var tmp108 interface{} = []interface{}{}
	return demoRenderRowRec_impl(y, int64(0), width, tmp108)
}

func demoRenderRow(y int64, width int64) []*DrawCmd {
	return ConvertToDrawCmdSlice(demoRenderRow_impl(y, width))
}

func demoRenderFloorRec_impl(y interface{}, maxY interface{}, width interface{}, acc interface{}) interface{} {
	var tmp109 interface{} = GeInt(y, maxY)
	return func() interface{} {
		if tmp109.(bool) {
			return acc
		}
		return func() interface{} {
			var tmp110 interface{} = AddInt(y, int64(1))
			_ = tmp110 // suppress unused
			var tmp111 interface{} = demoRenderRow_impl(y, width)
			_ = tmp111 // suppress unused
			var tmp112 interface{} = Concat(tmp111, acc)
			_ = tmp112 // suppress unused
			return demoRenderFloorRec_impl(tmp110, maxY, width, tmp112)
		}()
	}()
}

func demoRenderFloorRec(y int64, maxY int64, width int64, acc []*DrawCmd) []*DrawCmd {
	return ConvertToDrawCmdSlice(demoRenderFloorRec_impl(y, maxY, width, acc))
}

func demoRenderFloor_impl(state interface{}) interface{} {
	var tmp113 interface{} = FieldGet(state, "gridHeight")
	var tmp114 interface{} = FieldGet(state, "gridWidth")
	var tmp115 interface{} = []interface{}{}
	return demoRenderFloorRec_impl(int64(0), tmp113, tmp114, tmp115)
}

func demoRenderFloor(state *IsoWalkState) []*DrawCmd {
	return ConvertToDrawCmdSlice(demoRenderFloor_impl(state))
}

func demoRenderPlayer_impl(state interface{}) interface{} {
	var tmp116 interface{} = FieldGet(state, "playerX")
	var tmp117 interface{} = FieldGet(state, "playerY")
	var tmp118 interface{} = demoMakeCoord_impl(tmp116, tmp117)
	var tmp119 interface{} = demoSpritePlayer_impl(struct{}{})
	var tmp120 interface{} = demoLayerPlayer_impl(struct{}{})
	var tmp121 interface{} = NewDrawCmdIsoEntity("player", tmp118.(*Coord), float64(0), float64(0), int64(0), tmp119.(int64), tmp120.(int64))
	return []interface{}{tmp121}
}

func demoRenderPlayer(state *IsoWalkState) []*DrawCmd {
	return ConvertToDrawCmdSlice(demoRenderPlayer_impl(state))
}

func demoRenderNpcs_impl(_unused0 interface{}) interface{} {
	var tmp122 interface{} = demoMakeCoord_impl(int64(2), int64(2))
	var tmp123 interface{} = demoSpriteNpcRed_impl(struct{}{})
	var tmp124 interface{} = demoLayerPlayer_impl(struct{}{})
	var tmp125 interface{} = NewDrawCmdIsoEntity("npc_red", tmp122.(*Coord), float64(0), float64(0), int64(0), tmp123.(int64), tmp124.(int64))
	var tmp126 interface{} = demoMakeCoord_impl(int64(13), int64(2))
	var tmp127 interface{} = demoSpriteNpcGreen_impl(struct{}{})
	var tmp128 interface{} = demoLayerPlayer_impl(struct{}{})
	var tmp129 interface{} = NewDrawCmdIsoEntity("npc_green", tmp126.(*Coord), float64(0), float64(0), int64(0), tmp127.(int64), tmp128.(int64))
	var tmp130 interface{} = demoMakeCoord_impl(int64(2), int64(13))
	var tmp131 interface{} = demoSpriteNpcBlue_impl(struct{}{})
	var tmp132 interface{} = demoLayerPlayer_impl(struct{}{})
	var tmp133 interface{} = NewDrawCmdIsoEntity("npc_blue", tmp130.(*Coord), float64(0), float64(0), int64(0), tmp131.(int64), tmp132.(int64))
	var tmp134 interface{} = demoMakeCoord_impl(int64(13), int64(13))
	var tmp135 interface{} = demoSpriteNpcYellow_impl(struct{}{})
	var tmp136 interface{} = demoLayerPlayer_impl(struct{}{})
	var tmp137 interface{} = NewDrawCmdIsoEntity("npc_yellow", tmp134.(*Coord), float64(0), float64(0), int64(0), tmp135.(int64), tmp136.(int64))
	var tmp138 interface{} = demoMakeCoord_impl(int64(8), int64(8))
	var tmp139 interface{} = demoSpriteNpcPurple_impl(struct{}{})
	var tmp140 interface{} = demoLayerPlayer_impl(struct{}{})
	var tmp141 interface{} = NewDrawCmdIsoEntity("npc_purple", tmp138.(*Coord), float64(0), float64(0), int64(0), tmp139.(int64), tmp140.(int64))
	return []interface{}{tmp125, tmp129, tmp133, tmp137, tmp141}
}

func demoRenderNpcs() []*DrawCmd {
	return ConvertToDrawCmdSlice(demoRenderNpcs_impl(struct{}{}))
}

func renderIsoDemo_impl(state interface{}) interface{} {
	var farBg interface{} = demoRenderFarGrid_impl(struct{}{})
	var midBg interface{} = demoRenderMidGrid_impl(struct{}{})
	var nearBg interface{} = demoRenderNearGrid_impl(struct{}{})
	var floor interface{} = demoRenderFloor_impl(state)
	var npcs interface{} = demoRenderNpcs_impl(struct{}{})
	var player interface{} = demoRenderPlayer_impl(state)
	var tmp142 interface{} = Concat(farBg, midBg)
	var tmp143 interface{} = Concat(tmp142, nearBg)
	var tmp144 interface{} = Concat(tmp143, floor)
	var tmp145 interface{} = Concat(tmp144, npcs)
	return Concat(tmp145, player)
}

func RenderIsoDemo(state *IsoWalkState) []*DrawCmd {
	return ConvertToDrawCmdSlice(renderIsoDemo_impl(state))
}

func getIsoCamera_impl(state interface{}) interface{} {
	var tmp146 interface{} = FieldGet(state, "camX")
	var tmp147 interface{} = FieldGet(state, "camY")
	return &Camera{X: tmp146.(float64), Y: tmp147.(float64), Zoom: float64(1)}
}

func GetIsoCamera(state *IsoWalkState) *Camera {
	return getIsoCamera_impl(state).(*Camera)
}
