// Code generated by ailang. DO NOT EDIT.
package sim_gen

func generate_impl(n interface{}, f interface{}) interface{} {
	return func() interface{} {
		_scrutinee := n
		_ = _scrutinee // suppress unused
		switch _scrutinee {
		case int64(0):
			return []interface{}{}
		default:
			return func() interface{} {
				var tmp1 interface{} = SubInt(n, int64(1))
				_ = tmp1 // suppress unused
				return func() interface{} {
					var tmp2 interface{} = CallFunc(f, tmp1)
					_ = tmp2 // suppress unused
					return func() interface{} {
						var tmp3 interface{} = SubInt(n, int64(1))
						_ = tmp3 // suppress unused
						return func() interface{} {
							var tmp4 interface{} = generate_impl(tmp3, f)
							_ = tmp4 // suppress unused
							return Cons(tmp2, tmp4)
						}()
					}()
				}()
			}()
		}
	}()
}

func generate(n int64, f interface{}) []*Tile {
	return ConvertToTileSlice(generate_impl(n, f))
}

func tilesToDraw_impl(tiles interface{}, width interface{}, idx interface{}) interface{} {
	return func() interface{} {
		_scrutinee := tiles
		_ = _scrutinee // suppress unused
		if ListLen(_scrutinee) == 0 {
			return []interface{}{}
		} else if ListLen(_scrutinee) >= 1 {
			t := ListHead(_scrutinee)
			_ = t // suppress unused
			rest := ListTail(_scrutinee)
			_ = rest // suppress unused
			return func() interface{} {
				var x interface{} = ModInt(idx, width)
				_ = x // suppress unused
				return func() interface{} {
					var y interface{} = DivInt(idx, width)
					_ = y // suppress unused
					return func() interface{} {
						var cmd interface{} = func() interface{} {
							var tmp7 interface{} = MulInt(x, int64(8))
							_ = tmp7 // suppress unused
							return func() interface{} {
								var tmp8 interface{} = IntToFloat(tmp7)
								_ = tmp8 // suppress unused
								return func() interface{} {
									var tmp9 interface{} = MulInt(y, int64(8))
									_ = tmp9 // suppress unused
									return func() interface{} {
										var tmp10 interface{} = IntToFloat(tmp9)
										_ = tmp10 // suppress unused
										return func() interface{} {
											var tmp11 interface{} = FieldGet(t, "biome")
											_ = tmp11 // suppress unused
											return NewDrawCmdRect(tmp8.(float64), tmp10.(float64), float64(8), float64(8), tmp11.(int64), int64(0))
										}()
									}()
								}()
							}()
						}()
						_ = cmd // suppress unused
						return func() interface{} {
							var tmp5 interface{} = AddInt(idx, int64(1))
							_ = tmp5 // suppress unused
							return func() interface{} {
								var tmp6 interface{} = tilesToDraw_impl(rest, width, tmp5)
								_ = tmp6 // suppress unused
								return Cons(cmd, tmp6)
							}()
						}()
					}()
				}()
			}()
		} else {
			panic("non-exhaustive match")
		}
	}()
}

func tilesToDraw(tiles []*Tile, width int64, idx int64) []*DrawCmd {
	return ConvertToDrawCmdSlice(tilesToDraw_impl(tiles, width, idx))
}

func npcsToDraw_impl(npcs interface{}) interface{} {
	return func() interface{} {
		_scrutinee := npcs
		_ = _scrutinee // suppress unused
		if ListLen(_scrutinee) == 0 {
			return []interface{}{}
		} else if ListLen(_scrutinee) >= 1 {
			npc := ListHead(_scrutinee)
			_ = npc // suppress unused
			rest := ListTail(_scrutinee)
			_ = rest // suppress unused
			return func() interface{} {
				var cmd interface{} = func() interface{} {
					var tmp13 interface{} = FieldGet(npc, "pos")
					_ = tmp13 // suppress unused
					return func() interface{} {
						var tmp14 interface{} = FieldGet(tmp13, "x")
						_ = tmp14 // suppress unused
						return func() interface{} {
							var tmp15 interface{} = MulInt(tmp14, int64(8))
							_ = tmp15 // suppress unused
							return func() interface{} {
								var tmp16 interface{} = IntToFloat(tmp15)
								_ = tmp16 // suppress unused
								return func() interface{} {
									var tmp17 interface{} = FieldGet(npc, "pos")
									_ = tmp17 // suppress unused
									return func() interface{} {
										var tmp18 interface{} = FieldGet(tmp17, "y")
										_ = tmp18 // suppress unused
										return func() interface{} {
											var tmp19 interface{} = MulInt(tmp18, int64(8))
											_ = tmp19 // suppress unused
											return func() interface{} {
												var tmp20 interface{} = IntToFloat(tmp19)
												_ = tmp20 // suppress unused
												return func() interface{} {
													var tmp21 interface{} = FieldGet(npc, "id")
													_ = tmp21 // suppress unused
													return func() interface{} {
														var tmp22 interface{} = AddInt(int64(10), tmp21)
														_ = tmp22 // suppress unused
														return NewDrawCmdRect(tmp16.(float64), tmp20.(float64), float64(8), float64(8), tmp22.(int64), int64(2))
													}()
												}()
											}()
										}()
									}()
								}()
							}()
						}()
					}()
				}()
				_ = cmd // suppress unused
				return func() interface{} {
					var tmp12 interface{} = npcsToDraw_impl(rest)
					_ = tmp12 // suppress unused
					return Cons(cmd, tmp12)
				}()
			}()
		} else {
			panic("non-exhaustive match")
		}
	}()
}

func npcsToDraw(npcs []*NPC) []*DrawCmd {
	return ConvertToDrawCmdSlice(npcsToDraw_impl(npcs))
}

func selectionToDraw_impl(sel interface{}) interface{} {
	return func() interface{} {
		_scrutinee := sel
		_ = _scrutinee // suppress unused
		_adt := _scrutinee.(*Selection)
		switch _adt.Kind {
		default:
			selectionNone := _adt
			_ = selectionNone // suppress unused
			return []interface{}{}
		case SelectionKindTile:
			x := _adt.SelectionTile.Value0
			_ = x // suppress unused
			y := _adt.SelectionTile.Value1
			_ = y // suppress unused
			return func() interface{} {
				var tmp23 interface{} = MulInt(x, int64(8))
				_ = tmp23 // suppress unused
				return func() interface{} {
					var tmp24 interface{} = IntToFloat(tmp23)
					_ = tmp24 // suppress unused
					return func() interface{} {
						var tmp25 interface{} = MulInt(y, int64(8))
						_ = tmp25 // suppress unused
						return func() interface{} {
							var tmp26 interface{} = IntToFloat(tmp25)
							_ = tmp26 // suppress unused
							return func() interface{} {
								var tmp27 interface{} = NewDrawCmdRect(tmp24.(float64), tmp26.(float64), float64(8), float64(8), int64(4), int64(3))
								_ = tmp27 // suppress unused
								return []interface{}{tmp27}
							}()
						}()
					}()
				}()
			}()
		}
	}()
}

func selectionToDraw(sel *Selection) []*DrawCmd {
	return ConvertToDrawCmdSlice(selectionToDraw_impl(sel))
}

func concatDrawCmds_impl(a interface{}, b interface{}) interface{} {
	return func() interface{} {
		_scrutinee := a
		_ = _scrutinee // suppress unused
		if ListLen(_scrutinee) == 0 {
			return b
		} else if ListLen(_scrutinee) >= 1 {
			x := ListHead(_scrutinee)
			_ = x // suppress unused
			rest := ListTail(_scrutinee)
			_ = rest // suppress unused
			return func() interface{} {
				var tmp28 interface{} = concatDrawCmds_impl(rest, b)
				_ = tmp28 // suppress unused
				return Cons(x, tmp28)
			}()
		} else {
			panic("non-exhaustive match")
		}
	}()
}

func concatDrawCmds(a []*DrawCmd, b []*DrawCmd) []*DrawCmd {
	return ConvertToDrawCmdSlice(concatDrawCmds_impl(a, b))
}

func processSelection_impl(input interface{}, world interface{}) interface{} {
	var tmp29 interface{} = FieldGet(input, "clickedThisFrame")
	return func() interface{} {
		if tmp29.(bool) {
			return func() interface{} {
				var tileX interface{} = func() interface{} {
					var tmp43 interface{} = FieldGet(input, "worldMouseX")
					_ = tmp43 // suppress unused
					return func() interface{} {
						var tmp44 interface{} = DivFloat(tmp43, float64(8))
						_ = tmp44 // suppress unused
						return FloatToInt(tmp44)
					}()
				}()
				_ = tileX // suppress unused
				return func() interface{} {
					var tileY interface{} = func() interface{} {
						var tmp41 interface{} = FieldGet(input, "worldMouseY")
						_ = tmp41 // suppress unused
						return func() interface{} {
							var tmp42 interface{} = DivFloat(tmp41, float64(8))
							_ = tmp42 // suppress unused
							return FloatToInt(tmp42)
						}()
					}()
					_ = tileY // suppress unused
					return func() interface{} {
						var tmp30 interface{} = GeInt(tileX, int64(0))
						_ = tmp30 // suppress unused
						return func() interface{} {
							var tmp31 interface{} = FieldGet(world, "planet")
							_ = tmp31 // suppress unused
							return func() interface{} {
								var tmp32 interface{} = FieldGet(tmp31, "width")
								_ = tmp32 // suppress unused
								return func() interface{} {
									var tmp33 interface{} = LtInt(tileX, tmp32)
									_ = tmp33 // suppress unused
									return func() interface{} {
										var tmp34 interface{} = func() interface{} {
											if tmp30.(bool) {
												return tmp33
											}
											return false
										}()
										_ = tmp34 // suppress unused
										return func() interface{} {
											var tmp35 interface{} = GeInt(tileY, int64(0))
											_ = tmp35 // suppress unused
											return func() interface{} {
												var tmp36 interface{} = func() interface{} {
													if tmp34.(bool) {
														return tmp35
													}
													return false
												}()
												_ = tmp36 // suppress unused
												return func() interface{} {
													var tmp37 interface{} = FieldGet(world, "planet")
													_ = tmp37 // suppress unused
													return func() interface{} {
														var tmp38 interface{} = FieldGet(tmp37, "height")
														_ = tmp38 // suppress unused
														return func() interface{} {
															var tmp39 interface{} = LtInt(tileY, tmp38)
															_ = tmp39 // suppress unused
															return func() interface{} {
																var tmp40 interface{} = func() interface{} {
																	if tmp36.(bool) {
																		return tmp39
																	}
																	return false
																}()
																_ = tmp40 // suppress unused
																return func() interface{} {
																	if tmp40.(bool) {
																		return NewSelectionTile(tileX.(int64), tileY.(int64))
																	}
																	return NewSelectionNone()
																}()
															}()
														}()
													}()
												}()
											}()
										}()
									}()
								}()
							}()
						}()
					}()
				}()
			}()
		}
		return FieldGet(world, "selection")
	}()
}

func processSelection(input *FrameInput, world *World) *Selection {
	return processSelection_impl(input, world).(*Selection)
}

func initWorld_impl(seed interface{}) interface{} {
	var w interface{} = int64(8)
	var h interface{} = int64(8)
	var tiles interface{} = func() interface{} {
		var tmp58 interface{} = MulInt(w, h)
		_ = tmp58 // suppress unused
		return generate_impl(tmp58, func(i interface{}) interface{} {
			return func() interface{} {
				var tmp59 interface{} = ModInt(i, int64(4))
				_ = tmp59 // suppress unused
				return &Tile{Biome: tmp59.(int64)}
			}()
		})
	}()
	var patrolPath interface{} = []interface{}{NewDirectionEast(), NewDirectionEast(), NewDirectionSouth(), NewDirectionSouth(), NewDirectionWest(), NewDirectionWest(), NewDirectionNorth(), NewDirectionNorth()}
	var testNpcs interface{} = func() interface{} {
		var tmp47 interface{} = &Coord{X: int64(2), Y: int64(2)}
		_ = tmp47 // suppress unused
		return func() interface{} {
			var tmp48 interface{} = NewMovementPatternPatternRandomWalk(int64(30))
			_ = tmp48 // suppress unused
			return func() interface{} {
				var tmp49 interface{} = &NPC{Id: int64(1), Pos: tmp47.(*Coord), Pattern: tmp48.(*MovementPattern), MoveCounter: int64(30), PatrolIndex: int64(0)}
				_ = tmp49 // suppress unused
				return func() interface{} {
					var tmp50 interface{} = &Coord{X: int64(5), Y: int64(3)}
					_ = tmp50 // suppress unused
					return func() interface{} {
						var tmp51 interface{} = NewMovementPatternPatternRandomWalk(int64(45))
						_ = tmp51 // suppress unused
						return func() interface{} {
							var tmp52 interface{} = &NPC{Id: int64(2), Pos: tmp50.(*Coord), Pattern: tmp51.(*MovementPattern), MoveCounter: int64(45), PatrolIndex: int64(0)}
							_ = tmp52 // suppress unused
							return func() interface{} {
								var tmp53 interface{} = &Coord{X: int64(4), Y: int64(4)}
								_ = tmp53 // suppress unused
								return func() interface{} {
									var tmp54 interface{} = &NPC{Id: int64(3), Pos: tmp53.(*Coord), Pattern: NewMovementPatternPatternStatic(), MoveCounter: int64(0), PatrolIndex: int64(0)}
									_ = tmp54 // suppress unused
									return func() interface{} {
										var tmp55 interface{} = &Coord{X: int64(1), Y: int64(1)}
										_ = tmp55 // suppress unused
										return func() interface{} {
											var tmp56 interface{} = NewMovementPatternPatternPatrol(ConvertToDirectionSlice(patrolPath))
											_ = tmp56 // suppress unused
											return func() interface{} {
												var tmp57 interface{} = &NPC{Id: int64(4), Pos: tmp55.(*Coord), Pattern: tmp56.(*MovementPattern), MoveCounter: int64(0), PatrolIndex: int64(0)}
												_ = tmp57 // suppress unused
												return []interface{}{tmp49, tmp52, tmp54, tmp57}
											}()
										}()
									}()
								}()
							}()
						}()
					}()
				}()
			}()
		}()
	}()
	var tmp45 interface{} = &PlanetState{Width: w.(int64), Height: h.(int64), Tiles: ConvertToTileSlice(tiles)}
	var tmp46 interface{} = initBridge_impl(struct{}{})
	return &World{Tick: int64(0), Planet: tmp45.(*PlanetState), Npcs: ConvertToNPCSlice(testNpcs), Selection: NewSelectionNone(), Bridge: tmp46.(*BridgeState), ViewMode: NewViewModeViewBridge()}
}

func InitWorld(seed int64) *World {
	return initWorld_impl(seed).(*World)
}

func renderForView_impl(world interface{}) interface{} {
	var tmp60 interface{} = FieldGet(world, "viewMode")
	return func() interface{} {
		_scrutinee := tmp60
		_ = _scrutinee // suppress unused
		switch _scrutinee {
		default:
			return func() interface{} {
				var tmp61 interface{} = FieldGet(world, "bridge")
				_ = tmp61 // suppress unused
				return renderBridge_impl(tmp61)
			}()
		}
	}()
}

func renderForView(world *World) []*DrawCmd {
	return ConvertToDrawCmdSlice(renderForView_impl(world))
}

func updateBridgeView_impl(world interface{}, newTick interface{}) interface{} {
	var updatedBridge interface{} = func() interface{} {
		var tmp69 interface{} = FieldGet(world, "bridge")
		_ = tmp69 // suppress unused
		return stepBridge_impl(tmp69, newTick)
	}()
	return RecordUpdate(world, map[string]interface{}{"bridge": updatedBridge, "tick": newTick})
}

func updateBridgeView(world *World, newTick int64) *World {
	return updateBridgeView_impl(world, newTick).(*World)
}

func updatePlanetView_impl(world interface{}, input interface{}, newTick interface{}) interface{} {
	var newSelection interface{} = processSelection_impl(input, world)
	var updatedNpcs interface{} = func() interface{} {
		var tmp70 interface{} = FieldGet(world, "npcs")
		_ = tmp70 // suppress unused
		return func() interface{} {
			var tmp71 interface{} = FieldGet(world, "planet")
			_ = tmp71 // suppress unused
			return func() interface{} {
				var tmp72 interface{} = FieldGet(tmp71, "width")
				_ = tmp72 // suppress unused
				return func() interface{} {
					var tmp73 interface{} = FieldGet(world, "planet")
					_ = tmp73 // suppress unused
					return func() interface{} {
						var tmp74 interface{} = FieldGet(tmp73, "height")
						_ = tmp74 // suppress unused
						return updateAllNPCs_impl(tmp70, tmp72, tmp74)
					}()
				}()
			}()
		}()
	}()
	return RecordUpdate(world, map[string]interface{}{"tick": newTick, "npcs": updatedNpcs, "selection": newSelection})
}

func updatePlanetView(world *World, input *FrameInput, newTick int64) *World {
	return updatePlanetView_impl(world, input, newTick).(*World)
}

func updateGalaxyView_impl(world interface{}, newTick interface{}) interface{} {
	return RecordUpdate(world, map[string]interface{}{"tick": newTick})
}

func updateGalaxyView(world *World, newTick int64) *World {
	return updateGalaxyView_impl(world, newTick).(*World)
}

func step_impl(world interface{}, input interface{}) interface{} {
	var newTick interface{} = func() interface{} {
		var tmp78 interface{} = FieldGet(world, "tick")
		_ = tmp78 // suppress unused
		return AddInt(tmp78, int64(1))
	}()
	var newWorld interface{} = func() interface{} {
		var tmp77 interface{} = FieldGet(world, "viewMode")
		_ = tmp77 // suppress unused
		return func() interface{} {
			_scrutinee := tmp77
			_ = _scrutinee // suppress unused
			switch _scrutinee {
			default:
				return updateBridgeView_impl(world, newTick)
			}
		}()
	}()
	var drawCmds interface{} = renderForView_impl(newWorld)
	var cam interface{} = &Camera{X: float64(0), Y: float64(0), Zoom: float64(1)}
	var output interface{} = func() interface{} {
		var tmp75 interface{} = []interface{}{}
		_ = tmp75 // suppress unused
		return func() interface{} {
			var tmp76 interface{} = []interface{}{}
			_ = tmp76 // suppress unused
			return &FrameOutput{Draw: ConvertToDrawCmdSlice(drawCmds), Sounds: ConvertToInt64Slice(tmp75), Debug: ConvertToStringSlice(tmp76), Camera: cam.(*Camera)}
		}()
	}()
	return []interface{}{newWorld, output}
}

func Step(world *World, input *FrameInput) interface{} {
	return step_impl(world, input)
}
