// Code generated by ailang. DO NOT EDIT.
package sim_gen

func generate_impl(n interface{}, f interface{}) interface{} {
	return func() interface{} {
		_scrutinee := n
		_ = _scrutinee // suppress unused
		switch _scrutinee {
		case int64(0):
			return []interface{}{}
		default:
			return func() interface{} {
				var tmp1 interface{} = SubInt(n, int64(1))
				_ = tmp1 // suppress unused
				var tmp2 interface{} = CallFunc(f, tmp1)
				_ = tmp2 // suppress unused
				var tmp3 interface{} = SubInt(n, int64(1))
				_ = tmp3 // suppress unused
				var tmp4 interface{} = generate_impl(tmp3, f)
				_ = tmp4 // suppress unused
				return Cons(tmp2, tmp4)
			}()
		}
	}()
}

func generate(n int64, f interface{}) []*Tile {
	return ConvertToTileSlice(generate_impl(n, f))
}

func tilesToDraw_impl(tiles interface{}, width interface{}, idx interface{}) interface{} {
	return func() interface{} {
		_scrutinee := tiles
		_ = _scrutinee // suppress unused
		if ListLen(_scrutinee) == 0 {
			return []interface{}{}
		} else if ListLen(_scrutinee) >= 1 {
			t := ListHead(_scrutinee)
			_ = t // suppress unused
			rest := ListTail(_scrutinee)
			_ = rest // suppress unused
			return func() interface{} {
				var x interface{} = ModInt(idx, width)
				_ = x // suppress unused
				var y interface{} = DivInt(idx, width)
				_ = y // suppress unused
				var cmd interface{} = func() interface{} {
					var tmp7 interface{} = MulInt(x, int64(8))
					_ = tmp7 // suppress unused
					return func() interface{} {
						var tmp8 interface{} = IntToFloat(tmp7)
						_ = tmp8 // suppress unused
						return func() interface{} {
							var tmp9 interface{} = MulInt(y, int64(8))
							_ = tmp9 // suppress unused
							return func() interface{} {
								var tmp10 interface{} = IntToFloat(tmp9)
								_ = tmp10 // suppress unused
								return func() interface{} {
									var tmp11 interface{} = FieldGet(t, "biome")
									_ = tmp11 // suppress unused
									return NewDrawCmdRect(tmp8.(float64), tmp10.(float64), float64(8), float64(8), tmp11.(int64), int64(0))
								}()
							}()
						}()
					}()
				}()
				_ = cmd // suppress unused
				var tmp5 interface{} = AddInt(idx, int64(1))
				_ = tmp5 // suppress unused
				var tmp6 interface{} = tilesToDraw_impl(rest, width, tmp5)
				_ = tmp6 // suppress unused
				return Cons(cmd, tmp6)
			}()
		} else {
			panic("non-exhaustive match")
		}
	}()
}

func tilesToDraw(tiles []*Tile, width int64, idx int64) []*DrawCmd {
	return ConvertToDrawCmdSlice(tilesToDraw_impl(tiles, width, idx))
}

func npcsToDraw_impl(npcs interface{}) interface{} {
	return func() interface{} {
		_scrutinee := npcs
		_ = _scrutinee // suppress unused
		if ListLen(_scrutinee) == 0 {
			return []interface{}{}
		} else if ListLen(_scrutinee) >= 1 {
			npc := ListHead(_scrutinee)
			_ = npc // suppress unused
			rest := ListTail(_scrutinee)
			_ = rest // suppress unused
			return func() interface{} {
				var cmd interface{} = func() interface{} {
					var tmp13 interface{} = FieldGet(npc, "pos")
					_ = tmp13 // suppress unused
					return func() interface{} {
						var tmp14 interface{} = FieldGet(tmp13, "x")
						_ = tmp14 // suppress unused
						return func() interface{} {
							var tmp15 interface{} = MulInt(tmp14, int64(8))
							_ = tmp15 // suppress unused
							return func() interface{} {
								var tmp16 interface{} = IntToFloat(tmp15)
								_ = tmp16 // suppress unused
								return func() interface{} {
									var tmp17 interface{} = FieldGet(npc, "pos")
									_ = tmp17 // suppress unused
									return func() interface{} {
										var tmp18 interface{} = FieldGet(tmp17, "y")
										_ = tmp18 // suppress unused
										return func() interface{} {
											var tmp19 interface{} = MulInt(tmp18, int64(8))
											_ = tmp19 // suppress unused
											return func() interface{} {
												var tmp20 interface{} = IntToFloat(tmp19)
												_ = tmp20 // suppress unused
												return func() interface{} {
													var tmp21 interface{} = FieldGet(npc, "id")
													_ = tmp21 // suppress unused
													return func() interface{} {
														var tmp22 interface{} = AddInt(int64(10), tmp21)
														_ = tmp22 // suppress unused
														return NewDrawCmdRect(tmp16.(float64), tmp20.(float64), float64(8), float64(8), tmp22.(int64), int64(2))
													}()
												}()
											}()
										}()
									}()
								}()
							}()
						}()
					}()
				}()
				_ = cmd // suppress unused
				var tmp12 interface{} = npcsToDraw_impl(rest)
				_ = tmp12 // suppress unused
				return Cons(cmd, tmp12)
			}()
		} else {
			panic("non-exhaustive match")
		}
	}()
}

func npcsToDraw(npcs []*NPC) []*DrawCmd {
	return ConvertToDrawCmdSlice(npcsToDraw_impl(npcs))
}

func selectionToDraw_impl(sel interface{}) interface{} {
	return func() interface{} {
		_scrutinee := sel
		_ = _scrutinee // suppress unused
		_adt := _scrutinee.(*Selection)
		switch _adt.Kind {
		default:
			selectionNone := _adt
			_ = selectionNone // suppress unused
			return []interface{}{}
		case SelectionKindTile:
			x := _adt.SelectionTile.Value0
			_ = x // suppress unused
			y := _adt.SelectionTile.Value1
			_ = y // suppress unused
			return func() interface{} {
				var tmp23 interface{} = MulInt(x, int64(8))
				_ = tmp23 // suppress unused
				var tmp24 interface{} = IntToFloat(tmp23)
				_ = tmp24 // suppress unused
				var tmp25 interface{} = MulInt(y, int64(8))
				_ = tmp25 // suppress unused
				var tmp26 interface{} = IntToFloat(tmp25)
				_ = tmp26 // suppress unused
				var tmp27 interface{} = NewDrawCmdRect(tmp24.(float64), tmp26.(float64), float64(8), float64(8), int64(4), int64(3))
				_ = tmp27 // suppress unused
				return []interface{}{tmp27}
			}()
		}
	}()
}

func selectionToDraw(sel *Selection) []*DrawCmd {
	return ConvertToDrawCmdSlice(selectionToDraw_impl(sel))
}

func concatDrawCmds_impl(a interface{}, b interface{}) interface{} {
	return func() interface{} {
		_scrutinee := a
		_ = _scrutinee // suppress unused
		if ListLen(_scrutinee) == 0 {
			return b
		} else if ListLen(_scrutinee) >= 1 {
			x := ListHead(_scrutinee)
			_ = x // suppress unused
			rest := ListTail(_scrutinee)
			_ = rest // suppress unused
			return func() interface{} {
				var tmp28 interface{} = concatDrawCmds_impl(rest, b)
				_ = tmp28 // suppress unused
				return Cons(x, tmp28)
			}()
		} else {
			panic("non-exhaustive match")
		}
	}()
}

func concatDrawCmds(a []*DrawCmd, b []*DrawCmd) []*DrawCmd {
	return ConvertToDrawCmdSlice(concatDrawCmds_impl(a, b))
}

func starToScreen_impl(pos interface{}) interface{} {
	var centerX interface{} = float64(320)
	var centerY interface{} = float64(240)
	var scale interface{} = float64(20)
	var tmp29 interface{} = FieldGet(pos, "x")
	var tmp30 interface{} = MulFloat(tmp29, scale)
	var tmp31 interface{} = AddFloat(centerX, tmp30)
	var tmp32 interface{} = FieldGet(pos, "y")
	var tmp33 interface{} = MulFloat(tmp32, scale)
	var tmp34 interface{} = AddFloat(centerY, tmp33)
	return []interface{}{tmp31, tmp34}
}

func starToScreen(pos *Vec3) interface{} {
	return starToScreen_impl(pos)
}

func starRadius_impl(luminosity interface{}) interface{} {
	var logLum interface{} = func() interface{} {
		var tmp35 interface{} = GtFloat(luminosity, float64(0))
		_ = tmp35 // suppress unused
		return func() interface{} {
			if tmp35.(bool) {
				return func() interface{} {
					if GtFloat(luminosity, float64(100)).(bool) {
						return float64(4)
					} else if GtFloat(luminosity, float64(1)).(bool) {
						return func() interface{} {
							var tmp38 interface{} = DivFloat(luminosity, float64(50))
							_ = tmp38 // suppress unused
							return AddFloat(float64(3), tmp38)
						}()
					} else {
						return func() interface{} {
							var tmp39 interface{} = MulFloat(luminosity, float64(2))
							_ = tmp39 // suppress unused
							return AddFloat(float64(2), tmp39)
						}()
					}
				}()
			} else {
				return float64(2)
			}
		}()
	}()
	return logLum
}

func starRadius(luminosity float64) float64 {
	return starRadius_impl(luminosity).(float64)
}

func renderStar_impl(star interface{}) interface{} {
	var pos interface{} = func() interface{} {
		var tmp42 interface{} = FieldGet(star, "pos")
		_ = tmp42 // suppress unused
		return starToScreen_impl(tmp42)
	}()
	var radius interface{} = func() interface{} {
		var tmp41 interface{} = FieldGet(star, "luminosity")
		_ = tmp41 // suppress unused
		return starRadius_impl(tmp41)
	}()
	var color interface{} = func() interface{} {
		var tmp40 interface{} = FieldGet(star, "spectral")
		_ = tmp40 // suppress unused
		return spectralColor_impl(tmp40)
	}()
	return func() interface{} {
		_scrutinee := pos
		_ = _scrutinee // suppress unused
		if len(_scrutinee.([]interface{})) == 2 {
			sx := _scrutinee.([]interface{})[0]
			_ = sx // suppress unused
			sy := _scrutinee.([]interface{})[1]
			_ = sy // suppress unused
			return NewDrawCmdCircleRGBA(sx.(float64), sy.(float64), radius.(float64), color.(int64), true, int64(5))
		} else {
			panic("non-exhaustive match")
		}
	}()
}

func renderStar(star *Star) *DrawCmd {
	return renderStar_impl(star).(*DrawCmd)
}

func renderStars_impl(stars interface{}) interface{} {
	return func() interface{} {
		_scrutinee := stars
		_ = _scrutinee // suppress unused
		if ListLen(_scrutinee) == 0 {
			return []interface{}{}
		} else if ListLen(_scrutinee) >= 1 {
			s := ListHead(_scrutinee)
			_ = s // suppress unused
			rest := ListTail(_scrutinee)
			_ = rest // suppress unused
			return func() interface{} {
				var tmp43 interface{} = renderStar_impl(s)
				_ = tmp43 // suppress unused
				var tmp44 interface{} = renderStars_impl(rest)
				_ = tmp44 // suppress unused
				return Cons(tmp43, tmp44)
			}()
		} else {
			panic("non-exhaustive match")
		}
	}()
}

func renderStars(stars []*Star) []*DrawCmd {
	return ConvertToDrawCmdSlice(renderStars_impl(stars))
}

func renderGalaxyMap_impl(catalog interface{}) interface{} {
	var bg interface{} = NewDrawCmdRect(float64(0), float64(0), float64(640), float64(480), int64(1052688), int64(0))
	var title interface{} = NewDrawCmdText("Galaxy Map - Local Stars", float64(200), float64(20), int64(16), int64(16777215), int64(10))
	var solLabel interface{} = NewDrawCmdText("Sol", float64(325), float64(245), int64(12), int64(16777215), int64(10))
	var starCmds interface{} = func() interface{} {
		var tmp49 interface{} = FieldGet(catalog, "stars")
		_ = tmp49 // suppress unused
		return renderStars_impl(tmp49)
	}()
	var tmp45 interface{} = []interface{}{}
	var tmp46 interface{} = concatDrawCmds_impl(starCmds, tmp45)
	var tmp47 interface{} = Cons(solLabel, tmp46)
	var tmp48 interface{} = Cons(title, tmp47)
	return Cons(bg, tmp48)
}

func renderGalaxyMap(catalog *StarCatalog) []*DrawCmd {
	return ConvertToDrawCmdSlice(renderGalaxyMap_impl(catalog))
}

func processSelection_impl(input interface{}, world interface{}) interface{} {
	var tmp50 interface{} = FieldGet(input, "clickedThisFrame")
	return func() interface{} {
		if tmp50.(bool) {
			return func() interface{} {
				var tileX interface{} = func() interface{} {
					var tmp64 interface{} = FieldGet(input, "worldMouseX")
					_ = tmp64 // suppress unused
					return func() interface{} {
						var tmp65 interface{} = DivFloat(tmp64, float64(8))
						_ = tmp65 // suppress unused
						return FloatToInt(tmp65)
					}()
				}()
				_ = tileX // suppress unused
				var tileY interface{} = func() interface{} {
					var tmp62 interface{} = FieldGet(input, "worldMouseY")
					_ = tmp62 // suppress unused
					return func() interface{} {
						var tmp63 interface{} = DivFloat(tmp62, float64(8))
						_ = tmp63 // suppress unused
						return FloatToInt(tmp63)
					}()
				}()
				_ = tileY // suppress unused
				var tmp51 interface{} = GeInt(tileX, int64(0))
				_ = tmp51 // suppress unused
				var tmp52 interface{} = FieldGet(world, "planet")
				_ = tmp52 // suppress unused
				var tmp53 interface{} = FieldGet(tmp52, "width")
				_ = tmp53 // suppress unused
				var tmp54 interface{} = LtInt(tileX, tmp53)
				_ = tmp54 // suppress unused
				var tmp55 interface{} = func() interface{} {
					if tmp51.(bool) {
						return tmp54
					}
					return false
				}()
				_ = tmp55 // suppress unused
				var tmp56 interface{} = GeInt(tileY, int64(0))
				_ = tmp56 // suppress unused
				var tmp57 interface{} = func() interface{} {
					if tmp55.(bool) {
						return tmp56
					}
					return false
				}()
				_ = tmp57 // suppress unused
				var tmp58 interface{} = FieldGet(world, "planet")
				_ = tmp58 // suppress unused
				var tmp59 interface{} = FieldGet(tmp58, "height")
				_ = tmp59 // suppress unused
				var tmp60 interface{} = LtInt(tileY, tmp59)
				_ = tmp60 // suppress unused
				var tmp61 interface{} = func() interface{} {
					if tmp57.(bool) {
						return tmp60
					}
					return false
				}()
				_ = tmp61 // suppress unused
				return func() interface{} {
					if tmp61.(bool) {
						return NewSelectionTile(tileX.(int64), tileY.(int64))
					}
					return NewSelectionNone()
				}()
			}()
		}
		return FieldGet(world, "selection")
	}()
}

func processSelection(input *FrameInput, world *World) *Selection {
	return processSelection_impl(input, world).(*Selection)
}

func initWorld_impl(seed interface{}) interface{} {
	var w interface{} = int64(8)
	var h interface{} = int64(8)
	var tiles interface{} = func() interface{} {
		var tmp80 interface{} = MulInt(w, h)
		_ = tmp80 // suppress unused
		return generate_impl(tmp80, func(i interface{}) interface{} {
			return func() interface{} {
				var tmp81 interface{} = ModInt(i, int64(4))
				_ = tmp81 // suppress unused
				return &Tile{Biome: tmp81.(int64)}
			}()
		})
	}()
	var patrolPath interface{} = []interface{}{NewDirectionEast(), NewDirectionEast(), NewDirectionSouth(), NewDirectionSouth(), NewDirectionWest(), NewDirectionWest(), NewDirectionNorth(), NewDirectionNorth()}
	var testNpcs interface{} = func() interface{} {
		var tmp69 interface{} = &Coord{X: int64(2), Y: int64(2)}
		_ = tmp69 // suppress unused
		var tmp70 interface{} = NewMovementPatternPatternRandomWalk(int64(30))
		_ = tmp70 // suppress unused
		var tmp71 interface{} = &NPC{Id: int64(1), Pos: tmp69.(*Coord), Pattern: tmp70.(*MovementPattern), MoveCounter: int64(30), PatrolIndex: int64(0)}
		_ = tmp71 // suppress unused
		var tmp72 interface{} = &Coord{X: int64(5), Y: int64(3)}
		_ = tmp72 // suppress unused
		var tmp73 interface{} = NewMovementPatternPatternRandomWalk(int64(45))
		_ = tmp73 // suppress unused
		var tmp74 interface{} = &NPC{Id: int64(2), Pos: tmp72.(*Coord), Pattern: tmp73.(*MovementPattern), MoveCounter: int64(45), PatrolIndex: int64(0)}
		_ = tmp74 // suppress unused
		var tmp75 interface{} = &Coord{X: int64(4), Y: int64(4)}
		_ = tmp75 // suppress unused
		var tmp76 interface{} = &NPC{Id: int64(3), Pos: tmp75.(*Coord), Pattern: NewMovementPatternPatternStatic(), MoveCounter: int64(0), PatrolIndex: int64(0)}
		_ = tmp76 // suppress unused
		var tmp77 interface{} = &Coord{X: int64(1), Y: int64(1)}
		_ = tmp77 // suppress unused
		var tmp78 interface{} = NewMovementPatternPatternPatrol(ConvertToDirectionSlice(patrolPath))
		_ = tmp78 // suppress unused
		var tmp79 interface{} = &NPC{Id: int64(4), Pos: tmp77.(*Coord), Pattern: tmp78.(*MovementPattern), MoveCounter: int64(0), PatrolIndex: int64(0)}
		_ = tmp79 // suppress unused
		return []interface{}{tmp71, tmp74, tmp76, tmp79}
	}()
	var catalog interface{} = initLocalCatalog_impl(struct{}{})
	var solSystem interface{} = initSolSystem_impl(struct{}{})
	var tmp66 interface{} = &PlanetState{Width: w.(int64), Height: h.(int64), Tiles: ConvertToTileSlice(tiles)}
	var tmp67 interface{} = initBridge_impl(struct{}{})
	var tmp68 interface{} = initShipLevels_impl(struct{}{})
	return &World{Tick: int64(0), Planet: tmp66.(*PlanetState), Npcs: ConvertToNPCSlice(testNpcs), Selection: NewSelectionNone(), Bridge: tmp67.(*BridgeState), ViewMode: NewViewModeViewBridge(), StarCatalog: catalog.(*StarCatalog), CurrentSystem: solSystem.(*StarSystem), ShipLevels: tmp68.(*ShipLevels)}
}

func InitWorld(seed int64) *World {
	return initWorld_impl(seed).(*World)
}

func renderForView_impl(world interface{}) interface{} {
	var tmp82 interface{} = FieldGet(world, "viewMode")
	return func() interface{} {
		_scrutinee := tmp82
		_ = _scrutinee // suppress unused
		switch _scrutinee {
		default:
			return func() interface{} {
				var bridgeCmds interface{} = func() interface{} {
					var tmp84 interface{} = FieldGet(world, "bridge")
					_ = tmp84 // suppress unused
					return renderBridge_impl(tmp84)
				}()
				_ = bridgeCmds // suppress unused
				var planetCmds interface{} = func() interface{} {
					var tmp83 interface{} = FieldGet(world, "currentSystem")
					_ = tmp83 // suppress unused
					return renderSolarSystem_impl(tmp83)
				}()
				_ = planetCmds // suppress unused
				return concatDrawCmds_impl(bridgeCmds, planetCmds)
			}()
		}
	}()
}

func renderForView(world *World) []*DrawCmd {
	return ConvertToDrawCmdSlice(renderForView_impl(world))
}

func updateBridgeView_impl(world interface{}, newTick interface{}) interface{} {
	var updatedBridge interface{} = func() interface{} {
		var tmp94 interface{} = FieldGet(world, "bridge")
		_ = tmp94 // suppress unused
		return stepBridge_impl(tmp94, newTick)
	}()
	var updatedSystem interface{} = func() interface{} {
		var tmp93 interface{} = FieldGet(world, "currentSystem")
		_ = tmp93 // suppress unused
		return stepSystem_impl(tmp93, float64(0.001))
	}()
	return RecordUpdate(world, map[string]interface{}{"tick": newTick, "bridge": updatedBridge, "currentSystem": updatedSystem})
}

func updateBridgeView(world *World, newTick int64) *World {
	return updateBridgeView_impl(world, newTick).(*World)
}

func updatePlanetView_impl(world interface{}, input interface{}, newTick interface{}) interface{} {
	var newSelection interface{} = processSelection_impl(input, world)
	var updatedNpcs interface{} = func() interface{} {
		var tmp95 interface{} = FieldGet(world, "npcs")
		_ = tmp95 // suppress unused
		var tmp96 interface{} = FieldGet(world, "planet")
		_ = tmp96 // suppress unused
		var tmp97 interface{} = FieldGet(tmp96, "width")
		_ = tmp97 // suppress unused
		var tmp98 interface{} = FieldGet(world, "planet")
		_ = tmp98 // suppress unused
		var tmp99 interface{} = FieldGet(tmp98, "height")
		_ = tmp99 // suppress unused
		return updateAllNPCs_impl(tmp95, tmp97, tmp99)
	}()
	return RecordUpdate(world, map[string]interface{}{"tick": newTick, "npcs": updatedNpcs, "selection": newSelection})
}

func updatePlanetView(world *World, input *FrameInput, newTick int64) *World {
	return updatePlanetView_impl(world, input, newTick).(*World)
}

func updateGalaxyView_impl(world interface{}, newTick interface{}) interface{} {
	return RecordUpdate(world, map[string]interface{}{"tick": newTick})
}

func updateGalaxyView(world *World, newTick int64) *World {
	return updateGalaxyView_impl(world, newTick).(*World)
}

func step_impl(world interface{}, input interface{}) interface{} {
	var newTick interface{} = func() interface{} {
		var tmp105 interface{} = FieldGet(world, "tick")
		_ = tmp105 // suppress unused
		return AddInt(tmp105, int64(1))
	}()
	var newWorld interface{} = func() interface{} {
		var tmp104 interface{} = FieldGet(world, "viewMode")
		_ = tmp104 // suppress unused
		return func() interface{} {
			_scrutinee := tmp104
			_ = _scrutinee // suppress unused
			switch _scrutinee {
			default:
				return updateBridgeView_impl(world, newTick)
			}
		}()
	}()
	var drawCmds interface{} = renderForView_impl(newWorld)
	var cam interface{} = &Camera{X: float64(0), Y: float64(0), Zoom: float64(1)}
	var srCtx interface{} = &SRContext{Enabled: false, Velocity: float64(0), Gamma: float64(1), ViewAngle: float64(0)}
	var grCtx interface{} = &GRContext{Enabled: false, CenterX: float64(0.5), CenterY: float64(0.5), Phi: float64(0), Rs: float64(0), ObjectType: ""}
	var relCtx interface{} = &RelativityContext{Sr: srCtx.(*SRContext), Gr: grCtx.(*GRContext)}
	var ambientSettings interface{} = func() interface{} {
		var tmp103 interface{} = &RGBColor{R: float64(1), G: float64(1), B: float64(1)}
		_ = tmp103 // suppress unused
		return &AmbientSettings{Energy: float64(1), Color: tmp103.(*RGBColor)}
	}()
	var lightingCtx interface{} = func() interface{} {
		var tmp102 interface{} = []interface{}{}
		_ = tmp102 // suppress unused
		return &LightingContext{Enabled: false, Ambient: ambientSettings.(*AmbientSettings), Lights: ConvertToLightSourceSlice(tmp102), LightMultiplier: float64(1)}
	}()
	var output interface{} = func() interface{} {
		var tmp100 interface{} = []interface{}{}
		_ = tmp100 // suppress unused
		var tmp101 interface{} = []interface{}{}
		_ = tmp101 // suppress unused
		return &FrameOutput{Draw: ConvertToDrawCmdSlice(drawCmds), Sounds: ConvertToInt64Slice(tmp100), Debug: ConvertToStringSlice(tmp101), Camera: cam.(*Camera), Relativity: relCtx.(*RelativityContext), Lighting: lightingCtx.(*LightingContext)}
	}()
	return []interface{}{newWorld, output}
}

func Step(world *World, input *FrameInput) interface{} {
	return step_impl(world, input)
}
