// Code generated by ailang. DO NOT EDIT.
package sim_gen

func step__generate_impl(n interface{}, f interface{}) interface{} {
	return func() interface{} {
		_scrutinee := n
		_ = _scrutinee // suppress unused
		switch _scrutinee {
		case int64(0):
			return []interface{}{}
		default:
			return func() interface{} {
				var tmp1 interface{} = dict_Num_Int.Sub(n, int64(1))
				_ = tmp1 // suppress unused
				var tmp2 interface{} = CallFunc(f, tmp1)
				_ = tmp2 // suppress unused
				var tmp3 interface{} = dict_Num_Int.Sub(n, int64(1))
				_ = tmp3 // suppress unused
				var tmp4 interface{} = step__generate_impl(tmp3, f)
				_ = tmp4 // suppress unused
				return Cons(tmp2, tmp4)
			}()
		}
	}()
}

func step__generate(n int64, f interface{}) []Tile {
	return step__generate_impl(n, f).([]Tile)
}

func step__tilesToDraw_impl(tiles interface{}, width interface{}, idx interface{}) interface{} {
	return func() interface{} {
		_scrutinee := tiles
		_ = _scrutinee // suppress unused
		if ListLen(_scrutinee) == 0 {
			return []interface{}{}
		} else if ListLen(_scrutinee) >= 1 {
			t := ListHead(_scrutinee)
			_ = t // suppress unused
			rest := ListTail(_scrutinee)
			_ = rest // suppress unused
			return func() interface{} {
				var x interface{} = ModInt(idx, width)
				_ = x // suppress unused
				var y interface{} = dict_Num_Int.Div(idx, width)
				_ = y // suppress unused
				var cmd interface{} = func() interface{} {
					var tmp7 interface{} = dict_Num_Int.Mul(x, int64(8))
					_ = tmp7 // suppress unused
					return func() interface{} {
						var tmp8 interface{} = IntToFloat(tmp7)
						_ = tmp8 // suppress unused
						return func() interface{} {
							var tmp9 interface{} = dict_Num_Int.Mul(y, int64(8))
							_ = tmp9 // suppress unused
							return func() interface{} {
								var tmp10 interface{} = IntToFloat(tmp9)
								_ = tmp10 // suppress unused
								return func() interface{} {
									var tmp11 interface{} = FieldGet(t, "biome")
									_ = tmp11 // suppress unused
									return NewDrawCmdRect(tmp8.(float64), tmp10.(float64), float64(8), float64(8), tmp11.(int64), int64(0))
								}()
							}()
						}()
					}()
				}()
				_ = cmd // suppress unused
				var tmp5 interface{} = dict_Num_Int.Add(idx, int64(1))
				_ = tmp5 // suppress unused
				var tmp6 interface{} = step__tilesToDraw_impl(rest, width, tmp5)
				_ = tmp6 // suppress unused
				return Cons(cmd, tmp6)
			}()
		} else {
			panic("non-exhaustive match")
		}
	}()
}

func step__tilesToDraw(tiles []Tile, width int64, idx int64) []*DrawCmd {
	return ConvertToDrawCmdSlice(step__tilesToDraw_impl(tiles, width, idx))
}

func step__npcsToDraw_impl(npcs interface{}) interface{} {
	return func() interface{} {
		_scrutinee := npcs
		_ = _scrutinee // suppress unused
		if ListLen(_scrutinee) == 0 {
			return []interface{}{}
		} else if ListLen(_scrutinee) >= 1 {
			npc := ListHead(_scrutinee)
			_ = npc // suppress unused
			rest := ListTail(_scrutinee)
			_ = rest // suppress unused
			return func() interface{} {
				var cmd interface{} = func() interface{} {
					var tmp13 interface{} = FieldGet(npc, "pos")
					_ = tmp13 // suppress unused
					return func() interface{} {
						var tmp14 interface{} = FieldGet(tmp13, "x")
						_ = tmp14 // suppress unused
						return func() interface{} {
							var tmp15 interface{} = dict_Num_Int.Mul(tmp14, int64(8))
							_ = tmp15 // suppress unused
							return func() interface{} {
								var tmp16 interface{} = IntToFloat(tmp15)
								_ = tmp16 // suppress unused
								return func() interface{} {
									var tmp17 interface{} = FieldGet(npc, "pos")
									_ = tmp17 // suppress unused
									return func() interface{} {
										var tmp18 interface{} = FieldGet(tmp17, "y")
										_ = tmp18 // suppress unused
										return func() interface{} {
											var tmp19 interface{} = dict_Num_Int.Mul(tmp18, int64(8))
											_ = tmp19 // suppress unused
											return func() interface{} {
												var tmp20 interface{} = IntToFloat(tmp19)
												_ = tmp20 // suppress unused
												return func() interface{} {
													var tmp21 interface{} = FieldGet(npc, "id")
													_ = tmp21 // suppress unused
													return func() interface{} {
														var tmp22 interface{} = dict_Num_Int.Add(int64(10), tmp21)
														_ = tmp22 // suppress unused
														return NewDrawCmdRect(tmp16.(float64), tmp20.(float64), float64(8), float64(8), tmp22.(int64), int64(2))
													}()
												}()
											}()
										}()
									}()
								}()
							}()
						}()
					}()
				}()
				_ = cmd // suppress unused
				var tmp12 interface{} = step__npcsToDraw_impl(rest)
				_ = tmp12 // suppress unused
				return Cons(cmd, tmp12)
			}()
		} else {
			panic("non-exhaustive match")
		}
	}()
}

func step__npcsToDraw(npcs []*NPC) []*DrawCmd {
	return ConvertToDrawCmdSlice(step__npcsToDraw_impl(npcs))
}

func step__selectionToDraw_impl(sel interface{}) interface{} {
	return func() interface{} {
		_scrutinee := sel
		_ = _scrutinee // suppress unused
		_adt := _scrutinee.(*Selection)
		switch _adt.Kind {
		case SelectionKindNone:
			return []interface{}{}
		case SelectionKindTile:
			x := _adt.SelectionTile.Value0
			_ = x // suppress unused
			y := _adt.SelectionTile.Value1
			_ = y // suppress unused
			return func() interface{} {
				var tmp23 interface{} = dict_Num_Int.Mul(x, int64(8))
				_ = tmp23 // suppress unused
				var tmp24 interface{} = IntToFloat(tmp23)
				_ = tmp24 // suppress unused
				var tmp25 interface{} = dict_Num_Int.Mul(y, int64(8))
				_ = tmp25 // suppress unused
				var tmp26 interface{} = IntToFloat(tmp25)
				_ = tmp26 // suppress unused
				var tmp27 interface{} = NewDrawCmdRect(tmp24.(float64), tmp26.(float64), float64(8), float64(8), int64(4), int64(3))
				_ = tmp27 // suppress unused
				return []interface{}{tmp27}
			}()
		default:
			panic("non-exhaustive match")
		}
	}()
}

func step__selectionToDraw(sel *Selection) []*DrawCmd {
	return ConvertToDrawCmdSlice(step__selectionToDraw_impl(sel))
}

func step__concatDrawCmds_impl(a interface{}, b interface{}) interface{} {
	return func() interface{} {
		_scrutinee := a
		_ = _scrutinee // suppress unused
		if ListLen(_scrutinee) == 0 {
			return b
		} else if ListLen(_scrutinee) >= 1 {
			x := ListHead(_scrutinee)
			_ = x // suppress unused
			rest := ListTail(_scrutinee)
			_ = rest // suppress unused
			return func() interface{} {
				var tmp28 interface{} = step__concatDrawCmds_impl(rest, b)
				_ = tmp28 // suppress unused
				return Cons(x, tmp28)
			}()
		} else {
			panic("non-exhaustive match")
		}
	}()
}

func step__concatDrawCmds(a []*DrawCmd, b []*DrawCmd) []*DrawCmd {
	return ConvertToDrawCmdSlice(step__concatDrawCmds_impl(a, b))
}

func step__starToScreen_impl(pos interface{}) interface{} {
	var centerX interface{} = float64(320)
	var centerY interface{} = float64(240)
	var scale interface{} = float64(20)
	var tmp29 interface{} = FieldGet(pos, "x")
	var tmp30 interface{} = dict_Fractional_Float.Mul(tmp29, scale)
	var tmp31 interface{} = dict_Fractional_Float.Add(centerX, tmp30)
	var tmp32 interface{} = FieldGet(pos, "y")
	var tmp33 interface{} = dict_Fractional_Float.Mul(tmp32, scale)
	var tmp34 interface{} = dict_Fractional_Float.Add(centerY, tmp33)
	return []interface{}{tmp31, tmp34}
}

func step__starToScreen(pos Vec3) interface{} {
	return step__starToScreen_impl(pos)
}

func step__starRadius_impl(luminosity interface{}) interface{} {
	var logLum interface{} = func() interface{} {
		var tmp35 interface{} = dict_Ord_Float.Gt(luminosity, float64(0))
		_ = tmp35 // suppress unused
		return func() interface{} {
			if tmp35.(bool) {
				return func() interface{} {
					if dict_Ord_Float.Gt(luminosity, float64(100)).(bool) {
						return float64(4)
					} else if dict_Ord_Float.Gt(luminosity, float64(1)).(bool) {
						return func() interface{} {
							var tmp38 interface{} = dict_Fractional_Float.Div(luminosity, float64(50))
							_ = tmp38 // suppress unused
							return dict_Fractional_Float.Add(float64(3), tmp38)
						}()
					} else {
						return func() interface{} {
							var tmp39 interface{} = dict_Fractional_Float.Mul(luminosity, float64(2))
							_ = tmp39 // suppress unused
							return dict_Fractional_Float.Add(float64(2), tmp39)
						}()
					}
				}()
			} else {
				return float64(2)
			}
		}()
	}()
	return logLum
}

func step__starRadius(luminosity float64) float64 {
	return step__starRadius_impl(luminosity).(float64)
}

func step__renderStar_impl(star interface{}) interface{} {
	var pos interface{} = func() interface{} {
		var tmp42 interface{} = FieldGet(star, "pos")
		_ = tmp42 // suppress unused
		return step__starToScreen_impl(tmp42)
	}()
	var radius interface{} = func() interface{} {
		var tmp41 interface{} = FieldGet(star, "luminosity")
		_ = tmp41 // suppress unused
		return step__starRadius_impl(tmp41)
	}()
	var color interface{} = func() interface{} {
		var tmp40 interface{} = FieldGet(star, "spectral")
		_ = tmp40 // suppress unused
		return spectralColor_impl(tmp40)
	}()
	return func() interface{} {
		_scrutinee := pos
		_ = _scrutinee // suppress unused
		if len(_scrutinee.([]interface{})) == 2 {
			sx := _scrutinee.([]interface{})[0]
			_ = sx // suppress unused
			sy := _scrutinee.([]interface{})[1]
			_ = sy // suppress unused
			return NewDrawCmdCircleRGBA(sx.(float64), sy.(float64), radius.(float64), color.(int64), true, int64(5))
		} else {
			panic("non-exhaustive match")
		}
	}()
}

func step__renderStar(star *Star) *DrawCmd {
	return step__renderStar_impl(star).(*DrawCmd)
}

func step__renderStars_impl(stars interface{}) interface{} {
	return func() interface{} {
		_scrutinee := stars
		_ = _scrutinee // suppress unused
		if ListLen(_scrutinee) == 0 {
			return []interface{}{}
		} else if ListLen(_scrutinee) >= 1 {
			s := ListHead(_scrutinee)
			_ = s // suppress unused
			rest := ListTail(_scrutinee)
			_ = rest // suppress unused
			return func() interface{} {
				var tmp43 interface{} = step__renderStar_impl(s)
				_ = tmp43 // suppress unused
				var tmp44 interface{} = step__renderStars_impl(rest)
				_ = tmp44 // suppress unused
				return Cons(tmp43, tmp44)
			}()
		} else {
			panic("non-exhaustive match")
		}
	}()
}

func step__renderStars(stars []*Star) []*DrawCmd {
	return ConvertToDrawCmdSlice(step__renderStars_impl(stars))
}

func step__renderGalaxyMap_impl(catalog interface{}) interface{} {
	var bg interface{} = NewDrawCmdRect(float64(0), float64(0), float64(640), float64(480), int64(1052688), int64(0))
	var title interface{} = NewDrawCmdText("Galaxy Map - Local Stars", float64(200), float64(20), int64(16), int64(16777215), int64(10))
	var solLabel interface{} = NewDrawCmdText("Sol", float64(325), float64(245), int64(12), int64(16777215), int64(10))
	var starCmds interface{} = func() interface{} {
		var tmp49 interface{} = FieldGet(catalog, "stars")
		_ = tmp49 // suppress unused
		return step__renderStars_impl(tmp49)
	}()
	var tmp45 interface{} = []interface{}{}
	var tmp46 interface{} = step__concatDrawCmds_impl(starCmds, tmp45)
	var tmp47 interface{} = Cons(solLabel, tmp46)
	var tmp48 interface{} = Cons(title, tmp47)
	return Cons(bg, tmp48)
}

func step__renderGalaxyMap(catalog *StarCatalog) []*DrawCmd {
	return ConvertToDrawCmdSlice(step__renderGalaxyMap_impl(catalog))
}

func step__processSelection_impl(input interface{}, world interface{}) interface{} {
	var tmp50 interface{} = FieldGet(input, "mouseEvents")
	var tmp51 interface{} = isLeftClick_impl(tmp50)
	return func() interface{} {
		if tmp51.(bool) {
			return func() interface{} {
				var tileX interface{} = func() interface{} {
					var tmp65 interface{} = FieldGet(input, "worldMouseX")
					_ = tmp65 // suppress unused
					return func() interface{} {
						var tmp66 interface{} = dict_Fractional_Float.Div(tmp65, float64(8))
						_ = tmp66 // suppress unused
						return FloatToInt(tmp66)
					}()
				}()
				_ = tileX // suppress unused
				var tileY interface{} = func() interface{} {
					var tmp63 interface{} = FieldGet(input, "worldMouseY")
					_ = tmp63 // suppress unused
					return func() interface{} {
						var tmp64 interface{} = dict_Fractional_Float.Div(tmp63, float64(8))
						_ = tmp64 // suppress unused
						return FloatToInt(tmp64)
					}()
				}()
				_ = tileY // suppress unused
				var tmp52 interface{} = dict_Ord_Int.Gte(tileX, int64(0))
				_ = tmp52 // suppress unused
				var tmp53 interface{} = FieldGet(world, "planet")
				_ = tmp53 // suppress unused
				var tmp54 interface{} = FieldGet(tmp53, "width")
				_ = tmp54 // suppress unused
				var tmp55 interface{} = dict_Ord_Int.Lt(tileX, tmp54)
				_ = tmp55 // suppress unused
				var tmp56 interface{} = func() interface{} {
					if tmp52.(bool) {
						return tmp55
					}
					return false
				}()
				_ = tmp56 // suppress unused
				var tmp57 interface{} = dict_Ord_Int.Gte(tileY, int64(0))
				_ = tmp57 // suppress unused
				var tmp58 interface{} = func() interface{} {
					if tmp56.(bool) {
						return tmp57
					}
					return false
				}()
				_ = tmp58 // suppress unused
				var tmp59 interface{} = FieldGet(world, "planet")
				_ = tmp59 // suppress unused
				var tmp60 interface{} = FieldGet(tmp59, "height")
				_ = tmp60 // suppress unused
				var tmp61 interface{} = dict_Ord_Int.Lt(tileY, tmp60)
				_ = tmp61 // suppress unused
				var tmp62 interface{} = func() interface{} {
					if tmp58.(bool) {
						return tmp61
					}
					return false
				}()
				_ = tmp62 // suppress unused
				return func() interface{} {
					if tmp62.(bool) {
						return NewSelectionTile(tileX.(int64), tileY.(int64))
					}
					return NewSelectionNone()
				}()
			}()
		}
		return FieldGet(world, "selection")
	}()
}

func step__processSelection(input *FrameInput, world *World) *Selection {
	return step__processSelection_impl(input, world).(*Selection)
}

func initWorld_impl(seed interface{}) interface{} {
	var w interface{} = int64(8)
	var h interface{} = int64(8)
	var tiles interface{} = func() interface{} {
		var tmp82 interface{} = dict_Num_Int.Mul(w, h)
		_ = tmp82 // suppress unused
		return step__generate_impl(tmp82, func(i interface{}) interface{} {
			return func() interface{} {
				var tmp83 interface{} = ModInt(i, int64(4))
				_ = tmp83 // suppress unused
				return Tile{Biome: tmp83.(int64)}
			}()
		})
	}()
	var patrolPath interface{} = []interface{}{NewDirectionEast(), NewDirectionEast(), NewDirectionSouth(), NewDirectionSouth(), NewDirectionWest(), NewDirectionWest(), NewDirectionNorth(), NewDirectionNorth()}
	var testNpcs interface{} = func() interface{} {
		var tmp71 interface{} = Coord{X: int64(2), Y: int64(2)}
		_ = tmp71 // suppress unused
		var tmp72 interface{} = NewMovementPatternPatternRandomWalk(int64(30))
		_ = tmp72 // suppress unused
		var tmp73 interface{} = &NPC{Id: int64(1), Pos: AsCoord(tmp71), Pattern: tmp72.(*MovementPattern), MoveCounter: int64(30), PatrolIndex: int64(0)}
		_ = tmp73 // suppress unused
		var tmp74 interface{} = Coord{X: int64(5), Y: int64(3)}
		_ = tmp74 // suppress unused
		var tmp75 interface{} = NewMovementPatternPatternRandomWalk(int64(45))
		_ = tmp75 // suppress unused
		var tmp76 interface{} = &NPC{Id: int64(2), Pos: AsCoord(tmp74), Pattern: tmp75.(*MovementPattern), MoveCounter: int64(45), PatrolIndex: int64(0)}
		_ = tmp76 // suppress unused
		var tmp77 interface{} = Coord{X: int64(4), Y: int64(4)}
		_ = tmp77 // suppress unused
		var tmp78 interface{} = &NPC{Id: int64(3), Pos: AsCoord(tmp77), Pattern: NewMovementPatternPatternStatic(), MoveCounter: int64(0), PatrolIndex: int64(0)}
		_ = tmp78 // suppress unused
		var tmp79 interface{} = Coord{X: int64(1), Y: int64(1)}
		_ = tmp79 // suppress unused
		var tmp80 interface{} = NewMovementPatternPatternPatrol(ConvertToDirectionSlice(patrolPath))
		_ = tmp80 // suppress unused
		var tmp81 interface{} = &NPC{Id: int64(4), Pos: AsCoord(tmp79), Pattern: tmp80.(*MovementPattern), MoveCounter: int64(0), PatrolIndex: int64(0)}
		_ = tmp81 // suppress unused
		return []interface{}{tmp73, tmp76, tmp78, tmp81}
	}()
	var catalog interface{} = initLocalCatalog_impl(struct{}{})
	var solSystem interface{} = initSolSystem_impl(struct{}{})
	var tmp67 interface{} = &PlanetState{Width: w.(int64), Height: h.(int64), Tiles: ConvertToTileSlice(tiles)}
	var tmp68 interface{} = initInterior_impl(struct{}{})
	var tmp69 interface{} = initShipLevels_impl(struct{}{})
	var tmp70 interface{} = initNavigation_impl(struct{}{})
	return &World{Tick: int64(0), Planet: tmp67.(*PlanetState), Npcs: ConvertToNPCSlice(testNpcs), Selection: NewSelectionNone(), Interior: tmp68.(*InteriorState), ViewMode: NewViewModeViewInterior(), StarCatalog: catalog.(*StarCatalog), CurrentSystem: solSystem.(*StarSystem), ShipLevels: tmp69.(*ShipLevels), ShipNavigation: tmp70.(*ShipNavigation)}
}

func InitWorld(seed int64) *World {
	return initWorld_impl(seed).(*World)
}

func step__renderForView_impl(world interface{}, input interface{}) interface{} {
	var tmp84 interface{} = FieldGet(world, "viewMode")
	return func() interface{} {
		_scrutinee := tmp84
		_ = _scrutinee // suppress unused
		_adt := _scrutinee.(*ViewMode)
		switch _adt.Kind {
		case ViewModeKindViewInterior:
			return func() interface{} {
				var tmp85 interface{} = FieldGet(world, "interior")
				_ = tmp85 // suppress unused
				var tmp86 interface{} = FieldGet(world, "shipNavigation")
				_ = tmp86 // suppress unused
				return renderInterior_impl(tmp85, tmp86)
			}()
		case ViewModeKindViewPlanet:
			return func() interface{} {
				var tileCmds interface{} = func() interface{} {
					var tmp88 interface{} = FieldGet(world, "planet")
					_ = tmp88 // suppress unused
					return func() interface{} {
						var tmp89 interface{} = FieldGet(tmp88, "tiles")
						_ = tmp89 // suppress unused
						return func() interface{} {
							var tmp90 interface{} = FieldGet(world, "planet")
							_ = tmp90 // suppress unused
							return func() interface{} {
								var tmp91 interface{} = FieldGet(tmp90, "width")
								_ = tmp91 // suppress unused
								return step__tilesToDraw_impl(tmp89, tmp91, int64(0))
							}()
						}()
					}()
				}()
				_ = tileCmds // suppress unused
				var selCmds interface{} = func() interface{} {
					var tmp87 interface{} = FieldGet(world, "selection")
					_ = tmp87 // suppress unused
					return step__selectionToDraw_impl(tmp87)
				}()
				_ = selCmds // suppress unused
				return step__concatDrawCmds_impl(tileCmds, selCmds)
			}()
		case ViewModeKindViewGalaxyMap:
			return func() interface{} {
				var tmp92 interface{} = FieldGet(world, "starCatalog")
				_ = tmp92 // suppress unused
				return step__renderGalaxyMap_impl(tmp92)
			}()
		default:
			panic("non-exhaustive match")
		}
	}()
}

func step__renderForView(world *World, input *FrameInput) []*DrawCmd {
	return ConvertToDrawCmdSlice(step__renderForView_impl(world, input))
}

func step__updateInteriorView_impl(world interface{}, input interface{}, newTick interface{}) interface{} {
	var updatedInterior interface{} = func() interface{} {
		var tmp99 interface{} = FieldGet(world, "interior")
		_ = tmp99 // suppress unused
		return stepInterior_impl(tmp99, input)
	}()
	var updatedSystem interface{} = func() interface{} {
		var tmp98 interface{} = FieldGet(world, "currentSystem")
		_ = tmp98 // suppress unused
		return stepSystem_impl(tmp98, float64(0.001))
	}()
	var newVelocity interface{} = func() interface{} {
		var tmp94 interface{} = isVPressed_impl(input)
		_ = tmp94 // suppress unused
		return func() interface{} {
			if tmp94.(bool) {
				return func() interface{} {
					var tmp95 interface{} = FieldGet(world, "shipNavigation")
					_ = tmp95 // suppress unused
					var tmp96 interface{} = FieldGet(tmp95, "velocity")
					_ = tmp96 // suppress unused
					return cycleVelocity_impl(tmp96)
				}()
			}
			return func() interface{} {
				var tmp97 interface{} = FieldGet(world, "shipNavigation")
				_ = tmp97 // suppress unused
				return FieldGet(tmp97, "velocity")
			}()
		}()
	}()
	var updatedNav interface{} = func() interface{} {
		var tmp93 interface{} = FieldGet(world, "shipNavigation")
		_ = tmp93 // suppress unused
		return RecordUpdate(tmp93, map[string]interface{}{"velocity": newVelocity})
	}()
	return RecordUpdate(world, map[string]interface{}{"tick": newTick, "interior": updatedInterior, "currentSystem": updatedSystem, "shipNavigation": updatedNav})
}

func step__updateInteriorView(world *World, input *FrameInput, newTick int64) *World {
	return step__updateInteriorView_impl(world, input, newTick).(*World)
}

func step__updatePlanetView_impl(world interface{}, input interface{}, newTick interface{}) interface{} {
	var newSelection interface{} = step__processSelection_impl(input, world)
	var updatedNpcs interface{} = func() interface{} {
		var tmp100 interface{} = FieldGet(world, "npcs")
		_ = tmp100 // suppress unused
		var tmp101 interface{} = FieldGet(world, "planet")
		_ = tmp101 // suppress unused
		var tmp102 interface{} = FieldGet(tmp101, "width")
		_ = tmp102 // suppress unused
		var tmp103 interface{} = FieldGet(world, "planet")
		_ = tmp103 // suppress unused
		var tmp104 interface{} = FieldGet(tmp103, "height")
		_ = tmp104 // suppress unused
		return updateAllNPCs_impl(tmp100, tmp102, tmp104)
	}()
	return RecordUpdate(world, map[string]interface{}{"tick": newTick, "npcs": updatedNpcs, "selection": newSelection})
}

func step__updatePlanetView(world *World, input *FrameInput, newTick int64) *World {
	return step__updatePlanetView_impl(world, input, newTick).(*World)
}

func step__updateGalaxyView_impl(world interface{}, newTick interface{}) interface{} {
	return RecordUpdate(world, map[string]interface{}{"tick": newTick})
}

func step__updateGalaxyView(world *World, newTick int64) *World {
	return step__updateGalaxyView_impl(world, newTick).(*World)
}

func step_impl(world interface{}, input interface{}) interface{} {
	var newTick interface{} = func() interface{} {
		var tmp115 interface{} = FieldGet(world, "tick")
		_ = tmp115 // suppress unused
		return dict_Num_Int.Add(tmp115, int64(1))
	}()
	var newWorld interface{} = func() interface{} {
		var tmp114 interface{} = FieldGet(world, "viewMode")
		_ = tmp114 // suppress unused
		return func() interface{} {
			_scrutinee := tmp114
			_ = _scrutinee // suppress unused
			_adt := _scrutinee.(*ViewMode)
			switch _adt.Kind {
			case ViewModeKindViewInterior:
				return step__updateInteriorView_impl(world, input, newTick)
			case ViewModeKindViewPlanet:
				return step__updatePlanetView_impl(world, input, newTick)
			case ViewModeKindViewGalaxyMap:
				return step__updateGalaxyView_impl(world, newTick)
			default:
				panic("non-exhaustive match")
			}
		}()
	}()
	var drawCmds interface{} = step__renderForView_impl(newWorld, input)
	var cam interface{} = Camera{X: float64(0), Y: float64(0), Zoom: float64(1)}
	var shipV interface{} = func() interface{} {
		var tmp113 interface{} = FieldGet(newWorld, "shipNavigation")
		_ = tmp113 // suppress unused
		return FieldGet(tmp113, "velocity")
	}()
	var lorentzFactor interface{} = func() interface{} {
		var tmp112 interface{} = FieldGet(newWorld, "shipNavigation")
		_ = tmp112 // suppress unused
		return timeDilationFactor_impl(tmp112)
	}()
	var srCtx interface{} = func() interface{} {
		var tmp111 interface{} = dict_Ord_Float.Gt(shipV, float64(0.01))
		_ = tmp111 // suppress unused
		return SRContext{Enabled: tmp111.(bool), Velocity: shipV.(float64), Gamma: lorentzFactor.(float64), ViewAngle: float64(0)}
	}()
	var grCtx interface{} = func() interface{} {
		var tmp109 interface{} = FieldGet(newWorld, "shipNavigation")
		_ = tmp109 // suppress unused
		var tmp110 interface{} = FieldGet(tmp109, "grPhi")
		_ = tmp110 // suppress unused
		return &GRContext{Enabled: false, CenterX: float64(0.5), CenterY: float64(0.5), Phi: tmp110.(float64), Rs: float64(0), ObjectType: ""}
	}()
	var relCtx interface{} = &RelativityContext{Sr: AsSRContext(srCtx), Gr: grCtx.(*GRContext)}
	var ambientSettings interface{} = func() interface{} {
		var tmp108 interface{} = RGBColor{R: float64(1), G: float64(1), B: float64(1)}
		_ = tmp108 // suppress unused
		return &AmbientSettings{Energy: float64(1), Color: AsRGBColor(tmp108)}
	}()
	var lightingCtx interface{} = func() interface{} {
		var tmp107 interface{} = []interface{}{}
		_ = tmp107 // suppress unused
		return &LightingContext{Enabled: false, Ambient: ambientSettings.(*AmbientSettings), Lights: ConvertToLightSourceSlice(tmp107), LightMultiplier: float64(1)}
	}()
	var lodConfig interface{} = &LODConfig{Enabled: true, TransitionTime: float64(0), Hysteresis: float64(0.4), Full3DPixels: float64(12), BillboardPixels: float64(6), CirclePixels: float64(3), PointPixels: float64(1), Max3DObjects: int64(30)}
	var output interface{} = func() interface{} {
		var tmp105 interface{} = []interface{}{}
		_ = tmp105 // suppress unused
		var tmp106 interface{} = []interface{}{}
		_ = tmp106 // suppress unused
		return &FrameOutput{Draw: ConvertToDrawCmdSlice(drawCmds), Sounds: ConvertToInt64Slice(tmp105), Debug: ConvertToStringSlice(tmp106), Camera: AsCamera(cam), Relativity: relCtx.(*RelativityContext), Lighting: lightingCtx.(*LightingContext), Lod: lodConfig.(*LODConfig)}
	}()
	return []interface{}{newWorld, output}
}

func Step(world *World, input *FrameInput) interface{} {
	return step_impl(world, input)
}
