// Code generated by ailang. DO NOT EDIT.
package sim_gen

import (
	"strconv"
)

func specPixelWidth_impl(spec interface{}) interface{} {
	var tmp1 interface{} = FieldGet(spec, "widthMeters")
	var tmp2 interface{} = FieldGet(spec, "pixelsPerMeter")
	var tmp3 interface{} = IntToFloat(tmp2)
	var tmp4 interface{} = dict_Fractional_Float.Mul(tmp1, tmp3)
	return FloatToInt(tmp4)
}

func SpecPixelWidth(spec *TextureSpec) int64 {
	return specPixelWidth_impl(spec).(int64)
}

func specPixelHeight_impl(spec interface{}) interface{} {
	var tmp5 interface{} = FieldGet(spec, "heightMeters")
	var tmp6 interface{} = FieldGet(spec, "pixelsPerMeter")
	var tmp7 interface{} = IntToFloat(tmp6)
	var tmp8 interface{} = dict_Fractional_Float.Mul(tmp5, tmp7)
	return FloatToInt(tmp8)
}

func SpecPixelHeight(spec *TextureSpec) int64 {
	return specPixelHeight_impl(spec).(int64)
}

func clampToPowerOf2_impl(n interface{}) interface{} {
	var tmp9 interface{} = dict_Ord_Int.Lte(n, int64(64))
	return func() interface{} {
		var tmp10 interface{} = dict_Ord_Int.Lte(n, int64(128))
		_ = tmp10 // suppress unused
		var tmp11 interface{} = dict_Ord_Int.Lte(n, int64(256))
		_ = tmp11 // suppress unused
		var tmp12 interface{} = dict_Ord_Int.Lte(n, int64(512))
		_ = tmp12 // suppress unused
		var tmp13 interface{} = dict_Ord_Int.Lte(n, int64(1024))
		_ = tmp13 // suppress unused
		if tmp9.(bool) {
			return int64(64)
		}
		if tmp10.(bool) {
			return int64(128)
		}
		if tmp11.(bool) {
			return int64(256)
		}
		if tmp12.(bool) {
			return int64(512)
		}
		if tmp13.(bool) {
			return int64(1024)
		}
		return int64(2048)
	}()
}

func ClampToPowerOf2(n int64) int64 {
	return clampToPowerOf2_impl(n).(int64)
}

func specPixelWidthClamped_impl(spec interface{}) interface{} {
	var tmp14 interface{} = specPixelWidth_impl(spec)
	return clampToPowerOf2_impl(tmp14)
}

func SpecPixelWidthClamped(spec *TextureSpec) int64 {
	return specPixelWidthClamped_impl(spec).(int64)
}

func specPixelHeightClamped_impl(spec interface{}) interface{} {
	var tmp15 interface{} = specPixelHeight_impl(spec)
	return clampToPowerOf2_impl(tmp15)
}

func SpecPixelHeightClamped(spec *TextureSpec) int64 {
	return specPixelHeightClamped_impl(spec).(int64)
}

func texture_spec__digitToChar_impl(d interface{}) interface{} {
	var tmp16 interface{} = dict_Eq_Int.Eq(d, int64(0))
	return func() interface{} {
		var tmp17 interface{} = dict_Eq_Int.Eq(d, int64(1))
		_ = tmp17 // suppress unused
		var tmp18 interface{} = dict_Eq_Int.Eq(d, int64(2))
		_ = tmp18 // suppress unused
		var tmp19 interface{} = dict_Eq_Int.Eq(d, int64(3))
		_ = tmp19 // suppress unused
		var tmp20 interface{} = dict_Eq_Int.Eq(d, int64(4))
		_ = tmp20 // suppress unused
		var tmp21 interface{} = dict_Eq_Int.Eq(d, int64(5))
		_ = tmp21 // suppress unused
		var tmp22 interface{} = dict_Eq_Int.Eq(d, int64(6))
		_ = tmp22 // suppress unused
		var tmp23 interface{} = dict_Eq_Int.Eq(d, int64(7))
		_ = tmp23 // suppress unused
		var tmp24 interface{} = dict_Eq_Int.Eq(d, int64(8))
		_ = tmp24 // suppress unused
		if tmp16.(bool) {
			return "0"
		}
		if tmp17.(bool) {
			return "1"
		}
		if tmp18.(bool) {
			return "2"
		}
		if tmp19.(bool) {
			return "3"
		}
		if tmp20.(bool) {
			return "4"
		}
		if tmp21.(bool) {
			return "5"
		}
		if tmp22.(bool) {
			return "6"
		}
		if tmp23.(bool) {
			return "7"
		}
		if tmp24.(bool) {
			return "8"
		}
		return "9"
	}()
}

func texture_spec__digitToChar(d int64) string {
	return texture_spec__digitToChar_impl(d).(string)
}

func texture_spec__positiveToStr_impl(n interface{}) interface{} {
	var tmp25 interface{} = dict_Eq_Int.Eq(n, int64(0))
	return func() interface{} {
		if tmp25.(bool) {
			return ""
		}
		return func() interface{} {
			var digit interface{} = ModInt(n, int64(10))
			_ = digit // suppress unused
			var rest interface{} = dict_Num_Int.Div(n, int64(10))
			_ = rest // suppress unused
			var ch interface{} = texture_spec__digitToChar_impl(digit)
			_ = ch // suppress unused
			var tmp26 interface{} = texture_spec__positiveToStr_impl(rest)
			_ = tmp26 // suppress unused
			return ConcatString(tmp26, ch)
		}()
	}()
}

func texture_spec__positiveToStr(n int64) string {
	return texture_spec__positiveToStr_impl(n).(string)
}

func texture_spec__intToStr_impl(n interface{}) interface{} {
	var tmp27 interface{} = dict_Ord_Int.Lt(n, int64(0))
	return func() interface{} {
		var tmp30 interface{} = dict_Eq_Int.Eq(n, int64(0))
		_ = tmp30 // suppress unused
		if tmp27.(bool) {
			return func() interface{} {
				var tmp28 interface{} = dict_Num_Int.Sub(int64(0), n)
				_ = tmp28 // suppress unused
				return func() interface{} {
					var tmp29 interface{} = texture_spec__positiveToStr_impl(tmp28)
					_ = tmp29 // suppress unused
					return ConcatString("-", tmp29)
				}()
			}()
		}
		if tmp30.(bool) {
			return "0"
		}
		return texture_spec__positiveToStr_impl(n)
	}()
}

func texture_spec__intToStr(n int64) string {
	return texture_spec__intToStr_impl(n).(string)
}

func specCacheKey_impl(spec interface{}) interface{} {
	var w interface{} = specPixelWidthClamped_impl(spec)
	var h interface{} = specPixelHeightClamped_impl(spec)
	var tmp31 interface{} = FieldGet(spec, "roomId")
	var tmp32 interface{} = ConcatString(tmp31, "_")
	var tmp33 interface{} = FieldGet(spec, "surfaceType")
	var tmp34 interface{} = ConcatString(tmp32, tmp33)
	var tmp35 interface{} = ConcatString(tmp34, "_")
	var tmp36 interface{} = strconv.Itoa(int(w.(int64)))
	var tmp37 interface{} = ConcatString(tmp35, tmp36)
	var tmp38 interface{} = ConcatString(tmp37, "x")
	var tmp39 interface{} = strconv.Itoa(int(h.(int64)))
	var tmp40 interface{} = ConcatString(tmp38, tmp39)
	var tmp41 interface{} = ConcatString(tmp40, "_")
	var tmp42 interface{} = FieldGet(spec, "theme")
	var tmp43 interface{} = FieldGet(tmp42, "name")
	var tmp44 interface{} = ConcatString(tmp41, tmp43)
	var tmp45 interface{} = ConcatString(tmp44, "_s")
	var tmp46 interface{} = FieldGet(spec, "seed")
	var tmp47 interface{} = strconv.Itoa(int(tmp46.(int64)))
	return ConcatString(tmp45, tmp47)
}

func SpecCacheKey(spec *TextureSpec) string {
	return specCacheKey_impl(spec).(string)
}

func texture_spec__getSurfaceStyle_impl(spec interface{}) interface{} {
	var tmp48 interface{} = FieldGet(spec, "surfaceType")
	var tmp49 interface{} = dict_Eq_String.Eq(tmp48, "floor")
	return func() interface{} {
		var tmp51 interface{} = FieldGet(spec, "surfaceType")
		_ = tmp51 // suppress unused
		var tmp52 interface{} = dict_Eq_String.Eq(tmp51, "ceiling")
		_ = tmp52 // suppress unused
		if tmp49.(bool) {
			return func() interface{} {
				var tmp50 interface{} = FieldGet(spec, "theme")
				_ = tmp50 // suppress unused
				return FieldGet(tmp50, "floorStyle")
			}()
		}
		if tmp52.(bool) {
			return func() interface{} {
				var tmp53 interface{} = FieldGet(spec, "theme")
				_ = tmp53 // suppress unused
				return FieldGet(tmp53, "ceilingStyle")
			}()
		}
		return func() interface{} {
			var tmp54 interface{} = FieldGet(spec, "theme")
			_ = tmp54 // suppress unused
			return FieldGet(tmp54, "wallStyle")
		}()
	}()
}

func texture_spec__getSurfaceStyle(spec *TextureSpec) string {
	return texture_spec__getSurfaceStyle_impl(spec).(string)
}

func buildPrompt_impl(spec interface{}) interface{} {
	var w interface{} = specPixelWidthClamped_impl(spec)
	var h interface{} = specPixelHeightClamped_impl(spec)
	var surfaceStyle interface{} = texture_spec__getSurfaceStyle_impl(spec)
	var tmp55 interface{} = strconv.Itoa(int(w.(int64)))
	var tmp56 interface{} = ConcatString("Create a ", tmp55)
	var tmp57 interface{} = ConcatString(tmp56, "x")
	var tmp58 interface{} = strconv.Itoa(int(h.(int64)))
	var tmp59 interface{} = ConcatString(tmp57, tmp58)
	var tmp60 interface{} = ConcatString(tmp59, " pixel seamless tileable texture for a spaceship ")
	var tmp61 interface{} = FieldGet(spec, "surfaceType")
	var tmp62 interface{} = ConcatString(tmp60, tmp61)
	var tmp63 interface{} = ConcatString(tmp62, ". Style: ")
	var tmp64 interface{} = FieldGet(spec, "theme")
	var tmp65 interface{} = FieldGet(tmp64, "styleKeywords")
	var tmp66 interface{} = ConcatString(tmp63, tmp65)
	var tmp67 interface{} = ConcatString(tmp66, ". Surface details: ")
	var tmp68 interface{} = ConcatString(tmp67, surfaceStyle)
	return ConcatString(tmp68, ". The texture should be photorealistic, high detail, sci-fi aesthetic.")
}

func BuildPrompt(spec *TextureSpec) string {
	return buildPrompt_impl(spec).(string)
}

func buildRoomSpecs_impl(roomId interface{}, width interface{}, depth interface{}, height interface{}, theme interface{}, ppm interface{}, seed interface{}) interface{} {
	var tmp69 interface{} = &TextureSpec{SurfaceType: "floor", WidthMeters: width.(float64), HeightMeters: depth.(float64), PixelsPerMeter: ppm.(int64), Theme: theme.(*RoomTheme), RoomId: roomId.(string), Seed: seed.(int64)}
	var tmp70 interface{} = dict_Num_Int.Add(seed, int64(1))
	var tmp71 interface{} = &TextureSpec{SurfaceType: "ceiling", WidthMeters: width.(float64), HeightMeters: depth.(float64), PixelsPerMeter: ppm.(int64), Theme: theme.(*RoomTheme), RoomId: roomId.(string), Seed: tmp70.(int64)}
	var tmp72 interface{} = dict_Num_Int.Add(seed, int64(2))
	var tmp73 interface{} = &TextureSpec{SurfaceType: "wall_n", WidthMeters: width.(float64), HeightMeters: height.(float64), PixelsPerMeter: ppm.(int64), Theme: theme.(*RoomTheme), RoomId: roomId.(string), Seed: tmp72.(int64)}
	var tmp74 interface{} = dict_Num_Int.Add(seed, int64(3))
	var tmp75 interface{} = &TextureSpec{SurfaceType: "wall_s", WidthMeters: width.(float64), HeightMeters: height.(float64), PixelsPerMeter: ppm.(int64), Theme: theme.(*RoomTheme), RoomId: roomId.(string), Seed: tmp74.(int64)}
	var tmp76 interface{} = dict_Num_Int.Add(seed, int64(4))
	var tmp77 interface{} = &TextureSpec{SurfaceType: "wall_e", WidthMeters: depth.(float64), HeightMeters: height.(float64), PixelsPerMeter: ppm.(int64), Theme: theme.(*RoomTheme), RoomId: roomId.(string), Seed: tmp76.(int64)}
	var tmp78 interface{} = dict_Num_Int.Add(seed, int64(5))
	var tmp79 interface{} = &TextureSpec{SurfaceType: "wall_w", WidthMeters: depth.(float64), HeightMeters: height.(float64), PixelsPerMeter: ppm.(int64), Theme: theme.(*RoomTheme), RoomId: roomId.(string), Seed: tmp78.(int64)}
	return []interface{}{tmp69, tmp71, tmp73, tmp75, tmp77, tmp79}
}

func BuildRoomSpecs(roomId string, width float64, depth float64, height float64, theme *RoomTheme, ppm int64, seed int64) []*TextureSpec {
	return ConvertToTextureSpecSlice(buildRoomSpecs_impl(roomId, width, depth, height, theme, ppm, seed))
}
