// Code generated by ailang. DO NOT EDIT.
package sim_gen

// DirectionKind discriminates between variants of Direction
type DirectionKind int

const (
	DirectionKindNorth DirectionKind = iota
	DirectionKindSouth
	DirectionKindEast
	DirectionKindWest
)

// DirectionNorth holds data for the North variant
type DirectionNorth struct {
}

// DirectionSouth holds data for the South variant
type DirectionSouth struct {
}

// DirectionEast holds data for the East variant
type DirectionEast struct {
}

// DirectionWest holds data for the West variant
type DirectionWest struct {
}

// Direction is a sum type (discriminated union)
type Direction struct {
	Kind  DirectionKind
	North *DirectionNorth
	South *DirectionSouth
	East  *DirectionEast
	West  *DirectionWest
}

// NewDirectionNorth creates a new North variant
func NewDirectionNorth() *Direction {
	return &Direction{
		Kind:  DirectionKindNorth,
		North: &DirectionNorth{},
	}
}

// NewDirectionSouth creates a new South variant
func NewDirectionSouth() *Direction {
	return &Direction{
		Kind:  DirectionKindSouth,
		South: &DirectionSouth{},
	}
}

// NewDirectionEast creates a new East variant
func NewDirectionEast() *Direction {
	return &Direction{
		Kind: DirectionKindEast,
		East: &DirectionEast{},
	}
}

// NewDirectionWest creates a new West variant
func NewDirectionWest() *Direction {
	return &Direction{
		Kind: DirectionKindWest,
		West: &DirectionWest{},
	}
}

// IsNorth returns true if this is a North variant
func (v *Direction) IsNorth() bool {
	return v.Kind == DirectionKindNorth
}

// IsSouth returns true if this is a South variant
func (v *Direction) IsSouth() bool {
	return v.Kind == DirectionKindSouth
}

// IsEast returns true if this is a East variant
func (v *Direction) IsEast() bool {
	return v.Kind == DirectionKindEast
}

// IsWest returns true if this is a West variant
func (v *Direction) IsWest() bool {
	return v.Kind == DirectionKindWest
}

// MovementPatternKind discriminates between variants of MovementPattern
type MovementPatternKind int

const (
	MovementPatternKindPatternStatic MovementPatternKind = iota
	MovementPatternKindPatternRandomWalk
	MovementPatternKindPatternPatrol
)

// MovementPatternPatternStatic holds data for the PatternStatic variant
type MovementPatternPatternStatic struct {
}

// MovementPatternPatternRandomWalk holds data for the PatternRandomWalk variant
type MovementPatternPatternRandomWalk struct {
	Value0 int64
}

// MovementPatternPatternPatrol holds data for the PatternPatrol variant
type MovementPatternPatternPatrol struct {
	Value0 []*Direction
}

// MovementPattern is a sum type (discriminated union)
type MovementPattern struct {
	Kind              MovementPatternKind
	PatternStatic     *MovementPatternPatternStatic
	PatternRandomWalk *MovementPatternPatternRandomWalk
	PatternPatrol     *MovementPatternPatternPatrol
}

// NewMovementPatternPatternStatic creates a new PatternStatic variant
func NewMovementPatternPatternStatic() *MovementPattern {
	return &MovementPattern{
		Kind:          MovementPatternKindPatternStatic,
		PatternStatic: &MovementPatternPatternStatic{},
	}
}

// NewMovementPatternPatternRandomWalk creates a new PatternRandomWalk variant
func NewMovementPatternPatternRandomWalk(v0 int64) *MovementPattern {
	return &MovementPattern{
		Kind:              MovementPatternKindPatternRandomWalk,
		PatternRandomWalk: &MovementPatternPatternRandomWalk{Value0: v0},
	}
}

// NewMovementPatternPatternPatrol creates a new PatternPatrol variant
func NewMovementPatternPatternPatrol(v0 []*Direction) *MovementPattern {
	return &MovementPattern{
		Kind:          MovementPatternKindPatternPatrol,
		PatternPatrol: &MovementPatternPatternPatrol{Value0: v0},
	}
}

// IsPatternStatic returns true if this is a PatternStatic variant
func (v *MovementPattern) IsPatternStatic() bool {
	return v.Kind == MovementPatternKindPatternStatic
}

// IsPatternRandomWalk returns true if this is a PatternRandomWalk variant
func (v *MovementPattern) IsPatternRandomWalk() bool {
	return v.Kind == MovementPatternKindPatternRandomWalk
}

// IsPatternPatrol returns true if this is a PatternPatrol variant
func (v *MovementPattern) IsPatternPatrol() bool {
	return v.Kind == MovementPatternKindPatternPatrol
}

// NPC is a record type
type NPC struct {
	Id          int64
	Pos         Coord
	Pattern     MovementPattern
	MoveCounter int64
	PatrolIndex int64
}

// Coord is a record type
type Coord struct {
	X int64
	Y int64
}

// Camera is a record type
type Camera struct {
	X    float64
	Y    float64
	Zoom float64
}

// MouseState is a record type
type MouseState struct {
	X       float64
	Y       float64
	Buttons []int64
}

// KeyEvent is a record type
type KeyEvent struct {
	Key  int64
	Kind string
}

// StructureTypeKind discriminates between variants of StructureType
type StructureTypeKind int

const (
	StructureTypeKindStructureHouse StructureTypeKind = iota
	StructureTypeKindStructureFarm
	StructureTypeKindStructureRoad
)

// StructureTypeStructureHouse holds data for the StructureHouse variant
type StructureTypeStructureHouse struct {
}

// StructureTypeStructureFarm holds data for the StructureFarm variant
type StructureTypeStructureFarm struct {
}

// StructureTypeStructureRoad holds data for the StructureRoad variant
type StructureTypeStructureRoad struct {
}

// StructureType is a sum type (discriminated union)
type StructureType struct {
	Kind           StructureTypeKind
	StructureHouse *StructureTypeStructureHouse
	StructureFarm  *StructureTypeStructureFarm
	StructureRoad  *StructureTypeStructureRoad
}

// NewStructureTypeStructureHouse creates a new StructureHouse variant
func NewStructureTypeStructureHouse() *StructureType {
	return &StructureType{
		Kind:           StructureTypeKindStructureHouse,
		StructureHouse: &StructureTypeStructureHouse{},
	}
}

// NewStructureTypeStructureFarm creates a new StructureFarm variant
func NewStructureTypeStructureFarm() *StructureType {
	return &StructureType{
		Kind:          StructureTypeKindStructureFarm,
		StructureFarm: &StructureTypeStructureFarm{},
	}
}

// NewStructureTypeStructureRoad creates a new StructureRoad variant
func NewStructureTypeStructureRoad() *StructureType {
	return &StructureType{
		Kind:          StructureTypeKindStructureRoad,
		StructureRoad: &StructureTypeStructureRoad{},
	}
}

// IsStructureHouse returns true if this is a StructureHouse variant
func (v *StructureType) IsStructureHouse() bool {
	return v.Kind == StructureTypeKindStructureHouse
}

// IsStructureFarm returns true if this is a StructureFarm variant
func (v *StructureType) IsStructureFarm() bool {
	return v.Kind == StructureTypeKindStructureFarm
}

// IsStructureRoad returns true if this is a StructureRoad variant
func (v *StructureType) IsStructureRoad() bool {
	return v.Kind == StructureTypeKindStructureRoad
}

// PlayerActionKind discriminates between variants of PlayerAction
type PlayerActionKind int

const (
	PlayerActionKindActionNone PlayerActionKind = iota
	PlayerActionKindActionInspect
	PlayerActionKindActionBuild
	PlayerActionKindActionClear
)

// PlayerActionActionNone holds data for the ActionNone variant
type PlayerActionActionNone struct {
}

// PlayerActionActionInspect holds data for the ActionInspect variant
type PlayerActionActionInspect struct {
}

// PlayerActionActionBuild holds data for the ActionBuild variant
type PlayerActionActionBuild struct {
	Value0 StructureType
}

// PlayerActionActionClear holds data for the ActionClear variant
type PlayerActionActionClear struct {
}

// PlayerAction is a sum type (discriminated union)
type PlayerAction struct {
	Kind          PlayerActionKind
	ActionNone    *PlayerActionActionNone
	ActionInspect *PlayerActionActionInspect
	ActionBuild   *PlayerActionActionBuild
	ActionClear   *PlayerActionActionClear
}

// NewPlayerActionActionNone creates a new ActionNone variant
func NewPlayerActionActionNone() *PlayerAction {
	return &PlayerAction{
		Kind:       PlayerActionKindActionNone,
		ActionNone: &PlayerActionActionNone{},
	}
}

// NewPlayerActionActionInspect creates a new ActionInspect variant
func NewPlayerActionActionInspect() *PlayerAction {
	return &PlayerAction{
		Kind:          PlayerActionKindActionInspect,
		ActionInspect: &PlayerActionActionInspect{},
	}
}

// NewPlayerActionActionBuild creates a new ActionBuild variant
func NewPlayerActionActionBuild(v0 StructureType) *PlayerAction {
	return &PlayerAction{
		Kind:        PlayerActionKindActionBuild,
		ActionBuild: &PlayerActionActionBuild{Value0: v0},
	}
}

// NewPlayerActionActionClear creates a new ActionClear variant
func NewPlayerActionActionClear() *PlayerAction {
	return &PlayerAction{
		Kind:        PlayerActionKindActionClear,
		ActionClear: &PlayerActionActionClear{},
	}
}

// IsActionNone returns true if this is a ActionNone variant
func (v *PlayerAction) IsActionNone() bool {
	return v.Kind == PlayerActionKindActionNone
}

// IsActionInspect returns true if this is a ActionInspect variant
func (v *PlayerAction) IsActionInspect() bool {
	return v.Kind == PlayerActionKindActionInspect
}

// IsActionBuild returns true if this is a ActionBuild variant
func (v *PlayerAction) IsActionBuild() bool {
	return v.Kind == PlayerActionKindActionBuild
}

// IsActionClear returns true if this is a ActionClear variant
func (v *PlayerAction) IsActionClear() bool {
	return v.Kind == PlayerActionKindActionClear
}

// ClickKindKind discriminates between variants of ClickKind
type ClickKindKind int

const (
	ClickKindKindClickLeft ClickKindKind = iota
	ClickKindKindClickRight
	ClickKindKindClickMiddle
)

// ClickKindClickLeft holds data for the ClickLeft variant
type ClickKindClickLeft struct {
}

// ClickKindClickRight holds data for the ClickRight variant
type ClickKindClickRight struct {
}

// ClickKindClickMiddle holds data for the ClickMiddle variant
type ClickKindClickMiddle struct {
}

// ClickKind is a sum type (discriminated union)
type ClickKind struct {
	Kind        ClickKindKind
	ClickLeft   *ClickKindClickLeft
	ClickRight  *ClickKindClickRight
	ClickMiddle *ClickKindClickMiddle
}

// NewClickKindClickLeft creates a new ClickLeft variant
func NewClickKindClickLeft() *ClickKind {
	return &ClickKind{
		Kind:      ClickKindKindClickLeft,
		ClickLeft: &ClickKindClickLeft{},
	}
}

// NewClickKindClickRight creates a new ClickRight variant
func NewClickKindClickRight() *ClickKind {
	return &ClickKind{
		Kind:       ClickKindKindClickRight,
		ClickRight: &ClickKindClickRight{},
	}
}

// NewClickKindClickMiddle creates a new ClickMiddle variant
func NewClickKindClickMiddle() *ClickKind {
	return &ClickKind{
		Kind:        ClickKindKindClickMiddle,
		ClickMiddle: &ClickKindClickMiddle{},
	}
}

// IsClickLeft returns true if this is a ClickLeft variant
func (v *ClickKind) IsClickLeft() bool {
	return v.Kind == ClickKindKindClickLeft
}

// IsClickRight returns true if this is a ClickRight variant
func (v *ClickKind) IsClickRight() bool {
	return v.Kind == ClickKindKindClickRight
}

// IsClickMiddle returns true if this is a ClickMiddle variant
func (v *ClickKind) IsClickMiddle() bool {
	return v.Kind == ClickKindKindClickMiddle
}

// FrameInput is a record type
type FrameInput struct {
	Mouse            MouseState
	Keys             []*KeyEvent
	ClickedThisFrame bool
	WorldMouseX      float64
	WorldMouseY      float64
	TileMouseX       int64
	TileMouseY       int64
	ActionRequested  PlayerAction
	TestMode         bool
}

// UiKindKind discriminates between variants of UiKind
type UiKindKind int

const (
	UiKindKindUiPanel UiKindKind = iota
	UiKindKindUiButton
	UiKindKindUiLabel
	UiKindKindUiPortrait
	UiKindKindUiSlider
	UiKindKindUiProgressBar
)

// UiKindUiPanel holds data for the UiPanel variant
type UiKindUiPanel struct {
}

// UiKindUiButton holds data for the UiButton variant
type UiKindUiButton struct {
}

// UiKindUiLabel holds data for the UiLabel variant
type UiKindUiLabel struct {
}

// UiKindUiPortrait holds data for the UiPortrait variant
type UiKindUiPortrait struct {
}

// UiKindUiSlider holds data for the UiSlider variant
type UiKindUiSlider struct {
}

// UiKindUiProgressBar holds data for the UiProgressBar variant
type UiKindUiProgressBar struct {
}

// UiKind is a sum type (discriminated union)
type UiKind struct {
	Kind          UiKindKind
	UiPanel       *UiKindUiPanel
	UiButton      *UiKindUiButton
	UiLabel       *UiKindUiLabel
	UiPortrait    *UiKindUiPortrait
	UiSlider      *UiKindUiSlider
	UiProgressBar *UiKindUiProgressBar
}

// NewUiKindUiPanel creates a new UiPanel variant
func NewUiKindUiPanel() *UiKind {
	return &UiKind{
		Kind:    UiKindKindUiPanel,
		UiPanel: &UiKindUiPanel{},
	}
}

// NewUiKindUiButton creates a new UiButton variant
func NewUiKindUiButton() *UiKind {
	return &UiKind{
		Kind:     UiKindKindUiButton,
		UiButton: &UiKindUiButton{},
	}
}

// NewUiKindUiLabel creates a new UiLabel variant
func NewUiKindUiLabel() *UiKind {
	return &UiKind{
		Kind:    UiKindKindUiLabel,
		UiLabel: &UiKindUiLabel{},
	}
}

// NewUiKindUiPortrait creates a new UiPortrait variant
func NewUiKindUiPortrait() *UiKind {
	return &UiKind{
		Kind:       UiKindKindUiPortrait,
		UiPortrait: &UiKindUiPortrait{},
	}
}

// NewUiKindUiSlider creates a new UiSlider variant
func NewUiKindUiSlider() *UiKind {
	return &UiKind{
		Kind:     UiKindKindUiSlider,
		UiSlider: &UiKindUiSlider{},
	}
}

// NewUiKindUiProgressBar creates a new UiProgressBar variant
func NewUiKindUiProgressBar() *UiKind {
	return &UiKind{
		Kind:          UiKindKindUiProgressBar,
		UiProgressBar: &UiKindUiProgressBar{},
	}
}

// IsUiPanel returns true if this is a UiPanel variant
func (v *UiKind) IsUiPanel() bool {
	return v.Kind == UiKindKindUiPanel
}

// IsUiButton returns true if this is a UiButton variant
func (v *UiKind) IsUiButton() bool {
	return v.Kind == UiKindKindUiButton
}

// IsUiLabel returns true if this is a UiLabel variant
func (v *UiKind) IsUiLabel() bool {
	return v.Kind == UiKindKindUiLabel
}

// IsUiPortrait returns true if this is a UiPortrait variant
func (v *UiKind) IsUiPortrait() bool {
	return v.Kind == UiKindKindUiPortrait
}

// IsUiSlider returns true if this is a UiSlider variant
func (v *UiKind) IsUiSlider() bool {
	return v.Kind == UiKindKindUiSlider
}

// IsUiProgressBar returns true if this is a UiProgressBar variant
func (v *UiKind) IsUiProgressBar() bool {
	return v.Kind == UiKindKindUiProgressBar
}

// DrawCmdKind discriminates between variants of DrawCmd
type DrawCmdKind int

const (
	DrawCmdKindSprite DrawCmdKind = iota
	DrawCmdKindRect
	DrawCmdKindText
	DrawCmdKindIsoTile
	DrawCmdKindIsoEntity
	DrawCmdKindUi
	DrawCmdKindLine
	DrawCmdKindTextWrapped
	DrawCmdKindCircle
	DrawCmdKindRectScreen
	DrawCmdKindGalaxyBg
	DrawCmdKindStar
)

// DrawCmdSprite holds data for the Sprite variant
type DrawCmdSprite struct {
	Id int64
	X  float64
	Y  float64
	Z  int64
}

// DrawCmdRect holds data for the Rect variant
type DrawCmdRect struct {
	X     float64
	Y     float64
	W     float64
	H     float64
	Color int64
	Z     int64
}

// DrawCmdText holds data for the Text variant
type DrawCmdText struct {
	Text     string
	X        float64
	Y        float64
	FontSize int64
	Color    int64
	Z        int64
}

// DrawCmdIsoTile holds data for the IsoTile variant
type DrawCmdIsoTile struct {
	Tile     Coord
	Height   int64
	SpriteId int64
	Layer    int64
	Color    int64
}

// DrawCmdIsoEntity holds data for the IsoEntity variant
type DrawCmdIsoEntity struct {
	Id       string
	Tile     Coord
	OffsetX  float64
	OffsetY  float64
	Height   int64
	SpriteId int64
	Layer    int64
}

// DrawCmdUi holds data for the Ui variant
type DrawCmdUi struct {
	Id       string
	Kind     UiKind
	X        float64
	Y        float64
	W        float64
	H        float64
	Text     string
	SpriteId int64
	Z        int64
	Color    int64
	Value    float64
}

// DrawCmdLine holds data for the Line variant
type DrawCmdLine struct {
	X1    float64
	Y1    float64
	X2    float64
	Y2    float64
	Color int64
	Width float64
	Z     int64
}

// DrawCmdTextWrapped holds data for the TextWrapped variant
type DrawCmdTextWrapped struct {
	Text     string
	X        float64
	Y        float64
	MaxWidth float64
	FontSize int64
	Color    int64
	Z        int64
}

// DrawCmdCircle holds data for the Circle variant
type DrawCmdCircle struct {
	X      float64
	Y      float64
	Radius float64
	Color  int64
	Filled bool
	Z      int64
}

// DrawCmdRectScreen holds data for the RectScreen variant
type DrawCmdRectScreen struct {
	X     float64
	Y     float64
	W     float64
	H     float64
	Color int64
	Z     int64
}

// DrawCmdGalaxyBg holds data for the GalaxyBg variant
type DrawCmdGalaxyBg struct {
	Opacity     float64
	Z           int64
	SkyViewMode bool
	ViewLon     float64
	ViewLat     float64
	Fov         float64
}

// DrawCmdStar holds data for the Star variant
type DrawCmdStar struct {
	X        float64
	Y        float64
	SpriteId int64
	Scale    float64
	Alpha    float64
	Z        int64
}

// DrawCmd is a sum type (discriminated union)
type DrawCmd struct {
	Kind        DrawCmdKind
	Sprite      *DrawCmdSprite
	Rect        *DrawCmdRect
	Text        *DrawCmdText
	IsoTile     *DrawCmdIsoTile
	IsoEntity   *DrawCmdIsoEntity
	Ui          *DrawCmdUi
	Line        *DrawCmdLine
	TextWrapped *DrawCmdTextWrapped
	Circle      *DrawCmdCircle
	RectScreen  *DrawCmdRectScreen
	GalaxyBg    *DrawCmdGalaxyBg
	Star        *DrawCmdStar
}

// NewDrawCmdSprite creates a new Sprite variant
func NewDrawCmdSprite(id int64, x float64, y float64, z int64) *DrawCmd {
	return &DrawCmd{
		Kind:   DrawCmdKindSprite,
		Sprite: &DrawCmdSprite{Id: id, X: x, Y: y, Z: z},
	}
}

// NewDrawCmdRect creates a new Rect variant
func NewDrawCmdRect(x float64, y float64, w float64, h float64, color int64, z int64) *DrawCmd {
	return &DrawCmd{
		Kind: DrawCmdKindRect,
		Rect: &DrawCmdRect{X: x, Y: y, W: w, H: h, Color: color, Z: z},
	}
}

// NewDrawCmdText creates a new Text variant
func NewDrawCmdText(text string, x float64, y float64, fontSize int64, color int64, z int64) *DrawCmd {
	return &DrawCmd{
		Kind: DrawCmdKindText,
		Text: &DrawCmdText{Text: text, X: x, Y: y, FontSize: fontSize, Color: color, Z: z},
	}
}

// NewDrawCmdIsoTile creates a new IsoTile variant
func NewDrawCmdIsoTile(tile Coord, height int64, spriteId int64, layer int64, color int64) *DrawCmd {
	return &DrawCmd{
		Kind:    DrawCmdKindIsoTile,
		IsoTile: &DrawCmdIsoTile{Tile: tile, Height: height, SpriteId: spriteId, Layer: layer, Color: color},
	}
}

// NewDrawCmdIsoEntity creates a new IsoEntity variant
func NewDrawCmdIsoEntity(id string, tile Coord, offsetX float64, offsetY float64, height int64, spriteId int64, layer int64) *DrawCmd {
	return &DrawCmd{
		Kind:      DrawCmdKindIsoEntity,
		IsoEntity: &DrawCmdIsoEntity{Id: id, Tile: tile, OffsetX: offsetX, OffsetY: offsetY, Height: height, SpriteId: spriteId, Layer: layer},
	}
}

// NewDrawCmdUi creates a new Ui variant
func NewDrawCmdUi(id string, kind UiKind, x float64, y float64, w float64, h float64, text string, spriteId int64, z int64, color int64, value float64) *DrawCmd {
	return &DrawCmd{
		Kind: DrawCmdKindUi,
		Ui:   &DrawCmdUi{Id: id, Kind: kind, X: x, Y: y, W: w, H: h, Text: text, SpriteId: spriteId, Z: z, Color: color, Value: value},
	}
}

// NewDrawCmdLine creates a new Line variant
func NewDrawCmdLine(x1 float64, y1 float64, x2 float64, y2 float64, color int64, width float64, z int64) *DrawCmd {
	return &DrawCmd{
		Kind: DrawCmdKindLine,
		Line: &DrawCmdLine{X1: x1, Y1: y1, X2: x2, Y2: y2, Color: color, Width: width, Z: z},
	}
}

// NewDrawCmdTextWrapped creates a new TextWrapped variant
func NewDrawCmdTextWrapped(text string, x float64, y float64, maxWidth float64, fontSize int64, color int64, z int64) *DrawCmd {
	return &DrawCmd{
		Kind:        DrawCmdKindTextWrapped,
		TextWrapped: &DrawCmdTextWrapped{Text: text, X: x, Y: y, MaxWidth: maxWidth, FontSize: fontSize, Color: color, Z: z},
	}
}

// NewDrawCmdCircle creates a new Circle variant
func NewDrawCmdCircle(x float64, y float64, radius float64, color int64, filled bool, z int64) *DrawCmd {
	return &DrawCmd{
		Kind:   DrawCmdKindCircle,
		Circle: &DrawCmdCircle{X: x, Y: y, Radius: radius, Color: color, Filled: filled, Z: z},
	}
}

// NewDrawCmdRectScreen creates a new RectScreen variant
func NewDrawCmdRectScreen(x float64, y float64, w float64, h float64, color int64, z int64) *DrawCmd {
	return &DrawCmd{
		Kind:       DrawCmdKindRectScreen,
		RectScreen: &DrawCmdRectScreen{X: x, Y: y, W: w, H: h, Color: color, Z: z},
	}
}

// NewDrawCmdGalaxyBg creates a new GalaxyBg variant
func NewDrawCmdGalaxyBg(opacity float64, z int64, skyViewMode bool, viewLon float64, viewLat float64, fov float64) *DrawCmd {
	return &DrawCmd{
		Kind:     DrawCmdKindGalaxyBg,
		GalaxyBg: &DrawCmdGalaxyBg{Opacity: opacity, Z: z, SkyViewMode: skyViewMode, ViewLon: viewLon, ViewLat: viewLat, Fov: fov},
	}
}

// NewDrawCmdStar creates a new Star variant
func NewDrawCmdStar(x float64, y float64, spriteId int64, scale float64, alpha float64, z int64) *DrawCmd {
	return &DrawCmd{
		Kind: DrawCmdKindStar,
		Star: &DrawCmdStar{X: x, Y: y, SpriteId: spriteId, Scale: scale, Alpha: alpha, Z: z},
	}
}

// IsSprite returns true if this is a Sprite variant
func (v *DrawCmd) IsSprite() bool {
	return v.Kind == DrawCmdKindSprite
}

// IsRect returns true if this is a Rect variant
func (v *DrawCmd) IsRect() bool {
	return v.Kind == DrawCmdKindRect
}

// IsText returns true if this is a Text variant
func (v *DrawCmd) IsText() bool {
	return v.Kind == DrawCmdKindText
}

// IsIsoTile returns true if this is a IsoTile variant
func (v *DrawCmd) IsIsoTile() bool {
	return v.Kind == DrawCmdKindIsoTile
}

// IsIsoEntity returns true if this is a IsoEntity variant
func (v *DrawCmd) IsIsoEntity() bool {
	return v.Kind == DrawCmdKindIsoEntity
}

// IsUi returns true if this is a Ui variant
func (v *DrawCmd) IsUi() bool {
	return v.Kind == DrawCmdKindUi
}

// IsLine returns true if this is a Line variant
func (v *DrawCmd) IsLine() bool {
	return v.Kind == DrawCmdKindLine
}

// IsTextWrapped returns true if this is a TextWrapped variant
func (v *DrawCmd) IsTextWrapped() bool {
	return v.Kind == DrawCmdKindTextWrapped
}

// IsCircle returns true if this is a Circle variant
func (v *DrawCmd) IsCircle() bool {
	return v.Kind == DrawCmdKindCircle
}

// IsRectScreen returns true if this is a RectScreen variant
func (v *DrawCmd) IsRectScreen() bool {
	return v.Kind == DrawCmdKindRectScreen
}

// IsGalaxyBg returns true if this is a GalaxyBg variant
func (v *DrawCmd) IsGalaxyBg() bool {
	return v.Kind == DrawCmdKindGalaxyBg
}

// IsStar returns true if this is a Star variant
func (v *DrawCmd) IsStar() bool {
	return v.Kind == DrawCmdKindStar
}

// FrameOutput is a record type
type FrameOutput struct {
	Draw   []*DrawCmd
	Sounds []int64
	Debug  []string
	Camera Camera
}

// OptionKind discriminates between variants of Option
type OptionKind int

const (
	OptionKindSome OptionKind = iota
	OptionKindNone
)

// OptionSome holds data for the Some variant
type OptionSome struct {
	Value0 interface{}
}

// OptionNone holds data for the None variant
type OptionNone struct {
}

// Option is a sum type (discriminated union)
type Option struct {
	Kind OptionKind
	Some *OptionSome
	None *OptionNone
}

// NewOptionSome creates a new Some variant
func NewOptionSome(v0 interface{}) *Option {
	return &Option{
		Kind: OptionKindSome,
		Some: &OptionSome{Value0: v0},
	}
}

// NewOptionNone creates a new None variant
func NewOptionNone() *Option {
	return &Option{
		Kind: OptionKindNone,
		None: &OptionNone{},
	}
}

// IsSome returns true if this is a Some variant
func (v *Option) IsSome() bool {
	return v.Kind == OptionKindSome
}

// IsNone returns true if this is a None variant
func (v *Option) IsNone() bool {
	return v.Kind == OptionKindNone
}

// Tile is a record type
type Tile struct {
	Biome int64
}

// PlanetState is a record type
type PlanetState struct {
	Width  int64
	Height int64
	Tiles  []*Tile
}

// SelectionKind discriminates between variants of Selection
type SelectionKind int

const (
	SelectionKindNone SelectionKind = iota
	SelectionKindTile
)

// SelectionNone holds data for the SelectionNone variant
type SelectionNone struct {
}

// SelectionTile holds data for the SelectionTile variant
type SelectionTile struct {
	Value0 int64
	Value1 int64
}

// Selection is a sum type (discriminated union)
type Selection struct {
	Kind          SelectionKind
	SelectionNone *SelectionNone
	SelectionTile *SelectionTile
}

// NewSelectionNone creates a new SelectionNone variant
func NewSelectionNone() *Selection {
	return &Selection{
		Kind:          SelectionKindNone,
		SelectionNone: &SelectionNone{},
	}
}

// NewSelectionTile creates a new SelectionTile variant
func NewSelectionTile(v0 int64, v1 int64) *Selection {
	return &Selection{
		Kind:          SelectionKindTile,
		SelectionTile: &SelectionTile{Value0: v0, Value1: v1},
	}
}

// IsSelectionNone returns true if this is a SelectionNone variant
func (v *Selection) IsSelectionNone() bool {
	return v.Kind == SelectionKindNone
}

// IsSelectionTile returns true if this is a SelectionTile variant
func (v *Selection) IsSelectionTile() bool {
	return v.Kind == SelectionKindTile
}

// World is a record type
type World struct {
	Tick      int64
	Planet    PlanetState
	Npcs      []*NPC
	Selection Selection
}
