// Code generated by ailang. DO NOT EDIT.
// This file contains effect handler interfaces for your game.
// Implement these interfaces to provide platform-specific behavior.
package sim_gen

// DebugHandler provides the Debug effect implementation.
// Implement this interface to control debug behavior in your game.
type DebugHandler interface {
	// Log records a debug message with auto-injected location.
	// Example: d.logs = append(d.logs, LogEntry{Message: msg, Location: location, Timestamp: d.timestamp})
	Log(msg string, location string)
	// Assert records an assertion result.
	// Example: d.assertions = append(d.assertions, AssertionResult{...})
	Assert(cond bool, msg string, location string)
	// SetTimestamp sets the logical timestamp for subsequent operations.
	// Example: d.timestamp = t
	SetTimestamp(t int64)
	// Collect returns accumulated debug data (HOST-ONLY).
	// Example: return DebugOutput{Logs: d.logs, Assertions: d.assertions}
	Collect() DebugOutput
	// Reset clears the debug buffer for the next step.
	// Example: d.logs = d.logs[:0]; d.assertions = d.assertions[:0]
	Reset()
}

// RandHandler provides the Rand effect implementation.
// Implement this interface to control rand behavior in your game.
type RandHandler interface {
	// RandInt returns a random integer in [min, max].
	// Example: return rand.Int63n(max-min+1) + min
	RandInt(min int64, max int64) int64
	// RandFloat returns a random float in [min, max).
	// Example: return min + rand.Float64()*(max-min)
	RandFloat(min float64, max float64) float64
	// RandBool returns a random boolean.
	// Example: return rand.Intn(2) == 1
	RandBool() bool
	// SetSeed sets the random seed for deterministic behavior.
	// Example: rand.Seed(seed)
	SetSeed(seed int64)
}

// ClockHandler provides the Clock effect implementation.
// Implement this interface to control clock behavior in your game.
type ClockHandler interface {
	// DeltaTime returns seconds since last frame.
	// Example: return g.deltaTime
	DeltaTime() float64
	// TotalTime returns total game time in seconds.
	// Example: return g.totalTime
	TotalTime() float64
	// FrameCount returns the current frame number.
	// Example: return g.frameCount
	FrameCount() int64
}

// Handlers collects all effect handlers for this module.
type Handlers struct {
	Debug DebugHandler
	Rand  RandHandler
	Clock ClockHandler
}

// Init initializes the module with the provided handlers.
// Call this before using any functions that require effects.
func Init(h Handlers) {
	handlers = h
}

// handlers is the global handler registry.
var handlers Handlers
